### ISSUE TITLE
latex encoding of small letter u with grave accent

### ISSUE THREAD

**Issue by icornelius** [retorquere/zotero-better-bibtex#1040]
On export to Better BibLaTex, BBT writes `ù` as 
```
\{`u}
```
, which causes pandoc-citeproc to err out. From what I can see, BBT does not employ curly brackets in translation of other characters with diacritic marks. Removing the curly brackets (i.e, changing to
```
\`u
```
) allows pandoc-citeproc to process the .bib file and generate the correct result.

Report ID: UH7WJLC2-euc

**Comment by retorquere** [comment]
I'll look at it when I'm home, but this is valid latex, so you should also report this at pandoc, because they are erroring out on valid (and typical) latex code. I can maybe change the output as a convenience, but it's their parser that is at fault, not BBT. 

In general I would advice using better csl json or better csl yaml with pandoc. It's the native pandoc format and the bibtex to native translator has problems.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.180.7937](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.180.7937.xpi) ("fixes #1040").

**Comment by retorquere** [comment]
I've changed the output for `ù` but I still think it'd be good to report this to the pandoc devs.

**Comment by jgm** [comment]
It's invalid LaTeX.  Try it if you don't believe me.

The backslash needs to be immediately before the backtick.  You can use `` \`u ``, `` {\`u} ``, or `` \`{u} ``, but not ``\{`u}``.

**Comment by retorquere** [comment]
Christ that was dense of me. I stand corrected. The new release exports the right sequence.
