### ISSUE TITLE
Court field not appearing in Better BibTeX exports

### ISSUE THREAD

**Issue by RyanMcCarl** [retorquere/zotero-better-bibtex#1071]
- [X] I have verified in the Zotero addons screen that I have the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest) and Zotero installed
- [X] I am posting a single question, bug or feature request
- [X] I have included a descriptive subject of the problem
- [X] I am available for follow-up questions and testing
- [X] If I am posting an export or key-generation related bug report, I have included an error-report by selecting the problematic reference(s), right-clicking, and submitting an BBT error report from that popup menu - 

# Bug classification
## Exporting references
Exporting BibTeX - Error ID = CA23UIRE-euc

Thank you for this great tool. I just started using Zotero for legal citations and have set it up to auto-export a .bib file with Better BibTeX syntax. However, not every field with data is being exported into the .bib file. In particular, Zotero's "Court" field for legal cases ([which maps onto the CSL "authority" field](https://aurimasv.github.io/z2csl/typeMap.xml#map-case)) is not being exported into the .bib file. 

Here is an example. This is a standard citation that appears when I drag-and-drop the item into this text box:
`Lake River Corp. v. Carborundum Co., 769 F.2d 1284 (7th Cir. 1985).` `7th Cir.` is the court that decided the case.

Here is what the automatically exported .bib file shows for the item with the export format set to "Better BibTeX"; the "court" field is missing:

```
@misc{LakeRiverCorp1985,
  title = {Lake {{River Corp}}. v. {{Carborundum Co}}.},
  volume = {769},
  year = {1985},
  keywords = {liquidated damages},
  pages = {1284},
  note = {mlzsync1:0075\{"extrafields":\{"jurisdiction":"005us:c7United States|US|Seventh Circuit"\}\}}
}

```
What the item looks like in Zotero:
![screen shot 2018-10-08 at 2 31 22 am](https://user-images.githubusercontent.com/13208682/46601839-4f142380-caa3-11e8-9dbb-f5f87bf9b583.png)

Is this a bug, or do I need to switch export formats? I want a simple, standard format that I can use in Emacs, Pandoc, and Sublime Text.

Thank you,
Ryan

**Comment by retorquere** [comment]
Which field would you like it to show up in in the case of bibtex? For biblatex (which you get by exporting as "Better BibLaTeX" rather than "Better BibTeX"), it is exported as `institution`.

If your main target is Pandoc for anything but PDF output, I'd recommend "Better CSL" instead. Unless you use Pandoc to output PDF, it converts things back to CSL internally before it does anything else, and the conversion Zotero -> BibTeX -> Pandoc CSL is (necessarily) more lossy than just Zotero -> Pandoc CSL. BBT supports both pandoc-supported CSL formats (JSON and YAML).

**Comment by RyanMcCarl** [comment]
Thank you for your response. I was hoping the BibTeX entries would show a "court" field. The BibTeX [specification](http://www.bibtex.org/Format/) says that unknown tags (fields) "are ignored by BibTeX, thus can be used to store additional information without interfering with the final outcome of a document." With that in mind, I hoped that my automatic export would recreate all of the completed fields in the exported .bib file--including, for some legal cases, "court."

I am new to BibTeX so I could be wrong, but I assumed BibTeX was a standard and would be a good portable format for my citation library. But perhaps the Pandoc CSL is better. Since Zotero does not seem to have good bulk operations (adding or removing tags, changing item type, etc.), I would ideally like to be able to manipulate the parent citation items in a text editor, then reimport them into Zotero. 

Thank you for your help.

**Comment by retorquere** [comment]
Yeah but stuffing data in non-standard fields means you also need a custom bibtex style to use it at all, and I can't cater to every custom bibtex style.

If you can use a custom bibtex style, you can probably also use biblatex, and a Better BibLaTeX export will include the court. BibTeX should really only be used if your publisher forces you to -- it's really outdated at this point and superseded by biblatex.

Mind that bibtex (or biblatex) are really not good formats for round tripping data in Zotero. The export and import cannot roundtrip cleanly. Also, if I would stick the court into the `court` field, it would not be imported back because it's non-standard. Also, if you edit and re-import, you'll end up with duplicates. But if you're looking to do this anyhow, you may want to look at the "BetterBibTeX JSON" format. I use it internally for my tests but it gets as close to roundtripping cleanly as is possible in Zotero.

The CSL formats are great for Pandoc (unless you're using Pandoc to output PDF) but also don't roundtrip cleanly.

**Comment by RyanMcCarl** [comment]
That is helpful, thank you. Keep up the great work.
