### ISSUE TITLE
generating bibtex keys with hyphens using condense

### ISSUE THREAD

**Issue by aaronlandesman** [retorquere/zotero-better-bibtex#1117]
- [ ] I have verified in the Zotero addons screen that I have the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest) and Zotero installed
- [x] I am posting a single question, bug or feature request
- [ ] I have included a descriptive subject of the problem
- [ ] I am available for follow-up questions and testing
- [ ] If I am posting an export or key-generation related bug report, I have included an error-report by selecting the problematic reference(s), right-clicking, and submitting an BBT error report from that popup menu

# Bug classification

I would like to generate a key taking the first three words of the title in lower case, where there is a dash between each word. I am currently using

[shorttitle3_0:condense=-]

but for the title
"On the identifiability of ternary forms"
it returns 
"identifiabilityternaryforms"
instead of the desired
"identifiability-ternary-forms"

How would I use the condense filter to obtain the latter output?

**Comment by retorquere** [comment]
The above pattern doesn't work because condense does "split apart on spaces and re-join on `-`" (or whatever you pass to condense), but `shorttitle` (`3_0` is the default BTW) doesn't have any spaces, so there's nothing to split on.

Try `[Title:skipwords:select=1,3:lower:condense=-]` (note the capital `Title`) to see if that does what you want.

**Comment by aaronlandesman** [comment]
It works perfectly! Thanks so much!

**Comment by retorquere** [comment]
My pleasure.
