### ISSUE TITLE
Cyrillic symbols with [zotero] citekey style produce empty keys

### ISSUE THREAD

**Issue by taranarmo** [retorquere/zotero-better-bibtex#1130]
- [x] I have verified in the Zotero addons screen that I have the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest) and Zotero installed
- [x] I am posting a single question, bug or feature request
- [x] I have included a descriptive subject of the problem
- [x] I am available for follow-up questions and testing
- [x] If I am posting an export or key-generation related bug report, I have included an error-report by selecting the problematic reference(s), right-clicking, and submitting an BBT error report from that popup menu

I am using Zotero with russian texts and I found out that [zotero] citekey style do not produce proper citekeys for texts with Cyrillic scripts in title or authors. Other citekey styles work fine.

report ID 4QB8889J-euc

![screenshot_20190212_104734](https://user-images.githubusercontent.com/11619234/52619786-bd368000-2eb3-11e9-9134-99e89042edc1.png)

Other citekey styles seem to work fine

![screenshot_20190212_104947](https://user-images.githubusercontent.com/11619234/52619880-0090ee80-2eb4-11e9-947b-fb4a603025e3.png)

**Comment by retorquere** [comment]
That's how the `[zotero]` pattern works -- it aims to replicate the way Zotero itself generates citekeys as closely as possible, including all its problems. I don't recommend its use, it's mainly for if you already have a lot of papers using previous regular-Zotero BibTeX exports. The other citekey styles do work because they do transliteration.

If you want something that looks like the zotero keys but does use transliteration, try `[authors1]_[veryshorttitle]_[year][0]`.

**Comment by taranarmo** [comment]
Oh, OK, thank you. Then, I suppose, new users should be informed of such behavior? Or maybe other style should be used as default?

BTW, shall I close the issue?

**Comment by retorquere** [comment]
The first-run wizard does indicate that you really only should use `[zotero]` when you have existing papers that need it. I've added more explanation for the first-run dialog and the website about the `[zotero]` pattern.
