### ISSUE TITLE
Disable citekey generation for certain groups

### ISSUE THREAD

**Issue by demai** [retorquere/zotero-better-bibtex#1143]
Is it possible to disable citekey generation for certain collections or group libraries? I have some large group libraries with items that I will almost certainly never cite. We are using this group for acquisition management at our library so people add a lot of items all the time. Generating citekeys for these items seems to slow down Zotero startup.

**Comment by retorquere** [comment]
Generating only happens on startup when the items don't have a key set. Keys that already have a key shouldn't generate any BBT activity at all.

**Comment by demai** [comment]
Well, that's exactly the point. In those group many items get added all the time. So these new items won't have a key already since the others in the group don't have BBT installed. That's why I would like to disable automatic key generation for this particular group.

**Comment by retorquere** [comment]
OK but what's "all the time"? Hundreds a day?

**Comment by retorquere** [comment]
I'd like to see where the performance problem actually is before I make a change that might not be required.

**Comment by retorquere** [comment]
Can you restart with debugging enabled from the help menu, replicate the problem, and send a BBT error report? The part of BBT that does the key updates at start has benchmark logging when debug logging and it will tell me where in this process the problem lies.

**Comment by retorquere** [comment]
I really can't do much without a debug log -- I don't want to make undirected changes without knowing I'm addressing the actual problem.

Additionally, doing only partial key generation is tricky because it is assumed throughout BBT that the keys are available, so I need to be careful I don't break a lot of stuff. Collection-based is not strictly possible (an item could live in multiple collections), and checking for which collections an item lives in would incur a performance hit, exactly the problem we're looking to avoid. It would also require UI work, and I try to avoid UI work where possible; I don't enjoy doing it, and I'm not very good at it.

Group-based is in principle possible; as said, it will take some care not to break stuff in a lot of places, but first I need to know whether it would actually address the problem you experience. Another option I could look at is deferring cite key generation until export.

**Comment by demai** [comment]
Sorry for the delay. I will send a debug log asap.

Thanks for explaing why partial key generation might be problematic. I
wasn't aware of this.

Emiliano Heyns <notifications@github.com> schrieb am So., 3. März 2019,
15:58:

**Comment by demai** [comment]
Hmm, strangely enough I was not able to reproduce the problem at the moment. We can close this for the moment. In case this happens again I will send a BBT error report with debug log.
