### ISSUE TITLE
Some fields are ignored by CSL

### ISSUE THREAD

**Issue by Forrestus** [retorquere/zotero-better-bibtex#1192]
**Report ID:** ?

**Exporter used:** Zotero → Export library → Better BibTex (Keep updated)

**Expected behavior:** using Pandoc I wanted to generate a bibliography. I provided .md, .bib, reference.docx, .csl.

**Actual behavior:** The bibliography was generated, but some less common fields (for example `call-number`) were simply ignored and don't appear. They do appear however when I use Zotero's CSL editor.

Let me mention, that I'm definitely not an advanced user. I hope that the information I provide is useful enough.

And thank you very much for your program.

**Comment by retorquere** [comment]
Can you right click that reference and select "send error report" from the bbt entry in that popup menu (and then post the debug ID here)?

**Comment by retorquere** [comment]
The debug ID would give me a copy of the reference we're talking about. But if you're using pandoc, I'd strongly recommend using `Better CSL JSON` or `Better CSL YAML` over `Better BibTeX` (all of which support `Keep updated`).

BibTeX is really a last-ditch format these days; you should always use biblatex when you can (and I think pandoc supports it), but pandoc internally uses CSL, so it's much better to skip the BibTeX -> CSL transformation inside pandoc and go directly to CSL; each transformation is by necessity imperfect (as Zotero, BibTeX and CSL each have slightly different concepts of references), so the fewer translations, the better off you'll be. But in any case, in the transformation through BibTeX you'll incur the biggest loss, because it's the least fine-grained format available.

![Screenshot_2019-05-24 Webgraphviz](https://user-images.githubusercontent.com/132108/58308970-37579880-7e03-11e9-9c42-01822634eb4b.png)

**Comment by Forrestus** [comment]
**EJ5YXUZJ-euc**

The nature of the problem is such, that all items are affected, so I chose a random item for submitting the error.

**Comment by Forrestus** [comment]
Thank you for explaining everything. The problem is, my references in the text appear now with BBT citekeys and the tool I'm using ([Docdown](https://raphaelkabo.com/blog/posts/markdown-to-word/)) is tied to BBT, I think.

**Comment by retorquere** [comment]
Random doesn't matter, as long as there's a single item that we can both look at so that we don't talk past each other using abstract terms.

With that item, what's `Call Number` in Zotero gets exported as `lccn` by `Better BibTeX` and as `call-number` by `Better CSL JSON`. So the field is actually exported, you'd have to ask the pandoc crowd why they're not picking up `lccn`. But in any case, I'd recommend using `CSL JSON` or `CSL YAML` (which pandoc supports) directly rather than relying on their internal bibtex parser.

**Comment by retorquere** [comment]
BBT will generate `CSL JSON` and `CSL YAML` with BBT citation keys.

**Comment by retorquere** [comment]
if [this](https://raphaelkabo.com/blog/posts/markdown-to-word/) is DocDown, you can just point the --bibliograpy parameter to the csl-json/csl-yaml file instead of the bib file and it will work.

**Comment by retorquere** [comment]
That's not to say you can't use bibtex, but as said, you'd have to ask the pandoc people why they're not picking up `lccn`.

**Comment by Forrestus** [comment]
Wow, it works. I'm so grateful. So I think I need to ditch DocDown (the actual program is in the [following blogpost](https://raphaelkabo.com/blog/posts/introducing-docdown/)), and do the transformation manually each time (which is a pity, as DocDown was just one click in Ulyssess).

**Comment by retorquere** [comment]
You may not have to -- in the prefs pane of DocDown, in the "Location of the Zotero Bibliography file", just load the  csl-json or csl-yaml file. I don't think docdown does anything with the bib file, it probably just passes it to pandoc, so it should just work.

**Comment by Forrestus** [comment]
Of course, I thought of about it. Unfortunately, it turns out the program requires .bib. I will discuss it with its author. Thank you so much.

**Comment by retorquere** [comment]
I see you already opened some issues on the DocDown project -- something like https://github.com/lowercasename/docdown/issues/4 just doesn't happen when using csl-json/yaml, and shouldn't with bibtex when using pandoc, but this is one more example of why having the extra translation layer is to be avoided. 

Without samples I can't say who's in the wrong in that issue you opened, but my money is on BBT exporting valid TeX here. Exporting is unicode to TeX commands is easier than translating TeX commands to unicode)

**Comment by retorquere** [comment]
You can join the issue I've opened at https://github.com/lowercasename/docdown/issues/5
