### ISSUE TITLE
Timeout when exporting BibLaTeX

### ISSUE THREAD

**Issue by mikulcak** [retorquere/zotero-better-bibtex#1198]
Hi, 

first of all, thank you for the great work on this plugin! 

Quite often when (auto-)exporting my library, I run into a timeout error for which I haven't found a consistent fix. It often works to close completely close and restart Zotero, but not every time. 

The error shown is:
`[Exception... "Component not initialized"  nsresult: "0xc1f30001 (NS_ERROR_NOT_INITIALIZED)"  location: "JS frame :: chrome://zotero-better-bibtex/content/common.js :: ["./timeout.ts"]/timeout/< :: line 62315"  data: no]`

For some reason, the cache is empty every time I manually restart the export process from the preferences window as well. It slowly fills up, as it should, be often runs into the timeout. 

![error](https://user-images.githubusercontent.com/1401608/59025916-8961da80-8855-11e9-9e14-b2e00efd0ca3.jpeg)

I am using Zotero on macOS, latest Zotero and BetterBibTeX versions. 

Do you have any ideas what could be causing it? 

Thanks so much in advance!

**Comment by retorquere** [comment]
I really can't do much without a debug report.

**Comment by mikulcak** [comment]
I know. Working on it - so far, the error hasn't occurred again. As soon as it does, I'll post the debug info here. Thanks!

**Comment by retorquere** [comment]
If you can already get me a debug report even if the error has not occurred, that will give me a copy of your BBT settings so that I can see if cache priming is on. 

I don't think what you're seeing is a timeout error, the error happens inside my function called `timeout` but it complains about a component not being initialized and I'm guessing it has something to do with Zotero not being fully ready when I call it, which limits it to only two places in my code. Seeing your. settings may tell me which of the two it is.

**Comment by mikulcak** [comment]
Ah, I see, that sounds promising. I uploaded a report, ID `QNWSWFQS-euc`

So far the error hasn't occurred again. Maybe it's because I switched the auto export behavior from 'On Change' to "When Idle'?

Thank you!

**Comment by retorquere** [comment]
Priming is already on for you, which doesn't narrow down between those two instances which it could be.

When set to idle you're unlikely to experience the problem because by the time Zotero considers itself idle, it's pretty much guaranteed to be fully done initializing. If you do experience it again, just send a BBT log just after, I may be able to tell from that.

WRT to the cache fill, are you saying you can reproduce this scenario:

1. You export from the prefs and the cache fills to 100%
2. You close the prefs screen
3. You open the prefs screen and the cache is now at 0%

?

**Comment by mikulcak** [comment]
Alright, I finally managed to produce a log containing the error. You were right regarding On Change and When Idle, of course. When the latter is set, it just doesn't occur. The log is [here](https://www.dropbox.com/s/1p6x1xbb0y65ud9/zotero_error.zip?dl=0) The first time it occurs in this log is in line 2826. I hope it helps you track it down!

The caching problem hasn't occurred again. If it does and I can safely reproduce it, I can always open a separate issue.

**Comment by retorquere** [comment]
I'll look into the log as soon as I can, but can you verify the 3 step scenario above?

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.88.4114](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.88.4114.xpi) ("use Zotero setTimeout")

Install in Zotero by downloading [test build 5.1.88.4114](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.88.4114.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Can you try 4114?

**Comment by retorquere** [comment]
Thanks for getting back to me via PayPal 😄 . Yeah, usually I really want people around to test & verify but in this case the log had enough information to fix the problem.
