### ISSUE TITLE
Is there a working better-bibtex extension for Zotero 4.0.29.10

### ISSUE THREAD

**Issue by nukedone** [retorquere/zotero-better-bibtex#1214]
I am asking the question since I cannot install the bbt extension in my Zotero 4.0.29.10. The dialog reads that the plugin is not compatible with my version of Zotero Standalone.

**Comment by retorquere** [comment]
I suppose https://github.com/retorquere/zotero-better-bibtex/releases/tag/1.6.100 probably still works, but it's unmaintained, and I won't be able to help much with any problems you might run in to. I don't know what new functionality has been added to BBT since, nor what bugs have been fixed since, but I don't accept feature requests or bug reports for Zotero 4-compatible BBT.

**Comment by nukedone** [comment]
I managed it to work. I needed the proper zotfile (for those who need it) in version 4.2.8, which is available here https://legacycollector.org/firefox-addons/284723/zotfile-4.2.8.xpi
I have solved my problem. Closing the issue!

**Comment by retorquere** [comment]
That's a different extension though, not BBT.

**Comment by nukedone** [comment]
Surely, but they conflict.
