### ISSUE TITLE
CLSJSON via http request

### ISSUE THREAD

**Issue by bcdavasconcelos** [retorquere/zotero-better-bibtex#1219]
I am opening this issue with regards to this [discussion](https://discourse.devontechnologies.com/t/dt3-bibliography-formatted-reference-from-custom-md/48710/33)

Regarding this solution:
> I could instead offer something like http://127.0.0.1:23119/better-bibtex/item?<something>.csljson which would just return the csl-json form of the item (or anything else you’d want). 

I think it could work.

How can we test it?

Cheers!

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.99.4278](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.99.4278.xpi) ("Merge branch 'master' into devonthink")

Install in Zotero by downloading [test build 5.1.99.4278](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.99.4278.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Assuming you have Zotero installed; if you install 4278 linked to by @blip-bloop you will find the bibtex key in Zotero, and then you can call the url `http://127.0.0.1:23119/better-bibtex/items?/<bibtexkey>.csljson` and you'll get the CSL-JSON. You can do a simple test by just pasting the URL in your browser address bar, and you'll see the CSL-JSON displayed in the browser.

**Comment by retorquere** [comment]
I can also get you the notes (I see mention of notes in the discourse thread)

**Comment by bcdavasconcelos** [comment]
That would be lovely.

I had trouble retrieving the Journal name (I assume it is under the "Publication" item when item type "Journal Article" is selected).

**Comment by bcdavasconcelos** [comment]
Here is how [the script](https://gist.github.com/bcdavasconcelos/5a5c0d8c1aae10d6ee19289f3cb8670f) is coming along so far. Certainly others will improve upon it later on.

**Comment by retorquere** [comment]
CSL variables are documented [here](https://docs.citationstyles.org/en/stable/specification.html#appendix-iv-variables); I can also get you the internal representation of the Zotero item if you prefer that, but CSL is well standardized.

**Comment by retorquere** [comment]
When I export a journal article to CSL, the publication shows up as `container-title`.

**Comment by richardkaplan** [comment]
Any thoughts on how we could integrate this with DT3  so it functions similar to the existing Pubmed search script - except

- Rather than entering a search query, one would enter the BBT URL
- The script would then proceed to create a rich text document in DT3 for each citation in the BBT URL

**Comment by retorquere** [comment]
It could even use http://retorque.re/zotero-better-bibtex/citing/cayw/ to search inside Zotero to find the items of interest.

**Comment by bcdavasconcelos** [comment]
> CSL variables are documented [here](https://docs.citationstyles.org/en/stable/specification.html#appendix-iv-variables); I can also get you the internal representation of the Zotero item if you prefer that, but CSL is well standardized.

Yes, I got it right, but it isn't getting through for some reason. In the AS editor the variable is not getting the proper value.
I will check later with Christian (DT3 developer) to see if he can help figure out what is going on.

**Comment by retorquere** [comment]
Can you see it if you plug the URL into your browser? If so, it's out of my hands.

I can't help with the AS sie of things. I don't know much about AppleScript and that's unlikely to change.

**Comment by retorquere** [comment]
@richardkaplan I think what you want is for the PubMed script to call http://127.0.0.1:23119/better-bibtex/cayw?format=translate&translator=csljson instead of `pURLSearch`; you don't need  `pURLFetch` or `pURLView` because that gives you the items found directly as CSL-JSON. If you just click that URL you can see it at work; Zotero will pop up a search box and you'll get back CSL-JSON in the browser.

From there you can just replace all the XML fiddling in the pubmed script with things like `title of thePubmedArticleElement` to get properties out of the JSON object; @bcdavasconcelos script gives some samples. I've taken a stab at modifying the script but I kept getting lost in the syntactic sugar of applescript, and I can't find how to set breakpoints or print things to the console in applescript so debugging is tricky.

**Comment by richardkaplan** [comment]
That is a step in the right track except  http://127.0.0.1:23119/better-bibtex/cayw?format=translate&translator=csljson does a search by keyword for specific articles.  Is there a different search that lets me instead traverse the Zotero Collection tree and select a specific collection?

**Comment by richardkaplan** [comment]
That said, with regard to the goal of a Zotero to Devonthink data transfer link, I think there may be a much simpler solution that requires minimal if any Applescript.

Look at this example where I have been able to import web-based email into Devonthink using the indexed folder feature of Devonthink:

https://discourse.devontechnologies.com/t/cool-tip-auto-forward-office-365-email-into-dt3-zapier-indexed-dropbox-folder/48439

Queestion:  Would it be possible to take a BBT URL and have the output not be in JSON but rather in HTML?  Ideally we would have one HTML file per citation and then these HTML files would be placed in folders named based on the Zotero collections.  Really ideal would be if the format of those HTML files could be specified based on an HTML Template where the fields from the individual citations are replaced with actual data when the HTML files are created.

If you could do this then that set of folders/HTML files can be easily made part of the Devonthink database through its folder indexing feature  - thus you would not need to deal with Applescript or even Devonthink at all, except maybe a very short Devonthink script to call your new app.  The app you write to request the BBT URL and to process that data could be in any language you wish since it would be totally external to Devonthink.

**Comment by retorquere** [comment]
You can set the picker to classic mode and you'll get collections. That's not something I do, it's default functionality of zotero.

WRT outputting HTML from CAYW - it doesn't output files, you get one body of the text per invocation, and what is done with this text is out of the hands of BBT; anywhere that the concept of "multiple files" makes sense, CAYW can't do it (nor can zotero export, which also can only export a single body of text). In a more general sense, URLs can't return more than a single thing, even if that single thing can be interpreted by the receiving party as multiple things stuck together.

If you need something that saves items  to html on a schedule, that's technically possible but I'm not adding something so specialized with no overlap with BBTs mission to BBT. It could be a separate plugin. The csl-json pull-export/CAYW is part of bbt because it coincidentally worked because I added bibtex-related features, and I don't mind that at all, and I'll happily add the occasional simpel extension that builds on it, but html export has nothing to do with bibtex and it'd be a substantial addition to BBT.

**Comment by richardkaplan** [comment]
Agree on separate plugin  - will discuss elsewhere- thanks

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.101.4294](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.101.4294.xpi) ("cleanup")

Install in Zotero by downloading [test build 5.1.101.4294](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.101.4294.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
If there's nothing else to do, I propose we close the issue.

**Comment by richardkaplan** [comment]
I will test it out a bit more tonight but I belive i it is indeed fixed for now.  Thanks!
