### ISSUE TITLE
Better API description for scripting

### ISSUE THREAD

**Issue by fcastilloec** [retorquere/zotero-better-bibtex#1238]
The website has some information regarding the API for scripting, but it's very general.
I know that we can access `reference` and `item` objects, but there's no description of what fields are available.
Is there a way to debug the script? Maybe this way I can print the output of the objects somewhere to check for their content.

**Comment by retorquere** [comment]
You can ignore @blip-bloop in this instance - it's piping up because you labeled the issue as a bug (it really isn't).

The only way to debug postscripts is to add `Zotero.debug` statements. The API isn't really documented, I'll have a stab at generating jsdoc, but it's generally easier for me to just produce scripts on request. Most of the API sits in `translators/bibtex/reference.ts`, but the structure of the `item` is just the internal representation of Zotero items that Zotero hands to translators.

**Comment by fcastilloec** [comment]
Thanks so much, the changes you made to the `site/content/exporting/scripting.md` are extremely helpful! I think this will be enough to start developing more advanced scripts for my library

**Comment by retorquere** [comment]
I meant to respond once the site was live with the changes -- should be a few minutes more.

**Comment by retorquere** [comment]
It's always still OK to just request a script.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.127.4457](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.127.4457.xpi) ("fixes #1238")

Install in Zotero by downloading [test build 5.1.127.4457](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.127.4457.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
(forget about that build)
