### ISSUE TITLE
JSON/YAML format for pull export

### ISSUE THREAD

**Issue by danmackinlay** [retorquere/zotero-better-bibtex#1268]
[pull export](http://retorque.re/zotero-better-bibtex/exporting/pull/) is amazing and I use it very heavily. There are various difficulties with bibtex/biblatex support, to do with those formats being messy. It would be great if the pull export also supported `Better CSL YAML` and.or `Better CSL JSON` which are much easier for the end-user to massage, in addition to the BibTex/BibLatex currently supported.

**Comment by danmackinlay** [comment]
Oops, this is clearly an enhancement not a bug. I don't think I can edit the labels here though.

**Comment by retorquere** [comment]
That's OK. I'll update the documentation but your can already get csl-json by ending the pull url with `.csljson` or `.cslyaml` instead of `.biblatex`. AAMOF for any of the BBT formats you can pull-request them by ending the url in their format name, stripped of `better` and lowercase it, or any other format zotero supports by ending it in the translator guid you find in their header.
