### ISSUE TITLE
Exporting is slow again

### ISSUE THREAD

**Issue by rcoreilly** [retorquere/zotero-better-bibtex#1287]
**Exporter used:**

Better BibTeX

**Expected behavior:**

Second full export would be reasonably fast, under a minute hopefully, for my CCNLab group library which I just invited you to join for testing, which has 24,350 items.

**Actual behavior:**

First full export took well over 15 minutes, and second and subsequent ones took 6 minutes. At one point it was down to ~20 sec or so, but it seems like it has been slow like this for a while, but now I'm finally writing a paper so I really notice it. :)

**Comment by retorquere** [comment]
I see (I think) you've shared your library with me, but cache use (which must be the issue here) is dependent on your settings. It'd be helpful if you could enable debugging (see 2nd point from @label-gun), export your library as you would normally, and then right-click your library, and send a BBT debug log from there. That will give me a full copy of your library, your BBT settings, and a copy of the items in your library for testing.

**Comment by rcoreilly** [comment]
JR75IZ53-euc is the report number.   thanks!

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.139.4698](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.139.4698.xpi) ("make logging easier to trace")

Install in Zotero by downloading [test build 5.1.139.4698](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.139.4698.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
4698 doesn't change anything but will make it easier for me to trace the logs (which are pretty big in your case). Can you:

1. Enable debug logging as earlier
2. Export as you would normally
3. Export again as you would normally (since this should hit the cache)
4. Right-click the group or library you were exporting, and select "Send BBT debug log" (it looks like `JR75IZ53-euc` was sent from the Help menu, which does something slightly different -- in the debug log popup, you should find a "References" tab). While we're at it, check the "Send cache" checkbox. Maybe it will give me some clue as to what is happening.

Between 2. and 3. I should be able to find either why the cache is being dropped, or if not, hopefully some indication of why it's not being used.

**Comment by retorquere** [comment]
It's not structurally broken, at least, because this test passes:

```
When I import 15120 references from "export/*.json" : ✓ in 1403.217s
Then an export using "Better BibTeX" should match "export/*.bibtex" : ✓ in 285.561s
And should take less than 300 seconds : ✓ in 0.000s
And an export using "Better BibTeX" should match "export/*.bibtex" : ✓ in 27.523s
And should take less than 50 seconds : ✓ in 0.000s
```

(with times tested against the line above, so first-export is 285.561s uncached,, and second export hits the cache and takes 27.523s)

**Comment by rcoreilly** [comment]
done: D1162101057

**Comment by retorquere** [comment]
That's a Zotero debug log, I can't access those (that dialog also won't have had the `send cache` checkbox)

**Comment by rcoreilly** [comment]
doh.  IQ3KKDEL-euc

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.139.4703](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.139.4703.xpi) ("logging")

Install in Zotero by downloading [test build 5.1.139.4703](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.139.4703.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
In that log I see that most times you are actually hitting the cache, but the 2nd export is actually slower than the first. Can you get me a new log from 4703?

I'm pretty sure IQ3KKDEL-euc was sent from the Help menu. It helps, but it would be very helpful if you could again:

1. Enable debug logging as earlier
2. Export as you would normally
3. Export again as you would normally (since this should hit the cache)
4. Right-click the group or library you were exporting, and select "Send BBT debug log", making sure you see a "References" tab, and check the "Send cache" checkbox

Step 4 is likely different from what you did for IQ3KKDEL-euc -- when you submit from the Help menu, you won't see the References tab in the debug submission screen.

**Comment by retorquere** [comment]
For step 4 I mean I'd prefer the log to be sent from the right-click menu itself as highlighted in blue here.

<img width="1680" alt="Screenshot 2019-09-15 at 02 18 16" src="https://user-images.githubusercontent.com/132108/64915079-2a1e3b00-d75f-11e9-933d-be4787a309ff.png">

**Comment by rcoreilly** [comment]
DW78DW6G-euc

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.139.4706](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.139.4706.xpi) ("more logging")

Install in Zotero by downloading [test build 5.1.139.4706](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.139.4706.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
(forget 4706 if you saw that come by)

Super, I have the references now (although if you did check "send cache", that functionality seems broken for you, it was not included in the log).

I didn't include all the logging I needed so a new build is underway, but in the interim -- exporting 24k items in 20 seconds would mean that each item needs to be handled in less than a millisecond (including cache retrieval and writeout) and I don't think I've ever hit that. The (entirely non-scientific) tests I did long ago put cached writeouts at 3 milliseconds, and I don't think BBT has gotten 3 times faster since.

In my own tests, the cache still makes a considerable difference (around an order of magnitude) but that still makes for 1.9ms per item on my fairly fast machine. In your case however I'm seeing something I really did not expect:

```
Better BibTeX export took 549618, cache: {"hits":0,"misses":24352}
...
Better BibTeX export took 437542, cache: {"hits":24352,"misses":0}
```

which would mean that for you, fully cached exports are only barely faster (a factor 1.2 rather than a factor 10) which I can't yet explain. A new logging build is building and will be announced soon, I'll need a new 4-step dance from you, because I can't replicate this on my end.

**Comment by rcoreilly** [comment]
thanks!  I didn't click "send cache" -- will do so next time.  I'm just curious overall about what scope of computation is going on that takes such a long time per item?  It seems much longer overall than one would expect for transforming strings and writing them out to a file -- is it going over the network or something like that?

**Comment by retorquere** [comment]
It's not going over the network, but each item needs to be found in the cache according to (currently) 9 criteria -- even indexed, that takes time, and then there's the fact that strings in JavaScript are immutable, so assembling text also takes time. There's also some things I cannot escape -- Zotero hands me the items to export one-by-one, and even though I've also cached the Zotero DB-to-export-object transformation that would usually happen at this point, all this interaction between Zotero and the translator takes time (which is included in the 1.8ms I'm currently clocking per cached item).

But that's if I'm *not* transforming the strings. Converting Zotero items to bibtex is dog slow because the models for items don't match so I have to make lots of choices, and if you're doing transcoding of unicode to LaTeX (which you are), I have to do a lookup for every single character and assemble those into strings. Stock Zotero BibTeX is lots faster probably mainly because their lookup table is smaller, and they make less choices than I do.

That said, on my machine 24k items should be doable in under a minute.

**Comment by retorquere** [comment]
(as things stand currently, you don't need to send the cache, the log shows that the items are being found in the cache successfully)

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.139.4707](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.139.4707.xpi) ("more logging")

Install in Zotero by downloading [test build 5.1.139.4707](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.139.4707.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Can you get me the 4-step again with 4707? No need to send cache.

To get an idea of the lower bound of export time, you can export to `BetterBibTeX JSON`. That does almost nothing to the items it exports, using no export caching (but it will use Zotero DB-to-export-object transformation cache). It will be anywhere between extremely hard and impossible to make a translator faster than that (and without BBT it would usually be slower since you the serialization that's cached by the Zotero DB-to-export-object transformation cache is pretty slow).

**Comment by retorquere** [comment]
It literally takes over an hour to load your references in. Would you be OK with giving me a copy of your Zotero databases? That would be 

* zotero/zotero.sqlite
* zotero/better-bibtex.sqlite

make sure that Zotero is **not running** when taking a copy. If you see a file with `journal` in the name, Zotero is still running.

**Comment by rcoreilly** [comment]
SXTXJ4G8-euc -- would it still be useful to send you my raw db's?

**Comment by rcoreilly** [comment]
takes about 24 sec to export in json format.  sent you my db's

**Comment by retorquere** [comment]
The raw DBs would have saved me an hour of loading, but my test suite runs on the assumption that items are in the user library, and I haven't found a way to safely (and quickly) move everything from a group to the user library. I'm loading SXTXJ4G8-euc and I can save the DB after that is finished.

**Comment by retorquere** [comment]
The raw DB you sent has 24354, where SXTXJ4G8-euc has 24352. For my tests I need them to be the same. I'll try to find out which those two are, but if you could send me a new raw-DB/debug log pair that'd be really helpful.

**Comment by rcoreilly** [comment]
people are constantly adding things!  why does it have to be the same?

**Comment by retorquere** [comment]
I'll try to find the mismatch. It's just how my tests are set up currently -- I do cross checks to make sure my tests give consistent results.

**Comment by retorquere** [comment]
I've found the mismatch, but I still can't replicate the problem -- on my system, first export is 333 seconds, 2nd export is 53 seconds.

**Comment by retorquere** [comment]
Looking at my logs, it looks like my export is doing the same activities as yours, yours just takes massively longer (2.14ms/item vs 17.55ms/item)  for the cached export. I'm trying to think of reasons for this, but the only immediate difference I see is that you have Zotfile installed, and I can't think of a single reason why that should make a difference. How much memory does your system have? If you're running out of memory and dipping into the swap that would explain everything, but it doesn't seem likely to me you'd try to have such a massive library on a memory-constrained system.

**Comment by rcoreilly** [comment]
I have 16gb RAM and its a late 2016 MacBook Pro, 4 CPU / 8 HT system.  Is there anything like a profiler for this code?

**Comment by retorquere** [comment]
16GB is what I have, so that's not it. I'll try to think of another cause... puzzling though.

**Comment by retorquere** [comment]
There's at least one thing that's different -- your logs shows `Running handler 0 for itemDone` for every item saved, and that whatever happens there takes the bulk of the cached export time -- between that and the time I get my next item to export, 16 - 20 ms passes, and in your case, that adds up to a lot. I don't yet know why this is happening, but it's not something BBT does. I'll try the Zotero forums.

**Comment by rcoreilly** [comment]
I just tried doing exports with all add on's disabled except for BBT, with no difference in performance unfortunately :(

**Comment by rcoreilly** [comment]
is it possible that there is some difference in a group library vs. an individual user library?  perhaps some additional sync event that is taking place when an item is done?  you said you only test on user library not group?

**Comment by retorquere** [comment]
Can you get me a new log with all other extensions removed?

I should hope group vs user lib makes no difference, but can you share that group to zotero user bbt1287? I really don't want to have that large a group in my main profile, zotero starts up incredibly slow with that many items.

**Comment by rcoreilly** [comment]
It's not THAT bad :)  anyway, I shared it.  in the course of turning on / off extentions etc it updated to a current version of BBT, not the test versions you had me using before -- is that OK for the debug log?

**Comment by retorquere** [comment]
It's prohibitively bad for me - startup takes close to a minute, and I restart often (once every test run, and I run a lot of tests).

**Comment by rcoreilly** [comment]
can you test this group thing in a separate account or something like that?

**Comment by retorquere** [comment]
That's what the bbt1287 account is for. I can start Zotero with a new profile just for this test and sync with that account.

**Comment by retorquere** [comment]
Wow sync has been running for two hours straight and still not done.

**Comment by retorquere** [comment]
OK so I'm also seeing `Running handler 0 for itemDone` but it's taking a much more friendly 2-4ms, whatever it's doing.

I've posted on zotero-dev to see if they can give some insights on what's happening, but as far as I can tell right now, most of the difference between your experience and mine is that the itemDone handler is doing something heavy on your end -- if that's true, then it'd be out of my reach.

**Comment by rcoreilly** [comment]
Any ideas about what that ItemDone handler is all about?  I did some googling and it appears to be perhaps connected to PDF's - did you end up with all our PDF's in your massive sync, or not?  maybe it is doing something expensive on every PDF attachment?  I've got my setup configured to download all PDF's..

**Comment by retorquere** [comment]
I'm seeing the same slowdown on a new run now, and that isn't in `itemDone` but in my cache fetch. Hopefully this is reproducible in tests, maybe I'm not hitting an index.

**Comment by retorquere** [comment]
Can you give 4786 a spin? First export will be slow because installing a new BBT drops the cache.

**Comment by rcoreilly** [comment]
You've fixed it!!  super fast the second time!  758UBJS8-euc

**Comment by retorquere** [comment]
Awesome. New version has been released.

What it turned out to be was not the cache fetch, but the cache touch. Never would have thought.

Sorry for the long diagnosis and needing so many logs. I don't meet many libraries this big. I've added it as a test now so a regression should be spotted in the nightly test.
