### ISSUE TITLE
Feature suggestion: Show *BibTeX* server URL

### ISSUE THREAD

**Issue by Blaisorblade** [retorquere/zotero-better-bibtex#1291]
### Suggestion
Could you add some way to show the BibTeX server URL (another item, a checkbox somewhere, ...), near to "Show BibLaTeX server URL"?

### Rationale

The point is to highlight one has a choice. After reading #918, I looked at the URL and changed `.biblatex` to `.bibtex`; but I suffered #918 for long because I didn't know I had an option (nor that it fixed an issue I had).
(And I can't switch to biblatex, sorry — publishers decide, not me).

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.142.4802](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.142.4802.xpi) ("pull-request: allow picking format")

Install in Zotero by downloading [test build 5.1.142.4802](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.142.4802.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Can you try 4802?

**Comment by Blaisorblade** [comment]
Cool, thanks for the prompt reply! And yeah, that'd be cool.

Nitpicks you might know:
- is "pull-request URL" meant to appear in the GUI? It's in "Show Better BibTeX pull-request URL" and the dialog. "Server URL" or "library export URL" seems better?

- Silly Q. I see 4 formats (including those I want) — Export library seems to have 6 from BibTeX, not sure if the other twos should be there?

**Comment by retorquere** [comment]
"Show Better BibTeX pull-request URL" disappears from view once the popup shows so I'd prefer to have at least some context on what's being shown. Maybe other platforms show more, but on MacOS, other than "Pull-request URL" there's no other indication what's being offered. "Server URL" is a bit too generic because BBT alone hosts several server URLs for various integrations, and Zotero also hosts its own server URLs.

WRT the missign translators: the other two would be `Better BibTeX Citation Key Quick Copy` and `BetterBibTeX JSON`:
  * `Better BibTeX Citation Key Quick Copy` really is meant for copy-paste/drag-drop, it just produces citekeys with some context for specific editors,
  *  `BetterBibTeX JSON` is just a slightly-polished dump of the objects as Zotero hands them to translators, and the primary use is for producing debug logs for me.

If I could hide these two form the Zotero UI, I would. It's technically possible to pull any export translator format you want from the pull request (eg http://127.0.0.1:23119/better-bibtex/library?/1/library.32d59d2d-b65a-4da4-b0a3-bdd3cfb979e7 to get RIS, or http://127.0.0.1:23119/better-bibtex/library?/1/library.36a3b0b5-bad0-4a04-b79b-441c7cef77db to get BBT JSON), but that's not really its intended purpose, and I don't really want to build an UI for it.

**Comment by Blaisorblade** [comment]
>  I'd prefer to have at least some context on what's being shown.

Some context, yes. But IMHO "pull request" is very confusing.
These URLs let you export the collection, no? That's why I proposed "library export URL", but I think I'd be happy with anything else.

I never heard "pull request" outside of "GitHub pull request" (and Google seems to agree), which this doesn't mean. I first thought that was a bug, or it was a special build from some GitHub pull request.

And even now, I have no idea how "pull request" relates to "library export" (sure, there's an HTTP request, but that's as helpful as "server URL").

Anyway, that was my 2 cents. The original issue is solved, so closing.

**Comment by retorquere** [comment]
I see your point, but then "library export" in Zotero usually means that the user initiates an export, and this doesn't actually export anything at that point - if you call that url, you get a copy of the library at that time. I agree that pull export is too technical. I'll see what the biblatex manual says about it (this was initially for biblatex only, as that can do a pull during compile). I'm open to other wording, but "export" sounds to me like it's being exported when you click the option, and that it doesn't.

(I'm keeping the issue open until I've merged it into a new release btw, lest I forget)

**Comment by Blaisorblade** [comment]
I see... for me it's implied by "export URL", but I see your point. Naming's hard.

**Comment by retorquere** [comment]
Yeah, it is. I think I picked pull export way back when in opposition to push export (auto-export) because it highlights who initiates the action. Likewise I now wonder about whether URL might not be overly technical... but then, outside people using it for biblatex, you'd have to be fairly technical to know what to do with the url at all.

**Comment by retorquere** [comment]
How about "on-demand export"?

**Comment by Blaisorblade** [comment]
Yeah that's cool with me. "On-demand export URL", still (yes, URL is a technical term, but one that the target audience probably knows).

**Comment by retorquere** [comment]
Our just something with Download

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.142.4804](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.142.4804.xpi) ("change strings")

Install in Zotero by downloading [test build 5.1.142.4804](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.142.4804.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
How about 4804?

**Comment by Blaisorblade** [comment]
Better, thanks!

BTW: will this auto-upgrade to the next non-test release?

**Comment by retorquere** [comment]
Yep!
