### ISSUE TITLE
Month field not enclosed in braces

### ISSUE THREAD

**Issue by kirk86** [retorquere/zotero-better-bibtex#1407]
I think that the bbt is not enclosing the filed `month` in braces `{}` which makes it difficult for other normalising software to parse the bib file.

I'm posting it as a question because I don't know if it's a bug or a feature?

**Comment by retorquere** [comment]
I'll need a debug log.

**Comment by kirk86** [comment]
As I said I don't know if bibtex provides a ubiquitous unified grammar for how entries should be formatted? A similar discussion [here](https://github.com/ge-ne/bibtool/issues/66) towards the end.

This is what I see in the exported `.bib` file
```
article{zou2005,
  title = {Evolutionary Selection},
  author = {Zou, Hui},
  year = {2005},
  month = apr,
  volume = {67},
  pages = {301--320},
  urldate = {2019-05-05},
  number = {2}
}

@article{zrnic2019,
  title = {Natural {{Analysts}}},
  author = {Zrnic, Tijana},
  year = {2019},
  month = jan,
  urldate = {2019-05-31}

```

**Comment by retorquere** [comment]
I really need that debug log.

**Comment by kirk86** [comment]
Here
```
Report ID: KB6MJNX7-euc
```

**Comment by retorquere** [comment]
Thank you. Yes, I have that reproducible, but I had forgotten that [BibTeXing]( http://ctan.cs.uu.nl/biblio/bibtex/base/btxdoc.pdf) says:

> **month** The month in  which  the  work  was  published  or,  for  an  unpublished work, in which it was written.  You should use the standard three-letter abbreviation, as described in Appendix B.1.3 of the LATEX book

which is so that language-sensitive styles can replace `jan` with `январь` for example. [Tame the BeaST](http://ctan.cs.uu.nl/info/bibtex/tamethebeast/ttb_en.pdf) confirms this reading, so I see this as a feature. What are you using for normalizing? Maybe it's something that's easy to fix in their parser.

**Comment by kirk86** [comment]
> What are you using for normalizing?

 I used bibtool in the thread I liked above I tried a regex which is pretty normal for bibtool to use regexs but didn't work, maybe the regex is not correct

If you're using anything different can you suggest what/why?

**Comment by retorquere** [comment]
Most regex engines can't parse nested structures (which bibtex files can be and often are) because nested structures aren't regular. Some engines have been augmented to allow it, but it's not easy to get right.

I don't have a tool; BBT's parser is available as an [npm module](https://www.npmjs.com/package/@retorquere/bibtex-parser), but constructing a roundtrip tool from that will be hard.

In the discussion on the bibtool repo you say "the reference manager that's doing that", but that's not BBTs output right? BBT generates `jan`, not `{jan}`, and I see the reference type is capitalized, so that can't be BBT.

But in the discussion on the bibtool repo I see the dev [agreeing with the BBT output](https://github.com/ge-ne/bibtool/issues/66#issuecomment-577283871), so bibtool will be able to parse `month = jan`, right? So there isn't a problem? I'm not familiar with bibtool, so I don't fully understand what's being discussed there.

Can a postscript not do what you want?

**Comment by retorquere** [comment]
(bibtex does define a grammar but you'll need a parser to read it. The rules for parsing bibtex are not simple)

**Comment by retorquere** [comment]
`jan` is just a pre-defined `@string` BTW. `@strings` can turn up in other places and they should parse correctly by whatever tool you end up choosing:

```
@string{analysts = {Analysts}}

@article{zrnic2019,
  title = "Natural " # analysts
  author = {Zrnic, Tijana},
  year = {2019},
  month = jan,
  urldate = {2019-05-31}
}
```

is valid bibtex.

Strange though that `urldate` is in the export. BBT shouldn't export `urldate` without an `url` field present.

**Comment by kirk86** [comment]
> is valid bibtex.

Ok, yes I wasn't sure about that whether it valid bibtex and apparently seems to be the appropriate for this particular type of field.

> Strange though that `urldate` is in the export. BBT shouldn't export `urldate` without an `url` field present.

Don't worry about that I deleted the `urldate` to keep things simple in the example. Sorry!

**Comment by retorquere** [comment]
BTW did BBT generate `title = {{{Another Capitalised Title which is Wrong}}}`? I can't readily think of a way to generate that with BBT. I wouldn't have enclosed `which is` this way.

**Comment by kirk86** [comment]
> BTW did BBT generate `title = {{{Another Capitalised Title which is Wrong}}}`? I can't readily think of a way to generate that with BBT. I wouldn't have enclosed `which is` this way.

Well, if you think about it I'm only interfacing with zotero to input/edit/delete references then BBT kicks in to export and keep the `.bib` file updated. So I presume that those `{{{ }}}` multiple braces are either by zotero when importing refs from the web and then BBT just dumps that as it is in the .bib file or somehow BBT does that on its own (which at this point you know way more on how things work behind the scenes.)

**Comment by retorquere** [comment]
I can't tell how a reference got into Zotero, but I'd be interested in getting a debug log on the item that generated `{{{Another Capitalised Title which is Wrong}}}`. This is most likely BBT output (the double braces are an implementation artefact that seems fairly unique to BBT), at the least I'll be able to explain why it's happening, but text like the all-lowercase `which is` is not usually included in those braces.

**Comment by kirk86** [comment]
> I'd be interested in getting a debug log on the item that generated

Hope this helps :wink: 
`Report ID: ABQSXBXS-euc`

**Comment by retorquere** [comment]
For me, that reference with your current settings yields

```
title = {Neural {{Architecture Search}} with {{Reinforcement Learning}}},
```

which is what I had expected. Items in Zotero should have titles sentence-cased BTW, not Title-Cased. If you sentence-case that title, the extra braces go away, but as it stands, the extra braces disclose the intent (whether it's there deliberately or not) of what's in Zotero.

**Comment by kirk86** [comment]
> Items in Zotero should have titles sentence-cased BTW, not Title-Cased

If I understand correctly you're saying that if this
`title = {Neural {{Architecture Search}} with {{Reinforcement Learning}}},`
is changed into this
`title = {Neural {{architecture search}} with {reinforcement rearning}}},`
the extra braces go away?

Is this controlled by some setting to something in zotero or BBT?

> (whether it's there deliberately or not

Definitely not deliberately on my part

BTW most papers' titles are like that `Title-Cased` and not `sentence-cased` and other titles might include extra characters such as `:, -, &`

**Comment by retorquere** [comment]
> `title = {Neural {{architecture search}} with {reinforcement learning}}}`, the extra braces go away?

Sort of -- you wouldn't enter `Neural {{architecture search}} with {reinforcement learning}}` in Zotero. In Zotero, you now have `Neural Architecture Search with Reinforcement Learning`. But Zotero expects titles to be entered in sentence case, and if you make exceptions to that (by capitalizing words), that means to Zotero "this is probably a proper noun, whatever you do with case-changes, exempt this". This makes it so that `I still have ISDN` doesn't come out as `I Still Have Isdn` when you generate a bibliography. To get the equivalent result in bibtex, you need those braces. But if you entered `Neural architecture search with reinforcement learning`, BBT would generate `Neural Architecture Search with Reinforcement Learning`.

There is also a setting in BBT that controls this ([here](https://retorque.re/zotero-better-bibtex/installation/preferences/advanced/#apply-title-casing-to-titles) and [here](https://retorque.re/zotero-better-bibtex/installation/preferences/advanced/#apply-brace-protection-to-capitalized-words)), but I don't generally recommend it. One of the effects of this is that if you use both Word/LibreOffice and LaTeX for document authoring, your references can come out cased differently. Storing the titles in Zotero in sentence case (which is how Zotero expects them) would prevent this.

BBT imports apply sentence-casing on import, but it's a minority of items that come into Zotero by way of the BBT import. Many import/web translators don't sentence case. Not all can in fact. This happens often enough that when you right-click a title in Zotero you will be presented with an option to sentence-case the title.

> Definitely not deliberately on my part

That's the problem. I can't see whether it's deliberate or not, so I have to assume it is.

> BTW most papers' titles are like that Title-Cased and not sentence-cased 

If they are in bibtex, that's actually the way it's supposed to be, and BBT will convert to sentence case on import. I can't vouch for what other translators do.

> and other titles might include extra characters such as :, -, &

That's not a problem. BBT assumes that what is in Zotero is free text and translates to valid latex during export.

**Comment by kirk86** [comment]
> But if you entered `Neural architecture search with reinforcement learning`, BBT would generate `Neural Architecture Search with Reinforcement Learning`.

The devil is always in the details isn't it?



> but I don't generally recommend it.

So the verdict is to leave things as is?

> you will be presented with an option to sentence-case the title.

Didn't know about this!

> That's the problem. I can't see whether it's deliberate or not, so I have to assume it is.

Try it for yourself, use [this](https://arxiv.org/abs/1906.00472) and import it in zotero. Then check the BBT export. In my case I see:
```
title = {Aging {{Phenomena}} during {{Phase Separation}} in {{Fluids}}: {{Decay}} of Autocorrelation for Vapor-Liquid Transitions},
  shorttitle = {Aging {{Phenomena}} during {{Phase Separation}} in {{Fluids}}},
``

**Comment by retorquere** [comment]
Yeah, but you have to admit that you can't blame the arXiv importer for those results; the title on that page is

> Aging Phenomena during Phase Separation in Fluids: Decay of autocorrelation for vapor-liquid transitions

which is a strange mix of title case and sentence case. Since Zotero nor BBT is crazy enough to do natural language parsing, both would have to assume that `Phenomena` and `Phase Separation` and `Fluids` are proper nouns. In any case, BBT is not involved with this import. BBT can't tell whether this was imported, or entered by you by hand.

> So the verdict is to leave things as is?

That's always up to you, but if you care about referencing, and you want to also use these in Word/LibreOffice at some point, I'd fix that title. This particular title is wrong in any case -- I don't know of a single style that has a mixed sentence-title case policy, and at my uni, you'd likely get points docked if you had many of these.

**Comment by kirk86** [comment]
> the title on that page is

That is 99.9% of what titles on arxiv look like and yup and I don't blame the importer.
 

> I'd fix that title

So I suppose a viable way would be to use one of the config methods you showed cause I didn't all of a sadden go mad and start right clicking on each entry individual to sentence-case?

**Comment by retorquere** [comment]
That's viable, yes.

**Comment by retorquere** [comment]
But I don't know what the results would look like across styles, because the generated bibtex would still be mixed sentence-title case.

**Comment by kirk86** [comment]
My understanding from discussions with the author of bibtool is that nested braces are unnecessary regardless of case (Unless if I understood wrong?)

**Comment by retorquere** [comment]
Case in what sense?

**Comment by kirk86** [comment]
> Case in what sense?

Regardless of it's sentence-case/title-case or mixup

**Comment by retorquere** [comment]
He's mostly right. I take it you are referring to

> The recommended way is to write 
> `title = {Another Capitalised Title which is Wrong}`
> Double braces are never needed. And single braces in title and booktitle only. And just in case they contain an acronym or TeX constructs like
> `title = {{iSAQB] tips {\&} tricks}`

Which is right but doesn't cover all cases. I agree with this recommended way, but the Zotero counterpart to this is `Another capitalised title which is wrong`. If you have that in Zotero, you get the recommended output above. But if you have `Another Capitalised Title which is Wrong` in Zotero, that simply means something substantially different, and that difference is found in the output of BBT.

WRT the double braces, that is an implementation artifact to simplify BBT. BibTeX case handling is very regular, but the resulting behavior is [pretty complex](https://retorque.re/zotero-better-bibtex/support/faq/#why-the-double-braces), and with the double-bracing, I get a simple way to get the desired result. For an example: 

* `\emph{ISDN}` is case-protected.
* `{\emph{ISDN}}` is *cancels* case protection on `ISDN`, and styles that change case may turn this into `Isdn`, or `isdn`.
* `{{\emph{ISDN}}}` is case-protected

and there's a myriad of other things to account for. So he's right that the double-braces are not strictly necessary, but they're also valid and harmless, and it simplifies BBT. Trust me, BBT doesn't need any more complexity than it already has.

I have the author of `biber` (plk) drop in every once in a while, and njbart who knows so much about the behavior of bibtex I suspect he does nothing else 25hrs a day. This part of BBTs behavior is one of the things that came about under their guidance, and it would take a solid counter example to make me consider changing it. I know it's not pretty, and I'd love to see it simpler, but it'd probably take BBT to a level of complexity which I'd find hard to oversee (and part of BBT is there already), which is a maintenance nightmare.

**Comment by retorquere** [comment]
Are you satisfied with this answer?

**Comment by kirk86** [comment]
Absolutely, thanks :wink:
