### ISSUE TITLE
Installation error in Zotero 5.0.85 running on Ubuntu 19.10 

### ISSUE THREAD

**Issue by llukedevlin** [retorquere/zotero-better-bibtex#1483]
Error message: Add-on installation Failed: the addo-on "Zotero Better Bib(La)Tex" could not be installed. It may be incompatible with this version of Zotero". 

Debug output: 

1586185892753	addons.xpi	WARN	Add-on better-bibtex@iris-advies.com is not compatible with application version.

1586185893678	addons.update-checker	WARN	Request failed: https://github.com/retorquere/zotero-better-bibtex/releases/download/update.rdf/update.rdf - 404: Not Found

version => 5.0.85, platform => Linux x86_64, oscpu => Linux x86_64, locale => en-GB, appName => Zotero, appVersion => 5.0.85, extensions => Zotero LibreOffice Integration (5.0.22.SA.5.0.85, extension)

**Comment by retorquere** [comment]
Can you upload the extension you have downloaded somewhere that I could access it? Maybe something like

```
curl -F'file=@zotero-better-bibtex.xpi' https://0x0.st
```

**Comment by llukedevlin** [comment]
No problem, here it is: https://0x0.st/iuUz.xpi

**Comment by retorquere** [comment]
I can install that file on Mac Zotero just fine, and I know it should work on Linux because that's what Travis uses for its tests. I've b0rked my wired network so I can't currently reach my own Linux desktop, but I'll see if I can fix that tomorrow.

**Comment by retorquere** [comment]
I just found the discussion at https://forums.zotero.org/discussion/comment/352776 -- that's really important information, because there may be something wrong with the profile rather than with BBT. Before I go through the effort of replicating the problem, can you test whether you can replicate it on your own system in a clean profile? If that works, there's nothing I can do, then it's a Zotero issue/profile issue.

**Comment by llukedevlin** [comment]
Thank you for finding that information. I deleted the old profile and tried a clean profile, and can confirm that it installs correctly now, so the profile was wrong somehow. Thanks.
