### ISSUE TITLE
Better Bibtex exported bib file has syntax errors? 

### ISSUE THREAD

**Issue by cottrell** [retorquere/zotero-better-bibtex#1484]
I just installed the latest version to see if this was fixed but I seem to still get errors when I try to build with bibtex. 

```
Database file #1: mylibrary.bib
I was expecting a `,' or a `}'---line 370 of file mylibrary.bib
 : 
 : @article{arazi_bridging_2004,
(Error may have been on previous line)
I'm skipping whatever remains of this en
```

Exporting as vanilla bibtex (no better bibtex) results in no errors on build. 

What can I do to be a bit more precise in debugging this so this is a more helpful bug report?

**Comment by cottrell** [comment]
I found the issue, this line is not being escaped properly by the exporter. 

  abstract = {\href{/cgi-bin/nph-data_query?link_type=EJOURNAL&bibcode=2007PhyD..230Electronic Article Available50A}{ from \href{http://www.elsevier.com}{Elsevier Science.}},

**Comment by cottrell** [comment]
This is what that line looks like in the plain bibtex export (that works): 

`        abstract = {{\textless}A HREF="/cgi-bin/nph-data\_query?link\_type=EJOURNAL\&bibcode=2007PhyD..230...50A"{\textgreater}Electronic Article Available{\textless}/A{\textgreater} from {\textless}A HREF="http://www.elsevier.com"{\textgreater}Elsevier Science.{\textless}/A{\textgreater}},`

**Comment by retorquere** [comment]
I will still need a debug log as described by label-gun in point 1

**Comment by cottrell** [comment]
I think this is the debug ID

D664492460

**Comment by retorquere** [comment]
That's a Zotero debug ID, I have no access to those. If you follow the steps label-gun describes in point 1 I get a debug log that I can access.

**Comment by retorquere** [comment]
I really cannot do anything without a BBT debog ID.

**Comment by cottrell** [comment]
I posted something last night but is not showing up ... so unfortunately I lost the original text that caused the break. I tried to paste the things I posted above back in and repdroduce the error but not luck so far. Tried a bunch of combination with underscores and ampersands. You can see it was not escaping the underscore in the first case. 

Anyway, I think we should just close this and I'll repopen if I can get it to reproduce. I do have all the old version of the bibtex file (produced by the plan bibtex method) if you have any other guesses on what string in the abstract might reproduce am happy to try. 

This thread will still help anyone who might hit this probably and land here. Basic fix is just to find the entry in zotero and remove and weird character combination likely in a URL.

**Comment by retorquere** [comment]
That should really not be necessary. BBT should output valid bibtex under all circumstances. The sample unfortunately doesn't help me because I have as of yet no idea how I would cause BBT to output that.

**Comment by retorquere** [comment]
Did you load the `hyperref` package BTW? `hyperref` is needed to render URLs. 

I'm trying to find the docs but the standard Zotero bibtex exports `_` as `\_` because it exports the `<A HREF>` as `{\textless}A HREF{\textgreater}`. BBT exports it as `\href{...}`, and the URL part in `\href` is `verbatim`. In `verbatim` mode, underscores must not (not "do not have to be" -- "must not") be escaped.

**Comment by retorquere** [comment]
I do get an error with the sample above, but that's because the braces are unbalanced. As said, I wouldn't know how to cause BBT to do that, which is why I need the sample.

**Comment by cottrell** [comment]
Yes, definitely use hyperref outside of the bibliiography. It is definitely something subtle as merely pasting that in to the abstract and re-exporting did not cause the issue.

**Comment by retorquere** [comment]
That comes across as pretty hostile. I have no idea what set that off, but it isn't helpful in figuring out the cause of the problem you're experiencing. I don't understand from the last description ehat you pasted into the abstract, but it looks to me like it's trying to communicate frustration, not information I can use to solve your problem. 

For diagnosis, I need a debug report from a zotero item that exports something that doesn't work right. If your question is "can BBT export so that no extra packages are required", or "can BBT export so that it indicates what packages are required", that's something I could look at.

In the interim, since you are obviously not using the exported abstract (because what the standard zotero bibtex exporter produces clearly isn't what you'd want to render), I would suggest adding `abstract` to the BBT skip fields.

**Comment by retorquere** [comment]
Also, what's below compiles without error on Overleaf (notice that it does *not* load any packages besides `biblatex` for biblatex) if I add the missing brace at the end of `abstract`. In many cases, `href` is simply loaded by the environment, so my question was whether you could verify this.

biblatex:
```
\documentclass{article}
\usepackage[style=apa,backend=biber]{biblatex}

\begin{filecontents}{\jobname.bib}
@article{test,
      title = {Title},
      abstract = {\href{/cgi-bin/nph-data_query?link_type=EJOURNAL&bibcode=2007PhyD..230Electronic Article Available50A}{ from \href{http://www.elsevier.com}{Elsevier Science.}}}
}
\end{filecontents}
\addbibresource{\jobname.bib}
\begin{document}
\nocite{*}

\printbibliography
\end{document}
```

bibtex:
```
\documentclass{article}

\begin{filecontents}{\jobname.bib}
@article{test,
      title = {Title},
      abstract = {\href{/cgi-bin/nph-data_query?link_type=EJOURNAL&bibcode=2007PhyD..230Electronic Article Available50A}{ from \href{http://www.elsevier.com}{Elsevier Science.}}}
}
\end{filecontents}

\begin{document}

Random citation \cite{test} embeddeed in text.

\bibliography{\jobname} 
\bibliographystyle{ieeetr}

\end{document}
```
