### ISSUE TITLE
Sentence-casing at import

### ISSUE THREAD

**Issue by yolcu** [retorquere/zotero-better-bibtex#1486]
Better BibTeX FAQ explains that titles are automatically converted into sentence-case when importing items. Then, when exporting to Bib(La)TeX, some characters are protected via braces. I have two questions about this:
1. Is automatic sentence-casing currently supposed to be working without requiring me to do anything? Because I just can't get it to work even with a clean new profile in Zotero to prevent potential clashes with other settings. I set the corresponding setting to convert unconditionally (even if the title is guessed to already be in sentence-case), yet whenever I try to import an item from Firefox via the Zotero Connector the title is copied as is without getting sentence-cased.
2. For items with sentence-cased titles, export puts braces as intended. However, it does this not only for the title field but also for things like booktitle, publisher, series, etc. Is this intended? If I were to write a Bib(La)TeX entry by hand, I would not put braces in, say, a conference proceedings title since this does not get sentence-cased according to APA. In the end, should every single field be in sentence-case in Zotero for the braces to be inserted properly (as I would do by hand)?

If these are bugs, I can make a bug report in the proper format but I am not sure whether I am experiencing the intended behavior or not.

Thank you.

**Comment by retorquere** [comment]
> Better BibTeX FAQ explains that titles are automatically converted into sentence-case when importing items.

When importing with BBT, yes.

>     1. Is automatic sentence-casing currently supposed to be working without requiring me to do anything ... yet whenever I try to import an item from Firefox via the Zotero Connector the title is copied as is without getting sentence-cased.

This is the key bit. When you are importing using the connector, BBT only gets involved when the page you're scraping offers bibtex. If it offers anything else (which is usually the case), BBT doesn't get called by Zotero.

The reason BBT sentence-cases titles is because bibtex says that titles should be in Title Case, and Zotero expects sentence-case. There is no such standard for all other non-bibtex data that gets collected by the connector, so the assumption by most translators (even the Zotero bibtex translators) is that the scraped data is already sentence-cased.

>     2. For items with sentence-cased titles, export puts braces as intended. However, it does this not only for the title field but also for things like booktitle, publisher, series, etc. Is this intended?

Yes, but for different reasons:

1. `booktitle` and `series` are title-type fields, and are subject to bib(la)tex case meddling for non-english items
2. `publisher` is a literal-list field; since Zotero has only a single field for publisher, I treat the Zotero publisher field as if it is a list-of-one with a single literal name (and the last part is why it gets the braces). If I would not do that, `Rowman and Littlefield` would be treated as two publishing houses involved with that reference.

> If I were to write a Bib(La)TeX entry by hand, I would not put braces in, say, a conference proceedings title since this does not get sentence-cased according to APA. 

If the title is in sentence case in Zotero, you'll get no braces, so that should work out fine. If you have capitals in Zotero, those would be brace protected, but you'd want that regardless of whether the style sentence-cases or not.

> In the end, should every single field be in sentence-case in Zotero for the braces to be inserted properly (as I would do by hand)?

Yes. Zotero expects everything to be in sentence case, and BBT works from that assumption. You can [turn of brace-protection](https://retorque.re/zotero-better-bibtex/installation/preferences/advanced/#apply-case-protection-to-capitalized-words-by-enclosing-them-in-braces) if you want, but it then becomes style-dependent whether bibliographies rendered by Zotero itself or by bib(la) tex come out the same.

You can right-click a field in Zotero and Zotero will sentence-case for you, but this transformation is imperfect, you always need to check the results.

**Comment by yolcu** [comment]
Thank you very much for the detailed reply! You cleared up all my confusion.

**Comment by retorquere** [comment]
My pleasure
