### ISSUE TITLE
Export pandoc-citeproc citekeys to Word citations bookmarks 

### ISSUE THREAD

**Issue by vtcarlino** [retorquere/zotero-better-bibtex#1489]
Hi,
I just [discovered](https://github.com/retorquere/zotero-better-bibtex/issues/849#issuecomment-352294749) that BBT can migrate word documents to pandoc through the hidden citeprocNoteCitekey preference and a specific CSL file.

I would like to do the opposite: convert pandoc citekeys to Word citation bookmarks. Citations in the pandoc generated .docx aren't rendered in bookmarks, which means they can't be edited in Word.

Would it be possible to make a CSL file that does the pandoc to word conversion?

**Comment by vtcarlino** [comment]
Debug id: ZSRNDXFU-euc

**Comment by retorquere** [comment]
I honestly don't know - how do you envision this would work? And where would BBT sit in this pipeline?

**Comment by vtcarlino** [comment]
> how do you envision this would work

Like the "BetterBibTeX Citekeys" CSL style, but maybe I should submit that issue to Zotero as BBT doesn't produce anything like "Word citekeys" ...

**Comment by retorquere** [comment]
When you say

> I would like to do the opposite: convert pandoc citekeys to Word citation bookmarks. Citations in the pandoc generated .docx aren't rendered in bookmarks, which means they can't be edited in Word.

that means you want to start in Markdown, put it through pandoc to produce word, and then get a docx file that is connected to Zotero?

If that is the situation you have in mind, BBT would only be marginally involved in the case the citekeys you use in your markdown source might come from BBT. You'd have to convince pandoc to add enough information to the docx so that you can export Zotero-compatible bookmarks; suppose you use pandoc with Better CSL JSON instead of Better BibTeX (recommended anyhow if you use pandoc to generate Word files), you can add the itemID to the CSL object using a postscript:

```
if (Translator.BetterCSL) {
  reference.itemID = item.itemID
}
```

You'd then have to make pandoc put the references in the resulting docx file in BBT format. That's outside my area of expertise though -- I know the Word references include the serialized CSL objects and that somehow links up the doc file to Zotero, but I don't use Word, so I don't really know what happens there.

**Comment by vtcarlino** [comment]
Yes, I used Better CSL JSON. I'm note sure where to put that code?

**Comment by retorquere** [comment]
https://retorque.re/zotero-better-bibtex/installation/preferences/advanced/#postscript

**Comment by retorquere** [comment]
Does that give you enough information? For the rest of what you want, BBT is not involved, that relates only to how pandoc puts a bibliography into word. BBT can deliver the data but is not called upon by pandoc while it's creating the bibliography. For that you'll have to talk to the pandoc devs.

**Comment by vtcarlino** [comment]
Yes! Thanks a lot, I'll ask the pandoc dev
