### ISSUE TITLE
Question on syntax "if value empty", might want to add in Citation Keys doc

### ISSUE THREAD

**Issue by hitchhub** [retorquere/zotero-better-bibtex#1517]
How do I apply an "**if empty**" to a _part_ of the cite key?

So my situation is this: encyclopedia articles have no author, I want the key to be say
`[title][year]` instead of `[auth][year]`

but since the `[year]` is usually not empty, a simple `|` would not do.

Is there a way to apply `|` to a _part_ of the key, e.g. by putting braces? Or can the syntax
`[auth:(unspecified)]` be used with variables instead of the static "unspecified" string?

Thanks a lot in advance, BBT made me pick zotero for reference management and it rocks my master thesis! 😃 
Paul

**Comment by retorquere** [comment]
You can sort of do this with `[auth][>0][year] | [title][year]`, but that only really works if you have a single, leading block you want to select on.

WRT adding support for functions in the brace-default -- one of the things I regret not doing from the start is making my own syntax instead of implementing the JabRef format, but it's risky changing this now. Existing users have the right to assume that anything that anything that's between those braces will be used verbatim.

If you're willing to test, I can try to think of other ways to have "active defaults" with something that'd be either unlikely or illegal to show up verbatim in a citekey, maybe something like `[auth:([title])]` or `[auth:(=[title])]`, but I really need to get #1510/#1471 closed first.

**Comment by hitchhub** [comment]
thanks a lot!
makes me feel bad as I just found this in the docs:

> >X: a pseudo-function which aborts the current pattern generation if what came before it is X characters or less ([>0] is a typical use. You would typically use this with something like [auth][>0][year] | [title][year] which means if there's no author you get title-year rather than just year.

..or did you add it just now?

That resolves my issue, thanks!
As for the testing, I would have to do it some time in the distant future, my thesis consumes all the hours of the day, but thanks for suggesting!

**Comment by hitchhub** [comment]
And the orange highlighting of invalid syntax is really the shit, I ❤️ BBT

**Comment by retorquere** [comment]
> makes me feel bad as I just found this in the docs:
...
> ..or did you add it just now?

That has been there a long time, but don't worry about it. There's a lot to digest about BBT and even I sometimes forget that a particular feature already exists. Asking questions on BBT use is always OK, even if it's in the docs (although I might respond with a link to the docs if I'm swamped).

> As for the testing, I would have to do it some time in the distant future, my thesis consumes all the hours of the day, but thanks for suggesting!

That works just fine for me -- in sharp contrast to BBTs early days, I try to avoid gold-plating, so unless an active interest exists, I'll usually not add it.

> And the orange highlighting of invalid syntax is really the shit, I ❤️ BBT

Happy to hear that, the orange highlight took some doing.
