### ISSUE TITLE
Edit bibtex key within zotero

### ISSUE THREAD

**Issue by notuntoward** [retorquere/zotero-better-bibtex#1533]
I would like to be able to edit the bibtex key within zotero.  The way I'm doing that now is to export a bibtex file, edit the key there, and then reimport it -- quite slow on a 2000+ entry file.  

The reason I'm bringing the key back to Zotero is that I have to write in both Word and Latex, but want to keep a single, version-controlled bibliography database.

**Report ID:**
P38Z4VUK-euc

**Comment by retorquere** [comment]
You can just add or edit the line in the `extra` field that starts with `Citation Key:`. What's in there will be taken as the citation key. See https://retorque.re/zotero-better-bibtex/citing/#set-your-own-fixated-citation-keys .

**Comment by notuntoward** [comment]
Thanks, that works.

**Comment by retorquere** [comment]
Your initial question only asked about editing the key, but what you describe here is possible too. Right-click, BBT, "pin citekey" will write the current generated key to extra with the line label (which is what you call the boilerplate I think?), which you can then edit as you want.

A dedicated citekey field is planned for zotero, but I have no idea when they'll add it.

**Comment by retorquere** [comment]
(all the reimport will do is put the existing key in the `extra` field btw)

**Comment by notuntoward** [comment]
Thanks!  That's an even better workaround.  

What I don't understand is why the `Citation Key` isn't just directly editable.  Seems like you then wouldn't need a separate key in the `Extra` field.  Not under your control, I know...

**Comment by retorquere** [comment]
The item pane (which is where all the item details are editable) is hard to augment, much harder than the rest of the UI. I won't bore you with the details, but the upshot is that the whole item pane is destroyed and rebuilt whenever a new item is displayed, and I'm only notified of this after it has happened, which left me with two choices: either save the key after every keystroke (which led to an update storm which would sometimes get stuck in an update loop, because I also watch the item for edits), or I'd do it as zotero does it, save the key when the field loses focus, but then the field was sometimes destroyed before I got that event, meaning I'd lose the last keystroke.

That pane is actively hostile to being extended, and I did not feel like dealing with the weirdness of the race conditions that could occur. This stacks on top of the fact that I really, really don't like UI work.

The zotero team has committed to introducing a proper citekey field, which will solve all these problems. No idea when though. It's been talked about for years.

**Comment by notuntoward** [comment]
I understand, and thanks for BBT.  As is, it's really useful.

**Comment by retorquere** [comment]
Oh and I forgot to mention - even if I had managed to make that field at the top editable, I'd *still* have to store it in the extra field. Extensions aren't allowed to add actual fields to zotero. Putting it in the extra field also means it syncs, and that it's available to services like overleaf. Until the formal field comes, this is the only possible way.
