### ISSUE TITLE
span class="italic" not supported

### ISSUE THREAD

**Issue by hnguyen19** [retorquere/zotero-better-bibtex#1550]
**Report ID:** 6P26JL7L-euc

**Exporter used:** better bibtex

**Expected behavior:** italicized Latin names

**Actual behavior:** non-italicized Latin names

Thank you for helping me out.  Here are the details.

**Comment by retorquere** [comment]
Your title is

```
<span class="italic">Amaranthus rudis</span> and <span class="italic">A. tuberculatus</span> , One Species or Two?
```

Zotero does not support this notation (try right-clicking the item and select "Create bibliography from item"); it should be

```
<i>Amaranthus rudis</i> and <i>A. tuberculatus</i> , One Species or Two?
```

Also, you have quite a few auto-export errors like:

> C:\Users\huong\Box Sync\Propo\MyLib.bib does not have a parent folder

which means that part of that path no longer exists.

**Comment by hnguyen19** [comment]
Thank you for your quick response. Is my best bet now to manually change my title to <i>Amaranthus rudis</i> and <i>A. tuberculatus</i>? Is there a way to do that in batch? I have several entries that have the same issue. It's either the unsupported format or the italicize format not imported at all. By not imported italics, I mean the Latin names are italicized on the journal but imported as plain text in Title field.

It doesn't look like Rmarkdown has a problem looking for my .bib file. I guess the link included was the first folder that I save the exported file to, but I check "keep updated" when I export or update.

**Comment by retorquere** [comment]
> Thank you for your quick response. Is my best bet now to manually change my title to `<i>Amaranthus rudis</i> and <i>A. tuberculatus</i>`? Is there a way to do that in batch? I have several entries that have the same issue. 

It is possible, **but** mind that there is always a risk involved with batch editing. I tested this locally and it works but I can not be held accountable should things go wrong. You're reaching directly into the Zotero internals this way.

* Select all the items you want to change (or just select all items, this code will try not to change what doesn't need changing, but just selecting the ones you want is safer).

* From the Zotero menu, select `Tools` -> `Developer` -> `Run Javascript`

* In the window that pops up, select the checkbox that says `Run as async function`

* Paste in this code in the left textbox:

```
for (const item of Zotero.getActiveZoteroPane().getSelectedItems()) {
  const title = item.getField('title')
  const fixed = title.replace(/<span class="italic">(.*?)<\/span>/g, '<i>$1</i>')
  if (title !== fixed) {
    item.setField('title', fixed)
    await item.saveTx()
  }
}
```

* Click `Run`

But you should also report on the forums where you got this item, because the site fetcher ("translator") for that side should be doing this by default.

> It's either the unsupported format or the italicize format not imported at all. By not imported italics, I mean the Latin names are italicized on the journal but imported as plain text in Title field.

The italicized journal names are done by the citation style itself, it's not related to how you imported the item.

> It doesn't look like Rmarkdown has a problem looking for my .bib file. I guess the link included was the first folder that I save the exported file to, but I check "keep updated" when I export or update.

If that works that's fine, but in the initial log you posted inside the issues, there were quite a few of these errors.

**Comment by retorquere** [comment]
closing for lack of feedback
