### ISSUE TITLE
Options to use default import process?

### ISSUE THREAD

**Issue by airallergy** [retorquere/zotero-better-bibtex#1562]
**Report ID:** 6ZW6CI2V-euc

**Full Bib(La)TeX item you are trying to import:** https://gist.github.com/airallergy/156b968cff268392b3100d864a5b7d12

**Expected behavior:** doi without {}, don't use WOS's ISI as the citation key, clean extra field as the default import does

**Actual behavior:** doi with extra {}, WOS's ISI used as the pinned citation key, loads of irrelevant info in the extra field

In all, I am wondering if there is a way to use the zotero default import function (when betterbibtex is disabled), after which betterbibtex will sign a citation key for the newly imported items?

**Comment by retorquere** [comment]
BBT doesn't use the WOS's ISI as the citation key; BBT has no opinion on what should be used in the citation key. The bibtex in that gist says that the citation key is `ISI:000445987100063` and BBT just follows that.

I can get rid of the extra braces, and I can add a preference to discard the data that Zotero doesn't have fields for (what is termed "loads of irrelevant info" above). I'm less excited about discarding the citekey, but I can consider that.

May I ask what site produced this bibtex? Whatever program produced it doesn't understand bib(la)tex very well.

**Comment by airallergy** [comment]
it's Web of Science, clearly there is an inconsistency in the parsing of bib.

My current workaround is to disable bbt, then import, then re-enable bbt, so instead of discarding the citekey in bbt, I think it would be more convenient to let zotero handle the import process if possible.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.36.6744](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.36.6744.xpi) ("removing verbatim text from verbatim field...")

Install in Zotero by downloading [test build 5.2.36.6744](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.36.6744.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Then WOS should really clean up their BibTeX generation. That sample is ridiculous.

BBT by it's very nature aims to do things better than the standard Zotero translators. Even though the sample from the WOS is faulty (the double braces everywhere are not only necessary but actively harmful), I agree that removing the outer braces is better, even though `DOI` is a verbatim field, which is why they stayed there. I checked and bibtex has an exception for this case too, so I don't mind adding it.

I've added 3 new [hidden preferences](https://www.zotero.org/support/preferences/hidden_preferences):

* `extensions.zotero.translators.better-bibtex.import`: when `false`, defer imports to the standard Zotero bibtex importer
* `extensions.zotero.translators.better-bibtex.importExtra`: when `false`, discards fields on import that Zotero doesn't have fields for. This means data loss.
* `extensions.zotero.translators.better-bibtex.importCitationKey`: when `false`: discard citation key on import. This means data loss.

The latter two should in principle get you the desired results while still keeping BBTs better TeX translation. The first will cause BBT to decline all imports, deferring to the standard Zotero importer.

Build 6745 will drop here shortly; it will add these 3 preferences and remove the outer braces on `DOI` fields; all non-verbatim fields already have this behavior in BBT.

But WOS should really clean up that crap bibtex of theirs. Whoever write the code that produces it clearly hasn't ever used bib(la)tex.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.36.6745](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.36.6745.xpi) ("allow disabling import")

Install in Zotero by downloading [test build 5.2.36.6745](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.36.6745.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by airallergy** [comment]
Thanks for such quick fix.

The latter two are working perfectly (`.importExtra` and `.importCitationKey`), but the `.import` preference seems not working desirably.

The only difference when `.import` is false is a pop-up window to ask whether to import, which is what Zotero import would do. Other than that, the import results are still identical as before except for the fixed doi braces.

**Comment by retorquere** [comment]
I don't know this popup window? By what procedure do you get this?

**Comment by airallergy** [comment]
I double checked it, I was wrong about the popup window, sorry about any confusion.

However, the `.import` option makes no difference then, meaning the bbt importer is used either it's true or false. A debug report id is as follow when `.import` is false.

9SG9WXSF-euc

**Comment by retorquere** [comment]
I have that replicable. I'm looking into it.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.36.6751](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.36.6751.xpi) ("ncu")

Install in Zotero by downloading [test build 5.2.36.6751](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.36.6751.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Took longer than I had hoped, but found some tricky bugs while I was looking for it. 6751 should fix the issue. I'd still recommend using `importExtra` and `importCitationKey` over `import`, but then I'm biased of course.

**Comment by airallergy** [comment]
6751 works, cheers mate!

**Comment by retorquere** [comment]
I keep issues open so I don't forget to merge them, thanks for the confirmation. I'll cut a new release, you'll be upgraded automatically, but it's just what you have now with a new version number.
