### ISSUE TITLE
Quality report

### ISSUE THREAD

**Issue by Jmuccigr** [retorquere/zotero-better-bibtex#1589]
I'm using the version 5.2.45.6822, so that I can get the duplicate key report. Otherwise up to date on a Mac.

**Exporter used:**

BibTeX

## My questions/issues

1. Which report formats do the quality reports appear in? (Happy to add this to the docs page.)
1. The duplicate key report just occurs by itself on a line, without the preceding "% == BibTeX quality report" line, so I missed it at first because I was searching for "quality" in the file. Should there be such a preceding line? Could it be attached to the relevant item, as other reports are, or does it need to be at the end?
1. Some journal article entries (`@article`) are getting the error: "% Missing required field 'number'". But `number` (which Zotero calls `issue`) is not a requirement for journal articles.
1. Some books are getting the "% Missing required field 'author'" when they really don't have authors, just editors, which I believe is allowable.

TIA.

**Comment by Jmuccigr** [comment]
- debug ID for journal entry without number: F4Y2SPB2-euc
- debug ID for book without author: 9BWTBGRR-euc

**Comment by retorquere** [comment]
> * Which report formats do the quality reports appear in? (Happy to add this to the docs page.)

BibTeX and BibLaTeX. Since BibLaTeX is much better documented, the QRs for that are much more accurate/details. The BibTeX QR only has a few checks.

> * The duplicate key report just occurs by itself on a line, without the preceding "% == BibTeX quality report" line, so I missed it at first because I was searching for "quality" in the file. Should there be such a preceding line? Could it be attached to the relevant item, as other reports are, or does it need to be at the end?

In the current implementation at the end is the only way -- I go through the items linearly (since Zotero passes them to me linearly) so I only know at the end whether earlier items have duplicates. To put it anywhere else would require a 2-pass export.

> * Some journal article entries (`@article`) are getting the error: "% Missing required field 'number'". But `number` (which Zotero calls `issue`) is not a requirement for journal articles.

I can't replicate this. Can you go into the BBT advanced prefs and clear the cache and see whether you still have this problem?

> * Some books are getting the "% Missing required field 'author'" when they really don't have authors, just editors, which I believe is allowable.

http://ctan.cs.uu.nl/macros/latex/contrib/biblatex/doc/biblatex.pdf, section 2.1.1 Regular Types:

> **book**
>
> Required fields:author,title,year/date

Doesn't mean they render incorrectly, but according to the biblatex manual, they're mandatory.

**Comment by Jmuccigr** [comment]
> > * Which report formats do the quality reports appear in? (Happy to add this to the docs page.)
> 
> BibTeX and BibLaTeX. Since BibLaTeX is much better documented, the QRs for that are much more accurate/details. The BibTeX QR only has a few checks.

Great. Thanks.

> 
> > * The duplicate key report just occurs by itself on a line, without the preceding "% == BibTeX quality report" line, so I missed it at first because I was searching for "quality" in the file. Should there be such a preceding line? Could it be attached to the relevant item, as other reports are, or does it need to be at the end?
> 
> In the current implementation at the end is the only way -- I go through the items linearly (since Zotero passes them to me linearly) so I only know at the end whether earlier items have duplicates. To put it anywhere else would require a 2-pass export.

I thought that might be. Could it still get a prefixed line?

> 
> > * Some journal article entries (`@article`) are getting the error: "% Missing required field 'number'". But `number` (which Zotero calls `issue`) is not a requirement for journal articles.
> 
> I can't replicate this. Can you go into the BBT advanced prefs and clear the cache and see whether you still have this problem?

Ah, this is only happening with BibTeX report, not BibLaTeX.
> 
> > * Some books are getting the "% Missing required field 'author'" when they really don't have authors, just editors, which I believe is allowable.
> 
> http://ctan.cs.uu.nl/macros/latex/contrib/biblatex/doc/biblatex.pdf, section 2.1.1 Regular Types:
> 
> > **book**
> > Required fields:author,title,year/date
> 
> Doesn't mean they render incorrectly, but according to the biblatex manual, they're mandatory.

I looked at the [CTAN PDF](https://ctan.mirror.garr.it/mirrors/CTAN/biblio/bibtex/base/btxdoc.pdf), where it says:

> **book** A book with an explicit publisher. Required fields: author or editor, title, publisher, year. Optional fields: volume or number, series, address, edition, month, note.

Seems to me that the second reference is correct. Plenty of books have editors and no authors.

**Comment by retorquere** [comment]
> > In the current implementation at the end is the only way -- I go through the items linearly (since Zotero passes them to me linearly) so I only know at the end whether earlier items have duplicates. To put it anywhere else would require a 2-pass export.
> 
> I thought that might be. Could it still get a prefixed line?

Yep, sure.

> Ah, this is only happening with BibTeX report, not BibLaTeX.
>
> I looked at the [CTAN PDF](https://ctan.mirror.garr.it/mirrors/CTAN/biblio/bibtex/base/btxdoc.pdf), where it says:
> 
> > **book** A book with an explicit publisher. Required fields: author or editor, title, publisher, year. Optional fields: volume or number, series, address, edition, month, note.
> 
> Seems to me that the second reference is correct. Plenty of books have editors and no authors.

Those are for BibTeX, not BibLaTeX, but I see I've gotten a few of those wrong. Fix incoming.

**Comment by Jmuccigr** [comment]
Thank you!

I'd love to contribute a PR for the manual, but I'm not at all clear on which file to edit. The only one I see with the relevant text (export.md) has a warning up top not to edit.

**Comment by retorquere** [comment]
The docs for the preferences are taken from the [UI that declares them](https://github.com/retorquere/zotero-better-bibtex/blob/master/content/Preferences.xul) in `<bbt:doc>` elements.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.47.6861](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.47.6861.xpi) ("fixes #1589")

Install in Zotero by downloading [test build 5.2.47.6861](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.47.6861.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
That should fix the QR for BibTeX. I've disabled checking for optional fields for now because so few are specified in BibTeXing; `abstract` for example isn't listed but is a very common field in bibtex files, and deeming those unexpected would just clutter the QR, hiding missing required fields in the chatter.

**Comment by Jmuccigr** [comment]
Any chance this broke Zutiloʻs shortcut support by changing the name of the menu item to "Unpin BibTeX key" from "Unpin key for selection"?

I also notice that creating a book section from a book results in the bookʻs title not being moved to the book title field in the new entry. I donʻt think this was happening yesterday.

**Comment by retorquere** [comment]
> Any chance this broke Zutiloʻs shortcut support by changing the name of the menu item to "Unpin BibTeX key" from "Unpin key for selection"?

No, but that's because it's it's never been "Unpin key for selection":

```
$ git log -p locale/en-US/zotero-better-bibtex.dtd | grep -i unpin
 <!ENTITY better-bibtex.BetterBibTeX.citekey.unpin "Unpin BibTeX key">
 <!ENTITY better-bibtex.BetterBibTeX.citekey.unpin "Unpin BibTeX key">
 <!ENTITY better-bibtex.BetterBibTeX.citekey.unpin "Unpin BibTeX key">
 <!ENTITY better-bibtex.BetterBibTeX.citekey.unpin "Unpin BibTeX key">
 <!ENTITY better-bibtex.BetterBibTeX.citekey.unpin "Unpin BibTeX key">
 <!ENTITY better-bibtex.BetterBibTeX.citekey.unpin "Unpin BibTeX key">
 <!ENTITY better-bibtex.BetterBibTeX.citekey.unpin "Unpin BibTeX key">
 <!ENTITY better-bibtex.BetterBibTeX.citekey.unpin "Unpin BibTeX key">
-<!ENTITY better-bibtex.zoteroPane.citekey.unpin "Unpin BibTeX key">
+<!ENTITY better-bibtex.BetterBibTeX.citekey.unpin "Unpin BibTeX key">
    pin/unpin ui
+<!ENTITY better-bibtex.zoteroPane.citekey.unpin "Unpin BibTeX key">
```

> I also notice that creating a book section from a book results in the bookʻs title not being moved to the book title field in the new entry. I donʻt think this was happening yesterday.

It's still moved for me.

**Comment by retorquere** [comment]
The title that Zutilo uses doesn't matter. It's using the BBT code directly. It does indeed no longer work (just tested) but I don't see why. It calls the same code that I do from the context menu.

**Comment by Jmuccigr** [comment]
> > Any chance this broke Zutiloʻs shortcut support by changing the name of the menu item to "Unpin BibTeX key" from "Unpin key for selection"?
> 
> No, but that's because it's it's never been "Unpin key for selection":

That's what Zutilo calls it, so I thought maybe it was related to the problem.

> > I also notice that creating a book section from a book results in the bookʻs title not being moved to the book title field in the new entry. I donʻt think this was happening yesterday.
> 
> It's still moved for me.

Definitely not for me when BBT is on. Version 5.47.6861.

**Comment by Jmuccigr** [comment]
> The title that Zutilo uses doesn't matter. It's using the BBT code directly. It does indeed no longer work (just tested) but I don't see why. It calls the same code that I do from the context menu.

Very weird because I just updated it yesterday, set the keyboard equivalent, and tested it successfully.

**Comment by retorquere** [comment]
I've just downloaded 6861, newest Zutilo, Zotero 5.0.89, and "create book section" moves the title for me.

**Comment by Jmuccigr** [comment]
If I watch, I think I can see the title get deleted and then put back.

**Comment by retorquere** [comment]
Can you restart with debug logging enabled and get me a bbt log after you replicated that? I just don't see what you describe.

**Comment by retorquere** [comment]
Does it also happen with auto pin off? And with BBT uninstalled?

**Comment by retorquere** [comment]
It must be some kind of race condition between auto-pin and create-book-section

**Comment by retorquere** [comment]
Can you set the [hidden preference](https://www.zotero.org/support/preferences/hidden_preferences) `itemObserverDelay` to `3000` and see what happens?

**Comment by Jmuccigr** [comment]
v. 6861

1. With BBT & autopin, title remains.
1. With BBT disabled, title moved.
1. With BBT and no autopin, title moved.
1. With BBT, autopin, & itemObserverDelay set to 3000, title moved.

**Comment by retorquere** [comment]
That means it's a race condition. What must be happening is:

1. Zutilo duplicates (and thus saves) the item
2. Zotero notifies all listeners that an item has been saved
3. BBT picks up the item to pin the key, in the freshly duplicated state, and "saves" it
4. Zutilo modifies & "saves" the item
5. Zotero actually saves the item from step 4
6. Zotero actually saves the item from step 3

Step 5 and 6 may seem weird, and that's because Zotero object fetch & save are async, and Javascript async is, in fact, weird. The "save"s done in step 3 and 4 don't actually save the item, they say "put this action on the async queue and let me sleep until it's done" (the "actually" steps later). All non-async stuff is easy to grok, because that always just runs to completion, but with async, the execution paths become entangled. I don't know why 5 and 6 execute in this order, but that's what seems to happen.

There's a couple of ways around this:

**delay**

I could just add the auto-pin delay. The delay chosen would be somewhat arbitrary, and only "solves" the race condition by having BBT enter the "race" deliberately late, assuming the race has been ran when it starts. That would make the execution order 

1. Zutilo duplicates (and thus saves) the item
2. Zotero notifies all listeners that an item has in fact been saved
3. BBT wakes up, but says to itself "wake me up in 2 seconds, and then proceed"
4. Zutilo modifies & "saves" the item
5. Zotero actually saves the item from step 4
6. BBT picks up the item to pin the key, in the now hopefully modified state, and "saves" it
6. Zotero actually saves the item from step 6

This relies on picking an interval that's sufficiently large to be sure that step 5 has taken place, but not so large that users start to wonder why BBT isn't auto-pinning. I'm not a great fan of solutions like this (but I have at least one in BBT).

**Transactional save**

Zutilo could use a transaction to do copy-to-booksection; a transaction should mean notifiers only get pinged when the transaction completes

**clone instead of duplicate**

Zutilo could use `clone` instead of `duplicate`; `clone` doesn't save, so step 2 would never get triggered.

The delay will pragmatically work, but I'd argue that a transaction or clone are the proper solution. If you fetch-modify-save an item, and anything between fetch and save is async, you have no guarantee about execution order (and you can't see whether someone else already grabbed the item.

**Comment by Jmuccigr** [comment]
PS the shortcut key for unpin seems to work now as well.

**Comment by retorquere** [comment]
That could be another race condition, but not one that involves pinning, it could be extension load order.

**Comment by retorquere** [comment]
@willsALMANJ, we're facing a race condition with `Create Book section`. The clean fix would require Zutilo to duplicate most of the code of Zotero's `duplicate`. If that's not an option for Zutilo, I'll fix it with kludge in BBT.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.47.6894](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.47.6894.xpi) ("autopin delay")

Install in Zotero by downloading [test build 5.2.47.6894](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.47.6894.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by Jmuccigr** [comment]
OK, I installed 6894 and reset the delay and all seems well so far. New book sections are seeing the title shift to book title, as expected.

**Comment by retorquere** [comment]
Alright. It's a bit of a kludge, but if it works, it works.

**Comment by retorquere** [comment]
But back to the original question: does the QR now show the duplicate keys as desired?

**Comment by Jmuccigr** [comment]
> But back to the original question: does the QR now show the duplicate keys as desired?

Yes, it does for me.

PS I just noticed that there's a contextual menu called "Tag duplicate citation keys", which does just what it sounds like. Has that always been there?

**Comment by retorquere** [comment]
Not always, but a long time.
