### ISSUE TITLE
Retrieve BBT citekeys

### ISSUE THREAD

**Issue by davdent** [retorquere/zotero-better-bibtex#1593]
As as result of some unfortunate maneuvers I have lost my BBT citekeys. Essentially, my .zotero folder was erased (I am running under Ubuntu 20.04) and I restored Zotero from a backup of my Zotero folder. As a result, I have all of my references and attachments, but not the citekeys. Zotero does not recognize that BBT is installed -- although all of the BBT sqlite files are in the Zotero folder -- nor my other extensions.

Is there any way that I can tell Zotero to use the BBT database, and hopefully recover the citekeys? Failing this, what would be the best way to reinstall BBT? If I do reinstall BBT, will it use the old database files? I do have access to the old .Zotero file if there is anything in there that could help.

Thanks in advance.

**Comment by davdent** [comment]
I really do think that debug does not apply in this case. Thanks!

**Comment by retorquere** [comment]
It doesn't, but I have github issues set up so that you should have been offered a choice of 5 issues types after clicking the [new issue](https://github.com/retorquere/zotero-better-bibtex/issues/new/choose) button, one of which is `question` which wouldn't have triggered this. It looks like you weren't offered this choice, or the issue would have had a label, and @label-gun wouldn't have shown up.

Anyhow, if your backup isn't ancient, just re-installing BBT should do the job. Like Zotero, BBT uses the DB already present when it starts up, and only creates a new DB if none is present.

**Comment by davdent** [comment]
This is good to know. Thank you. I will reinstall and see what happens. 
BTW, when I click the link to add an issue on the BBT github page, it takes me right to where I add a the issue heading and comment, no questions asked.

**Comment by retorquere** [comment]
In other words if you are here: https://github.com/retorquere/zotero-better-bibtex/issues

and click the **New issue** button

you are taken here: https://github.com/retorquere/zotero-better-bibtex/issues/new

?

**Comment by retorquere** [comment]
Ah, I think I have it -- the readme pointed to `/new`, not `/new/choose`. Thanks!

**Comment by retorquere** [comment]
Please let me know if BBT everything goes right after installing BBT by the waty.

**Comment by davdent** [comment]
Worked perfectly. Thank you.
