### ISSUE TITLE
Hang while loading translators

### ISSUE THREAD

**Issue by daeh** [retorquere/zotero-better-bibtex#1620]
**Report ID:**
3MT9ERR7-euc

**Expected behavior:**
BBT finishes initializing.

**Actual behavior:**
Recently Better BibTex has started hanging while waiting for the Zotero translators. I tried resetting the translators but that didn't change anything. No matter how long I wait, the "BBT: Initalizing" window stays up, the Citekeys show the hourglass, and the BBT preference plane stays empty.

Thanks for the help!

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.54.6993](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.54.6993.xpi) ("lock tracing")

Install in Zotero by downloading [test build 5.2.54.6993](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.54.6993.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Can you send me a new log from 6993?

**Comment by daeh** [comment]
`NTVWFHNR-euc`
Thanks

**Comment by retorquere** [comment]
Can you check whether the Zutilo option `Copy Item Fields` (you'll have to enable it in the Zutilo preferences) shows up for you in the right-click menu?

**Comment by retorquere** [comment]
The problem is that I'm not seeing any errors in the log, but there's a promise Zotero is supposed to resolve to indicate it's OK for extensions to start working with the database, and that never gets resolved. In `NTVWFHNR-euc` I can see that you've been waiting for it to clear for half a minute with absolutely no other activity, with the promise still unresolved. Zutilo waits for the same promise for `Copy item fields`, so if that affects Zutilo too (especially if it affects Zutilo when no other extensions are installed) that's an indication that maybe it's a Zotero problem. If it does not affect Zutilo when no other plugins are installed, I'll need you to do the same test while adding plugins back one-by-one (not the Word/LO plugins, but the 3rd party plugins you have).

**Comment by daeh** [comment]
Yeah, that's the right hunch. I have several Zutilo contextual menu items enabled and they all show up except for 'Copy item fields' and 'Paste all item fields'. I'll troubleshoot a bit and see if I can turn up anything.

**Comment by daeh** [comment]
Some cache must have been causing an issue. The issue persisted when I disabled everything but BBT and Zutilo, but when I disabled everything a brought all the add-ons back one-by-one, everything seems peachy again. Thanks a ton for looking at it.

**Comment by retorquere** [comment]
Strange. Don't really like transient errors.
