### ISSUE TITLE
BetterBixTex export suddenly exports all arxiv articles as @online instead of @article

### ISSUE THREAD

**Issue by n-gao** [retorquere/zotero-better-bibtex#1669]
Suddenly, ArXiv articles are published as @online instead of @article as before. I would like to keep the @article version, is there a way to do this?

**Comment by retorquere** [comment]
With a [postscript](https://retorque.re/zotero-better-bibtex/exporting/scripting/):

```js
if (Translator.BetterBibLaTeX && reference.referencetype === 'online' && item.arXiv) reference.referencetype = 'article'
```

The recent change to `@online` was because of a [discussion](https://forums.zotero.org/discussion/comment/365145) on the Zotero forms where it was pointed out that the biblatex manual states that for `@article`, `journaltitle` is a mandatory field, so styles will likely expect it to be filled.

**Comment by n-gao** [comment]
Thanks that worked!

**Comment by eviatarbach** [comment]
Thank you for this solution! I was looking for a way to change this because my problem with the @online type is that the arXiv article titles are italicized in the bibliography, unlike standard journal articles. I think that this behavior is unexpected: I would expect arXiv articles to format in a similar way to published journal articles.
