### ISSUE TITLE
File link is lost when importing .bib item with citation keys 

### ISSUE THREAD

**Issue by sophieqzwang** [retorquere/zotero-better-bibtex#1709]
Overall, I want to preserve both the citation keys and the file links (to my large Dropbox folder) when importing .bib to Zotero. I am migrating to Zotero.

The .bib item has both the citation key field (already used in my Latex files) and the file field (linked to a PDF file on disk) populated already. Now, when I enable better bibtex when importing, the file is not linked as an attachment. When I disable the extension, the file will show up in Zotero as an attachment. 

**Report ID:** D1197042708

**Full Bib(La)TeX item you are trying to import:**

It looks like this and I am importing with the file selected as "Link to files in original location":
@article{my_previously_assigned_citation_key,
abstract = {abstract_here},
author = {author_here},
file = {:C$\backslash$:/Users/user_name/Dropbox/Literature/previously_stored_file_name.pdf:pdf},
title = {{title_here}},
}

**Expected behavior:**
Citation key assigned and the file linked to the PDF location also shows up as a link to the attachment. 

**Actual behavior:**
Citation key assigned; no file attachment or link visible.
When the better-bibtex extension is disabled when importing, the PDF file shows up, but then the citation key is lost.

**Comment by retorquere** [comment]
I can't read reports like `D1197042708`, those only go to the Zotero developers. But if I'd have to guess, this is Mendeley-generated bibtex; the Mendeley devs apparently couldn't be bothered to read the bibtex manual. I'll spare you the explanation, but you can either remove `file` from [verbatimFields](https://retorque.re/zotero-better-bibtex/installation/preferences/hidden-preferences/#verbatimfields) (but do change that back when done) or rename `file` to `files` in the bib file before import.

**Comment by sophieqzwang** [comment]
@retorquere You are absolutely right! The bib file was generated by Mendeley. Once I renamed `file` to `files` in the bib file, everything went through just fine! Thanks a lot!

**Comment by retorquere** [comment]
Just as an aside, in case you wanted to know why this happened -- if not, feel entirely free to skip the rest, most people don't need to know this about bibtex. But the Mendeley devs absolutely should have. Not the first grave error I've found in Mendeley-generated bibtex, and likely not the last.

BibTeX has, roughly speaking, two "modes" in which the input is parsed; verbatim mode, and "normal". In verbatim mode, LaTeX commands are not treated as instructions but as bare text -- in things like URLs (or, in this case, file paths), you don't really need anything *but* bare text, so disabling command handling means you don't have to escape backslashes and underscores and so on.

And here's the thing -- `file` fields are `verbatim` according to the bibtex/biblatex manual, so

```
file = {:C$\backslash$:/Users/user_name/Dropbox/Literature/previously_stored_file_name.pdf:pdf},
```

means *literally* a file under the non-existent `C$\backslash$:` folder (although I wonder why Mendeley would commit the further screw-up of having `C$\backslash$:` instead of `C:$\backslash$`). What it should have been is just

```
file = {:C:\Users\user_name\Dropbox\Literature\previously_stored_file_name.pdf:pdf},
```

or 

```
file = {:C:/Users/user_name/Dropbox/Literature/previously_stored_file_name.pdf:pdf},
```

if you would have changed that by hand it also would have worked.

Changing the hidden setting makes BBT not consider `file` fields as verbatim, so the Mendeley-bibtex would become

```
file = C\:/Users/user_name/Dropbox/Literature/previously_stored_file_name.pdf
```

after BBT has parsed it, and that I can import; alternately, what you did, is that BBT supports the unsupported `files` field, with the semantics "treat this as if you saw `file =`, but don't parse in verbatim mode.

**Comment by sophieqzwang** [comment]
Thanks a lot for the explanation! I would never have thought the issue is with the gravely-erroneously placed `\backslash` in the verbatim `file` field. I hope this will be useful for others migrating from Mendeley.
