### ISSUE TITLE
Citation key on mobile devices

### ISSUE THREAD

**Issue by sopertob** [retorquere/zotero-better-bibtex#1741]
*Please verify **all** of the below before submitting*:

1. you have picked the right category for the issue in the previous screen.
2. You are on the latest release of Zotero
3. in the Zotero addons screen you can see that you have the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest)
4 you are posting a single question.
5. the issue has a subject that succinctly describes the problem or question.
6. you are available for follow-up questions and testing.

Picking the right issue category is really important. Each category (`Export`, `General error`, `Import`, `Key generation`, `Question`) has different instructions for gathering the data necessary required to resolve the issue you are experiencing

**Your question/suggestion:**

Is it possible to have citation keys copy their information to the Extra field when BBT is creating them? Viewing a Zotero database on a mobile device (or over the web) does not show the citation key. (I understand that as a plugin, the actual key can't be shown).

**Comment by retorquere** [comment]
[yes](https://retorque.re/zotero-better-bibtex/installation/preferences/hidden-preferences/#autopindelay) :)

**Comment by sopertob** [comment]
> [yes](https://retorque.re/zotero-better-bibtex/installation/preferences/hidden-preferences/#autopindelay) :)

Thank you for your reply. Alas, I do not see in those options the resolution I am looking for. I was hoping that when I create a new entry and BBT creates a cite key for it that the cite key would be automatically copied to the Extra field. It's quite likely I am overlooking something obvious

**Comment by retorquere** [comment]
Sorry, that was too terse: "pinning" means that the key is written in de `extra` field; it is called "pinning" because however the citekey git into the `extra` field (by writing/editing it manually, or having BBT write it there), that will be the citekey for the item regardless of what else changed about the item. With [autoPinDelay](https://retorque.re/zotero-better-bibtex/installation/preferences/hidden-preferences/#autopindelay) set to anything higher than `0`, BBT will wait that many seconds after creation/change of the item, and after that writes the current key in the `extra` field (given there isn't one already).

**Comment by retorquere** [comment]
For existing items, you can select them all, right-click, and select "pin citekey" from the pop-up menu. That will write the citekey into the `extra` field for those items that don't have the key there already.

**Comment by sopertob** [comment]
Ah, thank you. This makes more sense to me now. I was able to get it to
work. I set the delay to 10 so that BBT wouldn't write out the key as
`zotero####` while I was filling in fields.
