### ISSUE TITLE
Cannot ignore "archivePrefix" export field

### ISSUE THREAD

**Issue by talesa** [retorquere/zotero-better-bibtex#1744]
Hello!
Firstly, thanks for this amazing piece of software!

The problem:
I cannot get Better Bibtex to ignore "archivePrefix" export field despite adding it (with different capitalization) to the "Fields to omit from export" field in the export settings.
![image](https://user-images.githubusercontent.com/6434262/108635187-f841f580-7475-11eb-9c57-2a26d379b4da.png)

**Report ID:**
IR9LXNSF-euc

**Exporter used:**
"Copy as Better Bibtex" `cmd+shift+c`

**Expected behavior:**
```
@article{brekelmans2020All,
  title = {All in the {{Exponential Family}}: {{Bregman Duality}} in {{Thermodynamic Variational Inference}}},
  author = {Brekelmans, Rob and Masrani, Vaden and Wood, Frank and Steeg, Greg Ver and Galstyan, Aram},
  year = {2020},
  journal = {ICML}
}
```

**Actual behavior:**
```
@article{brekelmans2020All,
  title = {All in the {{Exponential Family}}: {{Bregman Duality}} in {{Thermodynamic Variational Inference}}},
  author = {Brekelmans, Rob and Masrani, Vaden and Wood, Frank and Steeg, Greg Ver and Galstyan, Aram},
  year = {2020},
  archivePrefix = {arXiv},
  journal = {ICML}
}
```

Best wishes,
Adam

**Comment by talesa** [comment]
Dear @retorquere, you are absolutely amazing, never saw such a responsive author before, thank you so much!

**Comment by retorquere** [comment]
You're welcome. Does it work for you? I've added `IR9LXNSF-euc` as a case in my test suite, so it should, but I always prefer to actually know it's fixed for you.

**Comment by talesa** [comment]
Yes, I confirm it works perfectly!

**Comment by retorquere** [comment]
Cool, I'll merge it in a new release. You can just keep this or force-upgrade when it drops in about 10 minytes (the full test suite must pass again), you'll be upgraded automatically when Zotero checks for new plugin releases. The new version is just what you have with a new version number slapped on.

**Comment by retorquere** [comment]
skip-fields should be case insensitive, but it does so by lower-casing the skip-fields input on the assumption that BBT adds all fields in lowercase, which it did, except for `archivePrefix` and `primaryClass`, meaning it was always impossible to match those. These are now added in lowercase, and I've added an extra check to make sure I cannot add fields that are not all-lowercase, so it should not occur again, because my tests will fail, and I can't release official or test builds when any test fails. Keeps me honest.
