### ISSUE TITLE
Decapitalize the words of the title during key generation

### ISSUE THREAD

**Issue by talesa** [retorquere/zotero-better-bibtex#1745]
Hello!

[feature request]
Many of the articles in my library have all of the words in its title capitalized, e.g., "All in the Exponential Family: Bregman Duality in Thermodynamic Variational Inference".
I would like to be able to decapitalize the words of the title during key generation, see below.
I understand that the current behaviour is intended (i.e., a feature rather than a bug), but it would be great if the behaviour I'm seeking would also be supported via some setting, e.g. citation key field `[veryshorttitleN_M_K]` which would allow for decapitalization using argument `K` 🙏 

Thank you!

**Report ID:** IR9LXNSF-euc

**Expected behavior:**
Titles: 
"All in the Exponential Family: Bregman Duality in Thermodynamic Variational Inference"
"Flows for simultaneous manifold learning and density estimation"

Citation key format: Key
`[veryshorttitle1_0]`: `all`, `flows`
`[veryshorttitle2_0]`: `allexponential`, `flowssimultaneous`
`[veryshorttitle2_1]`: `Allexponential`, `Flowssimultaneous`
`[veryshorttitle2_2]`: `AllExponential`, `FlowsSimultaneous`

**Actual behavior:**
`[veryshorttitle1_0]`: `All`, `Flows`
`[veryshorttitle2_0]`: `AllExponential`, `Flowssimultaneous`
`[veryshorttitle2_1]`: `AllExponential`, `Flowssimultaneous`
`[veryshorttitle2_2]`: `AllExponential`, `FlowsSimultaneous`

It also applies to citation key format `shorttitleN_M`.

Best wishes,
Adam

**Comment by retorquere** [comment]
Wouldn't `[veryshorttitle1_0:lower]` etc work for you?

**Comment by retorquere** [comment]
BTW if you keep your titles in Title Case in Zotero you're going to run into bibliography styling problems. Zotero expects titles to be entered in sentence case.

**Comment by talesa** [comment]
Yes, `[veryshorttitle1_0:lower]` definitely would work!

>bibliography styling problems

If it wouldn't take you too much time, could you point me to what kind of problems should I beware of because of that?

**Comment by retorquere** [comment]
Zotero expects titles to be in sentence case, so if you are making a bibliography in a bib style that required sentence-cased titles, Zotero would just not do anything, and you'd end up with a bibliography in title case. At my uni, you'd get points docked for that.

Likewise, since BBT assumes titles to be in sentence case, it will assume that mid-sentence words with uppercase are things like proper names, and protects them against case-changed, and if you make a bibliography for a style that demands sentence case, all these words would be protected, and you'd end up with a bibliography in title-case.

You can turn off the latter behavior in BBT, but that wouldn't fix the problem in Zotero-rendered bibliographies.
