### ISSUE TITLE
CAYW URL override not working 

### ISSUE THREAD

**Issue by soenkewindhausen** [retorquere/zotero-better-bibtex#1747]
In the [Cite as you write Dokumentation](https://retorque.re/zotero-better-bibtex/citing/cayw/) it says, that one can override the abbreviations. 

> In your call to the CAYW URL, you can override the abbreviations by adding them to the query, e.g. http://127.0.0.1:23119/better-bibtex/cayw?format=mmd&page=&Section=sec., page-picks will have no label, and Section-picks will get sec. rather than Sec..

I try to modify a [Alfred Workflow](https://github.com/chrisgrieser/pandoc_alfred). 

script: `http://127.0.0.1:23119/better-bibtex/cayw?format=pandoc&page=&minimize=true`
Current behaviour: 
output: [@citekey, p. 11]

Expected behaviour: 
output: [@citekey, 11]

Debug: XINXHREB-euc

Love BTT, I use it every day. Thank you!

**Comment by soenkewindhausen** [comment]
Debug: XINXHREB-euc

**Comment by retorquere** [comment]
> script: `http://127.0.0.1:23119/better-bibtex/cayw?format=pandoc&page=&minimize=true`
> Current behaviour:
> output: [@citekey, p. 11]
> 
> Expected behaviour:
> output: [@citekey, 11]
> 
> Debug: XINXHREB-euc

I'm not familiar with Alfred, but it doesn't seem like you're triggering this URL yet:

*  In your logs, I only see a call to `http://127.0.0.1:23119/better-bibtex/cayw?format=pandoc`, without any parameters
* `http://127.0.0.1:23119/better-bibtex/cayw?format=pandoc&page=&minimize=true` would give `@citekey, 11`, not `[@citekey, 11]` -- to get brackets, the call would have to be to `http://127.0.0.1:23119/better-bibtex/cayw?format=pandoc&page=&minimize=true&brackets=true`, and since you're seeing brackets, you must be triggering an URL that has this option active.

Can you try typing the following in a shell window?

```
curl 'http://127.0.0.1:23119/better-bibtex/cayw?format=pandoc&page=&minimize=true&brackets=true'
```

**Comment by soenkewindhausen** [comment]
I am honestly not sure what I did wrong, but it worked!

This worked: 
`curl 'http://127.0.0.1:23119/better-bibtex/cayw?format=pandoc&page=&minimize=true&brackets=true'`

 Thanks you very much.
