### ISSUE TITLE
Any way to add file paths to export?

### ISSUE THREAD

**Issue by element4l** [retorquere/zotero-better-bibtex#1784]
I know there's a post asking about writing URLs, but this is slightly different. Is there a way to get file paths written to exported metadata in betterbibtex, biblatex, or with JSON or something like that? It would really help to sync, or at least push, Zotero libraries to other apps.

**Comment by retorquere** [comment]
Debug log. Please. You're leaving me blind here.  I don't know how I can have label-gun phrase this more clearly - open to suggestions here. A significant number of issue reports come without a debug log, and without it, I'd have to guess at your BBT configuration.

**Comment by element4l** [comment]
I'm very confused at the need for a debug log. This isn't a bug. I'm just
asking if there are any configurations that include the pdf's location...
Or if that could be added as a feature.

**Comment by retorquere** [comment]
Not this again. **Why must this be so hard?!** I have tried to make the message by @label-gun as chipper and neutral as possible while explaining that yes, I need this debug log, and I know better than you on this matter.

BBT is already supposed to add the paths, and if you could just do those 4 clicks to get me a debug log, I might be able to determine why for you it doesn't. And if it didn't already do this, I would *also* have requested a debug log, as a sample to test the new feature.

I am thoroughly baffled and more than a little exasperated that people ignore the request for a debug log twice, and then choose to argue I don't need a debug log when I explicitly request one. You have spent more time typing the previous message than it would have taken you to send the debug log. I could probably have fixed the problem or the misconfiguration by now if you were willing to let me help you.

*Please. send. a. debug. log.* **Please**. At the very least it will give me your BBT settings so that I may be able to replay this locally. I am the sole creator of BBT and I designed the debug log to help me understand under what conditions BBT operates on a system I cannot access. *Please* just simply trust me when I say I need a debug log.

**Comment by element4l** [comment]
Wow. Are you ok? This was a question, not a bug. I'm not having issues with
writing the file paths. I'm literally just asking if this even exists in
the first place. I didn't even know that it did this in the first place

Sheesh. Take a vacation or something. My god.

**Comment by retorquere** [comment]
I might not be OK, but having this conversation many times over does not help. I find myself in a situation where I genuinely want to help people use my software, but having to plead, but not too obviously, that I need a support log to help. If it were just you, I might not have minded, but I created label-gun because it is depressingly common, as is this discussion we're having here. Granted, you're the first to persist in the position. Congratulations. 

BBT has a ton of configuration options, some of which affect whether fields such as `path` get generated at all. If you'd have sent a debug log with the initial request, I might have been able to tell whether that is the case. The support request template asks for a debug log, label-gun quite politely stresses that it's more likely than not to apply to you. But you take the time to argue that surely I must be mistaken, rather than allowing me to help you.

I can see how one might think it wouldn't apply, given that we're not sure at this point whether it is a bug, but how can you hold to that conviction if I request it despite all that? I try to keep the conversation at a level where we can still get to the point where I can help you, and for all I know this *is* a bug that prevents generation of the `file` field in your case - would be lovely if I could exclude that. I hadn't expected a response to basically fuck off, but here we are.

**Comment by element4l** [comment]
I think you need to carefully re-read the entire conversation because
you're still confused, and rude. And that's the end of this conversation.

Goodbye.

**Comment by retorquere** [comment]
I have carefully re-read the conversation, and it did in fact go from polite, to pleading, to rude on my end, whereas you were unchangingly uncooperative.
