### ISSUE TITLE
Postfixed keys different between computers

### ISSUE THREAD

**Issue by shirdekel** [retorquere/zotero-better-bibtex#1788]
*Please verify **all** of the below before submitting*:

1. you have picked the right category for the issue in the previous screen.
2. You are on the latest release of Zotero
3. in the Zotero addons screen you can see that you have the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest)
4. you are posting a single bug or feature request.
5. the issue has a subject that succinctly describes the problem or question.
6. you are available for follow-up questions and testing.
7. you have included an support log ID here generated by reproducing the problem, selecting the problematic reference(s), right-clicking, and submitting an BBT support log from that popup menu, **not** from the `Help` menu.
8. you have included the *actual output* you got from exporting the items you sent in the debug log, not simplified fictional output or a description of the output, and a sample (*not* a description) of how you want it to look instead, again based on the actual items you selected in the previous step.

Picking the right issue category is really important. Each category (`Export`, `General error`, `Import`, `Key generation`, `Question`) has different instructions for gathering the data necessary required to resolve the issue you are experiencing

The support log is important; it gives me your current BBT settings and a copy of the problematic reference as a test case so I can best replicate your problem. Without it, I'm effectively blind.

**Support log ID:**]
Computer 1: RMKW5HAY-apse
Computer 2: YULW4P2S-apse

**Expected behavior:**
Citekeys that are postfixed retain the same keys across computers after sync.

**Actual behavior:**
Two entries with postfixed citekeys (e.g., heyns2021 for Entry 1 and keyns2021a for Entry 2) have their citekeys switched after syncing Zotero (such that Computer 2 has heyns2021a for Entry 1 and keyns2021 for Entry 2).

**Comment by retorquere** [comment]
There isn't much I can do about this (until Zotero creates a format citekey field), as Zotero does not tell me whether an item appears because it was synced in, or because it was just created by you. The closest you can get, I think, is:

On computer 1, set [autoPin](https://retorque.re/zotero-better-bibtex/installation/preferences/hidden-preferences/#autopindelay) to whatever you deem reasonable. This will make the citekey all items that are created/modified from that moment on pinned. This includes items that are synced in. These pinned citekeys will sync back out, so eventually, all installations that sync with the account will get pinned keys get synced back.

On the other computers (in this case, just computer 2), set the [conflict policy](https://retorque.re/zotero-better-bibtex/installation/preferences/citation-keys/#on-conflict-with-a-pinned-key-non-pinned-keys-will-be) to "postfixed".

In the above scenario, both systems would generate the citekey `heyns2021`, but it would be pinned on computer 1, and when that syncs to computer 2, the existing `heyns2021` should move out of the way... which I just now see is broken... I'll get to fixing that, but do you think you can live with the scenario I described?

**Comment by shirdekel** [comment]
Thanks! That makes sense. Is there a reason why Computer 1 couldn't also have a "postfixed" conflict policy? Seems to work either way for me.

However, more important for me is fixing existing entries. The only way to fix this automatically would be to pin all my entries and then sync, right? At the moment none of my entries are pinned. I supposed I imagined that it's more flexible this way in case I end up wanting to change the key scheme in the future (but this is unlikely). What are the downsides of pinning all the entries and then setting autoPin as you said?

**Comment by retorquere** [comment]
> Thanks! That makes sense. Is there a reason why Computer 1 couldn't also have a "postfixed" conflict policy? Seems to work either way for me.

For this scenario it doesn't matter what the key conflict policy is on computer 1. But I need to fix the keyconflict policy feature  before it'll work. I'll probably have something to test later today.

> However, more important for me is fixing existing entries. The only way to fix this automatically would be to pin all my entries and then sync, right?

Correct -- once I fix the conflict policy. 

> At the moment none of my entries are pinned. I supposed I imagined that it's more flexible this way in case I end up wanting to change the key scheme in the future (but this is unlikely). What are the downsides of pinning all the entries and then setting autoPin as you said?

Just that they won't update as you change the entry. At some point you generally don't want that to happen anyway -- when you start using the keys in articles, the keys being stable is generally more important than that they differ in minor ways from the article they refer to.

**Comment by shirdekel** [comment]
> For this scenario it doesn't matter what the key conflict policy is on computer 1. But I need to fix the keyconflict policy feature before it'll work. I'll probably have something to test later today.

Happy to help test whenever it's ready.

> Just that they won't update as you change the entry. At some point you generally don't want that to happen anyway -- when you start using the keys in articles, the keys being stable is generally more important than that they differ in minor ways from the article they refer to.

Yes, I agree. Thanks!

**Comment by retorquere** [comment]
That took a lot longer than I had expected, but build 676 should do it.

**Comment by retorquere** [comment]
> Thanks! That makes sense. Is there a reason why Computer 1 couldn't also have a "postfixed" conflict policy? Seems to work either way for me.

In this scenario, the keys on computer 1 will end up pinned, so the conflict policy won't actually do anything in the long run. Pinned keys don't move.

**Comment by shirdekel** [comment]
Great, thanks! I will only be able to test with the two computers on Monday, so I'll check back in then. 

To clarify, this isn't mean to "properly" fix the issue, but should allow me to now do what you suggested above? That is, pin all entries on one computer, enable autoPin, enable the "postfixed" conflict policy (can be on both computers), and then sync.

**Comment by retorquere** [comment]
This will be hard to structurally test for you, and I've added a test case to replay an approximation of your scenario, so you don't have to put in extra effort to validate it works -- knowing you have a workable solution would just give me closure. I'm going to roll this out in a new release anyhow, since this functionality was simply missing.

> To clarify, this isn't mean to "properly" fix the issue, but should allow me to now do what you suggested above? That is, pin all entries on one computer, enable autoPin, enable the "postfixed" conflict policy (can be on both computers), and then sync.

Correct. This is as proper as I'm able to fix it -- a proper fix would mean the databases would have to know about each other, and the only realistic way to achieve this is to use the Zotero sync mechanism. When Zotero gains a citekey field, which is said to be Real Soon Now, but that's been the status for a few years, for fairly good reasons, it will be fixed structurally, as you'll just get a sync conflict and the UI that Zotero already has for this will allow you to resolve the clash.

**Comment by shirdekel** [comment]
Pinning all the entries and enabling autoPin is a workable solution for me since it means that postfixed citekeys stay consistent across computers after syncing. Thanks for the help!
