### ISSUE TITLE
progress bar peristing at low state after export

### ISSUE THREAD

**Issue by bwiernik** [retorquere/zotero-better-bibtex#1835]
Support id
K7BAQ5EJ-euc

Once an export completes, the progress bar is resetting at a small state rather than disappearing.
![image](https://user-images.githubusercontent.com/4773225/120830746-d227f900-c52c-11eb-907e-bde05b8d9f91.png)

**Comment by bwiernik** [comment]
Fixed now! Thanks.

**Comment by retorquere** [comment]
I'm trying to get @wohenbushuang to give feedback on #1832, which I want to include in the new release, but if he doesn't respond tonight, I'm cutting a new release. I was trying not to generate too many releases because I got a complaint that the many updates to BBT prompted too many restart requests.
