### ISSUE TITLE
Problems using >X pseudo-filter 

### ISSUE THREAD

**Issue by Ypot** [retorquere/zotero-better-bibtex#1852]
**Support log ID:**
JG3ESEGA-euc

**Expected behavior:**
To admit this citation key format:

`[=forumPost/WebPage][WebsiteTitle:lower:capitalize:>0][Auth:prefix=.][Date:format-date=%Y-%m-%d.%H\:%M\:%S:prefix=.][shorttitle3_3:lower:capitalize:prefix=.][PublicationTitle:select=2,2:capitalize:prefix=.][Pages:prefix=.p.][Volume:prefix=.Vol.][NumberofVolumes:prefix=de]`

**Actual behavior:**
It doesn't admit it, but allows it if I delete the ":>0" part:
`[=forumPost/WebPage][WebsiteTitle:lower:capitalize][Auth:prefix=.][Date:format-date=%Y-%m-%d.%H\:%M\:%S:prefix=.][shorttitle3_3:lower:capitalize:prefix=.][PublicationTitle:select=2,2:capitalize:prefix=.][Pages:prefix=.p.][Volume:prefix=.Vol.][NumberofVolumes:prefix=de]`

Just to literate my problem a bit, this is unrelated to the issue:
I have problems generating citation keys for Websites, so I want to use the Author and/or the WebsiteTitle (if there is no WebsiteTitle, I will use the regular format: `[Auth][date=%oY:prefix=.][PublicationTitle:select=1,1:capitalize:prefix=.][shorttitle4_4:lower:capitalize:prefix=.][Pages:prefix=.p.][Volume:prefix=.Vol.][NumberofVolumes:prefix=de][Issue:prefix=.]`

**Comment by retorquere** [comment]
You were just a little early ;) the docs went out in preparation for a new release. In the mean time you can play around with build 1085.

**Comment by Ypot** [comment]
Thanks. Let's play!!
Have you changed the instructions to use it?
https://retorque.re/zotero-better-bibtex/citing/

I think now it says: [auth][>0][year] 
And before it said something like: [auth:>0][year]

**Comment by retorquere** [comment]
Both work. The first tests whether any of the pattern blocks before it generated output, the second only whether that particular block (to the point where `>0` appears) generated any content. `[auth][>0][year]` and `[auth:>0][year]` will generate the same output because in both cases precisely only the output of the first block is tested, but `[auth][journal][>0][year]` and `[auth][journal:>0][year]` will generate different results when author is filled but journal is not.

**Comment by Ypot** [comment]
That's great. Thank you!

**Comment by retorquere** [comment]
I'm prepping a release now.
