### ISSUE TITLE
Some Extra fields are not exported

### ISSUE THREAD

**Issue by mdbenito** [retorquere/zotero-better-bibtex#1862]
**Problem:** 

I have items with semi-structured content in the "Extra" field as `key:value` pairs separated by newlines. Some keys seem to be automagically handled by BTT, e.g. `arxiv`. Others are exported verbatim, e.g. `citecount`. Others are silently ignored, e.g. `code`. [The documentation](https://retorque.re/zotero-better-bibtex/exporting/extra-fields/) states that they are all made available to postscripts but shouldn't they be just exported if they cannot be handled?

**Support log ID:** K5BZYUN4-refs-euc

**Exporter used:** Better BibLaTeX.

**Expected behavior:**

Extra field in Zotero is exported as `annotation`. The following entry has Extra field = `code: https://github.com/stephenbates19/nestedcv_experiments`

```bibtex
@article{bates_crossvalidation_2021,
  title = {Cross-Validation: What Does It Estimate and How Well Does It Do It?},
  shorttitle = {Cross-Validation},
  author = {Bates, Stephen and Hastie, Trevor and Tibshirani, Robert},
  date = {2021-04-01},
  url = {https://arxiv.org/abs/2104.00673v2},
  urldate = {2021-04-17},
  abstract = {...Cut...},
  annotation = { code: https://github.com/stephenbates19/nestedcv_experiments }
  langid = {english}
}
```

**Actual behavior:**

The `code: xxx` field is silently dropped.

```bibtex
@article{bates_crossvalidation_2021,
  title = {Cross-Validation: What Does It Estimate and How Well Does It Do It?},
  shorttitle = {Cross-Validation},
  author = {Bates, Stephen and Hastie, Trevor and Tibshirani, Robert},
  date = {2021-04-01},
  url = {https://arxiv.org/abs/2104.00673v2},
  urldate = {2021-04-17},
  abstract = {...Cut...},
  langid = {english}
}
```
The following entry had the Extra field in Zotero `citecount: 00114 arXiv: 1708.00588` (with a newline as separator):

```bibtex
@article{raissi_hidden_2018,
  title = {Hidden {{Physics Models}}: {{Machine Learning}} of {{Nonlinear Partial Differential Equations}}},
  shorttitle = {Hidden {{Physics Models}}},
  author = {Raissi, Maziar and Karniadakis, George Em},
  date = {2018-03},
  journaltitle = {Journal of Computational Physics},
  shortjournal = {Journal of Computational Physics},
  volume = {357},
  pages = {125--141},
  issn = {00219991},
  doi = {10.1016/j.jcp.2017.11.039},
  url = {http://arxiv.org/abs/1708.00588},
  urldate = {2019-08-18},
  abstract = {...Cut...},
  annotation = {citecount: 00114},
  archiveprefix = {arXiv},
  eprint = {1708.00588},
  eprinttype = {arxiv}
}
```

If this is intended behaviour, what can I do to obtain the fields back?

**Comment by mdbenito** [comment]
I'm playing with postscripts and can get the field to be exported in YAML with

```javascript

if (Translator.BetterCSLYAML) {
    if (item.extraFields && item.extraFields.kv.code) {
     reference.code = item.extraFields.kv.code;
  }
}
```
I understand from #518  that this is expected to be required customization. But is the same true of biblatex exports?

**Comment by retorquere** [comment]
I'll have to update the documentation -- `code` should have been in that list in the docs, as should some others. The `extra` field code parsing is annoyingly complicated, and it will probably take me a few days to find the time to update the docs generator.

In the case of `code`, that is recognized as a valid field for some Zotero items (`bill` and `statute` to be specific), and fields that are valid for one object but sorta-valid for others will be spliced into the item that doesn't formally support it, the most well-known of these being a `DOI:` line in the `extra` fields of items that don't have a `DOI` field. It is less well know a whole host of fields can be introduced this way, including new creator types.

Extra-fields that are recognized as sorta-valid for either Zotero or CSL-JSON are removed from the `extra` map and added to the item as if they belonged there, and that's what happened to the `code` field, but currently, only biblatex `legislation` items use `item.code`, so it will not usually appear in the output. In a postscript you would find this value under `item.code` rather than `item.extraFields.kv.code`. I recognize this can be annoying as this is unhelpfully unpredictable. What I can do is make the unadulterated `extraFields` available in the postscript as `extra`, so that you would find `extra.kv.code` in the postscript even if it is also available as `item.code`. This is available in build 1143 that was just posted.

As for `citecount: `, that is simply not recognized as a `tex`, Zotero or CSL-JSON field, so it gets passed unchanged; as the "key" is not recognized, the colon doesn't denote it as a potential field, as regular text could have colons. The status of the `extra` field is a bit of a mixed bag -- some people treat it like a note field (I once did), and some treat it as a place to store extra variables (and Zotero supports some of that usage) but how much of it is recognized and how much is retained after the recognition process is not really standardized. In the case of BBT, anything that is recognized as `tex`, a Zotero field or a CSL-JSON field is moved out of the `item.extra` field, and what remains goes into an `annotation`.

**Comment by retorquere** [comment]
There is another issue though because I think `code: ` line should have shown up as `container-title` in the CSL output. I'll take a look at that.

**Comment by mdbenito** [comment]
Thanks for the detailed explanation! Having `extraFields` prepopulated with all values no matter where they land after would remove the need for the manual parsing I did above.

**Comment by retorquere** [comment]
That should already work in build 1143, but available as `extra.kv` in addition to the partially-stripped `item.extraFields.kv` . I'm sorry for the mess that is the `extra` field handling, it's just not standardized well.

`container-title` does indeed not yet show up in the CSL YAML, that's a problem I need to look into, but that's unfortunately part of the code that establishes whether an `extra` field should be recognized, and that has some gnarly graph-evaluation that I haven't touched in a long while, so it will likely take me a few days to get a fix out (which will also address the docs, as they come from the same analysis).

**Comment by retorquere** [comment]
Ha, I remember why `code` wasn't mapped into CSL exports. Hold on to your hat. This is a small chunk of the field mapping visualized.

![Screenshot 2021-06-29 at 09 37 52](https://user-images.githubusercontent.com/132108/123757192-012c5300-d8be-11eb-95df-21ea60f434dc.png)

* white = label which can be used in the `extra` field
* light green = CSL field
* cyan = Zotero field
* black arrow: maps-to
* grey dashed arrow: maps-to with multiple candidates
* blue-dashed arrow: maps-to by inference

so the label `container title` maps to the CSL field `container-title` and because the CSL-field `container-title` in turn maps to Zotero field `reporter`, and inference arrow is added between label `container title` and `reporter`. This means that if you have `container title: something` in your `extra` field, and you export to CSL-JSON/YAML, you will get a `container-title` field in your CSL item, and when you export to any non-CSL format, `item.reporter` will be filled.

The grey-dashed arrows were black arrows, but because there is the potential for overwrites when you export to CSL, and you have in your extra:

```
code: X
reporter: Y
```

both would want to write to the light-green `container-title`, which I figured would be strange behavior. But then, you'd have to know these intricate rules and how this massive graph of label mappings is put together to know that. That isn't reasonable. I think it'd be better to just execute these rules and just select the first match.

**Comment by mdbenito** [comment]
WOW 👀

**Comment by retorquere** [comment]
It's mostly supposed to "just work" keeping this complexity hidden from most. The new rule once implemented will be easier to follow.
