### ISSUE TITLE
Customisation of the export format for authors

### ISSUE THREAD

**Issue by OXiOSDev** [retorquere/zotero-better-bibtex#1912]
Hi,

I export Zotero with Better BibTeX for use it with Obsidian (community plugins : citations)
Everything work fine but I would like to be able to export the authors with each name between "author_name" separate by a comma and all the authors name between square brackets 
for exemple:
authors : ["name1", "name2", "name3"]

Could you help me ?

Thanks a lot

**Comment by OXiOSDev** [comment]
there is no issue so I don't upload a support log

**Comment by retorquere** [comment]
If it relates to export, which this does, I need a support log as per point 1. above. Then we can talk about actual data rather than synthetic examples like `name1`, which in my experience leads to us talking past each other. So if you would please humor me, a log as per point 1. above would really help. The ID will have `-refs-` in it.

**Comment by OXiOSDev** [comment]
Sorry for the misunderstanding

I hope that this log ID is the good one !

MyBetterZoteroLibrary.bib is the export of my Library

For exemple (modification in red):
Line 262 to 274 from this export :
@article{ACircularMappingCatheterIsNotMandatoryForIsolatingPulmonaryVeinsDuringParoxysmalAtrialFibrillationAblationWithRadiofrequency_JIntervCardElectrophysiol_2020,
  title = {A Circular Mapping Catheter Is Not Mandatory for Isolating Pulmonary Veins during Paroxysmal Atrial Fibrillation Ablation with Radiofrequency},
  author = {Xha\"et, Olivier and Deceuninck, Olivier and Robaye, Benoit and Dormal, Fabien and Collet, Benoit and Godeaux, V\'eronique and Huys, Florence and Ballant, Elisabeth and Gourdin, Maximilien and Blommaert, Dominique},
  date = {2020-10-19},
  journaltitle = {J Interv Card Electrophysiol},
  eprint = {33074448},
  eprinttype = {pmid},
  issn = {1572-8595},
  doi = {10.1007/s10840-020-00895-8},
  abstract = {PURPOSE: In this study, we evaluated the feasibility, efficacy, and safety of radiofrequency ablation of paroxysmal atrial fibrillation (AF) with the use of an ablation catheter only (non-CMC group) by retrospectively comparing its procedural success and recurrence rates at 1~year to ablation performed with the help of a circular mapping catheter (CMC group). METHODS: We compared the success and recurrence rates between 226 patients and 251 patients who underwent index ablation with and without the use of CMC, respectively. RESULTS: Freedom from recurrence was defined as a 1-year absence of AF/atrial tachycardia (AT) episodes {$>$}\,30~s, beyond the 3-month blanking period. There was no significant difference between the number of pulmonary vein isolations, recurrence rate of AF/AT, and the use of antiarrhythmic drugs after 1~year of ablation. The procedure and fluoroscopy times were lower in the non-CMC group compared with the CMC group (106\,{$\pm$}\,33 vs. 125\,{$\pm$}\,32~min, p\,{$<$}\,0.0001; 2.2\,{$\pm$}\,1.9 vs. 2.7\,{$\pm$}\,2.3~min, p\,=\,0.0002, respectively). CONCLUSIONS: Pulmonary vein isolation without the use of a CMC is feasible; moreover, the material costs, procedure time, and radiation exposure were reduced compared with the CMC group. Freedom of recurrence was similar between groups. Optimized use of 3D electro-anatomical mapping systems could reduce the radiation exposure for both the patient and physician.},
  langid = {english},
  keywords = {3D mapping,Ablation,Atrial fibrillation,Circular mapping catheter,Swing-fall technique}
}

What I expect :
@article{ACircularMappingCatheterIsNotMandatoryForIsolatingPulmonaryVeinsDuringParoxysmalAtrialFibrillationAblationWithRadiofrequency_JIntervCardElectrophysiol_2020,
  title = {A Circular Mapping Catheter Is Not Mandatory for Isolating Pulmonary Veins during Paroxysmal Atrial Fibrillation Ablation with Radiofrequency},
  author = {["Xha\"et, Olivier" and "Deceuninck, Olivier" and "Robaye, Benoit" and "Dormal, Fabien" and "Collet, Benoit" and "Godeaux, V\’eronique" and "Huys, Florence" and "Ballant, Elisabeth" and "Gourdin, Maximilien" and "Blommaert, Dominique”]},
  date = {2020-10-19},
  journaltitle = {J Interv Card Electrophysiol},
  eprint = {33074448},
  eprinttype = {pmid},
  issn = {1572-8595},
  doi = {10.1007/s10840-020-00895-8},
  abstract = {PURPOSE: In this study, we evaluated the feasibility, efficacy, and safety of radiofrequency ablation of paroxysmal atrial fibrillation (AF) with the use of an ablation catheter only (non-CMC group) by retrospectively comparing its procedural success and recurrence rates at 1~year to ablation performed with the help of a circular mapping catheter (CMC group). METHODS: We compared the success and recurrence rates between 226 patients and 251 patients who underwent index ablation with and without the use of CMC, respectively. RESULTS: Freedom from recurrence was defined as a 1-year absence of AF/atrial tachycardia (AT) episodes {$>$}\,30~s, beyond the 3-month blanking period. There was no significant difference between the number of pulmonary vein isolations, recurrence rate of AF/AT, and the use of antiarrhythmic drugs after 1~year of ablation. The procedure and fluoroscopy times were lower in the non-CMC group compared with the CMC group (106\,{$\pm$}\,33 vs. 125\,{$\pm$}\,32~min, p\,{$<$}\,0.0001; 2.2\,{$\pm$}\,1.9 vs. 2.7\,{$\pm$}\,2.3~min, p\,=\,0.0002, respectively). CONCLUSIONS: Pulmonary vein isolation without the use of a CMC is feasible; moreover, the material costs, procedure time, and radiation exposure were reduced compared with the CMC group. Freedom of recurrence was similar between groups. Optimized use of 3D electro-anatomical mapping systems could reduce the radiation exposure for both the patient and physician.},
  langid = {english},
  keywords = {3D mapping,Ablation,Atrial fibrillation,Circular mapping catheter,Swing-fall technique}
}

Support log ID : VEILWB2J-euc



Olivier Xhaet

**Comment by retorquere** [comment]
> For example (modification in red):

Text make-up like colors do not come through if you respond by mail. You can make things bold or italic if you enter them on the site (which is preferred over mail responses because I can restyle them for clarity).

It seems like you want to change

```
author = {Xha\"et, Olivier and Deceuninck, Olivier and Robaye, Benoit and Dormal, Fabien and Collet, Benoit and Godeaux, V\'eronique and Huys, Florence and Ballant, Elisabeth and Gourdin, Maximilien and Blommaert, Dominique},
```

into

```
author = {["Xha\"et, Olivier" and "Deceuninck, Olivier" and "Robaye, Benoit" and "Dormal, Fabien" and "Collet, Benoit" and "Godeaux, V\’eronique" and "Huys, Florence" and "Ballant, Elisabeth" and "Gourdin, Maximilien" and "Blommaert, Dominique”]},
```

this is different from what you said in your initial post BTW. These names are `and` separated, not comma-separated.

What you want is in principle possible using a [postscript](https://retorque.re/zotero-better-bibtex/exporting/scripting/) which I can help you write, but it's not going to be pretty, and it's going to be a fair bit of code, too.

Where is this format documented for the obsydian plugin? Before I start writing this code I'd prefer to know why the plugin author chose this rather strange format.

**Comment by njbart** [comment]
> `author = {["Xha\"et, Olivier" and "Deceuninck, Olivier" and "Robaye, Benoit" and "Dormal, Fabien" and "Collet, Benoit" and "Godeaux, V\’eronique" and "Huys, Florence" and "Ballant, Elisabeth" and "Gourdin, Maximilien" and "Blommaert, Dominique”]},`

I am pretty sure this is not a legitimate bibtex/biblatex name format at all, and the issue should be taken up with the obsidian-citation-plugin maintainers (unless, of course, I’m missing something, and someone can point us to authoritative bibtex/biblatex specs that would say otherwise.)

**Comment by retorquere** [comment]
Exactly, this is why I want to look at what the obsidian plugin expects precisely. It's not going to be behavior BBT is going to exhibit on its own, but if this is indeed what the obsydian plugin expects, with a postscript there's a lot of opportunity to output whatever you want.

**Comment by retorquere** [comment]
@hans, can you tell me more about what the plugin expects/needs?

**Comment by OXiOSDev** [comment]
First of all, I would like to apologize. I underestimated the complexity of the problem.

I will do a general overview of the process tonight and the result I would like to achieve

I realize that the cornerstone for optimizing data exchange between Zotero and Obsidian could be in the Obsidian plugin.

I will come back to you this evening (GMT + 1).

Nevertheless, I already wanted to thank you for your time and your help.

Olivier Xhaet

**Comment by retorquere** [comment]
No problem.

While names are indeed complex, generating the above output (either `and` separated or comma separated) wouldn't be particularly complex for me, as I could reshuffle the existing code and generalize name generation to include this format. But before I do that, I'd like to know what I'm targeting, to prevent I build integration infra for one particular and perhaps limited case rather than the more general case of obsydian integration.

I also really wonder why any app would choose to use bibtex as a format (even using an older version of the BBT parser to read it from the looks of it) and then choose this non-bib(la)tex format inside it. If the plugin wants to recover the names during parse, that's what the parser does. The bracket-and-quote format doesn't make sense to me as of yet. I also would not be able to parse it back in.

**Comment by hans** [comment]
Hi @OXiOSDev , you can certainly achieve what you'd like here in the Obisidian plugin rather than modifying the BibTeX export.

Because we use [Handlebars](https://handlebarsjs.com/guide/) for templating, you can accomplish the spec with a simple loop in your template, like so:
```
authors: [{{#each entry.author}}"{{this.family}}, {{this.given}}"{{#unless @last}}, {{/unless}}{{/each}}]
```

Note that double quotes `"` should be automatically escaped in the template insertions here, so this should produce valid YAML frontmatter, which is what I assume you're aiming for here.

**Comment by retorquere** [comment]
Ah - that looks like it's best discussed on the obsydian plugin repo rather than here.

**Comment by OXiOSDev** [comment]
Thanks a lot for your help even if the solution is not in your plugin for Zotero.

As you have understood, I try to obtain a valid YAML frontmatter with authors individualized to be able to make a sort with the dataview obsidian plugin

Olivier Xhaet

**Comment by retorquere** [comment]
No problem. This is what we were trying to suss out btw - we were trying to understand the problem given the proposed solution.
