### ISSUE TITLE
Option to export `language` as `language` and/or `langid`

### ISSUE THREAD

**Issue by alexreg** [retorquere/zotero-better-bibtex#1926]
It would be nice to have checkboxes to export Zotero's `language` field as biblatex's `language` and `langid` fields, separately — i.e., either of them, both, or neither.

**Zotero version:**
5.0.96.3

**BBT version:**
5.4.29

**Suport log ID:**
GSH7VLRI-refs-euc

Support log ID:

**Comment by retorquere** [comment]
These test logs include an item that serves two purposes:

* it makes sure that whatever discussion we have as a follow-up is about something definite rather than something hypothetical
* I add these to my test suite to prevent accidental regressions.

Please reopen the issue by adding a support log ID. The issue will re-open automatically when you comment.

**Comment by njbart** [comment]
Well, I think it would be wrong to even offer such an option. 

Zotero’s "Language" field and its exact counterpart, biblatex’s "langid" field, contain standardized tags and serve exactly one purpose: to switch hyphenation patterns and localise strings in the bibliography.

biblatex’s "language" field, OTOH, is supposed to contain information about the *content* of the work and to be rendered in human-readable form. In addition, it might very well contain more than one language, e.g., "Latin and English". Zotero does not have a counterpart.

So mapping Zotero’s "Language" field to biblatex’s "language" field is arguably a pretty bad idea, despite the homonymy.

If the language(s) of the work’s *content* have to be recorded in and rendered from Zotero, using any of the Zotero fields (or CSL variables) "Genre", "Medium", "Extra" might work. For exporting to biblatex, some BBT postscript solution should work, or the biblatex "language" variable could be defined in the Zotero entry using BBT syntax.

**Comment by alexreg** [comment]
@retorquere Test logs have no relevance to a feature suggestion.

**Comment by alexreg** [comment]
@njbart You're right about the purpose of the `langid` and `language` fields in biblatex, and I didn't realise the `language` field in Zotero was only about how it's displayed. Is there no field for the actual content language of the work?

**Comment by retorquere** [comment]
> @retorquere Test logs have no relevance to a feature suggestion.

That is a common misconception, which is why I renamed them to "support logs". Please let me be the judge of what I do or do not need for support.

This is aside the other conversation we're also having here, which we should resolve first, and if the outcome is "no action", then indeed I do not need a support log.

**Comment by alexreg** [comment]
@retorquere Apologies. I didn't read the bot's message properly, at first. (I did after posting the above comment, and thus deleted it quickly, but it seems you were even quicker heh!) I've included the log ID now. Sorry again.

**Comment by retorquere** [comment]
(much appreciated. If we do get to BBT changes, I will need a support log as per the steps listed under point 1., as that will give me the copy of the item as a test case; those IDs have `-refs` in the ID. But we can postpone that until we've settled the ongoing discussion)

**Comment by alexreg** [comment]
@retorquere Ah, certainly. I've updated the post with the right sort of support log now.

**Comment by duncdrum** [comment]
@njbart is this documented somewhere? i m pretty sure i have seen Zotero import from MARC/MODS catalogues to the language field, as describing the language of the work. I also can't understand how Zotero would use that field for hyphenation patterns anywhere.

**Comment by njbart** [comment]
> is this documented somewhere?

Not really. https://docs.citationstyles.org/en/1.0.1/specification.html#appendix-iv-variables does not even mention `language`. IIRC, it’s also not even possible to render this variable in the output. In the case of Zotero, it seems to be used exclusively for determining whether to title-case titles (if required by a CSL style file) or not.

The [1.0.2 draft](https://github.com/citation-style-language/documentation/blob/master/specification.rst#standard-variables) does mention it, though: "**language**    The language of the item;    Should be entered as an ISO 639-1 two-letter language code (e.g. "en", "zh"), optionally with a two-letter locale code (e.g. "de-DE", "de-AT")". 

I’m not sure whether this will change anything in terms of rendering capabilities, but it seems to support the idea that this field is to be used for language tags only, and, what’s more, for exactly one tag per entry. (Which precludes it being used for what I see to be one of the more useful purposes of the biblatex `language` field, i.e., rendering information about bi-/tri-/…-lingual editions and other unusual language constellations.)

**Comment by retorquere** [comment]
@njbart can that list of languages in the `language` field be used to determine what fields are what language (eg an english title in a german volume)?

**Comment by njbart** [comment]
Not at all.

**Comment by alexreg** [comment]
So is there no chance of a custom field for `language` rather than `langid`?

**Comment by retorquere** [comment]
If you just want an extra field in the export, you can use `tex.<any-field-you-want>: <value>` in the Zotero `extra` field. If you want to rename a field in the export, a postscript can do that. But looking at this issue history I thought we had settled on the current behavior wrt exporting the zotero `language` field to be the correct answer, and since the discussion stopped since then, I thought that was all there was to it. If you want help with a postscript, I'll be glad to create one for you, or if there are other reasons why `language` should be exported differently, I'm open to discussing them.

**Comment by alexreg** [comment]
@retorquere Ah, it's good to know this can be done with ha postscript to rename a field. I'll have a look at that (and only bother you again if it proves a challenge). Thanks for your help.

**Comment by retorquere** [comment]
Eh, the postscript environment isn't fully documented. I don't mind writing them.

**Comment by alexreg** [comment]
@retorquere In that case, I'd appreciate if you'd post an example of how to do this here... but take you're time, I have no particular rush. :-)

**Comment by retorquere** [comment]
To rename a field, without doing anything else? The simplest way is to do

```
if (Translator.BetterTeX && reference.has.language) {
  reference.has.language.name = 'someothername'
}
```

it's a bit cheety, the proper way would be to add a new field and remove the old one, but this just renames in situ. The downside is that any code behind it can't test for `reference.has.someotherfield` so it could get confusing at some point.

**Comment by alexreg** [comment]
Thanks very much.

Why can't it test for `reference.has.someotherfield`?

**Comment by retorquere** [comment]
Because `reference.has.<name>` is a pointer to a structure that itself has a field `name` which is set to `<name>` by BBT. Changing the latter value to `<newname>` doesn't delete the pointer `reference.has.<name>` and add the pointer `reference.has.<newname>`. The renamed field is still pointed to by `reference.has.<name>`.

**Comment by alexreg** [comment]
Cheers. While I'm at it, I might as well ask how you remome an old field and add a new one, as you originally suggested... unless it's kind of tricky?

**Comment by retorquere** [comment]
```
if (Translator.BetterTeX) {
  reference.add({ name: 'someotherfield', value: reference.remove('language').value })
}
```

`reference.remove` is always safe to use this way, if there is no field `language` it will return an empty `.value`, and passing an empty value to `reference.add` will cause it to ignore the call.

Technically the previous rename should be faster, but I don't think you can measure the difference to be honest.

**Comment by alexreg** [comment]
Thanks!
