### ISSUE TITLE
Add a Better Bibtex CSL to the Zotero Style Repository

### ISSUE THREAD

**Issue by kerim** [retorquere/zotero-better-bibtex#1959]
There is a [standard Bibtex style](https://www.zotero.org/styles?q=bibtex) in the CSL repository, but it would be great to have one that conforms to the BetterBibtex style instead. This would be especially useful on mobile where one cannot access plugins. I see someone tried a workaround by [creating an ios shortcut](https://appademic.tech/zotero-ios-shortcuts-better-bibtex-citation-keys/) that would do this, but it doesn't work for me. In any case, a CSL would be much simpler and more robust (less prone to breaking).

**Comment by kerim** [comment]
Not asking you to do this, but it seems that someone could write an iOS shortcut to search and read the citekeys from the JSON export?

**Comment by retorquere** [comment]
> OK. I think I can possibly work with this. I would basically have a text document synced from iCloud that I could search for the keys on mobile?

That is an alternate solution. You could build this with BBTs auto-export. What I meant earlier would use the CSL workflow you described, but with the CSL `note` field to hold the citekey.

> Not asking you to do this, but it seems that someone could write an iOS shortcut to search and read the citekeys from the JSON export?

No idea (I don't have iOS devices), but it depends on what you mean by "the JSON export". CSL-JSON? Maybe? BBT-JSON? No, because that's only available in the desktop client.
