### ISSUE TITLE
Zotero Menu Button for Manual Export

### ISSUE THREAD

**Issue by dm5n** [retorquere/zotero-better-bibtex#2001]
**Zotero version:** 5.0.96.3

**BBT version:** 5.6.11

System: macOS 12.0.1

Hi . Thanks so much for this excellent plugin.

I'm using it with Obsidian md and Zettlr.

After adding a reference to Zotero, there is an annoying delay before the library is auto-exported to .bib and .json files.

My current workaround is to goto the BBT menu in Zotero Preferences and hit the Export Now button.

Would it be possible to have this function on the Zotero menu bar or as a button on the app itself?

**Comment by dm5n** [comment]
Support log ID: 8M7WEJHN-apse

**Comment by retorquere** [comment]
You have [autoExportDelay](https://retorque.re/zotero-better-bibtex/installation/preferences/hidden-preferences/#autoexportdelay) set to a non-default value of 456 seconds -- 7 minutes and 36 seconds. The default is 5, the minimum is 1.

If you set auto-export mode set to manual or idle rather than immediate, the collections right-click menu gets a button to export auto-export collections set up for them.

**Comment by dm5n** [comment]
Fixed it, thanks.
