### ISSUE TITLE
Order of exported entry content

### ISSUE THREAD

**Issue by orzechow** [retorquere/zotero-better-bibtex#2038]
_support log ID: G882EKS5-refs-euc_

First of all, thanks for the helpful plugin! :+1: 

I'm using BetterBibLaTeX with auto-export in a git repository (without using `zotero.betterbibtex.push` – I prefer to use git manually as I'm checking the diff before committing).  
From time to time, when my library is exported, many entries in the `.bib` file have a diff, only because the order of their content (like place, number of pages, date, etc.) changes. E.g.:

```diff
 @book{siciliano_springer_2016,
   title = {Springer {{Handbook}} of {{Robotics}}},
   editor = {Siciliano, Bruno and Khatib, Oussama},
   date = {2016},
+  series = {Springer {{Handbooks}}},
   publisher = {{Springer International Publishing}},
   doi = {10.1007/978-3-319-32552-1},
-  langid = {english},
-  series = {Springer {{Handbooks}}}
+  langid = {english}
 }
```

While this is not a deal-braker, it hinders to keep track of real content change (new library entries, fixes of entry data, …).

So, is it possible to sort the entry content in BetterBibLaTeX when/before exporing, e.g. alphabetically, to keep their order and prevent such diffs?

I know, there are [a couple](https://github.com/retorquere/zotero-better-bibtex/issues/525) [of](https://github.com/retorquere/zotero-better-bibtex/issues/766) [issues](https://github.com/retorquere/zotero-better-bibtex/issues/957) where you explain that you have no influence on the order of entries – but this is about the order of content (or whatever the proper name) within the entries :grin:

**Comment by retorquere** [comment]
The fields should already be sorted consistently; the order is

<details><summary>expand to see list</summary>

- type
- ids
- title
- shorttitle
- booktitle
- author
- editor
- translator
- holder
- options
- date
- origdate
- year
- month
- journal
- journaltitle
- shortjournal
- series
- edition
- volume
- number
- eprint
- eprinttype
- primaryclass
- pages
- publisher
- address
- institution
- location
- issn
- doi
- url
- urldate

- [any fields not named here in alphabetical order]
 
- keywords
- annotation
- note
- groups
- timestamp
- files
- file
</details>

so `langid` should always come after `series`. Can it be that these are entries that haven't been updated since before I implemented this sorting, and that are now sorted this way?

**Comment by orzechow** [comment]
> The fields should already be sorted consistently

That would be great :ok_hand: 

> Can it be that these are entries that haven't been updated since before I implemented this sorting

Well, that's possible. My last commit of this bib file is from 2021-02-08, so already one year old.
Did you add the sorting afterwards?

> and that are now sorted this way?

Yes, now the sorting is according to your list.

**Comment by retorquere** [comment]
> > The fields should already be sorted consistently
> 
> That would be great 👌

By "should" I mean "is, and if it isn't for you, that's a bug I'd need to look into"

> Well, that's possible. My last commit of this bib file is from 2021-02-08, so already one year old. Did you add the sorting afterwards?

There have been 5 changes to the sort order:

2020-01-06 21:41:25 +0100
2020-08-27 10:33:26 +0200
2021-07-16 22:56:55 +0200
2021-07-17 00:33:49 +0200
2021-07-21 07:08:47 +0200

so that could fit.

**Comment by orzechow** [comment]
Alright, so then I'll observe, if that happens again to newer bib files – in which case, I'd reopen the issue.

Thanks for the quick response!
