### ISSUE TITLE
the setting/about:config does not represent bbt's real setting/behavior correctly

### ISSUE THREAD

**Issue by esnahn** [retorquere/zotero-better-bibtex#2049]
I can't reproduce the problem, but:

Even though "Force citation key to plain text" was unchecked,
BBT kept transliterating korean characters in [Auth] and [Title] to alphabet.

I was going to report that as an issue, but after I cycle (check-OK-uncheck-OK) the setting,
[Auth] works just as documented.

So I think that the checkbox(s) in the setting being incorrect (sometimes) was the real problem here.

Support log ID: IZME24Q8-refs-apse

**Comment by retorquere** [comment]
> So I think that the checkbox(s) in the setting being incorrect (sometimes) was the real problem here.

This isn't something BBT does. The preferences UI are managed by the firefox infrastructure that zotero uses, and are a direct reflection of the current settings without further work from addons (or zotero itself in fact). It would cost me extra work to interrupt this direct reflection. So it is not likely that the preference value and the checkbox are out of sync, that would mean a (transient) bug in firefox itself. The cause is almost certainly something else.

But your key pattern is

```
[Auth:ascii:lower][>0][year][veryshorttitle:lower] | [Auth][year]
```

so if a title is present in the key, it will *always* have been transliterated, not sometimes, because `veryshorttitle` is the only part that introduces the title to the key, and `veryshorttitle` always transliterates; the "force to ascii" only concerns after all else has been generated, it doesn't turn off transliteration for functions like `veryshorttitle`.

This means that the scenario you described, where the title is only sometimes transliterated, must at the very least have been with another pattern set. Given the current state of things, I don't have enough information to do a diagnosis.

If you get it again, just directly send a log of the affected item, maybe that makes gives me enough information to get it reproducible. Right now there seems to be a discrepancy between the behavior that is described and the actual state

**Comment by esnahn** [comment]
> The preferences UI are managed by the firefox infrastructure

Ok then it couldn't be the bbt's problem. Thanks for the quick answer.
If you are fine with it, I can close this issue.

For regarding the key format:
`[Auth:ascii:lower][>0][year][veryshorttitle:lower] | [Auth][year]`
It was created after the problem I was experiencing was gone, after cycling the setting.
So I can say that that can't be the reason for it.

By the way, my final key is now this:
`[Auth:replace=\[^가-힣\],,regex:eq=0][auth:lower][year][veryshorttitle:lower] | [Auth][year]`
which that only transliterate non-korean names.

**Comment by esnahn** [comment]
I think I reproduced the problem; slight differently.
Support log ID: QMMHDKGG-refs-apse

The log will say that I didn't change the `skipWords`, but I did, as you can see in this screenshot.
And the documentation states that "the list of words can be seen and changed"... but it didn't in this case.
![2022-02-14 174101](https://user-images.githubusercontent.com/1122053/153829936-cbada0db-34bf-4d36-91f3-18c6c828a5f2.png)

**Comment by retorquere** [comment]
Super, thanks for this diagnosis! There were a few places where BBT was reading from `extensions.translators.better-bibtex.` rather than `extensions.zotero.translators.better-bibtex.`. 2067 will fix that.

**Comment by esnahn** [comment]
That's nice! Thanks for the quick fix!
