### ISSUE TITLE
Zotero 6 beta citation key field

### ISSUE THREAD

**Issue by bwiernik** [retorquere/zotero-better-bibtex#2064]
Log ID: HUDQAFXA-refs-euc

In the latest Zotero beta, the new Preprint item type has a Citation Key field. This field picks up and matches the BBT Citation key, but editing this field does not currently change the BBT Citation key, so it reverts immediately. Better behavior would be for edits to this field to be function as pinning the key.

**Comment by retorquere** [comment]
JFC I'd have hoped they would have ran this by me earlier. This is going to be a pain to work around.

**Comment by bwiernik** [comment]
All types will get it eventually. They haven't added it to other types because they need to turn off syncing on the old schema first.

**Comment by retorquere** [comment]
It will be a PITA to do this piecemeal. So yes, it makes sense to use the field for pinning the citekey, but because they have chosen to pick the key out of my DB and fill it in that field, that route is effectively blocked, because the test "is that field filled, then it is a pinned key" is now gone, because that field is *always* filled now.

The only sensible thing for me is to wait until all item types have this field, then do a one-time migration of my DB to that field, and then move my DB to a place where Zotero doesn't pick it up anymore, because I will still need my own DB  to shadow these keys. So from the looks of it, the current state is just the way things are going to be until all item types have this field. Once that is available, I can split the pinning method between beta and release, but it will mean that in beta, all keys are pinned keys.

Really would have hoped to get more notice on a thing like this.

**Comment by retorquere** [comment]
> they need to turn off syncing on the old schema first.

wait -- all users must have migrated to 6 before *any* of these itemtypes get this field?! Meaning that 6 would go non-beta with only preprint having this field? Ay caramba! Please tell me I'm wrong on this 😭 .

**Comment by retorquere** [comment]
I am wrong, fortunately. That field uses `getField` to retrieve the value, but since I've patched `getField` to fetch the key from my DB, it reverts immediately. I know this will look shitty in the interim, but I'm going to see if I can wait out all itemtypes getting this, and then make that the storage for the (now always pinned) citekey.

**Comment by bwiernik** [comment]
@dstillman Tagging you in here in case there might be a smooth way to integrate here

**Comment by bwiernik** [comment]
Maybe an ultimate solution would be to add a check box that is "pin" next to this new field. You might not need a shadow copy then

**Comment by retorquere** [comment]
I will still need a shadow DB, because I need to be able to retrieve the keys synchronously in a few places.
