### ISSUE TITLE
Req: acronyms for organisations in citekeys 

### ISSUE THREAD

**Issue by glocalglocal** [retorquere/zotero-better-bibtex#2081]
When the author is an organisation, BBT correctly produces citekeys like these: 
`britishbroadcastingcorporationBBCHandbook19751976`
`departmentfordigitalculturemediaandsportConsultationRenewalDigital2021` 

The names of organisations are supposed to appear in full in Zotero and in references, but it would be more practical if citekeys looked like these:
`bbcBBCHandbook19751976`
`dcmsConsultationRenewalDigital2021`

I suppose one way to achieve that is adding a user-defined translation table, (re)generating citekeys, and possibly pinning the affected citekeys. The translation table would replace, say, all instances of `departmentfordigitalculturemediaandsport` with `dcms`.

**Comment by retorquere** [comment]
When you add a support log the issue should automatically reopen.

**Comment by glocalglocal** [comment]
I am not reporting a bug and there are no 'problematic reference(s)'. As I explained, BBT behaves as intended. I am just suggesting an idea for consideration.

**Comment by retorquere** [comment]
From the bot message:

> Support logs are useful for both analysis and for enhancement requests; in the case of export enhancements, @retorquere needs the copy of the references you have in mind.

**Comment by glocalglocal** [comment]
Zotero 6.0.4 generates this error while sending the log: 

![image](https://user-images.githubusercontent.com/16408198/160312258-b70ca088-101c-4138-a9c9-8c7006b994e0.png)

I am attaching an example reference as Zotero exported it if you want to see what I mean. It doesn't really add much to what I described earlier. I am guessing that many researchers use many sources from a small number of organisations. A small translation table in BBT would take minutes to populate and it would fix many of these citekeys. 

In this case `Department for Culture, Media and Sport` would be replaced with `dcms` on first run or when BBT was asked to refresh. 

[Exported Items.json.txt](https://github.com/retorquere/zotero-better-bibtex/files/8359048/Exported.Items.json.txt)

**Comment by retorquere** [comment]
Annoying. There's a button on the bottom-left that says "save copy of log", that will get you a zip that you can attach here; that will give me the same information. Can you try sending a log using the regular workflow, reproduce the error, and then again start up the log sender but save-and-attach here? That should put the problem you are experiencing in the logfile.

What platform are you on? The logs normally also gives me platform information and the BBT settings you have.

**Comment by glocalglocal** [comment]
Frankly, I don't see how any of this is necessary. All I am saying is that BBT works as intended but you and others might like a simple idea. If you don't have a reference with an author as in my examples, or don't wish to create one in 2-3 seconds, you can import the reference I sent you. Obviously, the default citation key format `[auth:lower][shorttitle3_3][year]` will generate the ugly key on any platform and in any working version of Zotero and BBT, because they work as intended. I don't see how the setup info would help if you can reproduce the above within seconds and then work from there. I may have to replace and pin selected citekeys manually after all. Thanks for the great extension.

**Comment by retorquere** [comment]
Would a CSV mapping work for you? It would have to live in a well-known place, build 2227 uses the profile directory. You can use it with `:acronyms` or `:acronyms=<filename>`; the first just assumes that `filename` is `acronyms`, so it is equivalent to `acronyms=acronyms`, and would expect a file `Zotero/better-bibtex/acronyms.csv` to exist. This file should have two columns, the first being the full name (case doesn't matter here), the second being the acronym (this will be used as-is).

That aside, and to be somewhat Frank in return, I don't see why you are fighting me over something that, barring the error you ran into, which I'd very much like to fix, was a simple request to click a few buttons, and I honestly don't know what mindset makes it that you can't just trust me when I say repeatedly that it adds value to me to have it. You have already spent a lot more time arguing about it than supplying it, so it can't be an objection on efficiency grounds, which, as far as I can tell, leaves the explanation that you feel you know better than me what I need to work efficiently. If that's the case, I don't know what to tell you.

I am adding new code for this feature request, which means I add test cases for these new features, and the support log gives me that based on real-world data, and especially for feature requests I want to build the exact sample the user has in mind so that when I have a solution, you can say either "that is what I had in mind", or not, so discussion becomes more targeted. Also, it removes the chance of a typo, or encoding issues, because the path from log ID to testcase is automated. In case of differences, it also gives me your BBT settings, which might explain differences. My process means that even test builds are fully production-ready as they will have passed my existing test suite plus a test for whatever change I made.

It feels utterly bizarre that I should have to justify this. Trust me, you are very much not the first to demand explanation for this, and to fight it even after I provide it, and this kind of interaction is incredibly depressing. I enjoy helping people use BBT, and al I ask is a few button clicks to make my life just a tad easier. I have no idea why people react so indignant to this. If you were curious rather than confrontational, a few clicks to send it and a question "what do you use this for?" would have cost the same amount of effort, would have gotten the same result, but would have been a way more pleasant experience for the both of us.

Yet here I find another indignant user, and me keeping my responses much less frank than I feel being right now, because I prefer not to let you walk away from this interaction without a solution.

**Comment by retorquere** [comment]
> or don't wish to create one in 2-3 seconds, you can import the reference I sent you.

You have spent way more than 2-3 seconds on this and could by your own reasoning have done this with next to no input.

Usually interactions with BBT users are pleasant, and I enjoy making the lives of BBT users easier. That enjoyment is very much not returned here. You seem out to argue with me, I've had a fucking rough week, and I don't have the energy to deal with this right now. Feel free to open a new issue if you want to proceed with the CSV mapping.
