### ISSUE TITLE
Citaiton Key column disappears

### ISSUE THREAD

**Issue by lrperlmu** [retorquere/zotero-better-bibtex#2136]
## Summary

On MacOS, Citation Key column disappears under certain conditions and I need to relaunch zotero to make it reappear.

## System and version information
MacOS 10.14.6
Zotero 6.0.6

## Reproduction Steps
1. Launch Zotero
    * Upon launching, the citation key column appears between "title" and "creator"
    * I can toggle this column on and off by right clicking the name of a column and selecting or deselecting "Citation Key" in the context menu
2. Click the red X in the upper left hand corner of the zotero window to close the window without terminating the application
3. Click the Zotero dock icon to open a zotero window
    * Upon opening a new window, the citation key column does not appear
    * (This is the step where I generated a support log. Support log ID below.)
    * When I right click the name of a column, "Citation Key" does not appear in the context menu as a column that can be added to the view
4. Right click the Zotero dock icon and select "Quit". This closes the Zotero window and terminates the application.
5. Launch Zotero
    * "Citation Key" column is back in business

## Support Log ID: 
AE2ERRYJ-refs-euc

**Comment by lrperlmu** [comment]
possibly related to #2088, though I'm not sure if it's exactly the same issue.

**Comment by retorquere** [comment]
Oh that could very well be related.

This problem unfortunately requires a substantial re-structuring of BBT. It's work I'm planning for the coming months but I can't give an ETA; until I have that restructuring done the cure is, unfortunately, "don't do that". BBT starts up when the main window displays, and on MacOS, that can happen more than once if you red-cross and re-open Zotero. The startup process of BBT isn't robust against that.

**Comment by qqobb** [comment]
> Click the red X in the upper left hand corner of the zotero window to close the window without terminating the application

I don't know anything about the issue, but it sounds like this could be related to https://github.com/jlegewie/zotfile/pull/595.

**Comment by qqobb** [comment]
There's also https://github.com/zotero/zotero/issues/1952.

**Comment by retorquere** [comment]
Yeah, it's related to that. I employ the same mitigation strategy, but it does not cover all cases.

**Comment by retorquere** [comment]
I'm going to change BBT to restartless start. This was necessary anyhow, and it'll likely solve this problem and a few other open issues, but it'll take (quite) a bit of time to get it done.

**Comment by dstillman** [comment]
Following up on https://groups.google.com/g/zotero-dev/c/jYbUlGEMJTc/m/Dj6Zr8lzAgAJ, there may not be a great solution to this at the moment, and XBL bindings are going away in the Fx102 branch anyway.

What if we just add Citation Key to all item types? What effect will that have on you? The Citation Key field in Preprint is just a regular field, but is there bare-minimum special functionality that a Citation Key field would need, from your perspective?

**Comment by lrperlmu** [comment]
Thanks for asking! To clarify, are you proposing that all zotero items could have a citation key field, even without using the BBT extension? Would launching BBT then make each item have 2 citation key fields that could potentially have different values? That would be kind of confusing especially when it comes to which one is used when exporting.

Citation key end user features that are important to me include:
1. Auto generate a citation key for each newly added item using my JabRef-ish pattern specified in settings.
2. Use this citation key when exporting to .bib file

**Comment by dstillman** [comment]
Sorry, my question was for @retorquere. Zotero was always going to get a Citation Key field field for all items — I'm just trying to coordinate with @retorquere to avoid problems for BBT users.

**Comment by retorquere** [comment]
> What if we just add Citation Key to all item types? What effect will that have on you? The Citation Key field in Preprint is just a regular field, but is there bare-minimum special functionality that a Citation Key field would need, from your perspective?

The main issue will be if/when to generate these keys. A lot of functionality in BBT assumes regular items always have a citekey. With the citekey in a normal (editable) item field, key behavior becomes equivalent to all items having pinned keys, and that means functionality changes for BBT users.

It seems to me the most understandable behavior would be to (only) generate keys when the field is empty. This does mean BBT would lose the dynamic keys and delayed-pinned keys, but mimicking these two behaviors with an item field would mean there would need to be something like a separate checkbox to indicate that the key is fixed, and that does not feel like a good UI concept to me.

With key behavior being like pinned keys it'd mean that if the keys are to follow the content of the item, it'd be a manual action by the user to adjust the keys to the item content; maybe a refresh button could be added next to the citekey field, and a right-click action on the item list to refresh keys. I'm sure some will be upset by this, but this seems like a decent compromise to get a real citekey field.

I'd propose that either Zotero's key-generating function be monkey-patchable so that I can replace it with the BBT key generator, or alternatively that Zotero just does not generate keys and leaves that to BBT. In the latter case, it'd be nice if it weren't too difficult for me to add the refresh button next to the citekey in the item pane. Other than that, no special functionality I can think of.

**Comment by Dellu** [comment]
It might be useful to adopt the idea of Core Plugin and Community Plugins from Obsidian. 
- Ship Better bibtex as a core plugin with every release of Zotero
- Make Zotero generate no cite key of its own: leave the task for Better Bibtex.

**Comment by retorquere** [comment]
In that scenario, why have a core plugin rather than just build it into Zotero? If not built in, what would it mean to be a core plug in? Just that I'm held to their release schedule? 

Once zotero adds its own citation key field, BBT will still generate its contents while installed.

**Comment by Dellu** [comment]
I  think generally, Zotero needs some means of organizing its plugins. They are cluttered everywhere and many users struggled to find them. 

- The idea of Core plugin is: just regular plugin; but shipped with the main application. Every modification and release is still made by the plugin developer (I guess). Community plugins are not shipped with the main application. The user has to manually install them.  

> Once zotero adds its own citation key field, BBT will still generate its contents while installed.
This is also good so far as it works for you.

**Comment by retorquere** [comment]
They can ship BBT with Zotero, you'd have to ask them.

**Comment by retorquere** [comment]
But this doesn't have to do with the issue under discussion here.

**Comment by retorquere** [comment]
The original issue has been solved a few versions back.
