### ISSUE TITLE
Also consider upper case prefixes as name prefixes

### ISSUE THREAD

**Issue by morxa** [retorquere/zotero-better-bibtex#2160]
When using the BibLaTeX exporter with extended name format, we already get bibtex entries like the following for names with a lower-case prefix:
```

@inproceedings{vangoghVanLowerCase2022,
  title = {'van' {{Lower Case}}},
  author = {family=Gogh, given=Vincent, prefix=van, useprefix=true},
  date = {2022}
}
```

However, if we also make the prefix upper case, the prefix is ignored:
```
@inproceedings{vangoghVanUpperCase2022,
  title = {'{{Van}}' {{Upper Case}}},
  author = {Van Gogh, Vincent},
  date = {2022}
}
```

This is problematic because at least some languages use upper case prefixes, e.g., Italian names seem to always use upper case prefixes.

Would it be possible to also consider upper case prefixes as prefixes and export them accordingly?

Support log ID: YWDV2QVV-refs-euc

**Comment by retorquere** [comment]
Sorry for the long silence -- this is something that will have to be addressed in [citeproc](https://github.com/Juris-M/citeproc-js) as I use their nameparser, embedded in Zotero.

**Comment by retorquere** [comment]
I will prepare a PR for the repo, nothing you need to do right now.

**Comment by njbart** [comment]
FWIW, Zotero and citeproc-js assume that there are no genuine upper-case particles. Every supposed upper-case particle that has been examined so far turned out to be part of a fixed multi-part family name. The litmus test is to check whether the family name minus the supposed particle is ever used for display and/or sorting, i.e., "Gogh" or "Robbia" being a form that might be displayed on its own, or the form "van Gogh" or "Della Robbia" being (at least optionally) sorted under "Gogh" or "Robbia". With upper-case elements this invariably does not seem to be the case. See extensive discussions [here (list of threads)](https://forums.zotero.org/discussion/comment/234560/#Comment_234560), in particular [the "Italian" thread](https://forums.zotero.org/discussion/51783/2/parsing-problem-on-italian-names/).

**Comment by morxa** [comment]
@njbart Thanks for pointing this out, I guess that's also my situation. So I'm not sure if my request still makes sense.

**Comment by retorquere** [comment]
Cool, so I think we can consider this closed?

**Comment by morxa** [comment]
Yes! If I realize that this is an issue after all, I'll come back.
