### ISSUE TITLE
Failed to automatically update the exported library

### ISSUE THREAD

**Issue by mental2008** [retorquere/zotero-better-bibtex#2210]
When importing or modifying an item, the plugin fails to automatically update my exported library. The progress bar in the upper right corner of Zotero looks like in a stuck state. However, I can update the library manually by clicking the "Export now" button. Any thoughts on it?

For your information, my support log ID is GYU28WMU-refs-apse.

Thanks for the help in advance!

**Comment by retorquere** [comment]
Can you get me a new log from 2948?

**Comment by retorquere** [comment]
How long did you wait for it to update? You have the auto-export delay set to close to half an hour.

**Comment by mental2008** [comment]
It seems to be stuck in progress. The mode I selected for automatic export is "on charge". So I think it should update the library as soon as the item changes. An strange thing is that I can't reproduce the same issue on another computer. I'm wondering if there is any configuration difference.

**Comment by retorquere** [comment]
I can indeed see you have set it to export "on change", but that means "when a change occurs, start the delay timer, then export". This is meant to prevent a cascade of exports if eg you are syncing items which would cause a rapid fire of exports. That delay is set to 5 seconds by default, so that means 5 seconds after the last item changed, auto-export starts. But you have the delay set to 1687, which means BBT will wait close to 30 minutes after the last change before exporting.

What change did you make to trigger the export? I see no indication an item has changed in `XHLA9EET-refs-apse`.

**Comment by mental2008** [comment]
I triggered the export by filling in the URL of the item. I just retried the latest test package. For your inference, the support log ID is GUFJTUX6-refs-euc. I'm confused as to why the delay changes in my environment, as it is not configurable.
