### ISSUE TITLE
Parts of citation key capitalized when they shouldn't be

### ISSUE THREAD

**Issue by JessRiedel** [retorquere/zotero-better-bibtex#2233]
My citation key format is 
   `auth.lower + year + veryshorttitle(1,0)`

Expected behavior: For a paper written in 2022 by John Smith called "Study of C. Elegans", the citation key should look like `smith2022study` .  In particular, the first letter of the word from the title should be uncapitalized.

Actual behavior: The first letter of the word from the title is capitalized, i.e., `smith2022Study`.

-----

Details:

The "`(1,0)`" parameters above are not necessary because they are the default, but I include them to emphasize that I would like the citation key to be completely uncapitalized.  

Unfortunately, rather than *un*-capitalizing the first word of the title when I specify (with the parameters `(1,0)`) that the title word should not be capitalized, Better BibTex just uses the first word as stored in the Zotero item, capitalized or not.  So I get `smith2022Study` if the item is titled "Study of C. Elegans", but if I change the title to "study of C. Elegans" I get `smith2022study`. Obviously this is not a solution.

**Comment by retorquere** [comment]
Support log as per instruction 1 above please.

**Comment by JessRiedel** [comment]
This doesn't have anything to do with a specific reference.  If you don't want to look at it without a support log, it's up to you.

**Comment by retorquere** [comment]
Please reread the bot comment and send a support log.

**Comment by retorquere** [comment]
It has everything to do with a specific reference. That specific reference is a sample of where you want the behavior to be different than it currently is, and that sample prevents us from talking in abstracta but we can be sure we're looking at the same item, with the same settings. I have absolutely no idea why people insist in fighting me on this. We're talking about  5 mouseclicks (less if you hover) and a copy-paste. It seems to be some kind of principled thing that people decide they know better than me how I can most efficiently deal with user requests.

But to make things easier for you, in the dummy data you supply, I don't see what the problem is. You supply 0 for number of words to actively capitalize, and BBT capitalized exactly that many. If you want the behavior to be different, we can talk about that after you supply a support log. Commenting on this issue, will automatically re-open it.
