### ISSUE TITLE
Newly installed BBT bulk assigns citekeys to items without citekey

### ISSUE THREAD

**Issue by rzach** [retorquere/zotero-better-bibtex#2290]
Upon a fresh Zotero install, after syncing my library and subsequently installing BetterBibTeX, BBT decided it would refresh all my citation keys to the BBT default (saying it found x thousand entries without a key, even though they all have keys). It did so without a dialog even though the "ask when bulk changing more than 10 keys" option was active (by default). I also was unable to halt the procedure, and the BBT prefs dialog said "waiting for BBT" to load while it completed the bulk update.

Debug log (after I changed the BBT citekey format setting): Q9CXN3T8-refs-apse

My guess is that something tells BBT that entries with cite keys that BBT has not seen before have none and so BBT refreshes them.  In any case it shouldn't do that without asking for permission first.

**Comment by retorquere** [comment]
That must be a bug then, and I'm exceptionally sorry that this happened to you -- are there backups of the BBT database in the zotero directory? There ought to be.

**Comment by retorquere** [comment]
I cannot reproduce your case yet, and I haven't yet found anything that would do this with better-bibtex.sqlite present.

I realize this will have been a very stressful "surprise" when it happened, might well still be, but this happening already stressful for me too without the "BBT decided to" phrasing. I assure you I have not put something in place to do this to you, and I am not flippant about data/code quality. While something obviously went wrong here, I test BBT as rigorously as I can.

**Comment by retorquere** [comment]
I've published a new version that will ask before it fills out what it thinks are missing keys. That won't help you of course -- if there is a backup of the Zotero DB, please make copies now so we can rollback safely. The only way I've been able to recreate the key regeneration is by corrupting the database, or removing it.

**Comment by retorquere** [comment]
What timezone are you in? It's pretty late here and I had meant to turn in for the night.

**Comment by rzach** [comment]
Not urgent!
________________________________

**Comment by retorquere** [comment]
Feels pretty urgent to me?

**Comment by qqobb** [comment]
@rzach: Only citation keys which are "pinned" and written to the Extra field are synced, see here: https://github.com/retorquere/zotero-better-bibtex/issues/1741#issuecomment-779055814.

Citation keys that are not pinned can't sync because they are stored in a separate database, `better-bibtex.sqlite`, that is unrelated to Zotero's database.

**Comment by retorquere** [comment]
Oh jeez I had missed that part - I thought you meant BBT decided to *replace* your keys. What qqobb says is exactly right. Once zotero gets around to a formal field for the citekey that problem goes away, but until that time pinning your keys is the only way to sync keys that is allowed by Zotero.

**Comment by retorquere** [comment]
You can have bbt auto-pin the key after modification/creation.

**Comment by qqobb** [comment]
@rzach: If you still have your old setup with the "correct" citekeys, pinning the keys on that setup should fix your issue. Going forward, you might want to use BBT's auto-pin option.

**Comment by retorquere** [comment]
That will indeed overwrite the newly generated keys with the pinned keys.

**Comment by rzach** [comment]
Hey all sorry I also didn't mean to be flippant, and also apologies for being unclear about what happened -- it only updated all unpinned cite keys since on the new install anything with dynamic keys on my other computers in fact didn't have keys on the new computer.  I didn't realize that Zotero itself doesn't sync bibtex keys, and that BBT doesn't sync dynamic keys.  And it wasn't a big deal because I could just refresh all the dynamic bibtex keys with my preferred key pattern after.  My suggestion was mainly that BBT shouldn't do that automatically on a new install without the user having the option to first set the preference. I understand that you fixed that, so this can probably be closed. Perhaps the documentation at https://retorque.re/zotero-better-bibtex/citing/ can mention that only pinned, but not dynamic, citation keys are synced by Zotero, so that there is no guarantee that dynamic citation keys are the same across different computers running Zotero?

Thanks, as always, for this important resource, and for addressing this issue so quickly!  Learned something new.

**Comment by retorquere** [comment]
I didn't fix it - I had a change that I now backed out that would ask, but if you said no, it would leave BBT in a non-working state. That seemed an acceptable tradeoff for the si I thought was at hand - existimg keys being overwritten. Now I know that it's just filling out empty keys, that's desirable, so that's back now. Pinning the keys, manually or auto, gets you the behavior you want.

**Comment by retorquere** [comment]
I didn't fix it - I had a change that I now backed out that would ask, but if you said no, it would leave BBT in a non-working state. That seemed an acceptable tradeoff for the si I thought was at hand - existing keys being overwritten. Now I know that it's just filling out empty keys, that's desirable, so that's back now. Pinning the keys, manually or auto, gets you the behavior you want.

Zotero does support citekey syncing - by pinning them in `extra`. They will show up on overleaf for example.
