### ISSUE TITLE
Escape underscores in dois

### ISSUE THREAD

**Issue by fusion809** [retorquere/zotero-better-bibtex#2326]
I just tried adding [this article](https://pubmed.ncbi.nlm.nih.gov/31143794/) to my reference list using Zotero and this extension's better BibTeX format and I received an error:

```
Missing $ inserted. ...PACrefDOI} \doi{10.4103/jehp.jehp_14_19}
```

and the error was eliminated by simply escaping the underscores in this DOI in the .bbl file used in compilation. It would be nice if Better BibTeX could do that automatically.

**Comment by fusion809** [comment]
Here is my debug log. [debuglog.zip](https://github.com/retorquere/zotero-better-bibtex/files/10101076/debuglog.zip)

**Comment by retorquere** [comment]
> Missing $ inserted. ...PACrefDOI} \doi{10.4103/jehp.jehp_14_19}

Do you have an MWE for this? The following compiles without error whether I "escape" the underscores or not, but inserts the backslashes in the rendered output if I have them (which is what one would expect for a verbatim field).

```
\documentclass{article}
\bibliographystyle{plainnat}
\usepackage{url}

\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@article{notaraParentalWeightStatus2019,
  title = {Parental Weight Status and Early Adolescence Body Weight in Association with Socioeconomic Factors},
  author = {Notara, Venetia and Magriplis, Emmanuella and Prapas, Christos and Antonogeorgos, George and {Rojas-Gil}, Andrea Paola and Kornilaki, Ekaterina N. and Lagiou, Areti and Panagiotakos, Demosthenes B.},
  year = {2019},
  journal = {Journal of Education and Health Promotion},
  volume = {8},
  pages = {77},
  issn = {2277-9531},
  doi = {10.4103/jehp.jehp\_14\_19},
  langid = {english},
  pmcid = {PMC6512222},
  pmid = {31143794},
  keywords = {Children weight status,health promotion,obesity risk factors,parental weight status,socioeconomic factors}
}

\end{filecontents}

\begin{document}
%\nocite{*}
\cite{notaraParentalWeightStatus2019}
\bibliography{\jobname.bib}
\end{document}
```

> Have you considered incorporating [bibtex-tidy](https://github.com/FlamingTempura/bibtex-tidy) into this extension?

No, I do not want to run my output through a tool like this, since BBT should just not output faulty bib(la)tex. I do not want to mask problems by post-processing the results, and many tools are naive about bibtex.

> It automatically escapes problem characters

and in doing so, it creates a problem, because AFAICT `doi` is a verbatim field, and my MWE shows that for me. `bibtex-tidy` doesn't seem to know about verbatim fields, which would make it a dangerous tool to use on a bibliography.

> and would fix that issue at least. May also reduce how much this extension has to do by itself.

We must first establish there is an issue at all. I cannot replicate the problem, as far as I know `doi` is a verbatim field, and should not escape characters this way. @njbart?

> Here is my debug log.

First, thank you for including a debug log, which makes my work so much easier. If you step through the wizard though, you will get a debug log ID in red. That already sends the log to me, and my tools are build around knowing the debug log ID. I can retrieve it from the zip, but it's much easier for me to just have the ID.

**Comment by fusion809** [comment]
Here is my MWE:

```latex
\documentclass[12pt,a4paper]{article}
\usepackage[natbibapa]{apacite}
\bibliographystyle{apacite}
\usepackage[colorlinks,citecolor=blue,urlcolor=blue, linkcolor=blue, bookmarks=false,hypertexnames=true]{hyperref}
\usepackage{doi} % hyperlink URLs
\renewcommand{\doi}[1]{\href{https://doi.org/#1}{#1}}
\date{}

\begin{document}
	\cite{notaraParentalWeightStatus2019}
	\bibliography{ref}
\addcontentsline{toc}{section}{References}
\end{document}
```

I've identified the cause of the error, it's partly due to my custom doi command. I've wanted my references to look like this:

![Notara reference](https://user-images.githubusercontent.com/4717341/204449135-490a1ac2-272d-4fd2-8691-e4945cddf987.png)

with doi: followed by the hyperlinked doi and it seems this is creating a problem, as this is more consistent with the APA referencing guide my uni uses.

**Comment by retorquere** [comment]
you can change the escaping rules using a postscript:

```
if (Translator.BetterTeX && tex.has.doi) {
  tex.add({ name: 'doi', value: tex.has.doi.value, enc: 'latex' })
}
```

but I'd recommend getting in touch with the style author to see if what you need can be added.

**Comment by fusion809** [comment]
Well it's not really an issue with this extension, so I'll close. I've been able to find a solution anyway, it involves adding \detokenize to the hyperlinked text for the doi command.
