### ISSUE TITLE
Syncing citations keys between computers

### ISSUE THREAD

**Issue by HumpyBlumpy** [retorquere/zotero-better-bibtex#2332]
Hello,
I am using zotero on two different computers, using the built-in sync to sync everything except the pdf files, which I sync separately using SyncThing.
My problem is that citations keys are sometimes different on both machines.
I use BetterBibTeX to export my library (and keep it up to date -- this is only set up on one machine). When working on the other machine, the citation keys often dont match the saved .bib file. Usually differing by a single character "a" or "b", etc at the end.
Is there a way to sync the citation keys as well? 

Thanks

**Comment by HumpyBlumpy** [comment]
debug id : GF8Z5UHQ-refs-euc

**Comment by mjthoraval** [comment]
Are you using pinned citation keys?
https://retorque.re/zotero-better-bibtex/citing/#set-your-own-fixed-citation-keys

**Comment by HumpyBlumpy** [comment]
No I dont think so, my extra field is mostly blank. Are you suggesting that pinning will enable syncing?
If so, how can I bulk pin my entire library? and is it possible to pin keys by default, or will I have to repin every time I add a new paper?

**Comment by retorquere** [comment]
Yes, those will sync. Bulk pin your keys by selecting all items, right click, bbt, pin citekeys.

There is a hidden setting to auto pin new keys, I'll add a visible pref for it in a few hours.

**Comment by retorquere** [comment]
Build 3495 makes auto-pinning available in the UI. If you set it to a non-zero value, the key will be automatically be pinned for new/changed items after that many seconds.

**Comment by HumpyBlumpy** [comment]
Thanks, I understand that it is not yet available in the main release?

What are possible disadvantages of having the keys pinned that I should keep in mind?

**Comment by ryofurue** [comment]
I was wondering whether it's possible to share everything, data and settings and all, via Dropbox.  I customize the citation-key formatter and had to do the same customization for all three machines of mine. I'll be soon buying a new machine and since I don't migrate any settings from other machines . . .  (I pay Zotero to share my database, which works well but settings aren't shared, it seems to me.)

**Comment by retorquere** [comment]
Settings would be technically possible, through load from disk at start of zotero. It'd mean the prefs ui would be mostly useless, as any change would get undone at next start, but it's possible.

When it comes to the rest of the data, which would be the cache, the auto exports, and the citekey database, that is not possible. They are all keyed on things that differ per installation, so these bbt databases are bound to the zotero.sqlite they build on, and they wouldn't work when copied over to a system with a different zotero.sqlite, even if from a user standpoint these two zotero.sqlite files would appear to be the same.

There's also no way to monitor for changes to the db as synced through Dropbox. Dropbox just isn't great for database files (which is why zotero recommends very much not syncing zotero.sqlite through Dropbox, as it is a question of when, not whether, that will corrupt your database).

**Comment by ryofurue** [comment]
> Settings would be technically possible, through load from disk at start of zotero.

That's what I'm after.

>  It'd mean the prefs ui would be mostly useless, as any change would get undone at next start, but it's possible.

Currently, I'm most interested in the format specifier (I don't know what's the best name for this feature) of BBT citation keys.  I don't use the default automatic keys. I customize how BBT generates the key from the bibliographic information of the paper.  So, I want to share this format specifier between my machines.

But, I don't understand your comment on UI preferences.  I customize various items in Zotero's "Preferences".  These changes must be written in some folder on my computer.  What happens if this folder is shared via Dropbox by my computers?  (That's how I share various preferences of some apps such as emacs, command-line shell, and an IME.)  I do understand you explanation about sqlite files.  Does that mean that the "Preferences" are stored as sqlite files?

(It's interesting that sqlite files don't work even if they are bit-by-bit copies. . . . I'll read something to understand this. I'm just curious.)

**Comment by retorquere** [comment]
> Currently, I'm most interested in the format specifier (I don't know what's the best name for this feature) of BBT citation keys.  I don't use the default automatic keys. I customize how BBT generates the key from the bibliographic information of the paper.  So, I want to share this format specifier between my machines. 

That's doable, although I'd prefer to stick the file in the BBT folder in the profile, and I'm not sure you can do partial sync of directories using Dropbox. 

> But, I don't understand your comment on UI preferences.  I customize various items in Zotero's "Preferences".  These changes must be written in some folder on my computer.  What happens if this folder is shared via Dropbox by my computers? 

I think that could work, they're either in prefs.js or user.js. That's a better option I think than what I was considering. You'd have to ask the zotero crew about the specifics. 

>  I do understand you explanation about sqlite files.  Does that mean that the "Preferences" are stored as sqlite files?

No, they are javascript-ish text files. 

> (It's interesting that sqlite files don't work even if they are bit-by-bit copies. . . . I'll read something to understand this. I'm just curious.)

They work if you can guarantee that only one instance of zotero wil ever be writing to it at any given time, and that you only start zotero on a pc where you guarantee that the sync will be complete. Otherwise you may have the database open and actively being written to while Dropbox simultaneously tries to update the file through sync. The internal structure must be preserved at all times and must be in line with the data zotero has cached from the db. It's easy to violate these expectations with Dropbox active, and that will at some point corrupt your db.
