### ISSUE TITLE
issue/number/article-number

### ISSUE THREAD

**Issue by retorquere** [retorquere/zotero-better-bibtex#2551]
### Debug log ID

FIL4RF9L-refs-euc

### What happened?

When importing

```bibtex
@Article{rs12132114,
AUTHOR = {Kolbe, Christine and Thies, Boris and Turini, Nazli and Liu, Zhiyu and Bendix, Jörg},
TITLE = {Precipitation Retrieval over the Tibetan Plateau from the Geostationary Orbit—Part 2: Precipitation Rates with Elektro-L2 and Insat-3D},
JOURNAL = {Remote Sensing},
VOLUME = {12},
YEAR = {2020},
NUMBER = {13},
ARTICLE-NUMBER = {2114},
URL = {https://www.mdpi.com/2072-4292/12/13/2114},
ISSN = {2072-4292},
ABSTRACT = {We present the new Precipitation REtrieval covering the TIbetan Plateau (PRETIP) as a feasibility study using the two geostationary (GEO) satellites Elektro-L2 and Insat-3D with reference to the GPM (Global Precipitation Measurement Mission) IMERG (Integrated Multi-satellitE Retrievals for GPM) product. The present study deals with the assignment of the rainfall rate. For precipitation rate assignment, the best-quality precipitation estimates from the gauge calibrated microwave (MW) within the IMERG product were combined with the GEO data by Random Forest (RF) regression. PRETIP was validated with independent MW precipitation information not considered for model training and revealed a good performance on 30 min and 11 km spatio-temporal resolution with a correlation coefficient of R = 0.59 and outperforms the validation of the independent MW precipitation with IMERG&rsquo;s IR only product (R = 0.18). A comparison of PRETIP precipitation rates in 4 km resolution with daily rain gauge measurements from the Chinese Ministry of Water Resources revealed a correlation of R = 0.49. No differences in the performance of PRETIP for various elevation ranges or between the rainy (July, August) and the dry (May, September) season could be found.},
DOI = {10.3390/rs12132114}
}
```

I'm not sure what `article-number` means, @njbart , any thoughts? I'm also looking at the biblatex manual which says

> **issue field (literal)**
> The issue of a journal. This field is intended for journals whose individual issues are identified by a designation such as ‘Spring’ or ‘Summer’ rather than the month or a number.
> ...
> **number field (literal)**
> The number of a journal or the volume/number of a book in a series. 

does that mean `issue` and `number` mean roughly the same, and I should not expect both to exist within one entry? The rules in `biber-tool.conf` seem to allow both in the same entry.

**Comment by njbart** [comment]
In the example, `article-number` seems to be used for what CMOS, 17e, 14.174, describes as follows:

> To facilitate online publication schedules, some journals have adopted a continuous publishing model in which each article is assigned a unique ID and is considered final the moment it is published online; any subsequent print version is reproduced without any changes. Articles that include a PDF version are all paginated starting at 1 and can be cited in the notes accordingly. In a note, cited page numbers precede the article ID (e0124310 in the example below). In a bibliography, do not include the page range for an article published in this way.

>> 2. Priyamvada Paudyal et al., “Obtaining Self-Samples to Diagnose Curable Sexually Transmitted Infections: A Systematic Review of Patients’ Experiences,” *PLoS ONE* 10, no. 4 (2015): 2-3, e0124310. https://doi.org/10.1371/journal.pone.0124310.

>> Paudyal, Priyamvada, Carrie Llewellyn, Jason Lau, Mohammad Mahmud, and Helen Smith. “Obtaining Self-Samples to Diagnose Curable Sexually Transmitted Infections: A Systematic Review of Patients’ Experiences,” *PLoS ONE* 10, no. 4 (2015): e0124310. https://doi.org/10.1371/journal.pone.0124310.

Note, however, that `article-number` is *not* a field supported by the biblatex default data model (see biblatex manual). It does not seem to be recognised by biblatex-apa or biblatex-chicago, either.

The appropriate field, according to the biblatex standard data model, is `eid` (see also https://tex.stackexchange.com/questions/194355/articleno-in-biblatex).

`eid` is also explicitly supported by biblatex-chicago (see its manual).

As to the number-issue distinction, see https://github.com/plk/biblatex/issues/726#issuecomment-372057382 :-).

Finally, when it comes to Zotero, things become less clear. Recommendations I’ve seen include putting article ids into the `pages` field, or using the cheater syntax, inserting `number=FooBar` into the `Extra` field (for both, see https://forums.zotero.org/discussion/comment/437419).

I’m not a big fan of using the Zotero pages field in this way (it does work for CMOS, but only because CMOS does not want the page range to be included in he bibliography anyway), so upon importing, I guess I’d rather go for mapping biblatex `eid` to `number=FooBar` inside the `Extra` field on the Zotero side.

**Comment by retorquere** [comment]
Unless the entry has a `number` field then.
