### ISSUE TITLE
[Bug]: Capitalization of `Package.jl` in Zotero title

### ISSUE THREAD

**Issue by hexaeder** [retorquere/zotero-better-bibtex#2562]
### Debug log ID

GZSDI9US-refs-euc

### What happened?

Thanks for creating that nice package; it really helps me a lot :) However, I found a problem with the `apply title-casing to titles` option in some cases: Titles like

`ControlSystems.jl: A Control Toolbox in Julia`

will be exported as

`{{ControlSystems}}.Jl: {{A Control Toolbox}} in {{Julia}}`

with wrongly capitalized `.Jl`. Apparently, it treats the `.` as a sentence-end marker even without whitespace after it.

**Comment by retorquere** [comment]
I could shift the bracing, but I'm using Zotero's title-caser under the hood, and that transforms

> ControlSystems.jl: A Control Toolbox in Julia

into

> ControlSystems.Jl: A Control Toolbox in Julia

so shifting the bracing doesn't solve your problem (this will also be the case for Zotero-generated bibliographies for a title-cased style), but if that is fixed in Zotero, BBT will automatically follow. In the mean time, the Zotero-supported way to get the output you want is to change the title into

> `<span class="nocase">ControlSystems.jl</span>: A Control Toolbox in Julia`

**Comment by retorquere** [comment]
does this do what you need? For a fix of the title-caser you will have to report it on the Zotero forums. I just inherit its behavior.

**Comment by hexaeder** [comment]
Sorry I was on vacation. Great tip! The `<span class="nocase">` in the title is all I need for know.  If i find time I'll report it in the Zotero forums, still think the default behavior is rather agressive.

Thanks for pointing me in the right direction and thanks for maintaining better-bibtex! :)
