### ISSUE TITLE
[Bug/Feature]: Stopped updating / exporting changes after recent update

### ISSUE THREAD

**Issue by kenanmike** [retorquere/zotero-better-bibtex#2618]
### Debug log ID

EGEBEXBS-euc/6.7.107-6

### What happened?

I added new bibliographical items to my Zotero expecting it to update my Bibtex file but after a recent update to the add-on it's not automatically updating or exporting anymore. I've updated Zotero & the add-on to the latest versions but still nothing. I actually can't see the features I used to be able to see on the Better Bibtex preferences window, most importantly the automatic export files I had set up along with their settings. Since the update, that window doesn't show anything:

![image](https://github.com/retorquere/zotero-better-bibtex/assets/85374001/3a1d9316-8b0e-4c49-a198-602d193c187d)
 Can you help?
 
 Thank you!

**Comment by retorquere** [comment]
Something must have gone wrong with the debug log submission -- I can't find `EGEBEXBS-euc/6.7.107-6`. Can you try again?

**Comment by kenanmike** [comment]
No worries I’ve just deleted the automatic export and started a new one and seems to be working fine again now

Best wishes,

Michael

On 12 Aug 2023, at 01:37, Emiliano Heyns ***@***.***> wrote:

﻿

Something must have gone wrong with the debug log submission -- I can't find EGEBEXBS-euc/6.7.107-6. Can you try again?

**Comment by daaaaaaaaaniel** [comment]
I'm having a similar issue. After a recent update (still running Zotero 6, latest version), auto-export and manual export both fail. When I click "Export now" to manually initiate an export from the Automatic Export tab, it displays an error:" ✅ Error: no citation key for 23771". Sure enough, all the new items that I've added to my Zotero library since the latest update do not have a citation key assigned to them. If I pin a citation key manually, I can coax BBT to generate a successful export. It's not ideal because I have to manually set the citation key for every new item. 

I tried to submit a bug report, but the button to send the debut report is not responding. Nothing happens when I click it. I even tried restarting with Loggining Enabled, and the debut report button was still "frozen." Same result when I restart without logging enabled. I cannot submit a debug report because the button freezes.

**Comment by retorquere** [comment]
There's an option in the help menu to send a debug log to file.io.

**Comment by daaaaaaaaaniel** [comment]
Log submitted through the Help menu! `478V2T8A-euc/6.7.113-6`

**Comment by retorquere** [comment]
@daaaaaaaaaniel can you try build 4941?

**Comment by daaaaaaaaaniel** [comment]
Fixes the issue, TY!!
