### ISSUE TITLE
Export unicode as plain-text latex: symbol ç

### ISSUE THREAD

**Issue by ellon-b** [retorquere/zotero-better-bibtex#2693]
### Debug log ID

-

### What happened?

If it is possible I'd like that the symbol ç is converted to {\c c} and Ç to {\c C}. Today better bibtex uses \c{c} for ç but this form leads to errors when its used in a style with automatic capitalization of words. Thank you very much.

**Comment by retorquere** [comment]
A debug log gives me a testcase to prevent regressions. It's absolutely a minute effort on your part and I'm at my wits end on how to politely ask for debug logs. Add a debug log ID, one with -refs- in the ID. You also haven't said whether you experience this with bibtex or biblatex. 

@njbart, opinions on the described difference?

**Comment by ellon-b** [comment]
Sorry, I couldn't get a debug log by method 1. By method 2 the debug log is GXP27WTS-euc/6.7.132-6. The issue happens with bibtex. I am adding an example. Thank you!
[MWE Symbol Export Better Bibtex.zip](https://github.com/retorquere/zotero-better-bibtex/files/13182283/MWE.Symbol.Export.Better.Bibtex.zip)

**Comment by ellon-b** [comment]
Hello. Thank you for your reply! I saw that now the author field translates ç to {\c c}, that's fine! However I need this behavior also in the **organization** field, actually this is the specific example I sent, since sometimes I need the organization to play the role of author in the bib style I have to use. Given that, I wonder if it is not possible to translate to ç to {\c c} in all the fields.

**Comment by retorquere** [comment]
This is exactly why I need a debug log (as per point 1).

**Comment by retorquere** [comment]
I'd still prefer to hear from @njbart -- I implemented a different translation for creators specifically for #1189, I don't know what the potential downsides are to switching to that generally, other than that it will lead to more verbose output (see the cleanup explanation in #1189).

**Comment by ellon-b** [comment]
Here is the ID from method 1: 4J8938IG-refs-euc/6.7.132.2693.5287-6
I read the issue you referenced and it seems that the recommend approach is to use {\c c} for ç, or for any other special symbol. Regarding verbose output, from my "user perspective", I don't think it is much verbose. Actually what I want using Better BibTex is correct code for the reference generation in my document. Specially because I manage my references in Zotero. In any case, my personal need for now would be this fixed in fields: authors, editor, organization... That is, anything that can assume a author role. Thank you once again!

**Comment by retorquere** [comment]
I get that, but "correct" is not a simple thing when it comes to bibtex, as not a whole lot is documented, and a lot of stuff is style-dependent. I don't mind making this change, but Nick knows a ton of edge cases and bibtex history that I have no idea about.

**Comment by retorquere** [comment]
I would still appreciate that debug log. If I'm making any changes, I want that test case to prevent regressions. I don't always remember why I have made certain changes in the past, and these test cases are the memory tying the change to the issue, and will warn me if I'm making changes further down the line that conflict with this.

**Comment by ellon-b** [comment]
In the last message I sent: 4J8938IG-refs-euc/6.7.132.2693.5287-6. Is this OK? It was done by right click in the reference.

**Comment by retorquere** [comment]
Sorry, I missed that. That is indeed what I meant. I'll build a branch that does the thing you want to see how much else is affected.

**Comment by njbart** [comment]
I would like to emphasize again that I do not actively use bibtex and have not tested anything myself at the moment.

That being said, the relevant documentation (Patashnik, 1988, BIBTEXing) has this:

![pat](https://github.com/retorquere/zotero-better-bibtex/assets/2765811/b78ef779-2913-4ee1-95c4-e7dbba06a070)

referring to Lamport, LaTeX: A Document Preparation System, for the following two tables:

![lam31](https://github.com/retorquere/zotero-better-bibtex/assets/2765811/27a5bbd1-fbca-4183-ae34-963b875ea258)

![lam32](https://github.com/retorquere/zotero-better-bibtex/assets/2765811/bca29a58-df53-4d11-ad46-8bc841e40058)

Therefore, when using bibtex, it seems correct to enclose the code for accented characters in curly braces throughout. 

The only simplification endorsed by Patashnik is `{\"o}` instead of `{\"{o}}`.

Again, all of this is based only on the documentation cited above and applies only to bibtex. It is quite possible that biblatex handles some of these things differently, and I would not recommend changing anything on the biblatex side until complaints are received. Also, using LaTeX code for special characters in a biblatex context would seem rather unusual anyway, since biblatex has full Unicode support.

I also don't see offhand what exactly was ultimately implemented concerning https://github.com/retorquere/zotero-better-bibtex/issues/1189 - was that `{\ss}` (which would match the documentation cited above) or something else?

**Comment by retorquere** [comment]
And things like `\textbackslash` ? Do those also need to be wrapped as `{\textbackslash}x` or can I just write them out as I do now with `\textbackslash x`?

**Comment by ellon-b** [comment]
I tested the [test build 6.7.136.2693.5328](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-6.7.136.2693.5328.xpi) and it worked fine for my needs. Thank you!

**Comment by zepinglee** [comment]
In addition to the correct slicing feature, enclosing with braces has the advantage that the case of the command is preserved in BibTeX's case transforms. In the following BST examples, `\c c` is transformed to `\C C` when converted to uppercase but `{\c c}` is transformed to `{\c C}` with the original `\c` protected, which is less likely to produce an error.

In `{\c{c}}`, the inner braces are not case-preserving since they are inside a "special character" (in terms of BibTeX). Thus they don't affect the LaTeX output.

```bst
  "\c c" "u" change.case$ top$
  "{\c c}" "u" change.case$ top$
  "{\c{c}}" "u" change.case$ top$
```
Output:
```
\C C
{\c C}
{\c{C}}
```

**Comment by retorquere** [comment]
But that's bibtex right, not biblatex? I thought biblatex handled these cases correctly.

**Comment by zepinglee** [comment]
> But that's bibtex right, not biblatex? I thought biblatex handled these cases correctly.

Yes, it's BibTeX only. And biblatex does handles this correctly. I agree the biblatex side doesn't need to change.

In the following example, biber converts all the three diacritics to Unicode form and passes them to LaTeX to perform the case conversion (`\MakeUppercase`, `\MakeSentenceCase`, etc.).

```tex
\documentclass{article}
\begin{filecontents}[force,noheader]{\jobname.bib}
@misc{ITEM-1,
  title = {Foo \c c Bar1},
}
@misc{ITEM-2,
  title = {Foo {\c c} Bar2},
}
@misc{ITEM-3,
  title = {Foo {\c{c}} Bar3},
}
\end{filecontents}
\usepackage{biblatex}
\addbibresource{\jobname.bib}
\DeclareFieldFormat{titlecase}{\MakeUppercase{#1}}
\begin{document}
\nocite{*}
\printbibliography
\end{document}
```

Biber .bbl output:
```
...
      \field{title}{Foo ç Bar1}
...
      \field{title}{Foo ç Bar2}
...
      \field{title}{Foo ç Bar3}
...
```

<img width="169" alt="Screenshot 2023-11-12 at 00 13 17" src="https://github.com/retorquere/zotero-better-bibtex/assets/12290822/148c072d-f43b-4e84-aa92-b53e6cfaf80f">
