### ISSUE TITLE
BUG: TypeError: ItemToolbar is null

### ISSUE THREAD

**Issue by jinze1234599** [retorquere/zotero-better-bibtex#2764]
### Debug log ID

D499971405

### What happened?

Since the update of Zotero 7 new beta version (today, Jan 25), this plug does not work and this warning message popping up each time Zotero launches.
<img width="355" alt="iShot_2024-01-25_16 06 10" src="https://github.com/retorquere/zotero-better-bibtex/assets/22242839/be97447f-070f-44f3-983a-61b61465106f">

**Comment by jinze1234599** [comment]
D499971405

**Comment by retorquere** [comment]
Those go to the Zotero team, not to me. Read the bot message.

**Comment by retorquere** [comment]
I'll see what I get from the Zotero team wrt that change in Zotero, but it might be days before I get a response.

**Comment by LXF-DX3906** [comment]
> Those go to the Zotero team, not to me. Read the bot message.这些是给Zotero团队的，而不是给我的。阅读机器人消息。

I got a debug log id using method 2: BITKTPU3-fio-ToiZ2c5cu2B6

**Comment by retorquere** [comment]
Very likely, but I can't read `D<number>` reports. I have a potential fix, running through the test suite now.

**Comment by jakobkilian** [comment]
Same issue here. Only happens when plugin is activated at startup of Zotero. 
If it is deactivated at startup and manually activated it doesn't give errors but still doesn't start. The logs of the activation are below. If I can help with logs or something, just let me know. thx!

`(3)(+0007621): Enabling plugin better-bibtex@iris-advies.com

(3)(+0000007): Calling bootstrap method 'startup' for plugin better-bibtex@iris-advies.com version 6.7.144 with reason ADDON_ENABLE

(2)(+0000000): Plugin better-bibtex@iris-advies.com is missing bootstrap method 'startup' this.warn@chrome://zotero/content/xpcom/zotero.js:1246:71 _callMethod@chrome://zotero/content/xpcom/plugins.js:191:16 onEnabling@chrome://zotero/content/xpcom/plugins.js:458:13 callAddonListeners@resource://gre/modules/AddonManager.jsm:1519:48 callAddonListeners@resource://gre/modules/AddonManager.jsm:3570:52 updateAddonDisabledState@resource://gre/modules/addons/XPIDatabase.jsm:2764:29 setUserDisabled@resource://gre/modules/addons/XPIDatabase.jsm:718:25 enable@resource://gre/modules/addons/XPIDatabase.jsm:1257:27 handleEvent@chrome://mozapps/content/extensions/aboutaddons.js:3068:27 `

**Comment by retorquere** [comment]
Please try build 5711

**Comment by jakobkilian** [comment]
works like a charm! Thx for the quick help

**Comment by retorquere** [comment]
new release is building
