### ISSUE TITLE
Export of "Contributor" to "WITH"

### ISSUE THREAD

**Issue by 1-user1** [retorquere/zotero-better-bibtex#2837]
### Debug log ID

N/A: because I do not share data

### What happened?

# Overview
This issue is about works with contributors, i.e.:

> Meyers, K. (with Long, W. T.). (2014). Withering worrying.

## Description of the problem
BBT exports a "contributor" as a "collaborator" and does not use the `WITH` field of biblatex-apa.

<details><summary></summary>

## CSL background
In CSL 1.0.2 the following is specified:

> **contributor**
> A minor contributor to the item; typically cited using “with” before the name when listed in a bibliography

-- https://docs.citationstyles.org/en/stable/specification.html#name-variables

</details>

## biblatex background
biblatex specifies:

> **collaborator**
> A secondary editor or a consultant to the editor.

-- https://mirror.funkfreundelandshut.de/latex/macros/latex/contrib/biblatex/doc/biblatex.pdf

<details><summary></summary>

## Conclusion 1
A CSL-contributor should maybe not be exported as a biblatex-collaborator.

</details>

## biblatex continued
biblatex covers **_Editorial_** Roles in section 2.3.6. I did not find information for author roles.

## APA7 as a concrete citation style with support for contributors
APA7 specifies that contributors (APA calls them "nonprimary authors") should be credited using the word "with".

## biblatex-apa
The package biblatex-apa (authored by Philip Kime, who is also the first author of biblatex) covers author roles in section 4.2.2. In the example data it looks like:
```
AUTHOR         = {C. B. Blair},
AUTHOR+an:role = {1="Principal Investigator"},
```
However, looking at the example data, this feature is not used for handling the contributor role. Instead biblatex-apa handles contributors using `WITH   = {C. Contributor}`.
Note: I did not find any documentation for `WITH`

See example 9.8:9 in the package examples: https://markov.htwsaar.de/tex-archive/macros/latex/contrib/biblatex-contrib/biblatex-apa/biblatex-apa-test.pdf
and see the data: https://mirrors.ctan.org/macros/latex/contrib/biblatex-contrib/biblatex-apa/biblatex-apa-test-references.bib

## Conclusion 2
- I am unsure, if `WITH` is a relict of older versions or if this is the way to go. Maybe Philip Kime @plk can answer this.
- Either way, BBT should use `WITH` or `+an:role`, from my point of view.

## Workflow
When exporting the following item from zotero

```
[
	{
		"id": "Meyers-2014-WitheringWorrying",
		"type": "book",
		"title": "Withering worrying",
		"author": [
			{
				"family": "Meyers",
				"given": "K."
			}
		],
		"contributor": [
			{
				"family": "Long",
				"given": "W. T."
			}
		],
		"issued": {
			"date-parts": [
				[
					"2014"
				]
			]
		}
	}
]
```

BBT generates

```
@book{Meyers-2014-WitheringWorrying,
  title = {Withering Worrying},
  author = {Meyers, K.},
  editora = {Long, W. T.},
  editoratype = {collaborator},
  date = {2014}
}
```

instead of

```
@BOOK{9.8:9,
  AUTHOR = {K. Meyers},
  WITH   = {W. T. Long},
  TITLE  = {Withering Worrying},
  DATE   = {2014}
}
```

**Comment by retorquere** [comment]
> N/A: because I do not share data

So enter a sample dummy entry that exhibits the problem and submit that. My experience with recreating the situation based on how users describe things is not great.

**Comment by retorquere** [comment]
> A CSL-contributor should maybe not be exported as a biblatex-collaborator.

I don't even know what this means. BBT exports data from the Zotero database, I don't convert to CSL and then to biblatex, so a CSL-constributor is never exported as a biblatex-collaborator, because CSL doesn't enter the picture. This is exactly why I need a sample entry. We're bound to waste time trying to understand each other while a debug log will just tell me exactly what you are looking at, and I don't have much time to waste.

**Comment by retorquere** [comment]
If you don't get me a sample, I can't really act on this. I'm not guessing my way through this.

**Comment by retorquere** [comment]
You appear to have no idea how BBT works and are not responding to feedback, and I'm not going to plead for the information I need to help you.

You can submit a debug log or attach sample entry exported in "BetterBibTeX JSON" here, and the issue will automatically reopen.

**Comment by retorquere** [comment]
> I don't know what data is transferred when sending a debug log.

But you could have known had you asked, because you can save the log from the debug log wizard to see exactly what is being sent.

> Thus, I am not sending any. 

And if you persist in not sending *any*, not even pasting the BBT JSON entry here, I can't help you. 

> I created a dummy entry and included the JSON definition

You don't even understand enough of the relevant technical matters to know that "the JSON definition" is meaningless here. [This](https://www.rfc-editor.org/rfc/rfc8259.html) is the JSON definition. You are talking about CSL-JSON, which is one of the two popular ways to represent CSL (*not* Zotero) data. CSL is intended for citeproc, and it is one of the **output** formats Zotero uses. It is **not** the contents of the item in your database, it is a **lossy** export of it. 

>  in my issue (please see Workflow). You can easily import this entry as follows:

And I'm telling you, **again**, that this is CSL, and CSL is entirely irrelevant to the question you are posing. I need **BetterBibTeX JSON**. Please stop lecturing me on this and actually read what I said, and make an effort to understand.

>     1. In GitHub: Click the copy code icon
> 
>     2. In zotero: Select File -> Import from Clipboard

Oh, we're going to be condescending now? I am very familiar with how this works. I am also familiar with users who are confidently wrong.

> Zotero implements CSL (Citation Style Language; https://docs.citationstyles.org/en/stable/index.html), i.e., the **zotero** contributor field holds what is defined by the **CSL**. Summarising this in short: The definition of the zotero contributor field is:

Yes dude, **I know**. But **BBT does not use CSL in any way, shape or form** in producing bib(la)tex output, and so it is **irrelevant** what your CSL looks like. Please stop posting CSL-JSON unless you have a CSL-JSON question. Zotero implements ton of stuff that has nothing to do with BBT. CSL is one of those things.

The conceptual models underlying the Zotero database, CSL-JSON and biblatex have tons of differences. `BetterBibTeX JSON` exports items in Zotero database format.

> > A minor contributor to the item; typically cited using “with” before the name when listed in a bibliography
> 
> -- https://docs.citationstyles.org/en/stable/specification.html#name-variables

Yes. Also:

The current population of Bangladesh is 174,333,283

-- https://www.worldometers.info/world-population/bangladesh-population/

which is equally relevant to your question and the work I might do to address it. Post a `BetterBibTeX JSON` export, or submit a debug log. The issue will automatically reopen when you do, but you are seriously testing me.

**Comment by retorquere** [comment]
I'll take a look, I'll have to read the biblatex-apa docs, but if `with`has no documentation and the `+` version does, I'm going with that.

**Comment by retorquere** [comment]
> I just created the BBT JSON and checked its content. It contains personal information like my zotero user ID. 

Nonsense. I bet you are looking at the value `36a3b0b5-bad0-4a04-b79b-441c7cef77db`. This is the ID of the `BetterBibTeX JSON` translator, and is the same for everyone.

**Comment by retorquere** [comment]
I owe you an apology. That should not have been there, I have no need for those. I'll add that to the scrub.

**Comment by retorquere** [comment]
> I might also not want to share my tags, relations, and maybe others.

Those aren't present unless you tagged the item. I don't export tags not related to the chosen entries.

Relations I'll add to the scrub since I don't need them. The "maybe others" I'd like to hear about. I'm open to data minimization, but I'm making an exception in this case for not taking a debug log ID. The general rule will be that I will need a debug log ID. I have wasted much too much time teasing out information of users.

**Comment by retorquere** [comment]
@njbart do you know what the options are to get the desired result for biblatex-apa without interfering with non-biblatex-apa usage? If at all possible I want to solve it in a way that does not require a BBT setting. BBT already has too many.

**Comment by njbart** [comment]
Hate to disappoint you, but I'm afraid an additional BBT setting will be required. While ‘data annotations’ are officially *supported* by biblatex (see biblatex manual, version 3.19, section 3.7), I have yet to see them *used* by any style other than biblatex-apa. Even the biblatex ‘standard styles‘ (see biblatex manual, section 3.3) as well as biblatex-chicago and many others continue to require the format BBT has been outputting so far, i.e., something like:

```
@book{Meyers-2014-WitheringWorrying,
  title = {Withering Worrying},
  author = {Meyers, K.},
  editora = {Long, W. T.},
  editoratype = {collaborator},
  date = {2014}
}
```

**Comment by retorquere** [comment]
But wouldn't that work out well here? I add the annotation and biblatex-apa picks that up, while other styles will ignore it?

**Comment by retorquere** [comment]
Oh wait - the editora fields. Blegh.

**Comment by retorquere** [comment]
Still -- any reason to go with `with` if it's undocumented?

**Comment by retorquere** [comment]
Build 6035 has preliminary support. You can enable it at time of export. I still have to add it to auto-export, and I still don't know whether I'm going to settle on `with` or an annotation (if the latter is even an option).

6035 also offers better data minimization for the debug log. I'd appreciate it if you could check whether this would have been acceptable for you. It's a bit of a balancing act, because if I offer too many choices to turn things off, people will use those, and I'm back to pleading for information I need to help people, and I'm thoroughly fed up with that.

**Comment by retorquere** [comment]
> It is great to be able to turn thing off, but if I turn on the "items" option, `"uri": "http://zotero.org/users/XXXXXXX/items/YYYYYYY",` is included.

I can't replicate this. Where do you see this? When I send a debug log, this is what I'm shown for the items, verbatim:

```
{
  "config": {
    "id": "36a3b0b5-bad0-4a04-b79b-441c7cef77db",
    "label": "BetterBibTeX JSON",
    "preferences": {
      "kuroshiro": true
    }
  },
  "version": {
    "zotero": "6.0.37",
    "bbt": "6.7.174.emile.ws-203-68.han.nl"
  },
  "collections": {},
  "items": [
    {
      "key": "AMKRF9F6",
      "version": 10,
      "itemType": "journalArticle",
      "volume": "18",
      "pages": "243256",
      "publicationTitle": "Israel Journal of Mathematics",
      "date": "1974",
      "title": "Infinite abelian groups, Whitehead problem and some constructions",
      "creators": [
        {
          "firstName": "Saharon",
          "lastName": "Shelah",
          "creatorType": "author"
        }
      ],
      "tags": [],
      "dateAdded": "2018-03-04T10:57:43Z",
      "dateModified": "2018-03-04T10:57:43Z",
      "itemID": 87,
      "attachments": [],
      "notes": [
        {
          "key": "FG9A8DWX",
          "version": 15,
          "itemType": "note",
          "parentItem": "AMKRF9F6",
          "note": "<p>MR 50:9582</p>",
          "tags": [],
          "dateAdded": "2018-03-04T10:57:43Z",
          "dateModified": "2018-03-04T10:57:43Z"
        }
      ],
      "citationKey": "shelahInfiniteAbelianGroups1974"
    }
  ]
}
```

No URIs or relations there, and no tags because I didn't add any.

> I don't know what happens when I click on "Send BBT debug log". Am I able to review and edit the data before it is send? 

That sends exactly what you get when you click "save copy of log". That's why it's a copy.

> Or only review it? Or is it send directly?

No. It gets sent when you click "continue"

> If I am able to edit the data, I could manually delete the user ID and also my tags, relations, and maybe others.

That ain't happening.

I am very open to further scrubbing the data (and I think I did, because I cannot replicate getting the uri field through the debug log window), but I have the debug log precisely because I know exactly what I'm getting. I've wasted days on multiple occasions because a user made a change to submitted data without telling becayse he thought the change was immaterial but which caused me to think something fundamental was broken in BBT and send me chasing phantoms for days (or more precisely, nights). People want my time, we need to come to a reasonable agreement on what I'm getting to spend my time effectively, and I'm absolutely done begging for it.

Relations are already scrubbed (for me, I don't know how you're still seeing them). If you don't want to send tags, don't add tags to the sample. If there's anything else, tell me, and I'll scrub it, because on the regular I don't need anything personal, I just need to know I'm looking at the same thing you do.

As for the "maybe others", tell me what these others are, and I'll see whether I can scrub them without damaging my process. I can imagine there may be sync data in the log, and if there is, tell me, and I'll remove it. But I can't act on "maybe others".

**Comment by retorquere** [comment]
6057 adds auto-export

> It is great to be able to turn thing off, but if I turn on the "items" option, "uri": "http://zotero.org/users/XXXXXXX/items/YYYYYYY", is included.

I still cannot reproduce this on 6035 or 6057. I would really like to know where you found these so that I can scrub them.

**Comment by retorquere** [comment]
> There seems to be something wrong with the behavior. I can reproduce the following behavior:

The checkboxes were wired up wrong. A new build will drop in 10 minutes or so.

> Maybe also some other thoughts:
> 
>     * The whole window is called "Send BBT debug log", however, I can deselect "debug log". This naming conflict could be fixed

Feel free to suggest something, but I'd sooner change the text of the checkbox. The term "debug log" has been in use for ages. That you can exclude parts is new.

>     * A preview of "cache" is missing (files database and cache)

I'd sooner remove preview entirely. The screen is pretty cluttered as it is, and it's only a partial preview, because Zotero locks up if I put too much text there.

>     * I am able to resize the window, but the content does not follow. It would be nice to be able to enlarge the preview.

I have no clue how to do this, the UI technology is almost completely undocumented, and I detest UI work. I don't see this happening.

>     * Can the cache be send without the items?

Yes

> If yes, the cache checkbox should be in a new row, shouldn't it? If no, it should be grayed out, if items is unselected.

Maybe it should, but I'm getting overlapping checkboxes. The UI tech of Zotero 6 is beyond legacy. And they're still really item-related caches.

**Comment by retorquere** [comment]
We're reaching the point where we seem to be making changes for the sake of making changes. The point was to make the debug log more privacy-friendly, I want to focus on whether that goals is achieved.

> > Especially, if you decide to
> 
> remove preview entirely

Sooner, not likely. I have no incentive to remove it. The debug log is low priority and I've already spent more time on this in the past week than I did the past year.
