### ISSUE TITLE
Browser Cannot Conntect to Zotero/BBT Hangs during startup

### ISSUE THREAD

**Issue by despdx** [retorquere/zotero-better-bibtex#2887]
**For people joining this issue**, you can submit a log either by going to Help => Better BibTeX Debug log, or Help => Send log to fle.io. I really need logs because I cannot yet reproduce the problem, and I need clues to the cause.

**If those don't work**, and you're on a Mac or Linux, there's another way to capture a debug log 

On MacOS, you can get a log by starting Zotero with

```
/Applications/Zotero.app/Contents/MacOS/zotero -jsconsole -purgecaches -ZoteroDebugText > $HOME/BBT.txt
```

or on Linux

```
zotero -P BBTTEST -jsconsole -purgecaches -ZoteroDebugText > $HOME/BBT.txt
```

Let Zotero start to the point where you have reproduced the problem, then you can shut Zotero down. In both cases, there will be a file `BBT.txt` in your home directory. You can attach it here, or email it to emiliano.heyns@iris-advies.com`.

Another option, if you're on Linux or Mac and willing to share a full copy of your Zotero profile, I could try to reproduce the problem with that. I don't have access to a Windows machine unfortunately. And I really need a way to reproduce this. To get this copy:

```
zip $HOME/Zotero.zip $HOME/Zotero
```

and mail that to emiliano.heyns@iris-advies.com

## What I know so far

There is a Zotero method BBT *must* call. I call it at a time that Zotero has declared it safe to call it. **Yet that Zotero method hangs when I do, hanging BBT in the process**. Calling it also appears to take down the connector, when these two things have nothing to do with each other. I currently have a workaround in place that helps for some people, not for others, and I cannot reproduce this problem myself, and it's pretty goddamn hard to fix a ghost bug that I cannot see, and that given where it happens, just shouldn't be able to happen.

## related Zotero forums threads

https://forums.zotero.org/discussion/comment/463327#Comment_463327
https://forums.zotero.org/discussion/comment/463326#Comment_463326
https://forums.zotero.org/discussion/comment/463324#Comment_463324

**Comment by retorquere** [comment]
Please do upgrade; I've added a workaround to .200, it may also solve this problem. The difference between .190 and .192 does not explain the problem, because they're functionally identical.

**Comment by despdx** [comment]
Yeah, my reproducing procedure suggests more to do with the upgrade process than a bug in a particular addon version.  I already upgraded to 200.  So far so good.

**Comment by retorquere** [comment]
Can you upgrade to .201 and see if the connector problem is still fixed for you?

**Comment by lgsmith** [comment]
I'm also having this issue, and my 'add-on' window in the zotero desktop app appears to say I'm on .201. My desktop app's version is 6.0.35. My zotero connector's version is 5.0.123. Disabling the better bibtex extension does restore the zotero connector's function. I'm using firefox for kubuntu 22.04 LTS, version 122.0.

What other information can I provide to help?

**Comment by retorquere** [comment]
Oh man I hope a log will say something here. Does debug log submission work? Is this reliably reproducible for you?

**Comment by despdx** [comment]
Oh, very interesting.  It's broken again after the update to 201.  I went to Tools > Add-ons, and BBT was showing an update was available, so I clicked on "restart". Now, I'm getting the same error as before about connecting not working.  I see a suck spinner icon next to the words "better bibtex: translators" in the right pane of Zotero desktop app.

**Comment by despdx** [comment]
I tried to disable BBT and restart.  But I got this on the command line:
```
[18113, Main Thread] ###!!! ABORT: file resource://gre/modules/Sqlite.jsm, line 148
[18113, Main Thread] ###!!! ABORT: file resource://gre/modules/Sqlite.jsm, line 148
/home/<readaced>/local/Zotero_linux-x86_64/zotero: line 13: 18113 Segmentation fault      (core dumped) "$CALLDIR/zotero-bin" -app "$CALLDIR/application.ini" "$@"
```

**Comment by despdx** [comment]
Okay, I started Zotero again, enabled the plugin and clicked "restart".  It started up and finished initializing BBT.  It works, again.

**Comment by retorquere** [comment]
> I don't know about that. How do I do it? I can attach a log if you tell me where to find it on my filesystem...

Help menu, Better bibtex debug log

**Comment by retorquere** [comment]
> I see a suck spinner icon next to the words "better bibtex: translators" in the right pane of Zotero desktop app.

If the aforementioned debug log doesn't work, there will be an entry "send to file.io" in the Help menu. Please send that. Wonder what's broken *now*. I must call a method in Zotero before start, and it just hangs sometimes since recently.

**Comment by retorquere** [comment]
> Okay, I started Zotero again, enabled the plugin and clicked "restart". It started up and finished initializing BBT. It works, again.

If you do see any of these problems again, please try one of the debug log methods. I am traveling tomorrow so I may not always respond immediately.

**Comment by lgsmith** [comment]
When I restarted to activate logging I stopped seeing this issue. I'm not sure what 'moved' underneath me, but I seem to have something that works now on my laptop.

On my workstation for work, the issue is still present even with the .201 upgrade. In fact it's behaving how my laptop was behaving yesterday. In any case, I managed to send this debug report from my workstation (but not sure that it has anything useful in it): `D790041850`

**Comment by despdx** [comment]
> ... does the better bibtex debug log or the file.io log from the help menu work? ...

I don't think so. I clicked on it, and nothing happened. But, I don't know if that is correct behavior or not.

**Comment by despdx** [comment]
Oh,  interesting.  It's broken again.  Maybe that's why the "Send debug log" didn't work.

**Comment by despdx** [comment]
Hmm, looks like there was another update.  It was automatic; I didn't do anything to initiate the update.  I'm at .202 now.

It's petty clear that the bug I'm reporting is that BBT hangs or crashes on start up, and Zotero doesn't notice.  It shows up as enabled in the Add-ons window, but, in the right pane, I again see the stuck spinner icon and the words "better bibtex: translators".

Perhaps I should change the name of this issue to something like "BBT Hangs after Update, No Logged Errors, Breaks Connector, Zotero Works Fine Otherwise".

**Comment by retorquere** [comment]
> It's petty clear that the bug I'm reporting is that BBT hangs or crashes on start up,

Oh great, it's clear to you when it isn't to me *or* the Zotero developers. I'm sure you'll have a fix shortly then.

**Comment by retorquere** [comment]
The problem is **not at al clear**, I've been searching frenetically for what could possibly be causing this for a week. But hey, yeah, renaming the issue will help of course! Why didn't I think of this!

There is a Zotero method BBT *must* call. I call it at a time that Zotero has declared it safe to call it. **Yet that Zotero method hangs when I do**. Calling it also appears to take down the connector, when these two things have nothing to do with each other. I currently have a workaround in place that helps for some people, not for others, and I cannot reproduce this problem myself, and it's pretty goddamn hard to fix a ghost bug that I cannot see, and that given where it happens, just shouldn't be able to happen.

**Comment by retorquere** [comment]
If you're on a Mac or Linux there's another way to capture a debug log. I really need a debug log. Or, if you're on Linux or Mac, a full copy of your Zotero profile, so I could 

> The problem is **not at al clear**, I've been searching frenetically for what could possibly be causing this for a week. But hey, yeah, renaming the issue will help of course! Why didn't I think of this!
> 
> There is a Zotero method BBT _must_ call. I call it at a time that Zotero has declared it safe to call it. **Yet that Zotero method hangs when I do, hanging BBT in the process**. Calling it also appears to take down the connector, when these two things have nothing to do with each other. I currently have a workaround in place that helps for some people, not for others, and I cannot reproduce this problem myself, and it's pretty goddamn hard to fix a ghost bug that I cannot see, and that given where it happens, just shouldn't be able to happen.

**Comment by retorquere** [comment]
On MacOS, you can get a log by starting Zotero with

```
/Applications/Zotero.app/Contents/MacOS/zotero -jsconsole -purgecaches -ZoteroDebugText > $HOME/BBT.txt
```

or on Linux

```
zotero -P BBTTEST -jsconsole -purgecaches -ZoteroDebugText > $HOME/BBT.txt
```

Let Zotero start to the point where you have reproduced the problem, then you can shut Zotero down. In both cases, there will be a file `BBT.txt` in your home directory. You can attach it here, or email it to emiliano.heyns@iris-advies.com`.

**Comment by despdx** [comment]
Woah woah. I'm on your side!  I'm trying to understand the problem, too, so I just realized that BBT could hang without causing all of Zotero hang; I didn't know that could happen.  I wasn't complaining or suggesting you do anything.

I have the STDOUT for zotero, and I see the same thing there as I previously reported. But, I changed my startup procedure to include the debug version, so, if it happens again, I'll be able to get you a nice log of the whole session.  I quit and used those options to zotero and didn't have any problem this time.  We're poised for the next step.  Evidence suggests it will happen after the next upgrade.

**Comment by retorquere** [comment]
Yeah, I apologize for my earlier rant. It's been stressful but that's no reason to take it out on others.

**Comment by retorquere** [comment]
So it's no longer reproducible? 😭

**Comment by despdx** [comment]
No problem.  I'm sorry I'm not able to provide more insight.

Well, I cannot reproduce it by doing anything specific...oh wait, sorry, I could downgrade and upgrade again, right?  Okay, let me try...hmm, no I cannot reproduce it myself. I tried removing BBT and installing .190, then installing .192 over that, then I tried upgrading .192 to .202 via manual "check for updates and that didn't work.  And I did it again, too. I couldn't get it to break, again.  According to my old notes, this process reproduced the problem in the past, so I'm confused again.

**Comment by retorquere** [comment]
transient errors are the worst

**Comment by retorquere** [comment]
If anyone hits the error again, please also try an earlier Zotero beta.

**Comment by LambdaP** [comment]
I have been pretty consistently unable to get papers using the Zotero Connector extension lately. Tried restarting everything etc.

I started Zotero using the diagnostic command line in the first comment in this thread, then tried using the Connector, and it worked fine. Restarted Zotero normally, still worked fine.

Aren’t computer marvelous.

**Comment by retorquere** [comment]
Gaah, these transient errors! Are you on Linux or macos by any chance.

**Comment by despdx** [comment]
Linux

**Comment by retorquere** [comment]
Would you be OK with sharing your zotero profile (which, to be clear, would contain all your Zotero data) privately? I have to find a way to replicate the problem, and with a profile that at least sometimes has the problem, I could just hammer that profile. I have a private Linux box that I could use for tests, this wouldn't leave my personal systems, not shared with anyone, not sent to github. Are you on zotero 6 or 7?

**Comment by retorquere** [comment]
Can someone please try build 6346?

**Comment by retorquere** [comment]
Can someone please try build 6349?

**Comment by retorquere** [comment]
I've rolled this into a new release. I'd appreciate feedback on whether release .203+ structurally solves the issue.

**Comment by retorquere** [comment]
Minutes is pretty long though. If that's repeatable I'd love a log. But if that time is just spent waiting for the 2nd signal (the log has information on whether this is the case), there isn't anything I can do about that.

**Comment by mjthoraval** [comment]
Here are the details.
I have followed the same steps: 
- Open 10 tabs.
- Close and reopen Zotero
- While reopening, keep pressing `Ctrl`+`Page Down` for 5 minutes

After releasing the keys, I waited some time, during which Zotero was still very busy.
Then this appeared:
![image](https://github.com/retorquere/zotero-better-bibtex/assets/36054098/37e9ea5e-9018-4076-a81f-b7ce45e714ef)

I pressed `Continue`.

It took 2 minutes 45 seconds to get the header to appear in the Item Pane.
Then another 2 minutes 40 seconds to get the Citation key column appear, so 5 minutes 25 in total after releasing the keys.

Here is the Debug log ID: H7QPQ4VH-euc/6.7.203-7

**Comment by mjthoraval** [comment]
I have tried also pressing `Stop script`.
The Citation key column still appears after waiting for 7 minutes.

**Comment by retorquere** [comment]
> Here is the Debug log ID: H7QPQ4VH-euc/6.7.203-7

Yeah that shows what I already suspected:

```
orchestrator: start took 00:07:59.336
```

which is insanely long but that is the time Zotero takes to clear the 2nd signal on your system. I'll see whether the Zotero crew wants to dive into this, but between "mysterious breakage of core Zotero functionality" and "BBT takes forever to start up", I'm picking the latter.

**Comment by retorquere** [comment]
Still -- the BBT database init independently takes over 2 minutes, which is ridiculous. A new build is incoming, please send a new log.

**Comment by despdx** [comment]
> Would you be OK with sharing your zotero profile (which, to be clear, would contain all your Zotero data) privately? I have to find a way to replicate the problem, and with a profile that at least sometimes has the problem, I could just hammer that profile. I have a private Linux box that I could use for tests, this wouldn't leave my personal systems, not shared with anyone, not sent to github. Are you on zotero 6 or 7?

Sure, that would fine.  How can I send it to you?  What do I send?

**Comment by mjthoraval** [comment]
I got similar results with the test build 6.7.203.2887.6364.
- 2 minutes 8 seconds to load the header
- plus 2 minutes 17 seconds to load the Citation key column

-> So 4 minutes 2 seconds in total to load the Citation key column.
Debug log ID: WQPIDRRP-euc/6.7.203.2887.6364-7

But to be fair here, the test protocol is a bit extreme, and Zotero itself does not react very well to it. So BBT is probably not to blame here.

For comparison, here are the times if I do not press `Ctrl`+`Page Down` for 5 minutes after starting Zotero:
- 22 seconds to load the header
- plus 7 seconds to load the Citation key column

-> So 29 seconds in total to load the Citation key column.
Debug log ID: VHY9RXTS-euc/6.7.203.2887.6364-7

This is in line with what I had reported to Zotero before: (see [this post](https://forums.zotero.org/discussion/114548/zotero-7-beta-disappearing-tabs-during-loading)) .
And the PDF Reader does not seem to handle very well a continuous flow of actions in recent versions (see [this post](https://forums.zotero.org/discussion/114771/zotero-7-beta-problems-with-loading-of-pdf-files-in-the-reader)), [especially in Troubleshooting Mode](https://forums.zotero.org/discussion/comment/464396/#Comment_464396).

**Comment by retorquere** [comment]
These builds add only logging, so they won't be any faster than they were. A new build is incoming, I'd appreciate a new log. The 2.5 minutes wasn't in the part where I added logging.

**Comment by mjthoraval** [comment]
The first test has killed Zotero:
![image](https://github.com/retorquere/zotero-better-bibtex/assets/36054098/849dfae7-6627-4618-8a1e-888e5ff1c9d8)

![image](https://github.com/retorquere/zotero-better-bibtex/assets/36054098/61652cc9-796b-44a3-9f52-6233310dad08)

I will try again.

**Comment by retorquere** [comment]
But can you do a plain start and post a log? I've added more timing logging. Something really strange is going on -- there are large chunks of time (over a minute in the last log) where BBT does not appear to doing anything but there isn't anything else in the logs.

**Comment by mjthoraval** [comment]
The second try was successful: QE2WV8GQ-euc/6.7.203.2887.6378-7
- 1 minute 22 seconds to load the header
 - plus 4 minutes 49 seconds to load the Citation key column

-> So 6 minutes 11 seconds in total to load the Citation key column.

I guess it was getting longer due to the additional logs, and opening the Debug Output window was the thing that killed Zotero...

And a log for a normal restart without doing anything during the restart: RUY8E96J-euc/6.7.203.2887.6378-7

**Comment by mjthoraval** [comment]
New one: 68K53T59-euc/6.7.203.2887.6382-7
- 3 minutes to load the header
- plus 5 minutes to load the Citation key column

-> So 8 minutes in total to load the Citation key column.

And normal restart: LEYDJBEN-euc/6.7.203.2887.6382-7

**Comment by mjthoraval** [comment]
3EVTPXAQ-euc/6.7.203.2887.6385-7

**Comment by mjthoraval** [comment]
Another one with the sync disabled: IY6WIBTQ-euc/6.7.203.2887.6385-7
And a normal restart: 3XGDWEU7-euc/6.7.203.2887.6385-7

**Comment by retorquere** [comment]
Interesting:

* IY6WIBTQ shows database activity while BBT is starting up, and then BBT startup took 00:05:18.394 after waiting 00:07:56.551 for zotero
* 3XGDWEU7 has no DB activity and then BBT startup took 00:00:07.661 after waiting 00:00:21.645 for zotero

and it is consistently the database attach that causes these long startup times.

What do you mean by

> with the sync disabled

?

**Comment by mjthoraval** [comment]
> What do you mean by
> > with the sync disabled

I have disabled this option:
![image](https://github.com/retorquere/zotero-better-bibtex/assets/36054098/c474a307-22c3-4e37-94fd-c6cb47c59647)

I understand that it can pollute the debug log for Zotero, and it can also affect loading performances, as it starts syncing during startup.
So the devs usually prefer logs without syncing.

3EVTPXAQ-euc/6.7.203.2887.6385-7 (with syncing) took more than 10 minutes to load BBT...

**Comment by mjthoraval** [comment]
![image](https://github.com/retorquere/zotero-better-bibtex/assets/36054098/7fe5fa25-2b7b-44cc-a235-f63d9d381a1e)

It seems that this has put BBT into the broken state (the Citation key column does not come out).

I was still able to send you a debug log:
Send debug log to file.io: JL8C95HS-fio-HQHheDsr3LqJ

![image](https://github.com/retorquere/zotero-better-bibtex/assets/36054098/7c2ac329-6aa7-4902-ae40-d55b49de76ec)

I will try again after dinner.

**Comment by mjthoraval** [comment]
A simple restart first: J9P6JPL6-euc/6.7.203.2887.6388-7

**Comment by mjthoraval** [comment]
I have reduced the time pressing `Ctrl`+`Page Down` to 1 minute.
It has also crashed BBT:
![image](https://github.com/retorquere/zotero-better-bibtex/assets/36054098/9e3216fa-6339-4e7f-9ce6-7d0d6ec6914a)

Send debug log to file.io: PIJVQTX6-fio-vCYwWmzcx2Zh

**Comment by mjthoraval** [comment]
5 minutes: PEMRVNMW-euc/6.7.203.2887.6389-7
The Debug ID is: D888904307

Normal: U2GU68NT-euc/6.7.203.2887.6389-7
The Debug ID is: D1200806120

**Comment by mjthoraval** [comment]
5 minutes: L5NZW2QB-euc/6.7.203.2887.6391-7
Normal: RPJ74TE4-euc/6.7.203.2887.6391-7

**Comment by retorquere** [comment]
Yeah so it's down to: BBT startup took 00:00:02.974 after waiting 00:13:12.028 for Zotero. So the time BBT took to start up is .just under 3 seconds after waiting for 13(!) minutes for Zotero to be ready, because I'm purposely doing nothing until Zotero is ready. I don't know how to account for it only taking 5 minutes from your test? That's not what the timestamps in the log indicate.

I'll see what I can get from the Zotero crew.

**Comment by retorquere** [comment]
> 5 minutes: L5NZW2QB-euc/6.7.203.2887.6391-7
> Normal: RPJ74TE4-euc/6.7.203.2887.6391-7

And the difference between those scenarios is whether you have sync enabled? Maybe I should just suspend sync during startup.

**Comment by mjthoraval** [comment]
Sorry, I have shortened the explanations in the recent tests.
To clarify the test procedure:
- I disable the automatic sync, so that it does not interfere with the startup of Zotero.
- I also do not trigger it manually, so that there should not be any sync operation in the reports I send you, to simplify as much as possible.
- The 5 minutes I mention is the time I continuously press on `Ctrl`+`Page Down` just after opening Zotero.
- The times that you measure are the recovery times. I reported them earlier, to give you some idea of what I was seeing. But I understand that you have more detailed information from the logs. And I also gave up checking the loading times of Zotero and BBT when it went over 10 minutes...
- In more recent tests, I have also included the simpler procedure, where I do not do anything during startup. I do not press on `Ctrl`+`Page Down` and just wait until I can see the Citation key column in the Items Tree. This is what I describe as "5 minutes" (of `Ctrl`+`Page Down`) vs "Normal" (no `Ctrl`+`Page Down`). So the continuous switching between tabs is the culprit here. I would need to test separately for the influence of allowing the automatic sync to run during startup.

So the steps described above:

> The closest torturing steps I could get were:
> - Open 10 tabs.
> - Close and reopen Zotero
> - While reopening, keep pressing `Ctrl`+`Page Down` for 5 minutes
> 
> -> During that time, and for a few minutes after, it looked like the Citation key column would not load. But after waiting a few minutes, it still came back and worked properly.
> So if you keep Zotero busy, you can temporarily prevent BBT from loading.

I have focused on these steps, because it shows that I can delay the startup of BBT (as a consequence of the long delay for opening Zotero) as long as I want.

My interpretation is that Zotero tries to perform all the operation that it can register, without any safety fuse to forget old operations that are probably meaningless when they are finally performed. That would explain why the accumulation of 5 minutes of instructions to switch between tabs and load them end up in more than 10 minutes to recover.
But I have no idea how it actually works, so this is just guessing.

To be fair, this test case is probably not something that would really need to be optimized against, as it is quite far from realistic usage. But I have noticed that the recent versions of the betas are significantly slower to load. I guess that it is related to all the additional layers that add to the loading time: new UI, new header of the Item Pane, preview, automatic extraction of references, figures, equations, automatic extraction of table of content, ... With all these extra loads, whenever one of these steps has troubles, it can delay the whole loading process. So the test case is designed to push the limits to something easier to quantify than the extra 10 or 20 seconds observed to start Zotero.

Let me know if I should continue doing these tests, or if the simple "Normal" restart process is sufficient for optimizing the startup of Zotero and loading of BBT.

**Comment by retorquere** [comment]
> * The 5 minutes I mention is the time I continuously press on `Ctrl`+`Page Down` just after opening Zotero.

I don't know what this does

> * The times that you measure are the recovery times

Not really I think? The times I measure are just various steps in the BBT startup.

> * the loading times of Zotero and BBT when it went over 10 minutes...

This is really just the Zotero startup time. It takes 13 minutes on your system from the time that BBT is told it can start to the time that it can actually safely install translators and access the database in that last test.

> * So the continuous switching between tabs

ah that's the `Ctrl`+`Page Down`?

> is the culprit here. I would need to test separately for the influence of allowing the automatic sync to run during startup.

That would be really helpful. If sync works OK, but tab switching triggers this, then they'll have an easier time figuring this out. Strange though, because it's their database access and the translators install which are the massive delays, and I don't see how that interacts with tab switching. But if that's something that happens even without BBT installed, the Zotero crew will want to get on that.

**Comment by mjthoraval** [comment]
Yes, `Ctrl`+`Page Down` is the shortcut for switching to the next tab.
It is cyclic, so the tab after the last one is the first one, i.e. the library tab.
So it just continuously cycles through the tabs if I keep pressing the shortcut.

I have tested the "5 minutes" procedure with all plugins disabled, included BBT, and doing a Restart with Logging Enabled.
Here is a debug output obtained: The Debug ID is D2093420213.

It still takes around 3 minutes after stopping to press `Ctrl`+`Page Down` to load the header of the Item Pane, with one item selected in the Items Tree.
That means 8 minutes after actually starting Zotero. But this time can be increased to any value you want, as continuously switching tabs will prevent Zotero from loading as long as you keep pressing it.
That seems to be similar to the loading time observed with BBT enabled. But I don't know if there are still operations still running in the background after that.

I can provide more testing to the devs if they think it is useful.

To see the influence of the automatic sync during loading, I just performed the "Normal" procedure: I just restart without doing anything else.
- Automatic sync disabled: 7HZEZQYK-euc/6.7.203.2887.6392-7
- Automatic sync enabled: FLI3WPRD-euc/6.7.203.2887.6392-7

**Comment by retorquere** [comment]
> Here is a debug output obtained: The Debug ID is D2093420213.

I have no access to those, but if you have the [debug log](https://github.com/retorquere/zotero-debug-log) plugin (which does nothing except add a menu entry) you can submit a log to file.io, which I can access.

> It still takes around 3 minutes after stopping to press Ctrl+Page Down to load the header of the Item Pane, with one item selected in the Items Tree.

That's strictly a Zotero problem then.

> But I don't know if there are still operations still running in the background after that.

There are, but they take seconds at most.

> Automatic sync disabled: 7HZEZQYK

BBT startup took 00:00:07.163 after waiting 00:00:17.911 for Zotero

> Automatic sync enabled: FLI3WPRD

BBT startup took 00:00:10.721 after waiting 00:00:19.585 for Zotero

so the sync is not the issue then (assuming something was actually syncing). The tab-switching wedges something in Zotero, and since BBT waits for that to clear, it will start up very late. I've not heard back from the devs, so if you could post this disabled-plugins scenario on their forums, that would be really appreciated.

**Comment by mjthoraval** [comment]
Here it is with more details:
https://forums.zotero.org/discussion/114993/zotero-7-beta-switching-tabs-delays-the-loading-of-zotero

The crazy RAM ramp up for more than 10 minutes after releasing the shortcut is what I meant by "operations still running in the background after that".

**Comment by mjthoraval** [comment]
I have tried to produce one for you, but it did not work:
![image](https://github.com/retorquere/zotero-better-bibtex/assets/36054098/2957d60e-b4a3-4684-82b6-9a45e22f07d8)

The data submitted to Zotero (to keep a record of it):
The Debug ID is D1698125593.

I still get the same error for a normal restart. So the plugin is not working for me.

**Comment by retorquere** [comment]
Blegh another thing that dropped out of 7 then. That problem is easy to fix though. I'll get a new version out when I'm home.

**Comment by retorquere** [comment]
Nope, that still works on beta 84. I don't know why FormData is undefined for you. A new build will drop soon that will confirm whether it actually is. Please try a new log from that (either BBT or file.io)

**Comment by mjthoraval** [comment]
- With only the BBT plugin enabled: 6RBYDU8G-euc/6.7.203.2887.6397-7
- With only the BBT plugin enabled during restart from file.io: RSJ3S4NV-fio-BUvy8aIDIcmv
- With only the Debug Log plugin enabled: FormData error
![image](https://github.com/retorquere/zotero-better-bibtex/assets/36054098/795d758a-cae4-492b-b4d6-43e44e22146b)

I had this already before: https://github.com/retorquere/zotero-better-bibtex/issues/2886#issuecomment-2122164430

**Comment by mjthoraval** [comment]
But I do not understand why a new BBT version would help understanding the problem with the Debug Log plugin?

**Comment by retorquere** [comment]
They use a common module to put up the file.io menu entry, so it's surprising to me that it works for BBT but not for debug log. It also just works for me, for both BBT and debug log.

**Comment by mjthoraval** [comment]
> I'm also getting a Windows machine later today.

Is it also working for you on Windows?

**Comment by retorquere** [comment]
I don't know, I haven't installed the system yet.

**Comment by despdx** [comment]
Sorry I haven't tried your debug pkgs.  Zotero/BBT has been working well, in the sense that BBT isn't hanging for me after auto update.  That's the issue I noticed, originally.

If I can find some time next week, though, I'll try your debug pkg.

I also want to say that Zotero doesn't take very long to start up for me.  I'm surprised by some of the numbers you are reporting here.  I would say maybe 30 seconds at most.

**Comment by retorquere** [comment]
No need to test these packages, the changes have been rolled into the new release. These extreme startup times need further diagnosis by the Zotero team.
