### ISSUE TITLE
stuck on export library to bibtex

### ISSUE THREAD

**Issue by BadoD** [retorquere/zotero-better-bibtex#2942]
### Debug log ID

PXHJZCDT-euc/6.7.219-6

### What happened?

I'm trying to export my library as better csl json but it is stuck in a window saying exporting elements

**Comment by retorquere** [comment]
Please go to Help -> Debug output logging -> Start with logging enabled, let Zotero restart, and then send a new log

**Comment by BadoD** [comment]
Ok, thanks for the follow up. I still can't export correctly yet.

I get this ID:

FKEDTK7X-fio-qH2ffFUemf1s

**Comment by retorquere** [comment]
I know, this is just for diagnosis. Doesn't the regular (`-euc` like you sent before, rather than `-fio`) log work? Those are more convenient for me.

I see no evidence of an export in FKEDTK7X-fio-qH2ffFUemf1s, did you reproduce the problem before sending the log?

Can you turn off attachment sync during diagnosis? You are over your free 300MB quota and that puts error messages in the log and it's harder to find actual error messages that way.

**Comment by retorquere** [comment]
Can you try the build from https://github.com/retorquere/zotero-better-bibtex/issues/2940#issuecomment-2285476897 ? May be the same problem.

**Comment by retorquere** [comment]
If it is not the same problem, commenting here will reopen this issue automatically.
