### ISSUE TITLE
Stuck on export

### ISSUE THREAD

**Issue by matthiasfabry** [retorquere/zotero-better-bibtex#2972]
### Debug log ID

SQWH5QKE-euc/6.7.226-7

### What happened?

much like #2954 and/or #2940 and/or #2942, I cannot export to bib files. This worked in Zotero 6 (although sometimes I had to enter the settings and manually "export now" instead of BBT automatically exporting after a change), but now it's stuck on "preparing Better BibTex +1"

**Comment by retorquere** [comment]
I don't see export activity in SQWH5QKE-euc/6.7.226-7. What were you trying to export?

**Comment by matthiasfabry** [comment]
I clicked on a collection and hit export. It opens a dialog with options, clicked on keep updated, gave the filename and save. Then it’s stuck on this message. Is this supposed to take more than 2 mins?

**Comment by retorquere** [comment]
> Is this supposed to take more than 2 mins?

No. A build will drop here soon that has more logging, please send a new log from that.

> much like #2954 and/or #2940 and/or #2942

it's not likely there is a relation.

**Comment by matthiasfabry** [comment]
YQF9PDU9-euc/6.7.226.6920-7

It appears as if zotero as a whole is not hanging though. While the "preparing BBT" message shows, graying out the main zotero window, I can still access the "File, Edit, Tools, etc." menus.

**Comment by matthiasfabry** [comment]
Ok this is really strange. I tried exporting another collection, at it went without problems. Then tried exporting the problematic collection again, and now it exports as normal. 

X224MX2B-euc/6.7.226.6920-7

**Comment by retorquere** [comment]
please try with build 6932

**Comment by matthiasfabry** [comment]
W3SEIVRK-euc/6.7.227.6932-7

**Comment by matthiasfabry** [comment]
HQKVE6NA-euc/6.7.227.6938-7

**Comment by retorquere** [comment]
So the translate starts and succeeds but there's still a recursion error. I'm looking into this but it may well take me a few days to come up with something.

**Comment by retorquere** [comment]
Does this build fix the problem?

**Comment by matthiasfabry** [comment]
Just out of curiosity, what turned out to be the problem?

**Comment by retorquere** [comment]
To be totally honest -- I think I know what triggered the problem, but I don't know what the actual problem was.

It looked like my database writes for the auto-exports triggered a recursive invocation of Zotero's dateparser; I have no idea why that happened, as I could find nothing about SQL writes through the Zotero API that did date parsing, so in the end I have just removed the trigger; I have taken the auto-exports out of the SQL database and have stuck them in preferences. I could not create a focused testcase (a so-called MWE) for the problem so a discussion about this on the dev list would not have gotten much traction.
