### ISSUE TITLE
ItemPaneManager is undefined on NixOs's 24.05 zotero_7

### ISSUE THREAD

**Issue by JJJHolscher** [retorquere/zotero-better-bibtex#2999]
### Debug log ID

3G26G2FL-fio-uvyfBIf15We2

### What happened?

Upon startup, Better Bibtex informs me
```
Better BibTex startup failed
TypeError: Zotero.ItemPaneManager is undefined
```
and proceeds not to show up under Tools, Library right click menu or the Settings.
Most important for me, Obsidian's `Zotero integration` plugin ceases to function.

### some other details

- This only happens on Zotero 7, not Zotero 6, I switched back.
- I first had Zotero 6 installed, then switched to Zotero 7. Zotero 7 inherited the settings and plugins of Zotero 6.
- I have no other add-ons enabled.
- I installed a style which I called better-bibtex.csl at some point. (it's the generic bibtex style, but with the better-bibtex citekey)
- My arch machine works fine with Zotero 7 + Better Bibtex.
- I updated Better Bibtex after posting this log just now, but the same issue persists after updating.

Apparently you are the only one able who can see my debug logs. Please don't make those public though please do email them to `[email redacted]` so I can see them as well.

**Comment by retorquere** [comment]
You can view them in the debug log viewer in the help menu.

**Comment by JJJHolscher** [comment]
Alright, thanks in that case I can make no sense of them. I'm not that experienced with zotero debugging.

**Comment by retorquere** [comment]
That is also in `3G26G2FL-fio-uvyfBIf15We2`. I'll take a look.

**Comment by JJJHolscher** [comment]
Not promising anything, but if you've got any insights/suspicions/intuitions to share as to the origin of the bug then I might be able to look myself. Though I understand if you don't consider that worth your time.

**what use I will probably be**
As mentioned I'm completely inexperienced with the Zotero API.
_Optimistically_, I'd spend half a day on this, and my deliverable would be more details on the origin of the bug.
Plausibly I'd do a pull request, though one that I'd expect to be messy enough that it won't be accepted, only highlight what edits made the bug go away for me.
_Pessimistically_, I will only give it another half hour of browsing, without ever doing any trial and error.

**in case you'd type a message for me to be able to start up**
I might benefit from additonal links as to what you think is a good beginner resource to Zotero plugin dev.
From a few minutes of searching I found(, without already having read them):
- https://www.zotero.org/support/dev/client_coding/javascript_api
- https://github.com/zotero/make-it-red

**Comment by retorquere** [comment]
Thanks! Man there isn't really a good intro to Zotero plugin development, most people took other plugins as skeletons and for anything interesting I actually read the Zotero source code.

The first thing that needs to be done is that ZoteroPane.ts and ZoteroItemPane.ts need to be merged, and instead of being triggered from orchestrator in the 'done' phase it needs to be triggered by `onMainWindow`, for which I've just added stubs. There's also stuff in loadUI that needs to be untangled.

This is not the easiest place to start TBH, but I appreciate it. Even if you could merge ZoteroPane.ts and ZoteroItemPane.ts and keep it working that would be a real help.

What platform are you on? My build process is well tested on Linux and MacOS, but not tested at all on Windows, and starting debug builds might work under WSL, will not work in the regular Windows environment.

**Comment by JJJHolscher** [comment]
Linux with NixOS.
Thanks for the guidelines, I'll look into it when I have some spare time.

**Comment by retorquere** [comment]
Things have changed substantially since October. If the issue still persists on the new Zotero/BBT, you can comment here, and the issue will re-open automatically.
