### ISSUE TITLE
Add postfix to both conficting citation keys

### ISSUE THREAD

**Issue by rytverhagen** [retorquere/zotero-better-bibtex#3043]
### Debug log ID

CTEETQF2-refs-euc/6.7.248-7

### What happened?

When two citation keys conflict (e.g., "Birch 2022"), BB renames keeps one "Birch 2022" and renames the other "Birch 2022a". I am trying to get it to rename both into "Birch 2022a" and "Birch 2022b". I use the following citation key formula "" [auth:lower][year][=].

**Comment by retorquere** [comment]
`[auth:lower][year][=]` is in the legacy format, and it isn't a valid formula yet, because `[=]` needs a number, but eg `[auth:lower][year][=0]` would automatically be translated to the new format (displayed under the current formula while you're editing):

```
auth.lower + shorttitle(3,3) + year
```

to get what you want you would add a postfix term:

```
auth.lower + shorttitle(3,3) + year + postfix(start=1)
```

but note that this will *always* postfix a letter, not just when disambiguation is needed.

**Comment by rytverhagen** [comment]
Thank you! I tried and it works. So, if i understand correctly it is currently impossible to do this only when disambiguation is needed. In this case, I will do it manually.  
(The reason I’d like this to work is because handling citation keys this way matches how in-text citations are handled in the actual literature I work with).

**Comment by retorquere** [comment]
That is indeed currently the case
