### ISSUE TITLE
inconsistent key generator between jabref  and zotero-better-bibtex

### ISSUE THREAD

**Issue by kiwonum** [retorquere/zotero-better-bibtex#31]
For duplicate keys, zotero-better-bibtex (0.1.37) produces the unique key differently with jabref.

jabref: http://jabref.sourceforge.net/help/LabelPatterns.php
Yared1998
Yared1998a
Yared1998b

zotero-better-bibtex:
Yared1998
Yared19980
Yared19981

It would be better to keep consistency.

**Comment by henningway** [comment]
I just started using BBT and experimented with the citekeys.

When I add a second reference which gives an identical citekey an '-1' is appended to the second key. From what I I was reading above and what I would prefer I expected 'a'. Can I change this behaviour somewhere? (I'm currently using '[auth:lower][year][0]' - btw what does the [0] stand for?)

And maybe one related and not totally on-topic-question: I will work with Lyx and plan to use biber/biblatex for the bibliography-generation and I haven't found a good description of a good workflow integrating Zotero yet. Any ideas where to look?

Thank you!

PS: I actually needed a while to find the BBT-Preferences, because I didn't expect to be with the general preferences (...)

**Comment by retorquere** [comment]
The `[0]` is a pseudo-function to [force the disambiguation postfix to numeric](https://zotplus.github.io/better-bibtex/citation-keys.html#functions) rather than alphabetic in order to mimic the stock behavior of Zotero. I don't use it myself (I like alphabetic myself) but it helps people who already have Bib files generated with the stock exporter to migrate. So if you just remove it from your pattern you should be good to go.

I don't use LyX myself, so I don't exactly know what the best process for it would be; if you want to use [LyZ](https://github.com/willsALMANJ/lyz) with BBT this would require changes in LyZ I think to have it pick up the BBT generated keys (something which zotxt also does, it's not hard, but it's a change), but if you just use the standard LyX facilities to pick your citations from your BibTeX file, you can just auto-export the relevant collection, and BBT will make sure it keeps up to date.

The placement of the BBT prefs was an arbitrary choice, I could have gone for a separate window, but I generally like to have all preferences in one place.

**Comment by retorquere** [comment]
The next version of BBT will also allow you to open the prefs from the Firefox addons manager

**Comment by henningway** [comment]
Nice! :-)
Thank you very much.
