### ISSUE TITLE
Conversion of accents to LateX

### ISSUE THREAD

**Issue by PietaSchofield** [retorquere/zotero-better-bibtex#443]
Hullo 

I apologise if this is a repeat question. I am having problems when I export to bibtex with the {\'i} character (acute accented i) I generate the character with alt-e i on my mac and it looks correct in Zotero however it exports as {\'\i} not {\'i} and this causes RefManageR in R to hang when reading the bib file. If I manually edit the bib file to convert this back to {\'i} then all is sweetness and light again. Other accented characters like {\"o} and even {\'e} seem to generate fine it is just the acute accented i

Pieta

**Comment by retorquere** [comment]
That's a bug. Can you right-click on that reference and select "send bbt
error"? That will give me the full reference so I can test.

**Comment by PietaSchofield** [comment]
Thanks I have sent error report D2THETD3

**Comment by retorquere** [comment]
Turns out it's not a bug: I've looked it up, and `{\'\i}` is actually the right translation for that character -- the `\i` suppresses the dot above the `i` to make sure the accent is rendered cleanly. Does RefManagerR fare any better with `\'{\i}`? I can render that instead, it's equivalent. But you've come across a RefmanageR bug at least, as `{\'\i}` is valid LaTeX, regardless of whether it should be the preferred rendering of "latin small letter I acute".

**Comment by retorquere** [comment]
The same problem would occur with accented `j` BTW, for the same reason.

**Comment by retorquere** [comment]
I think we'll have to file an issue for this at [RefManageR](https://github.com/mwmclean/RefManageR/issues). I'll be glad to help, but submitting the full reference that triggers the problem in RefManageR there will help Matthew find and fix the problem enormously, so if you could do that we could take it from there.

**Comment by retorquere** [comment]
closed for inactivity.
