### ISSUE TITLE
Question: what to backup?

### ISSUE THREAD

**Issue by floe** [retorquere/zotero-better-bibtex#471]
Hi, just a brief question about this very helpful piece of software: which files should I include in my backup?

There is a folder `better-bibtex` below my Zotero folder, but it seems to contain only backup files itself? Is it therefore sufficient if I just save `betterbibtex-lokijs.sqlite` and ignore the rest?

I'm on version 1.6.43, with Zotero 4.0.29.6. Thanks

**Comment by retorquere** [comment]
Yes, that's all that's required. Can you get me a list of files that are in your profile that seem BBT-related? I'll amend the cleanup procedures, I haven't always kept up.

**Comment by retorquere** [comment]
I'm hoping to do away with the database as soon as Zotero supports plugin-specific fields BTW, but that has been on the roster for years, I don't expect that to happen anytime soon.

**Comment by floe** [comment]
```
M       better-bibtex/cache.json.bak
!       better-bibtex/db.json
?       better-bibtex/db.json.bak
?       betterbibtex-lokijs.sqlite
I       betterbibtex-lokijs.sqlite-journal
I       betterbibtex.sqlite.bak
```

This is the list as seen by Subversion. I had also included `db.json` in my repo, but that seems to have vanished with recent versions...?

**Comment by retorquere** [comment]
db.json has been migrated into betterbibtex-lokijs.sqlite; it's been backed up because I'm paranoid about such things, but a new checkin takes care of that. Enough time has passed that this should no longer be necessary. Tests are running on that.

Be careful about your backup methods though. You don't want to backup running SQLite databases by checking them into subversion. You preferably want to do this while Zotero is not running, or make use of the SQLite [command line utilities](https://www.sqlite.org/cli.html).

**Comment by floe** [comment]
Hm, good point about SQLite & SVN, thanks for the hint.

**Comment by retorquere** [comment]
Especially in light of https://www.sqlite.org/howtocorrupt.html
