### ISSUE TITLE
Zotero Standalone doesn't show citekeys in reference list on startup

### ISSUE THREAD

**Issue by EricDJohnson** [retorquere/zotero-better-bibtex#497]
47METGGH
The Extra field in the middle Zotero pane is now ignoring the manually entered pinned/fixed key and instead displays a soft key (autogenerated based on the references metadata). Changing the data in the Extra field updates the middle pane with the corresponding pinned key until Zotero is closed/opened again. Besides adding references today, I have installed the OpenOffice add-on.

**Comment by retorquere** [comment]
I can't reproduce this yet on my side. To make sure I've understood correctly, this is what I've tried:

1. Enable "show citekey instead of Extra"
2. On a reference, pin a citekey, and change it, to make sure it's not a generated key
3. This displays both in the reference and the Extra column
4. Stopped firefox
5. start firefox
6. Pinned citekey shows as expected in Extra and in the reference

I take it for you, 6. doesn't hold.

Can you enable extended debugging, do the above, but between 3 and 4, and after 6, submit a debug log?

**Comment by EricDJohnson** [comment]
The above issue occurred in Zotero Standalone. I notice now when Standalone is re-started the middle pane displays the extra field verbatim (ie "bibtex: [citekey]"). When I scroll over a reference with the cursor the Extra field changes to either 1) the auto-generated soft key (if the pinned key was entered before this issue started today), or 2) the expected pinned key (only if the pinned key was entered today). 

Following the steps above, changing the Extra field in Zotero Firefox before restarting Firefox caused nothing to update the middle pane (before step 4). However, the middle pane did reflect the changes made in Zotero Standalone. After restarting Firefox (step 5), changes made to the Extra field were reflected in the middle pane, but if the pinned key was made before today an auto generated soft key is displayed.

The Standalone and Firefox versions are never open at the same time.

Using Zotero Firefox:
Debug log between steps 3 and 4 - 365FV4X6
Debug log after step 6 -TJKFVWCV

**Comment by retorquere** [comment]
Could you do two things for me:

* Upgrade to .56 (out just a minute ago). It doesn't change anything relevant, but the logging was a little hyperactive, and it makes it hard to see what's going on
* Break down your story into a step-by-step way you get your error condition

The way it looks to me now is:

You have at least 3 references

1. A reference with a pinned key that was pinned before Zotero started. Let's call this `P1`
1. A reference with a pinned key that was pinned after Zotero started. Let's call this `P2`
1. An other reference (doesn't matter which state). Let's call this reference `O`.

Scenario:

1. Startup Zotero Standalone
2. Pin a new citekey on `P2`
2. P1 and P2 show the `extra` field verbatim
3. If you click `O` and then back to `P1`, it now shows the *soft* key in the extra field, not the pinned key
4. If you select `P2`, it correctly shows the pinned key

The rest of the scenario (starting at "Following") is a little fuzzier to me. I take it it starts with

1. Stop Zotero Standalone, start Zotero Firefox

I think. But then, on which reference did you change `extra`? And what other steps did you do?

**Comment by retorquere** [comment]
I can't reproduce it here yet. I could reproduce it with an older version of BBT (.52) but not on .55 which you are running. Can you do the scenario from https://github.com/retorquere/zotero-better-bibtex/issues/497#issuecomment-219172095 again using https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.56-circle-2447.xpi (which is .56 with a bit of extra debugging)?

There is an Infinitesimally small change that I can't reproduce because I don't have a Windows system, and ZSA is still at 4.0.29.5 on OSX. It's not likely that the difference is between .10 (which is what you have) and .5 (which is what I can run), or that the diff would be Win vs OSX though.

**Comment by EricDJohnson** [comment]
Upgraded to .56-circle-2447.

Clarification on the 3 types of references

1. `P1`: A reference with a pinned key that was created before May 13
2. `P2`: A reference with a pinned key that was created or updated on May 13 or later
3. `O`: All other reference (no pinned key)

`P1` can become `P2` by changing "bibtex: [something]" to "bibtex: [somethingElse]"

Zotero Standalone scenario

1. Stop Zotero Firefox, start Zotero Standalone
2. In the middle pane, the Extra field is shown verbatim 
  - "bibtex: [citekey]", if `P1` or `P2`
  - empty, if `O`
3. Move the cursor over a reference, scroll up/down the middle pane, or switch to a different collection and the Extra field in the middle pane changes to:
  - auto generated soft key, if `P1`or `O`
  - pinned key, if `P2`
4. Until Zotero is restarted the Extra field will _now_ show a citation key (pinned or soft), not the verbatim text
5. After the verbatim behavior is removed, clicking between references does not change the display of the Extra field in the middle pane
  - `P1` and `O` shows a soft key
  - `P2` shows a pinned key
6. If the Extra field is changed in the right-hand pane (for any reference: `P1`, `P2`, or `O`), then reference becomes type `P2` and the Extra field in the middle pane displays the correct citation key

The behavior of Zotero Firefox has changed slightly since yesterday, May 13

Zotero Firefox scenario

1. Stop Zotero Standalone, start Zotero Firefox
2. No verbatim behavior. The Extra field in the middle pane displays citation keys as 
  - an auto generated soft key, if `P1`or `O`
  - a pinned key, if `P2`
3. If the Extra field is changed in the right-hand pane (for any reference: `P1`, `P2`, or `O`), then
   - on May 14: the reference becomes of type `P2` and the Extra field in the middle pane displays the correct pinned key
  - on May 13: the reference would not become a new `P2` and the Extra field in the middle pane would not change. Instead, the middle pane would display the same information from the last instance of Zotero Standalone (an auto generated soft key, if `P1`or `O`; or a pinned key, if a `P2` created in ZSA)

Debug logs:
ZSA created `P2` today, before restart - IKQTF7RR
ZSA after restart - AEGV82QF
ZFF created `P2` today, before restart - JZ57HQPA
ZFF after restart - G4EVNZ3V

**Comment by retorquere** [comment]
Can you try the following: install https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.56-circle-2448.xpi, go into BBT preferences, Advanced, check `Re-scan`, and restart Zotero. I would expect that should resolve the problem that `P1` behaves differently from `P2`.

I'll look further into the rest, but it'd be good to have that one out of the way if we can.

**Comment by EricDJohnson** [comment]
After installing .56-circle-2448 and re-scanning, `P1` and `P2` behave the same way.
(Apologies for not digging through the documentation well enough to find the re-scan option.)

This effectively resolves the the issue for ZFF. However, ZSA still displays the verbatim "bibtex: [citekey]" text after each restart. Again, moving through the records in any way will update the middle pane to show the expected pinned or soft citation key.

**Comment by retorquere** [comment]
I'm glad you didn't, because the re-scan in 2448 has some necessary improvements. I've merged these to master, and I'll cut a new release for that once we get the remaining problem fixed. Besides, most of the stuff in the Advanced pane should only be used if you know fairly well what they do, and even I sometimes forget.

WRT to the cause of the `P1`/`P2` problem, there have been some problems around .43 that may have led BBT to fail to store a key after a change, but once that happens, the key no longer updates until you change the reference (which forces a reference scan for a pinned key). As it is said

> There are only two hard things in Computer Science: cache invalidation and naming things.

or more pithily

> There are only two hard problems in Computer-Science:  2. Exactly-once execution 1. Guaranteed order of execution 2. Exactly-once execution

The problem you hit on was me getting cache invalidation wrong. The "re-scan at start" just finds all references that have "bibtex:" in the extra field and scans them as if they just updated, touching their cache entries. Assuming the cache issues have been fixed in the .50 range, that should be the end of this problem (although I will probably add a rescan for each new release, just to be sure).

But good! One problem down. So, if I understand you correctly, the remaining problem is specific to ZSA, which is now:

* After startup, the `extra` field doesn't show the key until you deselect-select the reference

Correct?

**Comment by retorquere** [comment]
oh and BTW, there's really no sensible way you could have known that `P1`/`P2` was related to the cache being out of sync, and that a re-scan would help. It took me a while to realise myself, and I wrote the bugger. The UI tells you there's a key in the `extra` field, and you should be able to trust that that is the key in use, even if that's not technically true. It once was, but that was too slow to be usable.

**Comment by EricDJohnson** [comment]
Hahaha, that's the first time I've seen the "pithy" version!
I'm glad this is helpful in the long run.

Yes, the remaining problem is specific to ZSA. 

- After startup, the `extra` field in the middle pane will only show the key after one of the following happens:

 1. the reference is moused over or selected in the middle pane (just this one reference will display properly)
 2. scrolling the middle pane (all references display properly)
 3. a new collection is viewed (all references display properly)

**Comment by retorquere** [comment]
OK, I have that reproducible. Must be a timing issue.

**Comment by EricDJohnson** [comment]
Okay. Happy to run more tests, if needed.

**Comment by retorquere** [comment]
This week is sick busy, so I'll probably not be able to look at this before Sunday.

**Comment by EricDJohnson** [comment]
Updated to 1.6.60. This bug appears resolved.
