### ISSUE TITLE
biblatex-apa newspaper export

### ISSUE THREAD

**Issue by nbrewk** [retorquere/zotero-better-bibtex#531]
Biblatex-apa provides a "newsarticle" entry for citations from newspapers and such. In this case, the field for the publication is "newspaper" rather than "journal" or "journaltitle". Biblatex-apa changes the way pages are listed in the reference list when a citation is a newspaper, in comparison to an article. This is not reflected in Better Biblatex export of a bibliography.

**Edit 1** I missed adding an example.

Intended behaviour on export of newspaper citation:
`@Newsarticle{Wright:2013,
title     = {{P.E.I} recruits six nurse practitioners},
author    = {Theresa Wright},
newspaper = {The Charlottetown Guardian},
date      = {2013-09-13},
url       = {http://www.theguardian.pe.ca/News/Local/2013-09-13/article-3389544/P.E.I.-recruits-six-nurse-practitioners/1},
}`

Zotero exports it as:
`@article{Wright:2013,
title     = {{P.E.I} recruits six nurse practitioners},
author    = {Theresa Wright},
journaltitle = {The Charlottetown Guardian},
date      = {2013-09-13},
url       = {http://www.theguardian.pe.ca/News/Local/2013-09-13/article-3389544/P.E.I.-recruits-six-nurse-practitioners/1},
}`

... with no way for Biblatex-apa to differentiate between an article from an academic journal, and one in a published newspaper. I realize I omitted "pages" from here, but I wanted to focus on the "journal/newspaper" fields.

**Comment by retorquere** [comment]
Are there more styles that have style-specific fields and reference types?
I imagine APA won't be the only one, so I'll need to think about a more
general way to handle these.

**Comment by nickbart1980** [comment]
I like the biblatex-chicago approach, which adds `entrysubtype={newspaper}` or `entrysubtype={magazine}`. Advantage: You get a biblatex db file that still works with other biblatex styles, too. Of course for biblatex-apa you'd have to apply a bit of biber/biblatex sourcemap magic to map `@article`+`entrysubtype={newspaper}` to `@newsarticle`.

Or possibly biblatex-apa could be convinced to adopt the biblatex-chicago approach …

**Comment by mushroomman** [comment]
I'm not quite sure about styles beyond APA. I had a look at the [example bib](http://get-software.net/macros/latex/contrib/biblatex-contrib/biblatex-apa/biblatex-apa-test-references.bib) that's on the CTAN site for biblatex-apa, but I don't see any other obvious deviations except @newsarticle.

**Comment by retorquere** [comment]
So that would cover biblatex-apa, but I was wondering whether there are other styles that don't follow the biblatex-chicago approach that @nickbart1980 talks about. Before I add an option like 'export biblatex-apa for biblatex' to the prefs, I'd like to know whether there are likely more of these, as I don't want to end up with a slew of exceptions if I can help it.

For the short term, a [postscript](https://github.com/retorquere/zotero-better-bibtex/wiki/Scripting-examples) should get the job done with something like:

```
if (this.item.itemType === 'newspaperArticle' && Translator.BetterBibTeX) {
  this.referencetype = 'Newsarticle';
  if (this.has.journaltitle) {
    this.has.journaltitle.name = 'newspaper';
  }
}
```

**Comment by retorquere** [comment]
assuming fixed

**Comment by ecseymour** [comment]
The postscript did not work for me, but I was wondering whether the code could be adapted to add an entrysubtype field set to 'newspaper' on export rather than change the reference type itself. That way I can suppress fields using LaTex like [this](http://tex.stackexchange.com/questions/172444/suppress-month-and-day-for-journal-articles-and-maintain-for-a-newspaper-article?noredirect=1&lq=1)

**Comment by retorquere** [comment]
The code above won't have worked for you because it specifically checks if you're exporting BibTeX, and I assume you're exporting BibLaTeX. In your case, this should get you there:

```
if (this.item.itemType === 'newspaperArticle' && Translator.BetterBibLaTeX) {
  this.add({ entrysubtype: 'newspaper' });
}
```

If you want it both for BibTeX and BibLaTeX, simply drop the second condition

```
if (this.item.itemType === 'newspaperArticle') {
  this.add({ entrysubtype: 'newspaper' });
}
```
