### ISSUE TITLE
veryshorttitle and compound words

### ISSUE THREAD

**Issue by maxleos** [retorquere/zotero-better-bibtex#551]
Hi, I'm not sure opening an issue is the right way to go about this, as I just have a question concerning syntax - so please just ignore this if you are too busy. 

The issue is the following: I am using Zotero Standalone with your BetterBibTex to manage my bibliography. I have BetterBibTex automatically generate citation keys, and would like them to be in the format: _author_first-word-of-title_year_. 

This was how BetterBibTex behaved previous to an update in the beginning of the year (I think), and many of my citation keys are formatted that way.

So far I have specified the citation key format as  [auth:lower]\_[veryshorttitle]\_[year] in the Zotero->BetterBibTex preferences following the advice given <a href="http://help.jabref.org/en/BibtexKeyPatterns">here</a>, which works fine in most cases.

However, for titles that begin with a hyphenated word, the automatic key generation skips the first element of the word and generates a key based on the second element. 

So a reference like 
_Author, Between-group competition, 2010_ 
generates the key: 
_author\_group\_2010_.

Instead, I would like to have a key generated that concatenates the two elements of the hyphenated word, i.e. 
_author\_betweengroup\_2010_.

Could you let me know which BetterBibTex/Jabref key-formatting command will achieve this?

**Comment by retorquere** [comment]
Looks like I deviated from what JabRef did in any case, which generates `author_group_2010`.

It's not hard to revert to the earlier behavior (which unfortunately did sometimes include odd punctuation characters), but I want to spend a little time thinking about what's the good route here.

**Comment by retorquere** [comment]
I'm just going to go back to the previous behavior. New release will probably be before the weekend somewhere.

**Comment by maxleos** [comment]
Sounds good, looking forward to it.

**Comment by retorquere** [comment]
Can you right-click that reference, select "Send Better BibTeX error", and post the red debug ID here? That will give me a reference to test, I have a fix lined up.

**Comment by retorquere** [comment]
Also, can you give https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.75-circle-2894.xpi a spin?

**Comment by retorquere** [comment]
Still interested?

**Comment by maxleos** [comment]
In order to continue writing, I manually changed my citation keys to reflect the the format [auth:lower]_[veryshorttitle]_[year]. That format wasn't very far from your original format, so it required only a few changes and now works fine.

This also means that I don't really have any error codes to report. I have sent you a report of a reference that previously had caused problems (because of the -'s- in the first word of the title). The reference is WATDWZ36.

**Comment by retorquere** [comment]
You currently have the citekey pattern set to `[zotero]`, which won't use the new word splitter (it mimics Zotero exactly, warts and all), but I could just change that to `[auth:lower]_[veryshorttitle]_[year]` to test for your initial request. But there is no reference with `Between-group` in WATDWZ36. I need to have a test case so I know what I'm aiming for.

**Comment by maxleos** [comment]
I'm not quite sure if this helps, but I have sent you an error report (NXTHGDTT) that contains a reference with 'between-group', and another one (SBWDR88B), where the reference 'Author, The co-evolution, 2003' results in the key 'author_co_2003'. In this case, a better key would be 'author_coevolution_2003'.

**Comment by retorquere** [comment]
For those two references, I now get `puurtinen_betweengroup_2009` and `bowles_coevolution_2003`. Can you try https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.75-circle-2942.xpi?

**Comment by maxleos** [comment]
With the version you sent me, I get **puurtinen_between-group_2009** and **parijs_co-evolution_2003**. Note the hyphens, which might better be avoided, and the editor instead of the author (parijs instead of bowles). 
Also, apostrophe s ('s) is merged with the word, while it would better be omitted; e.g. Bauer et al. _War's enduring effect_  results in the key **bauer_wars_2014**.
What's more, when the first word of a title is followed by a colon (:), this is included in the key - but that key would be nicer without; e.g. Sumner 1906 Folkways: a study of the... receives the key **sumner_folkways:_1906**, whereas **sumner_folkways_1906** would be nicer.

**Comment by retorquere** [comment]
What pattern do you use to generate these? The references you submitted in `SBWDR88B` and  `NXTHGDTT` had `[auth:lower]_[veryshorttitle:lower:fold]_[year]` (your current BBT settings are sent along with the reference), and with that they generate keys `puurtinen_betweengroup_2009` and `bowles_coevolution_2003`.

**Comment by retorquere** [comment]
also, can you submit the other references (Bauer et al. War's enduring effect/Folkways: a study of the...) through the error reporting mechanism, I'll add them to the test set.

**Comment by retorquere** [comment]
You aren't using the `[zotero]` pattern for this, are you? If I use the `[zotero]` pattern I get `puurtinen_between-group_2009` and `parijs_co-evolution_2003`, but that's by design. The `[zotero]` pattern replicates the key generation from the standard Zotero Bib(La)TeX exporters, including all their problems. It's really only there so people who have articles written using the default Zotero BibTeX support to move over easily, but the key generator has so many problems I don't generally recommend to keep using it. To be clear, I can't change the behavior of `[zotero]` because it's explicit purpose is to behave exactly as Zotero does. If you want sensible keys, use something like `[auth:lower]_[veryshorttitle:lower:fold]_[year]`.

Still interested in the other two references for testing.

**Comment by maxleos** [comment]
I just clicked on the link () you gave me above, installed the firefox add-on, and then had a look which references were generated. I also use Zotero standalone, which uses the Zotero settings for key generation, and it gives me **bowles_co_2003** as a key for the Bowles reference, not parijs. 
You find the references at UZBEJDU7 and X9DI96D8.

**Comment by retorquere** [comment]
I'm not sure what ***the Zotero settings for key generation*** unpacks to, as Zotero doesn't have configurable key generation, but if I export those references using `BibTeX` (so no BBT involvement whatsoever) rather than `Better BibTeX`, I get `puurtinen_between-group_2009` and `parijs_co-evolution_2003`. It is these values that the `[zotero]` patterns aims to replicate. This is by design and will not change.

From my end it looks like `bowles_co_2003` was generated using BBT (the stock Zotero BibTeX exporter wouldn't generate this from your reference), but I don't know with what pattern. Certainly not `[auth:lower]_[veryshorttitle:lower:fold]_[year]`. It looks like `edtr` made its way into your pattern, but that pattern is not what was sent along with the references you submitted. Can you look in the BBT preferences what the pattern is in the installation where you generated `bowles_co_2003`?

UZBEJDU7 and X9DI96D8 were generated on an installation that had the `[zotero]` pattern BTW. With `[auth:lower]_[veryshorttitle:lower:fold]_[year]` they generate keys `sumner_folkways_1906` and `bauer_war_2014` for me. With `[zotero]` they generate `sumner_folkways:_1906` and `bauer_wars_2014`, but this is *by design*. If you don't want the keys that Zotero would otherwise generate, you must use a different pattern.

Could you please try installing [this version](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.75-circle-2971.xpi), make sure to restart Firefox or Standalone, whichever is in use (OSX has a habit of keeping programs running -- you need to have fully quit and restarted Zotero to effectuate an installation of an extension), check what pattern is in use, and then check what references you get.

**Comment by retorquere** [comment]
To make sure, you say you use Zotero standalone, you  also installed these test versions of BBT in standalone right?

**Comment by retorquere** [comment]
I'd prefer to get this into the release I'm about to cut, so your feedback would be very valuable.

**Comment by maxleos** [comment]
I installed version zotero-better-bibtex-1.6.75-circle-2971.xpi in both Zotero and Zotero Standalone. The citation key style defaults to the scheme '[zotero]', which gives me  sumner_folkways:_1906 and parijs_co-evolution_2003 (I shared the reports with you at GFH49PX9 and KMCVZPIU). I'm not entirely sure what we're trying to achieve, though - are you defining a [better biblatex] citation key format that would replace the [zotero] one?

**Comment by retorquere** [comment]
I'm not specifically trying to achieve anything -  you said you wanted words separated by a dash to be used as a single word in key generation, I've made changes that I think accomplish this,  and I'm trying to find out whether it works to your satisfaction. 

To find this out, I need to know which pattern *you* want to use. I'm not looking to create a specific `[better biblatex]` formatter (no idea what it'd do, or what'd be useful for), nor am I looking to replace the `[zotero]` pattern (which does exactly what it's supposed to do even if I would not recommend its use). 

You said you previously got `coauthor` when the input had `co-author` in your reference, but that you now get `co-author`. I need to know which pattern you use that has seen this change. It is *not* `[zotero]` because that has *never* generated `coauthor` for this input, nor will it be changed to do so, because it's supposed to give `co-author` as it's output. 

The change I've made in response to this request is that words like `co-author` will be treated like single words in pattern parts like `title`,  `shorttitle` and `veryshorttitle`, but if you're not using any of those you obviously won't see that change. In your initial request you said you were using `[auth:lower]_[veryshorttitle]_[year]`, but that's not in any reference report you've sent me so far. 

Also please keep to one client (either zotero Firefox or zotero standalone) while after trying to figure this out. They usually don't share settings so switching between the two is just going to cause confusion. Please also don't have the two running at the same time with both bbt installed, bbt doesn't work well in that mode

**Comment by maxleos** [comment]
Sorry if I sounded offensive. I'm just a little confused here. So I guess what happens is that Zotero changed the way it generates citation key formats at some point (including the colon for titles ending on ':' in the citation key, for instance), which  broke the links in my documents. 

I thought that the citation key format was set by better bibtex, as it's tweaked it under that menu point. So I asked you if you could help me get back to the old behaviour e.g. **bornstein_betweengroup_2003** instead of **bornstein_group_2003** (my first post).

But now I understand that you never changed the way that citation keys are generated - is this correct?

**Comment by maxleos** [comment]
Sorry if I sounded offensive. I'm just a little confused here. So I guess what happens is that Zotero changed the way it generates citation key formats at some point (including the colon for titles ending on ':' in the citation key, for instance), which  broke the links in my documents. 

I thought that the citation key format was set by better bibtex, as it's tweaked it under that menu point. So I asked you if you could help me get back to the old behaviour e.g. **bornstein_betweengroup_2003** instead of **bornstein_group_2003** (my first post).

But now I understand that you never changed the way that citation keys are generated - is this correct?

**Comment by retorquere** [comment]
I'm likewise confused. Zotero hasn't changed the key-generation algorithm ever as far as I know. This is the algorithm used by the `BibTeX` and `BibLaTeX` exporters that come with Zotero. There's nothing configurable about this. This key-generation algorithm is fixed, I consider the keys it generates flawed, and it's not deterministic (if you have duplicate keys, whether a key gets a postfix (and if it does, which) differs depending on which combination of references you export. 

Better BibTeX has a way better key generator, but it *is* possible to have it generate bad keys - one of which (afaic) is to use `[zotero]` as your pattern, and thereby requesting the flawed algorithm. The sole reason this inadvisable pattern is the default is that if you come from using the standard BibTeX export, you will get the same keys you're used to, just vastly better BibTeX. 

But I recommend changing that default as soon as you can. `[auth:lower]_[veryshorttitle]_[year]` gets you close to the standard Zotero key generator while avoiding some of the problems (and coming with vastly improved BibTeX over the standard exporter). I think if you set that pattern, and then export with `Better  BibTeX` (and *not* `BibTeX`, which is the translator that comes with Zotero), you'll get what you want. If under those conditions you don't get the keys you want, I'd live to hear about it.

**Comment by maxleos** [comment]
I think I understand a bit better. Let me also just restate my issue.

For a reference like: Bornstein, Gary, and Zohar Gilula. 2003. ‘Between-Group Communication and Conflict Resolution in Assurance and Chicken Games’. _Journal of Conflict Resolution_ 47 (3): 326–39 the different citation key formats we have been mentioning generate the following keys:

- [zotero] gives me: **bornstein_between-group_2003**
- [auth:lower]\_[veryshorttitle]_[year] gives me: **bornstein_Group_2003**
- [auth:lower]\_[veryshorttitle:lower:fold]\_\[year] (which I had adopted before contacting you) gives me: **bornstein_group_2003**
- but my preferred key would be: **bornstein_betweengroup_2003**

Really the thing I was after was the syntax for the citation-key generator that would give me that last key format.

**Comment by retorquere** [comment]
The `:fold` is superfluous, as `veryshorttitle` is alway folded, but I don't know where `bornstein` comes form as it's not in any of the references you sent. With `[auth:lower]_[veryshorttitle:lower:fold]_[year]` I get `puurtinen_betweengroup_2009` (the only reference you sent that has "between-group") and `bowles_coevolution_2003` (the only reference you sent that has "2003").

Did you change the reference after installing the test version? BBT won't change the citation key until you change the reference. You can force a key update by right-clicking the reference and selecting "clear BibTeX key".

**Comment by retorquere** [comment]
No hold on, that isn't right -- changing the pattern will change all non-fixed citation keys. So just changing the pattern from `[zotero]` to `[auth:lower]_[veryshorttitle:lower:fold]_[year]` should do the trick. When I import [this](https://scholar.google.nl/scholar?hl=en&q=Bornstein%2C+Gary%2C+and+Zohar+Gilula.+2003.+%E2%80%98Between-Group+Communication+and+Conflict+Resolution+in+Assurance+and+Chicken+Games%E2%80%99.+Journal+of+Conflict+Resolution&btnG=&as_sdt=1%2C5&as_sdtp=) reference though, using `[auth:lower]_[veryshorttitle:lower:fold]_[year]`, I get `bornstein_betweengroup_2003`.

The citation key displayed doesn't always update immediately in the Zotero display, but in an export it should immediately take effect. If it's in the Zotero interface that the key doesn't update, try selecting any other reference are re-selecting Bornstein -- the key should show the updated version.

**Comment by maxleos** [comment]
Interesting, in my zotero, no matter what I do, the reference remains  `bornstein_group_2003`. I use (and have been using) exactly the citation format you use: `[auth:lower]_[veryshorttitle:lower:fold]_[year]`

It must somehow been screwed up - maybe zotero interacts in funny ways with jabref, bibdesk or some other programme? I'm inclined to leave this issue as it is, though, as the problem seems pretty intractable, but not very consequential (esp. since I've already changed most of the citation keys in my documents anyway). What do you think?

**Comment by retorquere** [comment]
I'd still love to get to the bottom of this. [This build](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.75-circle-3008.xpi) has specific logging in the `veryshorttitle` generator -- could you

* install it and restart Zotero
* enable extended debugging in the BBT prefs
* change the bornstein reference<sup>1</sup>
* right-click the bornstein reference and select "send better bibtex error"
* paste the debug ID here

That will tell me what goes into the `veryshorttitle` formatter and what it thinks the words are it gets to choose from.

<sup>1</sup> and back if you wish -- it doesn't matter what change it is, as long as it changes. Adding a character to the `extra` field and clicking away from the reference will do.

**Comment by retorquere** [comment]
One thing that consistently puzzles me is that in the debug reports you submit (like `KMCVZPIU` and `GFH49PX9`) you consistently have the `[zotero]` pattern set. The debug build I posted above won't help in this case as the `veryshorttitle` won't get called. I know that in a clean install the pattern will default to `[zotero]` -- please change it to `[auth:lower]_[veryshorttitle:lower:fold]_[year]` before step 3.

**Comment by maxleos** [comment]
I installed the version you sent me. However, it does not let me set the citation key pattern. The box is red and whenever I change it, it reverts back to `[zotero]`. I also changed the ref, but now I got the zotero pattern. I sent you the extended report at 2NPIRX2M.

**Comment by retorquere** [comment]
Just noticed the red box, you beat me to it; here's a new version: https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.75-circle-3010.xpi

**Comment by retorquere** [comment]
(I'll need a new report because the version you have forced `[zotero]` to be in effect.

**Comment by maxleos** [comment]
Aha, look at this! No error to be reported here: HJZ2CFWC

**Comment by maxleos** [comment]
And it also improved the key generation for refs 8JH3SQTP and WF58RA2C .

On a different note: when reporting BetterBibTex errors, I always have to: `'right-click on ref' -> Report better BibTex errors... -> Continue -> Go Back -> Continue`
in order to obtain the error code. That is, the reporter only works with going back-and-forth once.

**Comment by retorquere** [comment]
The improvement is mysterious because I only added logging. Superb, more ghost errors. `HJZ2CFWC` showed `veryshorttitle` working as it should, so it must be one if its callers. I've added more logging to [this](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.75-circle-3011.xpi) version, could you try again with that?

When you say "improvement", what does that mean? Remember I can't replicate the problem on my end, so I can't see what changed for you.

Same goes for the error reporting. I don't see that happening here, I can just click through and submit, no going back and forth.

Can you try disabling all Firefox extensions except Zotero & BBT, and try again (both the key generation and the error report)? It doesn't happen too often (anymore), but it *is* possible that another extension is interfering.

**Comment by maxleos** [comment]
I turned off all the add-ons, and turned them on one-by-one, sending an error report each time. 
No problems for most of the time (i.e. the report was sent straight away), but then I turned on the [keybinder](https://addons.mozilla.org/en-US/firefox/addon/keybinder/) add-on, which seems to have caused this problem.

**Comment by maxleos** [comment]
I turned off all the add-ons, and turned them on one-by-one, sending an error report each time. 
No problems for most of the time (i.e. the report was sent straight away), but then I turned on the [keybinder](https://addons.mozilla.org/en-US/firefox/addon/keybinder/) add-on, which seems to have caused this problem.

**Comment by retorquere** [comment]
I can reproduce the keybinder issue, but it's a different problem than generating the right citation key. Please leave it disabled for now.

I've looked at a few of the errors logs, but the ones I tried don't have the "between-groups" reference. Can you try changing that reference, submit a new report, and post its ID here?

**Comment by maxleos** [comment]
I have submitted the 'between-group' reference at `ZH5AXJKT`. Just to repeat, the idea would be that hyphenated words like 'between-group' would be concatenated when generating the citation key, i.e. a reference like

Author, Between-group competition, 2010

would get the key `author_betweengroup_2010` rather than `author_group_2010`.

**Comment by retorquere** [comment]
`ZH5AXJKT` was submitted with 1.6.75, not [1.6.75-circle-3011](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.75-circle-3011.xpi), so I can't tell what's going on.

**Comment by retorquere** [comment]
plus we already know 1.6.75 doesn't exhibit the behavior you want, I'm trying to get confirmation on a pre-release which does so I can merge that into the upcoming release.

**Comment by maxleos** [comment]
Ok, sorry, I don't know why the old version was installed. The new version `1.6.75-circle-3011` actually does generate the key in the format `author_betweengroup_2010` as you can see here: `SGE5UB7X`. Looks good!

**Comment by retorquere** [comment]
Could I bother you for one more round? Changes have been made to master between 3011 and now, [this](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.75-circle-3091.xpi) is #551 + those changes -- all tests run green, but it'd be great to have confirmation before I merge this & release.

**Comment by maxleos** [comment]
Cirle-3091 does not work for me (it doesn't generate any key at all), as it seems to conflict with Zotfile, which I'm also using.
I followed your instructions and installed Zotfile version 4.2.6, but without success.
```
Better BibTeX has been disabled because it has detected conflicting extension "ZotFile" 4.2.5 or
earlier. After upgrading to 4.2.6, Better BibTeX will start up as usual. A pre-release of ZotFile 4.2.6 can be
found at

https://addons.mozilla.org/en-US/firefox/addon/zotfile/versions/
```

**Comment by retorquere** [comment]
Can you enable extended debugging in BBT, install [this](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.75-circle-3094.xpi) (and restart) and submit a new debug log? There's another user that's experiencing this (#574) with Zotfile, but I haven't yet been able to reproduce the problem here. This build will explicitly report what version of Zotfile it thinks is installed.

**Comment by maxleos** [comment]
I couldn't go straight to the reporting page, because BBT was disabled...
So I installed the , and submitted a report (`98CBUH3T`), then installed the version you sent me, but couldn't send another report because 
`Better BibTeX has been disabled because it has detected conflicting extension "ZotFile" true.
After upgrading to ZotFile to 4.2.6, Better BibTeX will start up as usual.`

**Comment by retorquere** [comment]
Right, that was stoopid of me, of course you can't submit a debug report when BBT is disabled.

After restart, can you type `zotero://debug` in the address line, and look for errors (they'll be at the top) or lines containing `Addon:` (BBT's addon detection) and post those here?

*smacks forehead* I think I have it (the `true` in the message gave it away). Try [this](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.75-circle-3095.xpi).

**Comment by maxleos** [comment]
Typing zotero://debug resulted in a white screen, but I the 'real-time debug output' instructions [here](https://www.zotero.org/support/debug_output), and got a lot of output, which I included in the .txt file below. Lots of mentioning of BBT there, so I wasn't sure what to select.

[zotero_debug.txt](https://github.com/retorquere/zotero-better-bibtex/files/532849/zotero_debug.txt)

**Comment by maxleos** [comment]
The new version seems to work, though! Just for fun, I submitted an error report with my standard betweengroup reference to `7EPTPF22`.

**Comment by retorquere** [comment]
And this is with ZotFile installed -- super. I'm hoping to get confirmation on #547, and then I'll merge & release.

**Comment by retorquere** [comment]
Now there's still the head-scratcher why I didn't have the same problem on my end. But that's not a release-blocker.

**Comment by retorquere** [comment]
(oh and the white screen is because `zotero://debug` only does something when extended debugging is on -- but the real-time debug output is even richer than that, so super thanks for getting me that)

**Comment by maxleos** [comment]
Thank you for your hard and persistent work. I'm looking forward to using the new release.

**Comment by retorquere** [comment]
Tests are running, when they go green (and they should) I'm cutting a new release.
