### ISSUE TITLE
More flexible citation key patterns

### ISSUE THREAD

**Issue by dgerber** [retorquere/zotero-better-bibtex#552]
Hi, I'm unable to port a renaming pattern from zotfile, which should look like this:

 ```
[authors3+initials | WebsiteTitle | BlogTitle]_[year]_[title]
```

Problems are:
1. the `|` (OR) operator does work inside a pattern
2. some patterns described in the doc seem not to be implemented: `[authEtAl]`, `[authors3+initials]`.

Zotfile has a nicely extensible syntax, so one solution would be to delegate to a `[zotfile]` pattern (the reverse from `{%b}`).

**Comment by retorquere** [comment]
Fully untested: https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.72-circle-2804.xpi tries to pick up the Zotfile name for `[zotfile]`.

**Comment by dgerber** [comment]
That build returns only blanks for keys. Just a guess: isn't a `@` missing in `Zotero.Items.get(@item.itemID)`?

**Comment by retorquere** [comment]
Oops: https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.72-circle-2805.xpi

**Comment by dgerber** [comment]
It gives an infinite recursion... `ZotFile.wildcardTable` is called wether `{%b}` or `[zotfile]` are used or not. Maybe BBT could check patterns before monkey-patching?

**Comment by retorquere** [comment]
The patterns are not available before I monkey-patch it. Not entirely sure how it could loop because of it though -- the monkey-patching only happens on BBT init. It shouldn't matter how often wildcardTable is called, but I have no idea how the Zotfile filename formatter expects to be called or what context it expects.

I don't think I'm going to do this. Too fragile. if @jlegewie is interested, I'm willing to work with him on a PR, but as is, it's too risky.

**Comment by dgerber** [comment]
In the meantime, I found an acceptable solution with the (undocumented?) `[>0]` pattern.
BTW thanks to both of you for your work!

**Comment by retorquere** [comment]
Updated the wiki for the `>0` pattern.

**Comment by dgerber** [comment]
Actually, zotfile's syntax turns out to be a lot more manageable, especially for different document types. Would you consider an explicit preference in BBT to switch zotfile's monkey-patching on and off? A nice side-effect is that it would document the origin of that `%b`in zotfile -- I had a pattern with that name and it took some time to find out where it was overriden.

**Comment by retorquere** [comment]
is `%b` a legitimate pattern key in zotfile? Then I shouldn't be overriding it, full-stop. I thought it was unused. In any case, I'll add the preference.

Again, if the zotfile author makes available a method I can safely call to turn an item into a string according to its patterns, I'm open to doing that.

**Comment by retorquere** [comment]
(same goes for zotfile just calling into BBT rather than me monkey-patching it. This actually has my preference)

**Comment by dgerber** [comment]
> is %b a legitimate pattern key in zotfile?
Yes, there are [user-defined wildcards](http://zotfile.com/index.html#renaming-rules).

Now `[zotfile]` works as expected, if not monkey-patching. Are you going to merge branche 552 into master?

**Comment by retorquere** [comment]
I will.

I've added another safeguard -- even if the option is enabled (which it is by default so as not to disrupt existing behavior), if BBT finds that `%b` is already set, it won't overwrite it with the citation key.

**Comment by dgerber** [comment]
Oups, I meant to ask about the `[zotfile]` feature! It was only in the build linked above, now removed, so I lost it completely with the latest release...

**Comment by retorquere** [comment]
It is indeed gone; I couldn't get it to work reliably (the infinite recursion). If ZotFile makes available a method I can call safely, I'll be happy to bring it back.

**Comment by dgerber** [comment]
That's too bad, because it did work as long as both cross-patterns are not (accidentally) activated simultaneously.

@jlegewie, would you consider a patch to zotfile so that it does not greedily evaluate (unused) patterns?

Otherwise, what about a safety check when setting either preference in BBT -- "please uncheck the `%b` option and restart before using `[zotfile]`"?

**Comment by retorquere** [comment]
If we're going to work on this I'd *much* prefer not to have to patch in `%b` at all (I shouldn't have back then, but I was totally infatuated with monkey-patching at the time). It's easy and safe to get a citation key from BBT by calling `Zotero.BetterBibTeX.keymanager.get(item).citekey` -- I'd much prefer it if ZotFile would call that (should @jlegewie be interested) rather than me monkey-patching the behavior in, and if @jlegewie is not interested, I will most likely just deprecate the `%b` monkey patch now that I know it may interfere with existing behavior from ZotFile. Even with my detection it would still mean the behavior of `%b` is unpredictable.

BBT using the ZotFile generator would follow the same pattern. If there's a safe method I can call whenever I want given an item or an itemID, I'll happily plug that into the `[zotfile]` pattern.

**Comment by jlegewie** [comment]
I am generally open but a) don't have to time to look at it and b) still don't really get the details. Looks like to two different things to me. 1) not sure about the first. 2) Are you proposing that I add a wildcard to zotfile that is the bibtex key from `Zotero.BetterBibTeX.keymanager.get(item).citekey`? 

In any case, if someone wants to send a pull request, please use the 5.0 branch.

**Comment by retorquere** [comment]
They are indeed two different issues.

One is Zotfile calling into BBT, in case Zotfile would want access to the BBT citation key (which is what I monkey-patched in, and which I want to get rid of)

The other is BBT calling into ZotFile to get the name generated for a file so @dgerber and others could use that in constructing a citekey.

The unresolved matter is how to prevent infinite recursion in a case where the BBT pattern is `[zotfile]` and the zotfile pattern has something like `%b`. I really don't know yet how to make sure that doesn't happen.

BBT is also not 5.0-ready as of yet, so this'd be a mid-term thing anyhow.

**Comment by jlegewie** [comment]
The first thing should be super easy. I think adding a line to `addFields` here https://github.com/jlegewie/zotfile/blob/5.0/chrome/content/zotfile/wildcards.js#L208
should do it (of course, with some checking whether better bibtex is installed). 

No idea about the second. But I am open if someone wants to get into it. 

Different questions: Did you do this https://groups.google.com/forum/#!topic/zotero-dev/sO3DtOmKUxA ?

**Comment by retorquere** [comment]
Detecting BBT is simple enough -- if `Zotero.BetterBibTeX` is defined, it's installed.

I tried doing 2, but that resulted in an infinite recursion -- but probably because the ZotFile pattern had `%b`. I don't yet have a plan for how to detect that, and until then, I'd say this feature would be too dangerous to release.

Current BBT will indeed disable itself if it detects 5.0. getting BBT ready for 5.0 will be a major overhaul or perhaps even a full rewrite, and I'm strapped for time right now, so BBT will be late to the 5.0 party.

**Comment by jlegewie** [comment]
Yeah, zotfile wildcards have become messy over time. I wish I could change them all in a more systematic way.

Can you point me to a pull request for the disabling?

**Comment by retorquere** [comment]
I don't understand what you mean with "a pull request for the disabling", can you elaborate?

**Comment by jlegewie** [comment]
I was going to say a commit. But I already found it: https://github.com/retorquere/zotero-better-bibtex/commit/45a691dd3bd32439c2b551004d87a4ed8771d90d
Thanks!
