### ISSUE TITLE
Financial support for BetterBibTex

### ISSUE THREAD

**Issue by mijalce** [retorquere/zotero-better-bibtex#556]
I am using BetterBibTex for a longer period of time. I want to say that I am very satisfied, not only with what BBT is doing, but also how the requests for new features, bugs solving and improvements are handled. In my opinion BBT is becoming a very stable and big solution that strongly enhances Zotero. 
As a result of this I would suggest (and open it for a discussion) that BBT introduces some form of a financial support to the development of the solution. I do not suggest that the solution should be made only paid. However, I think that there should be given an option if somebody wants to "buy a coffee" to the developer to be able to that.  This could be done for example with donations of 3, 7 or 10 dollars/euro.

**Comment by retorquere** [comment]
That's incredibly thoughtful, but really not necessary. Someone anonymous did once before donate $5 through codewake somewhere in June, and I'm still waiting for Codewake to get off its behind and tell me who my benefactor was, or to release the money to me.

Without for a second wanting to come off as ungrateful, the trickle amounts that would come in through something like codewake would not really constitute financial support for BBT as much as they would constitute moral support. Moral support is **hugely appreciated**. The fact that you opened this issue is a great boost to my day. One of my users sent me a postcard and a bunch of stickers for my daughter, and that was wonderful. The fridge magnets are still up, and the postcard is stuck to her bed. Such keepsakes are a much more permanent reminder that what I'm doing is worthwhile; I'd honestly be more happy with such a postcard.

If you're in the humanities or biology or anything plausibly nature-related, my daughter would be stoked to hear about what you're doing, so a postcard addressed to her (in simple terms, she's 8. This is a great opportunity to explain your area of interest in a way that could contribute to [this hilarious reddit thread](https://www.reddit.com/r/AskReddit/comments/3hw3vu/phds_of_reddit_what_is_a_dumbed_down_summary_of/)) would make her day. If you're in a STEM field, my son (17, no simple terms required, he's very bright) would be super interested. In either case you'd be establishing my credentials as super-dad; no-one in their respective class at school will have dads receiving postcards from strangers around the world.

Another option would be a cheap secondhand book (don't buy new, new books are a ripoff, always use bookfinder.com) from your own area of interest. A book from your own area of interest, even if just a beat-up textbook for freshman classes (seriously, don't buy new textbooks. such a ripoff), gives me a nice idea of what people are using BBT for that I can put in my bookcase.

**Comment by reidpr** [comment]
How would one go about sending physical objects like these? I looked around briefly for a mailing address but didn't find one, which seems sensible to keep off the public internet, but clearly it can be done.

**Comment by retorquere** [comment]
Sending physical objects is a pretty arcane practice in this day and age, for sure, but I think in most locales it involves postage stamps and post boxes 😄 . 

My daughter's name is Alexandra<sup>1</sup>, my son's name is Leo<sup>2</sup>, and we live at

Deurnestraat 127
6843PP Arnhem
the Netherlands

Our address would be publicly available to any bad guys through online phonebooks<sup>5</sup>, so I reckon there's little additional risk in putting it up here.

---

<sup>1</sup> Alexandra's fav animal right now is dolphins, fav color is blue, loves to dance. She's very social, so a postcard showing where you're from or what you do would also be very exciting to her. Bouncy girly-girl if ever you've seen one, but will have no issue putting you in a headlock if you are nasty.
<sup>2</sup> Leo should be able to grok pretty much anything a undergrad in natural sciences would, he's in senior high<sup>3</sup> but is doing prep classes at undergrad level. Feel free to challenge him, he's getting a little cocky. Deeply into CS:GO and Overwatch. Will probably be blasé about getting a postcard<sup>4</sup> but secretly excited.
<sup>3</sup> well *technically* he's doing VWO, but I've tried to translate this to the American model. Which is nuts, BTW. Why so complicated people? And why is the Netherlands trying to emulate this system? Oy vey.
<sup>4</sup> at 17 you're not supposed to be impressed by stuff adults do I think, and certainly not when it happens offline
<sup>5</sup> we have another relic from the past: a land-line. For those under 20, that's a phone that only works when you're in your own home, sometimes even permanently tethered to a wall! Does *only* phone calls; no texts, no whatsapp, no snapchat. I know, crazy right?

**Comment by BenjaminHCCarr** [comment]
I tried sending beer, he request book. Apparently book went over well. I (gasp) bought new, as the one I wanted to send wasn't available in local stores or EU/UK online. Be prepared for slow overseas shipping, and stupid rates for transport :)

But yes @retorquere makes amazing products that HUGELY expand Zotero.

**Comment by retorquere** [comment]
Aw, that's nice! Didn't mean to appear ingrateful! It's actually your postcard and magnets that are still up<sup>1</sup> -- maybe you did have some effect because she has expanded her horizons from dolphin-trainer to dolphin-or-sea-lions-trainer.  Or maybe the sea-lion show we went to had some influence.

While I really do appreciate books (I *love* books), it's not intended as a way to get books into my hands I would/could not otherwise afford myself. But yeah, on bookfinder.com (one of my fav sites), shipping rates are often more than the book price... but that can still come to a whopping $5 for some very interesting books.

(IOW thanks @BenjaminHCCarr -- I generally have a hard time accepting praise, gifts or compliments. I don't mean to minimize anything.)

-----
<sup>1</sup> and don't think I didn't notice the shipping cost on that package! Jeez!

**Comment by retorquere** [comment]
(when it comes to books, I pointed to peoples' own area of interest because 1) they could have such a beat-up book just gathering dust, or they'd be easier to find, and 2) I have some fairly esoteric interests, and those can be hard to find/expensive)

**Comment by BenjaminHCCarr** [comment]
Would son be interested in my first edition OReilly "Running a Weblog using Slash"
:)  j/k

and you have helped the community so much it is well worth it. Glad the magnets are up!

We need to move her beyond dolphins but:

[Researchers record dolphin 'conversation' revealing possible spoken language](http://phys.org/news/2016-09-dolphin-conversation-revealing-spoken-language.html)
[http://phys.org/news/2016-09-dolphin-conversation-revealing-spoken-language.html](http://phys.org/news/2016-09-dolphin-conversation-revealing-spoken-language.html)

**Comment by BenjaminHCCarr** [comment]
Oh, and for people looking for gifts, books, etc,
Amazon now has [Amazon Warehouse in the US](https://www.amazon.com/s?me=A2L77EE7U53NWQ):
[https://www.amazon.com/s?me=A2L77EE7U53NWQ](https://www.amazon.com/s?me=A2L77EE7U53NWQ)

Things listed as "Used" but might have torn cellophane or dented box. I have had 100% success with them. Kids toys, books, cables, switches, and actually about 70% on a treadmill!!!!

Don't know if other markets have that, but we love it.

**Comment by retorquere** [comment]
Wow, old-school-cool. No, he won't even know what Slash (or /. for that matter) is, but that's some geek lore right there. I remember /. (and the geek fun of saying age-tee-tee-pee-colon-slash-slash-slash-dot-dot-org) before digg and then reddit ate it's breakfast, lunch and dinner. But my son is hard to peg down on matters technical -- in some ways very interested in technology, but can't be bothered to flash a custom ROM to his phone, or even upgrade when the OTA rolls in (if it ever does -- OnePlus has a shaky track record here) -- me, I select my phones based on whether there's a ROM community around it. I guess he's more science-oriented than technology-oriented, but he's also very much the applied guy. Always sort of figured he'd go for theoretical physics or crypto, but he's leaning strongly towards computer science/software engineering.

But if that boek is from your field of expertise, then a) I pity you if it is still, and b) it would qualify as interesting memorabilia ("you wouldn't *believe* what one of my users does!"). On my end, I have a copy of "Creating Applications with Mozilla", which is a surprisingly unhelpful book given what I do here (so much has changed, and Mozilla is dead-set on killing off XUL for reasons reasonably good and incredibly bad).

Also: holy crap, Douglas Adams was onto something. We need to have mars colonized before they start thanking us for the fish. Would this call for a biologist or an anthropologist?
