### ISSUE TITLE
Automatic Update doesnt happen in Mac OSX 10.10

### ISSUE THREAD

**Issue by rambalachandran** [retorquere/zotero-better-bibtex#557]
Hello,

I installed better-bibtex in Firefox and I changed the preferences to make Better BibTeX to be the default export format and set the Autoexport option under Better BibTeX to change. I then exported the Zotero library to a file called ZoteroRef.bib. After this I added a new reference to Zotero, but I dont see the bib file getting updated with the newly added reference. It will be of great help if you can tell me what is causing the issue

**Comment by retorquere** [comment]
Enable extended debugging in the BBT prefs, change a reference again, and submit a debug log by choosing "Report Better BibTeX error". If you post the debug ID (in red) here, I can investigate.

**Comment by rambalachandran** [comment]
Thank you. I did as you prescribed and the Report ID is **WBH6MZFD**

**Comment by retorquere** [comment]
From what I can tell from the logs, no auto-export is configured. Do you see one in the preferences?

**Comment by rambalachandran** [comment]
This is how my Better BibTeX option looks like
![screen shot 2016-08-31 at 6 31 36 pm](https://cloud.githubusercontent.com/assets/6717520/18148709/5f710c2c-6fa9-11e6-9598-aa7117feb3d3.png)

**Comment by retorquere** [comment]
That means you have no auto-export set up. Export again, and make sure you
tick the "keep updated" checkbox.

**Comment by rambalachandran** [comment]
I did this and now I have the particualar export showing up in the Auto export dialog box in Better BibTeX preferences. But after exporting, I added a new reference and changed the tags, but the bibtex file doesnt seem to get updated and the timestamp as observed in `ls -lrt` remains the same as  originally created time.

**Comment by retorquere** [comment]
Can you enable advanced debugging (if it's not still on), change a
reference, and then get me a new debug ID?

**Comment by retorquere** [comment]
Are you still experiencing this problem?

**Comment by retorquere** [comment]
Assuming this is no longer an issue; if it re-occurs, feel free to re-open.

**Comment by BenjaminHCCarr** [comment]
@retorquere didn't I have to rev from xpi due to a non-auto update on 10.10 about two months ago?

**Comment by retorquere** [comment]
I don't readily recall -- do you have anything I could search on?

**Comment by BenjaminHCCarr** [comment]
It's not in our emails, and not in the report customizer thread: https://github.com/retorquere/zotero-report-customizer/issues/18

I think it was on https://forums.zotero.org/ where you said I had to install an XPI by hand, something about this happening in April is ringing a bell, that I was months behind on a plugin that was set to auto update, it may have been a signature thing. But of course I can't find it.

But I also don't remember which of your 587 plugins it was :)

But maybe the April auto-update not working may ring a bell.

**Comment by rambalachandran** [comment]
It works now. Sorry for not getting back early.

**Comment by retorquere** [comment]
No worry. The UX of getting auto-exports violates what you can usually do with those dialog boxes, it's not strange to have missed it.

@BenjaminHCCarr anything that strikes my fancy gets a new plugin. The scaffolding I have for plugin dev makes it super easy to spin up a new one, even with the ferflixten extension signing that Mozilla now enforces. That is, easy for as long as it lasts. I would be surprised if Zotero is still Firefox based in a year, given that Mozilla has already repeatedly been [rather hostile towards Zotero](https://danstillman.com/2015/11/23/firefox-extension-scanning-is-security-theater), combined with the stated plan to [kill off the technology that makes Zotero possible in Firefox](https://blog.mozilla.org/addons/2015/08/21/the-future-of-developing-firefox-add-ons/) anywhere between now and end of next Februari. Mozilla hasn't handled their last major disruption (signing) with any kind of grace or technological insight, so I have little hope that they'll handle something way more complex and disruptive any more subtle.

**Comment by BenjaminHCCarr** [comment]
Zotero Standlaone 5.0 is in beta..... I haven't been following, imagine they are abandoning much, or moving to XULRunner (remember that?) which I think got spun off long ago.

**Comment by retorquere** [comment]
That's just temporary. They're looking at what the vaguely-promised webextensions-plus that Mozilla is planning is capable of, but they're actively looking at [Electron](http://electron.atom.io/). I'm not sure why they still put out a FF-based 5.0 (perhaps the work was so closed to finished they might as well), but my money is on Electron for the long term. It's a platform that is active *as* a platform, they welcome stuff of the complexity like Zotero, and who knows -- maybe a Zotero-fused-Scrivener can emerge, seeing what Atom is doing with Electron. For me, it's all the same -- a pest, because both 5.0 and Electron will (separately) require major effort to get BBT up and running. Less a port than a rewrite, using coding paradigms that are new to me, and not ooh-shiney-new but ugh-WHY-PEOPLE-new (I know why. Still don't like them).

XULRunner is dead (or rather, a [fragrant](https://groups.google.com/forum/#!searchin/mozilla.dev.platform/xulrunner/mozilla.dev.platform/o99wQZBjIJw/4eBoWbjEzjAJ) corpse waiting [disposal](https://groups.google.com/forum/#!searchin/mozilla.dev.platform/xulrunner/mozilla.dev.platform/_rFMunG2Bgw/C-4PcHj9IgAJ)). Zotero standalone is actually a custom, stripped build of  [Firefox](https://groups.google.com/forum/#!topic/zotero-dev/yy4-q_ZUA4M), aka [Firefox SDK](https://github.com/zotero/translation-server/issues/24).
