### ISSUE TITLE
titles are title-cased in .bib file; titleCase pref not present

### ISSUE THREAD

**Issue by reidpr** [retorquere/zotero-better-bibtex#558]
I have a citation whose title appears as so in Zotero:

> The parable of Google Flu: Traps in big data analysis

Expected output in the `.bib` file, which was what was happening until recently (not sure exactly when it changed over), is:

>     title = {The parable of {{Google Flu}}: {{Traps}} in big data analysis},

Actual output is:

>     title = {The Parable of {{Google Flu}}: {{Traps}} in Big Data Analysis},

i.e., the title is now modified to title case, but it didn't used to be.

The preference `titleCase` does not appear in my `about:config`.
Related issues might be #382 and #541.
This is Zotero standalone 4.0.29.11 with BBZ 1.6.73.
Thank you.

**Comment by retorquere** [comment]
According to my resident BibTeX expert (@nickbart1980) this would be the desired behavior for English references -  he will be able to explain better than I can, because I honestly don't know much about BibTeX.

Indeed those issues you name are related - do you have a reference that renders incorrectly because of the title casing? That would be an important test case.

**Comment by nickbart1980** [comment]
This *is* the desired behaviour (for English references) and follows best practice for both bibtex and biblatex.

Read https://tex.stackexchange.com/questions/10772/bibtex-loses-capitals-when-creating-bbl-file/140071#140071 – “[…] **some, but not all** citation styles require capitalization in titles (a.k.a. “title case”); other styles use ordinary case. Your bibliography database [and BBT output!] should work with both capitalization styles without modification, so […]: You must **write the title in the capitalized form**, and your `bst` style either keeps it this way or converts it to lower case. Lower-casing works indiscriminately-- BibTeX does not try to guess which words are proper names, acronyms etc. (note that even letters in the middle of words get lower-cased). To protect words that should always be capitalized, you enclose them in braces. […] Tl;dnr: **Capitalize all content words in titles, and enclose proper names and the like in braces.**”

**Comment by reidpr** [comment]
I wonder if I have an issue of correct behavior vs. actual behavior in the journals I submit to. I recall some years ago spending a decent amount of time updating my `.bib` files to sentence case, and while I don't recall exactly what was going on, a decent prior is that my past self did this for a good reason.

I will proceed with the current export behavior for a while and see if I run into issues.

That said, it's important for me to be able to export my data without this alteration, should the need arise; the principle of leaving user data alone is mentioned in #382.

[As documented](https://github.com/retorquere/zotero-better-bibtex/wiki/Configuration), I added a boolean preference in `about:config`, `extensions.zotero.translators.better-bibtex.titleCase`, set to false. But this did not change the behavior: still modified to title case.

The ideal case may be to have a checkbox in the *Translator options* dialog at export time, because it seems like the use case may be to work around broken BibTeX styles. That is, best practices don't work in some situations.

**Comment by retorquere** [comment]
That setting was removed, so I've removed it from the wiki. The reason I had it was because I simply didn't know the purpose of title casing, I thought at the time it was frivolous prettification, until @nickbart1980 explained what was going on. I like Bib(La)TeX a little less now I know what is going on TBH, but I understand that this is not behavior that should be optional given the Zotero-recommended way to enter references and the way Bib(La)TeX expects to find them.

I did say I would prefer not to touch the output, but @nickbart1980 convinced me otherwise. I could never adhere to that crede anyhow, as a lot of what BBT does intentionally touches the user input; adding braces for example, but also parsing out bibtex keys, changing html to LaTeX, etc.

I have no reason to doubt you had good reasons to go through your bib file, but I've changed policy to be a little more conservative about adding preferences to tweak BBTs behavior; if there is a behavior that works without a preference, that's my preference these days. I'm not particularly fond of the double-brace wrapping myself for example, but it works, so I'm just making that the standard behavior. There are already too many preferences; I should really lose auto-pinning (certainly with the upcoming 5.0, which makes that behavior a bear to get right), "export as ascii" (the defaults ought to work), "omit title and mimetype" (I'm having some serious doubts about the value of file attachments), and the zotfile extender (that was just a bad idea, I should have left integration to Zotfile), but these are already exposed preferences, so I'm leaving them in place for now.

If there is a reference that doesn't render correctly, the title casing wouldn't be best practice as far as I'm concerned; this would be an entirely different matter of course. In such a case, I'd try to find a fix that just works, and if that cannot be done, I would add an extra preference. But without such a reference, if the BibTeX renders correctly, I'd rather not vary behavior any further than I already do.

**Comment by retorquere** [comment]
(BTW, if a preference is not already present in `about:config`, that means the wiki is wrong. All prefs that BBT supports are pre-declared with defaults. If the pref is not there already with a default, BBT won't understand it)

**Comment by retorquere** [comment]
If there is a reference where the current behavior results in a reference that renders out wrong, please do re-open the issue. For now, without a failing sample, there's nothing much I can do.

**Comment by reidpr** [comment]
OK, here's one:

<img width="397" alt="screen shot 2016-10-07 at 3 34 20 pm" src="https://cloud.githubusercontent.com/assets/1682574/19206247/c9a7edb4-8ca4-11e6-90d8-603c8a5f8719.png">

Here, "like" should be capitalized.

I was able to fix this particular case by editing the `titleCaseLowerCase` pref. However, it was a bit frustrating. There's a different preference, `skipWords`, that also contains "like" but had no effect (as documented, but I searched for "words" in `about:config` and that's all that came up). Further, both of these are very long lists of words in a small text box and thus hard to edit. Also, the former is not alphabetized, so it took me a while to find "like".

I would also argue that the premise these word lists are based on is incorrect. That is, which words to leave lower-case in a title-cased string depends on things other than the word's sequence of characters, such as part of speech it's used as, in addition to various house styles. (See e.g. [en.stackexchange post](http://english.stackexchange.com/questions/14).) In this case, I'm sure that removing "like" has broken other references that really do need a lower-case "like".

Previously, I'd solved this problem with the all-lower-case export, which does not strictly follow the publisher's style, but no one's ever complained, and IMO it looks a lot better.

I would really prefer to turn off the title-case transformation altogether rather than try to debug it or reverse it in some post-processing step.

**Comment by reidpr** [comment]
Here's another one:

<img width="385" alt="screen shot 2016-10-07 at 4 07 21 pm" src="https://cloud.githubusercontent.com/assets/1682574/19206737/4dad5998-8ca8-11e6-9555-25835532cb94.png">

Here, the problem is "big", and it's not because it's in `titleCaseLowerCase` but rather because it's preceded by a curly quote:

<img width="272" alt="screen shot 2016-10-07 at 4 07 37 pm" src="https://cloud.githubusercontent.com/assets/1682574/19206751/62447a62-8ca8-11e6-9726-7dcc444a41c2.png">

**Comment by retorquere** [comment]
OK, a couple of things going on here:

1. `skipWords` only affects the key generation, not the title caser. It's not really meant to be edited, but if there's something that really annoys you, you can. When I still did I would usually copy the value to a text editor, modify it, and paste it back.
2. `titleCaseLowerCase` was a leftover from when I had my own titlecaser; I now use the one from citeproc-js, the citation processor that Zotero also uses. `titleCaseLowerCase` has not been used anywhere for a while.
3. As I now use the citeproc-js titlecaser, any title-casing problems will affect Zotero and BBT in the same way; if you generate a bibliography from Zotero in any one of the Chicago styles, you'll find (by and large) the same errors. I say by and large because BBT will update citeproc more often than Zotero will, so occasionally they will temporarily differ -- as is now the case with flu-trends. Each has a different error. You can play with the latest citeproc-js titlecaser [here](http://retorquere.github.io/zotero-better-bibtex/latex/index.html?titles=Using%20networks%20to%20combine%20%E2%80%9Cbig%20data%E2%80%9D%20and%20traditional%20surveillance%20to%20improve%20influenza%20predictions&unicode=true&titlecaser=citeproc&language=eng&translator=biblatex) to see its effects.
4. I have [submitted your two cases to citeproc-js](https://github.com/Juris-M/citeproc-js/issues/20); when the bug is fixed there, I will update and make a new release.
5. The "big data" reference can be fixed by writing it as Big Data (Big Data is usually capitalized when I see it)
6. in the interim, while waiting for the bugs in citeproc to be fixed: if you  always want "like" to be capitalized in that reference, writing it as "Like" will take care of that.

**Comment by retorquere** [comment]
BTW if you want BBT to mostly just leave the reference alone, you can add the [#LaTeX](https://github.com/retorquere/zotero-better-bibtex/wiki/From-Unicode-to-LaTeX-and-Back-Again#you-are-a-hardcore-latex-user) tag to the reference.

**Comment by Dabsen** [comment]
This new, unexpected capitalization behavior of better-bibtex is causing me massive problems. I do not understand Biblatex's automatic behavior very well, but it is in any case unable to cope with capitalization conventions for languages other than English (e.g. for French where the rules are very complicated). However, the new behavior makes it *impossible* to do the capitalization manually! Really, this can't stay an automatic behavior. We need a preference at the very least.

**Comment by retorquere** [comment]
I can't even parse what most of that says, but I think it's hardly counterintuitive to follow the Zotero recommendations and the BibTeX/BibLaTeX specification.

I've added a [hidden preference](https://github.com/retorquere/zotero-better-bibtex/wiki/Configuration#extensionszoterotranslatorsbetter-bibtexsuppresstitlecase-default-false) that will allow out-of-spec BibTeX if you enable it, and that's preferably the last I hear of it. The default will remain `false` because it's a design desideratum that references render the same whether you let Zotero of Bib(La)TeX render the bibliography (to the extent this is possible), and turning this on breaks that behavior. I'm waiting for #588 to resolve, and then I'll cut a new release which will have this in it.

**Comment by Dabsen** [comment]
Sorry I was unclear. The "specification" you refer to only makes sense for English references, as @nickbart1980 wrote. In other languages, like French, one may need to systematically undo what BBT does. So, adding an option seems wise. Thank you for that.

**Comment by retorquere** [comment]
The option doesn't do anything for non-English references. I have no idea what you mean with "undo what BBT does" -- BBT does hardly anything with non-English titles, so there's pretty much nothing to undo.

**Comment by Dabsen** [comment]
Oh! You mean BBT won't do anything to a reference if it contains an explicit language field referring to a language other than English? I had no idea. Sorry. My bibliography does not contain langid fields, except for foreign (from my point of view – not French) references: as my main document langage is French, biblatex will assume references are French unless otherwise specified.

**Comment by retorquere** [comment]
Yes. BBT can't know what language a reference is in if you don't tell it. The [assumption is that they're English](https://github.com/retorquere/zotero-better-bibtex/wiki/From-Unicode-to-LaTeX-and-Back-Again) unless otherwise specified.

**Comment by Dabsen** [comment]
Ah, I see! So that's the counter-intuitive (in my setting) part. It's the first time it's caused me a problem. The new behavior is fine, then, I'll just have to add language fields everywhere. Sorry for the confusion and loss of time.

**Comment by retorquere** [comment]
I have tests running on a separate branch which assumes references without an explicit language set are in the same language as Zotero itself.

**Comment by Dabsen** [comment]
That would be great. It would indeed be the behavior closest to biblatex's.

**Comment by reidpr** [comment]
@retorquere, thank you for your patience on this issue. I hope that I have not been too cranky. I'm facing a paper deadline, so that contributes to my heightened concern on it.

I appreciate the new pref. I assume this will solve my problem. I do hope you'll expose it in the UI, ideally at export time, for the reasons explained below, but that's not my hill to die on.

At a high level, I wonder if this is one of the perfect becoming the enemy of the good enough, or a complex feature being rolled out prematurely.

Here's the assessment I was facing:

1. A new, complex text transformation was introduced.
2. This transformation is buggy. (For example, of the first ~60 citations I reviewed after its introduction, two were broken.)
  1. The transformation is likely to remain buggy for some time, as it tries to solve a very difficult NLP problem that has multiple solutions depending on house style.
  2. Because the transformation is complex, it's very difficult to reverse without a preference setting. This is why the latter is so helpful to me.

A few follow ups on your points:

Item 2: Removing "like" from `titleCaseLowerCase` was in fact coincident with the first error being fixed. I don't recall what version I was on as of Friday, but it's definitely later than in the initial report.

Item 5: In my field, *big data* doesn't get any special treatment.

Item 6: Thanks for the workaround. As I mentioned, the preference is even better.

Thank you for your hard work on this software.

**Comment by retorquere** [comment]
I was actually serious about preferably not hearing about this issue again if the preference does what you want. As soon as #551 clears I'll cut a new release, but a #558-enabled pre-release is available [here](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.75-circle-3019.xpi) if you're in a hurry.

> I appreciate the new pref. I assume this will solve my problem. I do hope you'll expose it in the UI,

no

> ideally at export time, for the reasons explained below, but that's not my hill to die on.

absolutely not. Exposing export-time options affect much more of BBT than global preferences, plus UI-real-estate here is at a premium, so if something makes it here there must be a widespread and pressing need.

> At a high level, I wonder if this is one of the perfect becoming the enemy of the good enough, or a complex feature being rolled out prematurely.

You're free to wonder about this, but generating BibTeX that matches the Zotero bibliography output after rendering is a design desideratum -- I match Zotero's behavior here, so if you deem this premature you should also deem Zotero's bibliography handling premature. And, for all that matter, Bib(La)TeX's handling of such issues, which *also* does re-casing with loads of known edge cases.

> Item 5: In my field, *big data* doesn't get any special treatment.

Then the Zotero-approved method is to wrap that in `<span class="nocase>...</span>`. The new hidden BBT pref aside, Zotero will *also* not render that reference as you want without that. Stuff in titles wrapped this way will likewise not be case-manhandled by BBT.

> Item 6: Thanks for the workaround. As I mentioned, the preference is even better.

This is not a workaround. It's how Zotero works.

**Comment by retorquere** [comment]
I will usually try to deal with such confusion with a little more grace, but I'm in a hectic place right now, and my grace-supply has just about ran out. I can tell you feel strongly about this issue, I assume you can tell I do too. I consider the preference a wart, but I can see how it it could be useful to you and perhaps others, but given that I do think it's a wart it's something I prefer to spend as little time as possible thinking about.

If the hidden pref does *not* do what you want, we can talk about that. I'd prefer not to have an option present that does something we both don't like.
