### ISSUE TITLE
Has the installation method changed?

### ISSUE THREAD

**Issue by nevinstd** [retorquere/zotero-better-bibtex#562]
I was recently running a workflow with better-bibtex, and the computer I was working on had to have a clean wipe. As a result I have to reinstall programs including better-bibtex. I could swear that last time I installed it by searching for the Firefox plugin through Firefox's usual add-ons system. Now however I can only find this page about better-bibtex. I can't really make heads or tails about how to download and install it from here. I get a zip file that I can unzip, and then... ? 

I guess the primary question is: what happened to the add-on being in the Firefox database, and how can I install better-bibtex now?

**Comment by retorquere** [comment]
The [installation method](https://github.com/retorquere/zotero-better-bibtex/wiki/Installation) hasn't changed, at least not in a long while. There may at one time have been a version on addons.mozilla.org (I did at some point try, but honestly don't remember if I ever actually put it there), but AMO is a fairly hostile place for larger addons (which is also why Zotero itself isn't on there), so I'm self-hosting the addon.

There's no zipfile involved, and installation is exactly like the installation of Zotero itself; you just download the `xpi` from the [latest release](https://github.com/retorquere/zotero-better-bibtex/releases/latest) and install that as per the [installation instructions](https://github.com/retorquere/zotero-better-bibtex/wiki/Installation). On the "latest release" page you will indeed also find a zipfile, which you don't need. I can't prevent that from appearing alas, but it's the source code for that release for those who are interested.

If you still had a version installed from addons.mozilla.org, you have not been upgraded all that time. I've self-hosted BBT since at least 0.8.18, possibly earlier still, which went out in April 2015.

**Comment by nevinstd** [comment]
Huh. My other computer that wasn't wiped had Better Bibtex 1.6.74 on it. I could swear I've never downloaded this from github, but apparently I was mistaken. Also it seems that in my zeal to hit the big green "clone or download" button on the Code page, I completely missed the "installation" page. Here I was just very worried that I had done something wrong. 

Thank you for pointing me in the right direction!

**Comment by retorquere** [comment]
It doesn't need to be github, it was at one time hosted on a website, and I
did have an automatic upgrade path from that to github. It's just not
possible to automatically upgrade from AMO to non-AMO, or vice versa.
Mozilla actively and deliberately prevents it. So if you have anything
post-0.8.28, you must have at one time installed the xpi manually.

Github is in many ways not ideal for end-users, but it's simplified my dev
and release process tremendously. The green download button is one of those
things that is squarely targeted at developers, not users.
