### ISSUE TITLE
Default-language assumption for references that have no language set

### ISSUE THREAD

**Issue by retorquere** [retorquere/zotero-better-bibtex#571]
@nickbart1980, @Dabsen, can we talk about the BBT assumption that references that have no language set are English references? I'm toying with a branch that just assumes the Zotero locale for those references, but since locale-assumption is currently tied to the title-casing behavior, I'd have to add explicit language IDs for references that don't have them. Apparently, as per @Dabsen,

> as my main document langage is French, biblatex will assume references are French unless otherwise specified.

And then the title-casing would be odd behavior.

**Comment by Dabsen** [comment]
Plain BibTeX does not support multilingual bibliographies – it respects the language of the main document, I believe. The usual solution, I think (which I used before switching to biblatex) is to load the babelbib package, which does, indeed, respect the `language` field – and also assumes main document language by default. Biblatex uses the `langid` field and the main document language when there is none (see biblatex doc, 3.2.1.2). Is that what you needed to know?

**Comment by Dabsen** [comment]
After thinking about it, I am unsure. To be honest, I think that assuming everything is in English unless otherwise specified would suit most users best (the most frequent use-case is likely to be people who write in English, even though some might have the locale set to their native tongue.) But then, I think capitalizing does more harm to those users like me who assume another language, than it does good to the average user who writes in English:
1) For the average user who writes in English, having titles in sentence case is likely to be a minor nuisance. After all, it is what some styles require, and it is not shocking: biblatex will reproduce exactly the case that they have in Zotero. Many might not notice, and those who do notice have an easy, intuitive solution without needing to understand the language issue (they just need to click Transform>Title Case on the title that bothers them in Zotero).
2) For the user like me who has references in his language and does not expect them to be transformed, the capitalization is quite irksome, as it produces very bad output (the capitalization ends up done badly: every word including “and” and the like will be capitalized as the software only knows the exceptions for English). Moreover it is hard to revert without understanding that language is the underlying issue, which is not obvious (the only other solution is to reprogram one's biblatex style to lowercase the titles again).

But then, it seems to me that adding a langid equal to the locale whenever there is no explicit language set may be going too far. For the typical user, it will cause biblatex to treat their normal English references as written in a foreign language, causing such effects as weird quotation marks and incorrect hyphenation. I would instinctively favor the most conservative option : capitalizing if the language is explicitly English or the locale is (some variant of) English ; doing nothing otherwise (neither capitalizing, nor adding an explicit language id). Of course, this is unsatisfactory as it is very ad hoc (and it might not be possible given your code base), but it's probably what will disturb the least amount of users.

**Comment by nickbart1980** [comment]
Currently, BBT/bibtex wraps the title-like fields of non-English entries in extra sets of braces to prevent bibtex from tampering with them. I think this is a good solution, in particular since this can be expected to work even without loading any extra packages.

As to the “assumption that references that have no language set are English references” – I wouldn’t change that. Zotero makes the same assumption, and I’d find it too confusing to have to remember that BBT, depending on its settings, might assume something else.

I’d rather make sure that my DB does not contain any empty `language` fields. Batch editing via the JavaScript API is not too difficult; instructions are here: https://www.zotero.org/support/dev/client_coding/javascript_api#examplebatch_editing and https://gist.github.com/zuphilip/b942c8bf2f1126982517.

**Comment by retorquere** [comment]
1. Titlecase is, if I understand @nickbart1980 correctly, not required by some styles, but by the majority of styles when it comes to English refs. It is true that if you have your titles in Zotero in title-case format they'll usually render OK in Bib(La)TeX, but there are styles which demand that text can be sentence-cased, and these titles will not allow that.
2. No issue here. Branch deleted.

**Comment by retorquere** [comment]
Given that many people seem not to set the language ID, and given that, for English refs, title-casing is usually required, assuming that a reference is a "foreign" language in absence of a specified language is no less arbitrary than assuming it English -- even moreso if this is already the behavior that Zotero/citeproc exhibits (and I think that's what @nickbart1980 is saying). Forcing people to add a language id in order to match the Zotero behavior would not be the most conservative option in that case.

**Comment by Dabsen** [comment]
I was inclined to “minimal intervention” when unsure. But strictly speaking, that boils down to assuming a foreign language, which is not the most consistent behavior. So you're right. Anyhow: now that I understand BBT's behavior, I'm fine with it. @nickbart1980 thanks for the tip on batch editing, I'll use it.
