### ISSUE TITLE
How to acknowledge or cite BBT?

### ISSUE THREAD

**Issue by reidpr** [retorquere/zotero-better-bibtex#572]
Better BibTeX has been very helpful in preparing my papers, and I'd like to give appropriate credit. This includes the software itself as well as the top-notch, friendly support from @retorquere.

What guidance or preferred language do you have on acknowledgements, citation, or similar?

(I didn't find any in the wiki or prior issues.)

**Comment by retorquere** [comment]
This caught me kind of off-guard -- it's not something I've ever thought about. Do you mean something like a citation (in which case I could see if I can get something up on http://openresearchsoftware.metajnl.com/), or something like a project description? Or my name (Emiliano Heyns) rather than my handle (which has differed over the course of the years -- it's currently `retorquere`, but you'll also find me in the logs as `AllThatIsTheCase` (from my Wittgenstein period), `friflaj` (from my skydiving period) or just `Emiliano Heyns`)?

Although I wrote the code, there are 500+ issue reports that got me there, a few pull requests, indispensable help from @nickbart1980 who's become my go-to guy (I assume) for all things BibTeX (you'd think I'd know my BibTeX, but, errr...), and of course there are several software projects that I in turn depend on; Zotero of course, but also citeproc and libraries that help deal with the insanity that is unicode in Javascript... I'm a little hesitant to claim that this is a solitary effort.

That said, I do appreciate the hat-tip. I'm pretty proud of where BBT is now, I feel fairly confident that BBT can match any offering, commercial or otherwise, that isn't BibTeX-native.

**Comment by reidpr** [comment]
My initial inclination was something along the lines of the following in the acknowledgments section:

> We thank Emiliano Heyns for ...

But some projects like to be cited, for example Scikit-Learn has clear guidance for this IIRC.

To clarify the question, do you have a preference among:

* Acknowledgement similar to above
* Citation, in which case I'll need guidance on what to cite
* Neither

I agree it's not a solitary effort, but you are the leader and unusually easy to work with.

**Comment by retorquere** [comment]
I'm vain enough to not go for "neither" 😄 ; acknowledgement would be nice. I've looked at the openresearchsoftware process -- I might still do it, but it could take weeks to months to get it through.

**Comment by reidpr** [comment]
Great. I'll do the ack for now and revisit the citation question next time around.

**Comment by retorquere** [comment]
"Unusually easy to work with" is not, BTW, the way I'm commonly described by cow orkers, or by students who had the distinct pleasure either working with me or for me. I think "memorable" was the most flattering I ever got out of it.
