### ISSUE TITLE
Better BibTeX silently updates within a version of Juris-M it no longer supports?

### ISSUE THREAD

**Issue by drammock** [retorquere/zotero-better-bibtex#582]
report ID: R4J5DEDG

upon opening Juris-M, the "extras" column showed with all extra information displayed, instead of the usual "bibtex key" column with only the bibtex key displayed.  On attempting to export a reference, an error box said that "an error occurred while trying to export the selected file."  FYI I usually use Ctrl+Shift+C to do a "quick export" in bibtex format.  Linux (xubuntu 16.04), Juris-M 4.0.29.10m85...  hang on, just realized that apparently BetterBibTeX now requires 10m95 or later?  Apparently BetterBibTeX updated itself while my Juris-M version remained unchanged?  That seems like it shouldn't happen.  It was literally working fine a couple hours ago, and stopped working when I closed and then re-opened Juris-M the same day.  If indeed this was a BBT update, I think BBT should check whether its host version is still compatible with the updated version of BBT before silently doing a background update.

**Comment by retorquere** [comment]
That's a whole lot of assumptions on what I should do that do not take into account what I *can* do. The upgrade mechanism is part of Firefox, not better bibtex. I don't do the silent upgrade, Firefox does, and there is no way for me to check before the upgrade happens whether it should happen. M97 silently introduced  breaking changes of which I wasn't notified either; Juris-M  said m98 was going to be released to fix these breaking changes, but for some reason it hasn't dropped yet. I didn't ask for the m97 breakage, and I have no control over the Juris-M release schedule. 

If you check for new updates on your extensions you will find that a new BBT version was already published yesterday that will not disable itself on m97 (but it will complain about its presence on startup). But please note that the current BBT is *not* fully tested on m97 and cannot be fully tested on m97 and really needs m98 for full support to come back.

**Comment by drammock** [comment]
thanks for responding.  I poked around a bit and found that Juris-M does (like firefox) does have a setting "update addons automatically", which was checked (I didn't know that because I'd never seen that setting before, it's in a different place than I expected).  Still, I'm a little surprised that a change was introduced that is incompatible with such a recent version of Juris-M (m85 was released just 4 months ago).  I understand that Juris-M may be a moving target and you can't be expected to support all past versions...  but is there at least a way to trigger a dialog box in situations like mine, saying something like "BetterBibTeX has been updated but your version of Juris-M is now incompatible with it, please update Juris-M" (or something similar)?  The other option is for Juris-M to inspect the version constraints of its add-ons prior to applying the updates, and refuse to do so if it would break (I'll make that suggestion to Frank).

**Comment by retorquere** [comment]
That's not exactly what happened. What happened is that *Juris-M* changed right under me. I didn't make any changes that were incompatible with Juris-M; Juris-M m97 introduced a bug that trips up BBTs tests. But I don't honestly expect Frank to know everything that goes on in any of the extensions he may or may not know about -- he can't know what is and is not compatible with Juris-M. I don't recommend turning off auto-update, but you're correct that it is an option.

The breakage went undetected for a while until I made a change to BBT, causing my test suite to run; the test suite picks up the latest version of Zotero/Juris-M and tests against that, so this is when the bug was found. The breakage was there for a while, the tests just weren't run against them. I've now scheduled nightly test runs so if a new version drops that breaks BBT at least I'll know about it sooner, but I don't get notifications of releases of either of the two otherwise.

And if you updated to .78, you would have seen that the warning you propose is now exactly what occurs, so I'm at a loss trying to understand what else I could do. BBT .78 will allow you to work with m97 (which can't be fully tested but I expect most things will just work), m95 (which is tested) or m98beta2 (which is tested).

**Comment by drammock** [comment]
Thanks for the additional info.  I'll update both Juris-M and BBT and hope for the best.  Glad to hear you've already implemented what I suggested (i.e., an incompatibility popup warning of some kind).  I'm surprised that I didn't see the warning...  the update to .78 appears to be what triggered my setup to break, and it was in the process of digging for version numbers in making this issue report that I found a message saying BBT had been disabled and required 10m95 or later.

**Comment by retorquere** [comment]
The disabled message you saw was from .77. I released .78 specifically to allow m97 to work with BBT, even if I'm not super enthusiastic about putting out a build that has not been properly tested. But .78 is fully tested with Zotero, Zo I *expect* Juris-M will work, but I'd really rather just also run my tests on Juris-M. M98 was supposed to drop more than a week ago.
