### ISSUE TITLE
capitalization of titles in citation keys

### ISSUE THREAD

**Issue by ookimi** [retorquere/zotero-better-bibtex#594]
I am using the following pattern to generate bibtex keys:

`[authors2]_[year]_[shorttitle]`

Consider this entry:
Title: Improving statistical machine translation using comparable corpora
Year: 2010
Author: Snover, Matthew Garvey

This gets me the following bibtex key:
Snover_2010_Improvingstatisticalmachine

It is certainly useable, but would it not be much easier to read (for example, while choosing from the citations from the same author in a dropdown list in cite-as-you-write process) if the words in the title were capitalized or separated somehow? For example,

Snover_2010_ImprovingStatisticalMachine
Snover_2010_Improving_statistical_machine
Snover_2010_Improving.statistical.machine

I think capitalization of all words in titles when generating bibtex entries should be the default behavior.

**Comment by retorquere** [comment]
No accounting for taste I guess, but I'm not going to change the defaults. First it was because I wanted to track the JabRef behavior (and that's still generally the case, but I'm not super-strict about it anymore) but now it's just that BBT has been out in the wild for a while and I certainly don't want to make a change that could have citation keys for existing articles just change because the behavior behind the pattern changed.

In any case, what you want in the last two of your examples can be accomplished by 

* `[authors2:postfix,_][year:postfix,_][Title:skipwords:select,1,3:condense,_]`
* `[authors2:postfix,_][year:postfix,_][Title:skipwords:select,1,3:condense,.]`

The first can be done but the pattern is a little funky

* `[authors2:postfix,_][year:postfix,_][Title:skipwords:select,1,1:capitalize][Title:skipwords:select,2,1:capitalize][Title:skipwords:select,3,1:capitalize]`

**Comment by retorquere** [comment]
(as said, the initial behavior behind the pattern blocks was just that of JabRef, but personally I mainly use lowercase citekeys because I type them by hand, and I don't want to have to use the shift key all the time. Different strokes for different folks I suppose)

**Comment by ookimi** [comment]
Thanks for responding so quickly, and for the plugin in general! 
You are right, different strokes for different folks... your memory is way better than mine if you can remember all those titles :)

**Comment by ookimi** [comment]
Sorry, this is still not over... 

I tried this:
[authors2:postfix,_][year:postfix,_][Title:skipwords:select,1,1:capitalize][Title:skipwords:select,2,1:capitalize][Title:skipwords:select,3,1:capitalize]

This works in that it capitalizes words, skipping articles and prepositions, but it does not remove punctuation signs like ',",(,) - and they "break" the whole document.

What can I do about this? I guess the easiest would be to remove punctuation in the postscript - if I knew anything about it.

**Comment by retorquere** [comment]
Try `[authors2:postfix,_][year:postfix,_][Title:nopunct:skipwords:select,1,1:capitalize][Title:nopunct:skipwords:select,2,1:capitalize][Title:nopunct:skipwords:select,3,1:capitalize]`

**Comment by retorquere** [comment]
Or rather just `[authors2:postfix,_][year:postfix,_][Title:nopunct:skipwords:select,1,3:capitalize]`; I had forgotten `capitalize` does all words.

**Comment by retorquere** [comment]
If `nopunct` still leaves unwanted chars, you could do `[authors2:postfix,_][year:postfix,_][Title:nopunct:skipwords:select,1,3:capitalize:alphanum]`

**Comment by ookimi** [comment]
Sorry for the late reply, and thanks a lot! No bibtex problems with [Title:nopunct:skipwords:select,1,3:capitalize:alphanum].
Your plugin really helps my work a lot. Thanks again from all the Tex+zotero lovers.
