### ISSUE TITLE
Quality report: Wrongly flags capitalized one word titles as a problematic title-case

### ISSUE THREAD

**Issue by JohnLukeBentley** [retorquere/zotero-better-bibtex#596]
From 

```
% Zotero
Title: Republic
```

I get ...

```
% zotero-better-bibtex (via Better biblatex)
title= {Republic} % As expected
...
% Quality Report for plato_2004_republic: 
% Title looks like it was stored in title-case in Zotero
```

I expect ...

No such quality report.

A one word title, like "Republic", is (as a conceptual matter) either sentence case or title case. However, because a one word title that is capitalized is not a problem it shouldn't be flagged by zotero-better-bibtex (BBT) as "looks like it was stored in title-case in Zotero". 

Really, BBT wants to be catching titles that are `not sentence case`. If that is the criteria used, then this will exclude the false positive of one word capitalized titles (like "Republic"). "Republic" _is_ sentence case (even though it is also a title case) and on that basis it would be passed through without being flagged as problematic.

I'm using BBT 1.6.80. 

I have set (in Zotero about:config):

extensions.zotero.translators.better-bibtex.qualityReport = true
services.sync.prefs.sync.extensions.zotero.translators.better-bibtex.qualityReport = true

Report ID: KGAKI2DE (Two examples of one word capitilzed titles. plato_2004_republic and wenar_2015_rights).

**Comment by retorquere** [comment]
The casing check is indeed a little iffy. I use the QR mostly for detecting missing fields; I added the casing check because the python tool that inspired the QR had it.

I don't really have a good way to check for sentence-casing; case-checks would have to be a lot smarter about linguistic analysis than I can make them. Right now, I just use the CSL title-caser (which does a fairly good job for English titles, and understands the `nocase` conventions) to title-case the string and assume that if the string is the same pre- and post-title-casing, it's not sentence case. Which indeed runs into the issue you've outlined.

I've preceded the more speculative QR messages (which is almost all of them) with a question mark. The single-word titles you provided will not be flagged after the change I made, but it won't be hard to find other false positives.

**Comment by retorquere** [comment]
I have a debug build available at https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.80-circle-3229.xpi.

**Comment by JohnLukeBentley** [comment]
Thanks. That version takes care of one word titles at my end (Tested with both "Republic" and "republic").

Yes I see that as a general matter many of your checks might be speculative. Your preceding question mark and your phrase "looks like ..." are good as indicators of a speculative result, which might be a false positive is some cases.

But on testing for sentence case, wouldn't the follow work in most cases:

* Lower case all of the title string except for the first letter and any two consecutive letters that are capitals; then
* Compare to result to original
* If a match then the title is (likely) sentence case.

?

(That would handle both one word capitalized titles ("Republic") and titles with initialisms ("Crime rate in WA declines"): "Crime rate in WA declines" is another false positive.

I leave it up to you to judge whether you think that false positive warrants taking care of.

Anyway I think your quality report feature quite helpful (even if it is necessarily going to occasionally flag false positives). 

Perhaps a more important improvement here would be providing a toggle button or check option somewhere on the UI (Right click menu?) of the quality report.

**Comment by retorquere** [comment]
Sentence casing is a little more involved than that -- you have to take into account stuff like `<i>in</i>capable` and `proceedings if the <span class="nocase">IEEE</span>`. I can't test it right now, but are you sure `Crime rate in WA declines` yields a false positive? BBT should titlecase it to something like `Crime Rate in <span class="nocase">WA</span> Declines` and because that differs from the input should not report it.

I've thought about a right-click option in Zotero, but I'm mainly interested in quality of BibTeX references, not of Zotero references in general, and to decide in Zotero whether a reference has issues would mean I'd have to basically replicate the translator logic in the UI part of Zotero. That seems like a lot of work for relatively little gain.

In principle the CSL processor should be able to decide whether a reference has issues, as the CSL format has information on what fields it expects, but CSL processors are extremely lenient and will try to generate something legible out of even the worst; it has info on "if you don't see this, then do that", but not information on "you really ought to see this, but if not, fall back to that, I don't see this but that's properly optional". I tried that route but it didn't pan out.

**Comment by retorquere** [comment]
I've looked at other sentence-casers (the Zotero sentence-caser is decidedly not great) and I can't find any one that isn't insanely naive. I can either remove the test or indicate it's speculative state.

**Comment by JohnLukeBentley** [comment]
> I can't test it right now, but are you sure `Crime rate in WA declines` yields a false positive?

Sorry, it doesn't. It passes through without a problem.

It looks like there's nothing you need do here.

**Comment by retorquere** [comment]
@njbart is there any conceivable purpose to `numPages` for a `book` entry?

**Comment by retorquere** [comment]
(for BibTeX, not BibLaTeX, sorry)

**Comment by njbart** [comment]
Conceivable – yes (for comparison: about 14% of the 1700+ styles in the CSL style repo use the corresponding CSL variable `number-of-pages`). Used by the standard BibTeX styles – not that I know of.

**Comment by retorquere** [comment]
Is there a reasonable field I could export it to?

**Comment by njbart** [comment]
If a field is not in the original BibTeX specs, and no other established conventions exist, I’d always go for using the matching BibLaTeX field, in this case, `pagetotal`.

**Comment by retorquere** [comment]
Any suggestions for the following Zotero fields:

* rights (which I think means copyright)
* bookSection.callNumber
* tvBroadcast.runningTime
* videoRecording.medium
* newspaperArticle.section

**Comment by njbart** [comment]
BibTeX or BibLaTeX?

**Comment by retorquere** [comment]
both.

**Comment by njbart** [comment]
Most are only documented for biblatex (or one of its derivatives), though nothing will break if used with bibtex (AFAICT).

- `rights` “(which I think means copyright)” (it does)
	- Zotero itself never exports this field or forwards it to citeproc-js, and bibtex and biblatex have nothing even remotely similar. Ignore it.
- `bookSection.callNumber`
	- CallNumber in general could be mapped, together with Library,  to `library`
		- biblatex manual: “library – This field may be useful to record information such as a library name and a call number.”
- `tvBroadcast.runningTime`
	- `pagetotal`, maybe
- `videoRecording.medium`
	- `type`
- `newspaperArticle.section`
	- difficult; biblatex-chicago mentions `pages` (not practical for BBT, I would argue), and `usera`, while biblatex-apa uses `titleaddon` for stuff like “Special section”.

**Comment by retorquere** [comment]
Currently, if you have `archive` and `archiveLocation` set, and `archive` is `arXiv`, I use the `callNumber` as the `eprintclass`. If I go with `libraryCatalog` + `callNumber` to `library`, that could end up with duplicate info. Suggestions?

**Comment by njbart** [comment]
Well, if, based on the content of the archive field, you identify the content of a call number field as a component of some sort of electronic publishing information, why don’t you just skip exporting it to `library` in such cases?

I assume there’s an actual use case behind this, though in general I see a trend towards moving away from separating electronic publishing information into `eprint`, `eprinttype` etc., and instead using a URL only (just compare how the recommendations on presenting DOIs have changed in recent years in both CMOS and APA).

A different complication this makes me aware of is that in addition to library and call number we also have the fields archive and archive location, plus the CSL variable `archive-place` (accessible from within Zotero via the cheater syntax), which makes it 4 (or 5) fields for which I don’t really see any more sensible solution than combining them all into biblatex’s `library` field (unless using `eprint` and friends make any sense for that type of information, that is).

**Comment by retorquere** [comment]
There's not a specific case behind this, but I have a side project where I log what data is in Zotero references that I'm not outputting to bib(la)tex (which is data loss, basically), and this is what came up in my test suite so far. Data loss is not always a major issue for BBT, as its main target is to get well-rendering references, it's not meant to be a lossless interchange format, but it's undesirable to drop information that could be used in rendering references.
