### ISSUE TITLE
initialize failed: invalid bound parameter

### ISSUE THREAD

**Issue by drammock** [retorquere/zotero-better-bibtex#606]
Report ID: CR8C7BII
Platform: Linux x86_64
Juris-M: 4.0.29.12m95 standalone
BBT: 1.6.84 
Zotfile: 4.2.7

I'm getting a popup saying m95 has known incompatibilities and I should update to m98, but there is no m98 for Juris-M standalone.  I know you can't be expected to support all past versions, but m95 is the *current* version of standalone according to [here](https://juris-m.github.io/downloads/) and [here](https://github.com/Juris-M/zotero-standalone-build/releases).  I can't enable extended debugging because BBT is failing to initialize.

**Comment by drammock** [comment]
FWIW, the errors shown in the BBT preferences pane appear to be related to a group library.

**Comment by retorquere** [comment]
you can do the near-equivalent of extended debugging by going into the Zotero advanced prefs, enable "enable after restart", and then restarting. The log in CR8C7BII is nearly empty, and the one error that is in there relates to database schema init, not bound parameters. Can you get me a new log after doing the "enable" thing?

I'm sorry about the m95 message, but my time constraints do not allow supporting more than one version, so I have a fixed policy of only supporting the latest release, which in the case of Juris-M is m97. m95 should probably be fine, it's just that my tests aren't running against it. m97 isn't supported though because it unintentionally introduced breaking changes which I can't compensate for. m98, which is in beta but [should be released soon](https://github.com/Juris-M/zotero/issues/24#issuecomment-250714333) fixes those, but Frank is, as far as I can tell, even more pressed for time than I am. But putting this all together the support status of Juris-M is a little iffy right now.

It's incredibly inconvenient that Juris-M (and Zotero BTW) don't just update all clients at the same time -- BBT integrates into Zotero and Juris-M *very* intimately (as in it's taking some liberties maybe it shouldn't), to the point that the BBT test suite finds legitimate bugs in Juris-M with some regularity (as was the case for m97). This means that even legit changes in internals that are meant to be off-limits can break BBT. I can usually change BBT to follow suit, but I can't always follow suit in a way that keeps BBT backwards-compatible.

**Comment by drammock** [comment]
OK, I selected zotero's "enable after restart" but (as I learned when helping debug #600) it's not obvious that it's working: after restart, going to the advanced preferences shows the "enable" button (rather than the "disable" one) and the "enable after restart" box is unchecked.  Here's the report ID: FAMCAVTM  but the "errors" tab of the reporting dialog is showing something different from the BBT preferences pane.  Here's what the preferences pane says:

```
Initialize failed: Invalid bound parameter [object Object] in [
    "0": [object Object] {
        "_id": 350725
        "_libraryID": 2240613
        "_name": "phoible"
        "_description": "<p>Reference management for <a href=\"http://phoible.org\" rel=\"nofollow\">the PHOIBLE database</a> of phonological inventories.</p>"
        "_editable": true
        "_filesEditable": true
        "_loaded": true
        "_changed": false
        "_hasCollections": null
        "_hasSearches": null
        "_init": function ) {...}

        "objectType": "group"
        "id": 350725
        "libraryID": 2240613
        "name": "phoible"
        "description": "<p>Reference management for <a href=\"http://phoible.org\" rel=\"nofollow\">the PHOIBLE database</a> of phonological inventories.</p>"
        "editable": true
        "filesEditable": true
        "_get": function field) {...}

        "_set": function field, val) {...}

        "load": function ) {...}

        "loadFromRow": function row) {...}

        "exists": function ) {...}

        "hasCollections": function ) {...}

        "hasSearches": function ) {...}

        "clearCollectionCache": function ) {...}

        "clearSearchCache": function ) {...}

        "getCollections": function parent) {...}

        "hasItem": function itemID) {...}

        "save": function ) {...}

        "erase": function ) {...}

        "serialize": function ) {...}

        "_prepFieldChange": function field) {...}

    }
] [QUERY: SELECT libraryID FROM groups WHERE groupID=?]
```

As I said before, that appears to relate to a group library.

I understand about Juris-M being buggy and tight integration making things fragile.  But, I'll say again: *there is no version m98beta for standalone*.  m98beta is an XPI only.  So your policy is effectively "support only the latest version of the plugin."  Is that your intent?  If so that's fine, I just want to know that so I can downgrade and freeze BBT for my standalone install, as I strongly prefer the standalone app to the plugin.

**Comment by retorquere** [comment]
I think I have it. Try https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.84-br606-3308.xpi

I do understand there is no version m98 beta for standalone. I don't know why standalone and plugin have started to diverge and I fervently wish The Zotero team and Frank would just simply keep them on a simultaneous release, as I simply cannot afford to track more than one version. Even adding Juris-M at all was a hard decision to make, because it differs relevantly from Zotero from the pov of BBT. When I started BBT, standalone and plugin tracked rather closely, and I built my test suite around a browser testing tool called Selenium which I can't easily replace, but which cannot run the standalone versions, and without my test suite I'm lost. Given all that, my policy is indeed -- not merely effectively -- "support only the latest version of the plugin", although given the state of things, I do what I can for the other versions within reason.

In the current situation, the test suite runs against m98beta2, which is already a hack because the test suite used to pick up the latest Zotero/Juris-M automatically using roughly the same mechanism that Firefox uses. I had to bypass this because m97 fails on my tests for reasons I cannot work around. The fix in br606-3308 tests green against m98beta2, and I have no reason to assume it will not also work against m95. As an additional measure, I've set up nightly test runs of the master branch against m95, but I cannot afford to add more additional builds for m95 triggered on every checkin or on topic branches. The build already creeps towards 12 minutes, and I'd really rather not make that 20, and adding extra containers on circle would cost $100/month. Those nightlies will be canaries, but if there is a problem that builds green on m98 but not m95, I can't yet say what I'd do. I've just asked Frank to release m98; once that is done I'll start a discussion on simultaneous releases for all platforms. But this really is out of my hands.

In any case this all is going to change rather soon because in a few months, tops, Zotero has planned to EOL the plugin version, and Juris-M is bound to follow. At that time I will have to re-do my test suite, but right now the little time I have to spare is consumed getting the verflixte 5.0 port behind me. After that the test suite will consume all of my time, which should be in time for Zotero/Juris-M port towards Electron, which will, in turn, consume all my spare time.

You are of course welcome to freeze BBT, but where I have some wiggle room in supported Zotero/Juris-M versions, I absolutely cannot address problems on anything but the latest release of BBT. I will always ask people to upgrade before submitting an issue. I lack both time and infrastructure to cherry-pick things between versions.

**Comment by drammock** [comment]
that's fixed it, thanks!  I'm surprised to hear you say that Zotero plans to EOL the plugin version.  A recent email from Frank said:

> Zotero are offering Zotero 5.0 as Standalone installers and a Firefox plugin, but I will be offering only the Firefox plugin for the Juris-M 5.0 release.

I ask because the [Zotero Development Roadmap](https://www.zotero.org/support/development_roadmap) seems to have ended about 4 years ago and I didn't see anything in their GitHub repos about it...  apparently I'm looking in all the wrong places.  Where do you find out such things?

By the way, I totally understand that if I decide to freeze, I'm on my own for support.  And I'm really grateful for BBT!  It still baffles me that Zotero doesn't have some built-in way of adding exportable unique identifiers...

**Comment by retorquere** [comment]
I learned about this on the Zotero developers group: "[We will, however, be discontinuing the full-featured Zotero for Firefox sooner — as early as January 2017](https://groups.google.com/forum/#!msg/zotero-dev/yy4-q_ZUA4M/UBOP9OHMEAAJ)", where full-featured means "the Zotero plugin". What will remain is the same functionality as for Safari & Chrome, which will expect Standalone to be running.

A release (.86) has been scheduled and should be out in 15 minutes or so.

**Comment by retorquere** [comment]
A feature to add reference identifiers has been promised for years. I'm not holding my breath.

**Comment by retorquere** [comment]
I'm not sure what's the plan for Juris-M, but I don't think Frank is in a position to keep the plugin going on his own. I think Frank would appreciate the heads-up -- he may not be aware of the Zotero plans, which are, as one might say, on display in the bottom of a locked filing cabinet stuck in a disused lavatory with a sign on the door saying "Beware of the Leopard".

**Comment by retorquere** [comment]
The Mozilla signing API is hung and it's always anybody's guess how long it will take for them to fix this. Mozilla won't allow me to release a new version without passing that API, sorry.

**Comment by retorquere** [comment]
OK, the new release is out. It currently passes the test suite on m95, so you should be OK. On m97 you should *probably* be OK but I can't tell. Frank said m98 will drop tonight, but he hasn't yet said whether that would be the plugin or both plugin and standalone.

**Comment by retorquere** [comment]
m98 has dropped. BBT .86 will accept both m95 and m98; .86 will complain about m95 but otherwise proceed, but in the next release, BBT will accept both m95 and m98 without further warnings or complaints.

I should qualify my policy when it comes to version-support. It's not so much that I demand the last version to be installed; for Zotero, I consider anything >= 4.0.28 supported, where the latest plugin version is 4.0.29.16. The policy, loosely formulated, is "the latest version, and all versions that behave like the latest version". In the case of Zotero, 4.0.28 introduced breaking changes against 4.0.27, so I changed BBT to match and from that point on, anything that behaved as the latest version (which 4.0.28 still does) is supported (until new breaking changes are introduced, etc).

I misapplied the "from the working version on" policy in the case of Juris-M. m97 doesn't behave like m98, so it's not supported. But m95 *does* behave like m98, so it *is* supported (until breaking changes etc, but that would also drop m98 support).
