### ISSUE TITLE
How to add \noauthor for non existing author field

### ISSUE THREAD

**Issue by Oberreiter** [retorquere/zotero-better-bibtex#608]
The Wiki link to https://github.com/retorquere/zotero-better-bibtex/wiki/Scripting-API
doesn't exist. So I don't know how to check for a non existing entry. I tried the following but it completely removes the entries with no author.

```
if ( Translator.BetterBibLaTex ) {
 if ( this.item.author == "" ) {
  this.add({ name: 'author', value: "\noauthor"});
 }
}
```

**Comment by retorquere** [comment]
Oh, that page was out of date. What you want is

```
if ( Translator.BetterBibLaTex ) {
 if ( ! this.has.author ) {
  this.add({ name: 'author', bibtex: "\\noauthor"});
 }
}
```

`value` means "something the user could have typed in" which means it gets translated to LaTeX; `bibtex` means "what the user typed in, translated to LaTeX". By passing in `bibtex`, BBT assumes you know what you're doing and uses that. The double-backslash is required because the backslash is a javascript escape character, so `\noauthor` means `<newline>oauthor` in javascript. The double backslash means "no, actually a backslash".

No idea why your script would remove the entry entirely. The check for `this.item.author == ""` should fail because `this.item` (which is the zotero reference, not the bibtex reference) will never have the `author` field, thus it should be `undefined`, thus it should not match `""`. But perhaps it was not `undefined` but `null`, and `null` _does_ for reasons wholly mysterious match `""`, so that would always try to set `author`, but if `author` happens to be set already, it will throw an error, as you can't have more than one. The translators are not allowed to speak to you, the user, so the only thing that can be done is log to the error log -- maybe there's something there. In any case, should you want to replace a field, you could do so by adding `, replace: true` to the `.add` call, but the script above will check whether `author` is present before trying to add the fallback.

@njbart, is `\noauthor` something I should just add when no author info is present?

**Comment by Oberreiter** [comment]
I have to cite a certain abbreviation when no author is given. So i fund [Biblatex abbrevation for no author/editor/year/etc. in alphabetic style](http://tex.stackexchange.com/questions/213987/biblatex-abbrevation-for-no-author-editor-year-etc-in-alphabetic-style). So I needed a convenient method of getting {\noauthor} in my bib file. So I found your zotero addon.
And by adding the curly brackets I've got what I wanted.
```
if ( Translator.BetterBibLaTex ) {
 if ( ! this.has.author ) {
  this.add({ name: 'author', bibtex: "{\\noauthor}"});
 }
}
```
Thanks
Andreas
