### ISSUE TITLE
Title Export-Error in German papers and books

### ISSUE THREAD

**Issue by uni-hb** [retorquere/zotero-better-bibtex#614]
Hi,

i have a lot of german paper and books in my work. If I´m trying to export from Zotero with Better BibTex, the add-on changes the names to this:
title = {Der {{Güterverkehr}} von Morgen {{LKWs}} Zwischen {{Transporteffizienz}} Und {{Sicherheit}}},

correct would be (used normal bibtex export from Zotero):
title = {Der {Güterverkehr} von morgen {LKWs} zwischen {Transporteffizienz} und {Sicherheit}},

So some of the words whitch shouldn´t start with a capital letter get somehow a transformation.
So far this is only happening with german titles not the english ones.

Any ideas how I can fix this problem?

Best regards
Alex

**Comment by retorquere** [comment]
If you set the language of the reference to German the behavior will be turned off. What the default Zotero exporter does is in fact not correct; German (or more specifically: non-English) titles should not get capitalization protection at all, and if you don't mark your references as non-english, some bib(la)tex styles will still try to capitalize `von morgen` when rendering your document.

**Comment by retorquere** [comment]
Wait what? This is not happening with your English references? Can you submit a sample of an English reference which doesn't get recapitalization by right-clicking it and selecting "report BBT error"?

**Comment by uni-hb** [comment]
ICSKJ57D

this english ref is working fine:
@inproceedings{falie_noise_2007,
  title = {Noise {{Characteristics}} of {{3D Time}}-of-{{Flight Cameras}}},
  volume = {1},
  doi = {10.1109/ISSCS.2007.4292693},
  abstract = {Time-of-flight (TOF) cameras are based on a new technology that delivers distance maps by the use of a modulated light source. In this paper we first describe a set of experiments that we performed with TOF cameras. We then propose a noise model which is able to explain some of the phenomena observed in the experiments. The model is based on assuming a noise source that is correlated with the light source (shot noise) and an additional additive noise source (dark current noise). The model predicts well the dependency of the distance errors on the image intensity and the true distance at an individual pixel.},
  timestamp = {2016-06-20T07:14:57Z},
  booktitle = {2007 {{International Symposium}} on {{Signals}}, {{Circuits}} and {{Systems}}},
  author = {Falie, D. and Buzuloiu, V.},
  month = jul,
  year = {2007},
  keywords = {3D time-of-flight cameras,Additive noise,additive noise source,cameras,dark current noise,distance errors,distance measurement,Image analysis,image intensity,Image processing,image sensors,Information analysis,Laboratories,Layout,Lighting,light sources,measurement errors,modulated light source,optical modulation,optical noise,Pixel,shot noise,TOF cameras},
  pages = {1--4}
}

**Comment by retorquere** [comment]
Yeah but that has undergone title casing. It's just that all the words that weren't already capitalized are always excluded from titlecasing (words like `on`, `and`, etc). The rules for title/sentence-casing and how bib(la)tex expects its input are language-dependent and [somewhat crazy](https://github.com/retorquere/zotero-better-bibtex/issues/383).

**Comment by retorquere** [comment]
You don't have to fully type out `German` in the language field BTW. If you type `ger` BBT will know enough.

**Comment by uni-hb** [comment]
Ahh, ok !

Thank you for the quick response. :-D

**Comment by retorquere** [comment]
Zotero references have a `language` field.

The Zotero export treats every reference as English but then doesn't follow the proper bib(la)tex rules. Zotero recommends that references be stored in Zotero in sentence case, as that is what the embedded citation processor expects. Bib(la)tex needs references in Title Case for English references (but English references only) and sentence case for non-English. The default Zotero export does a little bit of both; it does do caps protection (which it shouldn't for non-English) but it does not do title-casing (which it should for English titles given its own recommendations)

It is possible to suppress title casing (even though this will on occasion yield non-compliant bib(la)tex) by typing `about:config` in the address bar of Firefox (assuming you use the plugin version of Zotero), searching for `suppressTitleCase`, and set it to `true`. This will keep caps-protection but will never title-case, regardless of language set or not set (also not for references explicitly marked as English!)

**Comment by njbart** [comment]
Let me just point out that `title = {Noise {{Characteristics}} of {{3D Time}}-of-{{Flight Cameras}}},` does *not* exemplify best practice – one should use `[Noise characteristics of 3D time-of-flight cameras]` in Zotero, which BBT exports (correctly) as `title = {Noise Characteristics of {{3D}} Time-of-Flight Cameras}` (both bibtex and biblatex).

Also, at the risk of sounding pedantic, ‘sentence case for non-English’ is not quite right, since non-English languages just don’t make a distinction between title case and sentence case: they have one case that never changes (and though this often *happens* to look like sentence case, it doesn’t always, as e.g. in German).

Finally let me add that I’m not a big fan of a `suppressTitleCase` option. I feel there’s only one way to skin this particular cat, and BBT is already doing it quite well. Providing an option which, as you say yourself, ‘will on occasion yield non-compliant bib(la)tex)’ will ultimately do more harm than good.

**Comment by retorquere** [comment]
You're right that "sentence case for non-English" isn't correct. When the reference is non-English, BBT and biblatex alike will just trust the capitalization as you put it in. 

I don't like the option either, and I don't want to encourage it, which is why it's a hidden option. But the request to "do what zotero does" comes back occasionally (in the tracker but also just through mail) and some people are quite adamant. It's less effort for me to direct them towards the hidden pref than it is to explain this quite complex issue (and life's too short, and I'm too busy). I personally had absolutely no idea biblatex was so complex under the hood, so I can easily imagine people not knowing or caring about this behavior.

**Comment by retorquere** [comment]
And not only is the time-of-flight reference not best practice, there are styles (Chicago?) where it will simply yield the wrong result.

**Comment by njbart** [comment]
Actually it’s `apa.csl` and `biblatex-apa`, and other sentence-case styles that will yield the wrong result with either `[Noise Characteristics of 3D Time-of-Flight Cameras]` or `title = {Noise {{Characteristics}} of {{3D Time}}-of-{{Flight Cameras}}},`.
