### ISSUE TITLE
Enable bibliography and citation-key QuickCopy simultaneously?

### ISSUE THREAD

**Issue by JessRiedel** [retorquere/zotero-better-bibtex#628]
I would like to be able to use one command to copy the full BibLaTeX bibliography, and a separate command to copy a citation key (e.g., \cite{author2018title}).  (Here, "command" can mean a shortcut like Cmd-Shift-C, or a menu option like "Edit > Copy Bibliography".)  Is this possible?  Currently, I can only get one to work at a time, and would have to go into preferences to change back and forth.

There are two categories in the drop down list at Zotero Preferences > Export > QuickCopy > Default Output Format.  They are "Bibliographic styles" and "Export formats".  [According to dstillman at Zotero](https://forums.zotero.org/discussion/comment/267820), if any of the options listed under "Export formats" are chosen, then "Edit > Copy Citation" will never work.  

"Edit > Copy Bibliography" and regular Drag&Drop both work, and do the same thing.  If one chooses "Better BibLaTex", then they produce full BibLaTex bibliographies.  If one chooses "Better BibLaTex QuickCopy", then they produce just a citation key (e.g., \cite{author2018title}). But there doesn't seem to be a way to produce bibliographies using "Edit > Copy Bibliography" and citation keys using "Edit > Copy Citation" (or Shift+Drag&Drop, or whatever).

Btw, I looked at [the thread with wilkohardenberg above](https://github.com/retorquere/zotero-better-bibtex/issues/311), but this doesn't seem to be an issue with Zutilo since I don't have that add-on.  The only other add-ons I have are ZotFile,  Zotero Word for Mac Integration, and Zotero LibreOffice integration. Disabling them changes nothing.

I also looked at [this thread with mmwood](https://github.com/retorquere/zotero-better-bibtex/issues/195), and I'm unsure if it's the same issue.

**Comment by retorquere** [comment]
No, this is a more fundamental issue than those two. Can it be done? That depends on what you mean with "can"; if you ask a programmer "can it be done", (s)he'll be answering one of these two questions:

1. Is there a law of nature, a formal rule of logic, or an engineered restriction (e.g. security measures) in place that makes your request physically and/or logically impossible? Then the answer is "no", otherwise it is "yes"
2. Is it feasible to do in a reasonable time? On the embedded assuming that question 1. yields "yes", the answer becomes contingent on the reasonableness of the effort.

In your case, 1. nets you a "yes", but 2. leans strongly towards "no" -- certainly not without outside help to provide expertise I lack.

To explain. Those two paths through the application do two very different things in Zotero, and each have engineered restrictions<sup>1</sup> in place that make them very hard to (ab)use for these purposes.

1. calls their exporter infrastructure (which is what BBT hooks into) and as you've found, you can only set one quick-export which is triggered by Zotero for the drag&drop, the associated hotkey (I always forget which) etc. There's no other path for me to hook into in Zotero that would allow choice here. I could engineer a second path, but as you may have noticed, UI work is not my forte, so I try to hook into existing infrastructure where I can.<sup>2</sup>

2. , "Copy Bibliography", calls the embedded citation processor combined with a CSL style you chose and a formatter (usually HTML) and and generates a fully-styled bibliography. It would *in principle* be possible to make a CSL style that simply dumped all fields for the references in a biblatex-compatible layout, and then install a formatter in Zotero to convert those fields into biblatex, but this would be pretty complicated work even if you were pretty familiar with CSL (and I am not); you'd be fighting the tool's purpose every step of the way.

---

<sup>1</sup> although they're not engineered *as* restrictions but their intended purpose means they have been built in such ways that there are no obvious and cleanly usable places to hook into them.

<sup>2</sup> even if that infrastructure wasn't strictly speaking meant to be hooked into. This specific aspect is making the BBT port to 5.0 especially tricky BTW so I have learned not to do this too often. UI work has the same problems, and these problems are going to become even greater once Zotero moves away from Firefox, which is due within weeks -- existing UI work will not work at all in the non-Firefox Zotero and will have to be re-done from scratch.

**Comment by JessRiedel** [comment]
OK, thanks very much for your illuminating reply. I can imagine ways to hack around this (e.g., a new shortcut that swaps between two choices of export format), but it would add complexity without helping many people besides me. Cheers.
