### ISSUE TITLE
Lack of option to disable citation key exported in extra field

### ISSUE THREAD

**Issue by eds89** [retorquere/zotero-better-bibtex#630]
Hello,
Currently, there's no way to disable the citation key exportation in the Extra field (as the string 'bibtex: citationkey'). In my Zotero, the extra field is used together with the Google Scholar Citations plugin, which automatically update it with the most recent number of citations.

Omitting the extra field from exporting will not help as it is exported in some custom translators I wrote for myself. I believe an option to disable citation key exportation in the extra field would be ideal.

**Comment by retorquere** [comment]
This cannot be done without help from the Zotero authors, for reasons of the combined effects of these two issues:

1. The exporters are fully isolated from each other; I cannot influence what the non-BBT exporters will write out (this is a good thing in principle).
2. Extension writers such as myself have been clamoring for years for a way to write extension-related data into the reference in a clean way, but the consistent response has been "it is coming some day, but in the meantime, just write it in the `extra` field"

I'd dearly love to write the information elsewhere as it adds complexity for me to (I have to watch out for infinite recursion on save for example), but there doesn't seem to be much progress. It's now slated for "somewhere after Zotero 5.0 releases", and since my own port to 5.0 still needs to be done, this is still an indeterminate but long way off.

Sorry about this, but it's effectively out of my hands.

**Comment by retorquere** [comment]
(I mean, you could stop pinning your citekeys and they won't be written in the `extra` fields, but then you have to make do with whatever is generated, and disambiguation-postfix when you sync your library becomes a crapshoot)

**Comment by retorquere** [comment]
closing for lack of feedback
