### ISSUE TITLE
creating a key with [authForeIni] not working

### ISSUE THREAD

**Issue by tobi2192** [retorquere/zotero-better-bibtex#648]
I'm running on Zotero Better Bib(La)Tex 1.6.94 for Firefox on MacOS Sierra. 
I'm not able to use [authForeIni] the from the JabRef key formatting syntax to create a key pattern. It says invalid pattern "authForeIni"

**Comment by retorquere** [comment]
Can you try [this version](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.94-br648-3604.xpi)?

**Comment by tobi2192** [comment]
Now it's working, thanks!

**Comment by retorquere** [comment]
Super, I've merged it to master and it will be part of the next release. You can safely keep using this version until that goes out, and you'll automatically be upgraded.

**Comment by tobi2192** [comment]
Oh, actually I found a minor bug with it: If there are two authors, [authorLastForeIni:upper][auth1:upper] gives me the first letter of the forename of the second author and the first letter of the lastname of the first author, istead of the initials of the first author.

**Comment by retorquere** [comment]
Isn't that what it's supposed to do?

According to the [jabref explanation](https://help.jabref.org/en/BibtexKeyPatterns):

* `[authorLastForeIni]` gives "the forename initial of the last author". Since there are two authors, the second author is the last, so you get the first letter of the forename of the second author. 
* `[auth1]` is actually `[authN]`, which gives "the first N characters of the first author’s last name" (Where `N` is `1` in this case), so: the first letter of the lastname of the first author.

**Comment by tobi2192** [comment]
Your right. I copy-pasted the wrong command, I'm sorry.

**Comment by retorquere** [comment]
No problem.
