### ISSUE TITLE
slow firefox startup again

### ISSUE THREAD

**Issue by rcoreilly** [retorquere/zotero-better-bibtex#687]
I just experienced the dreaded 10's of minutes firefox restart with the latest firefox update -- had debugging on so hopefully the report:  A7CZJD72 contains some useful info.  Per Jessica Mollick's previous report, I went to about:config when it finally finished startup, and saw that although the `extensions.zotero.translators.better-bibtex.scanCiteKeys` was set to false, the `services.sync.prefs.sync.extensions...` version of this preference was set to true, and indeed *all* of those settings were set to true.  See attached screenshot.  I toggled the scanCiteKeys there to false, and restarted firefox, and startup was fast.

However, I then tried turning that setting back to false and restarted and it was also still fast!  So I'm not sure this has anything to do with it.  Anyway, hopefully the report will give some useful info, and let me know if there is anything else I can try.  Thanks as always for such a great tool!

<img width="847" alt="screen shot 2017-07-24 at 2 26 53 am" src="https://user-images.githubusercontent.com/9605819/28501522-544934d0-7018-11e7-9257-2ce8fc97f1e3.png">

**Comment by rcoreilly** [comment]
ps. this happened right after upgrading to firefox 54.0.1 -- in general upgrades seem to trigger this problem

**Comment by retorquere** [comment]
The `services.sync.prefs.sync.extensions....` don't do anything anymore and will be removed in the next version; they wouldn't have caused slowness in any case because all those would do is sync the values of your settings across firefoxen if you were logged in to Firefox sync -- except I have never seen it work in practice. So having them true or false made no difference.

scanCitekeys *will* cause slowness, but it's turned off automatically after a scan, so by the time Firefox is responsive again, it will be `false`. You did experience a citation key scan triggered by the upgrade, but that mechanism is going to change in the rewrite I'm [currently doing for Zotero 5](https://github.com/retorquere/zotero-better-bibtex/issues/555). Upgrades of Zotero will no longer trigger a key scan in the Z5 version.

**Comment by retorquere** [comment]
Closing -- Z5 will be a wholly different beast, hopefully this will be better there.
