### ISSUE TITLE
Merge duplicates citekey selection and change issue

### ISSUE THREAD

**Issue by mijalche** [retorquere/zotero-better-bibtex#710]
Hi, 
I was testing for error #707 and there was no problem, however then I tried to merge the duplicates and observed the following:
- sometimes Zotero asks you which version you want to use but sometimes it does not. When Zotero does not ask you, it selects one of the citekeys, not necessarily the first one. When Zotero asks you which dulicate to use as a master. In the right reference panel it does not show the citekeys, so you need to assume that the first duplicate in the list has the citation key without the a,b,c or other extension. It will be good in the right reference panel also to display the citation key for the reference. 
- if after I create the duplicates I change the citation key format and I perform merge the old citation keys (based on old format pattern) are deleted and the merged reference have a completely new citation key based on the new pattern.
Error ID: E8UYMBK2 (before merging)
Error ID: 2CU9LPI6 (after merging)

**Comment by retorquere** [comment]
Wow, those are big points. This worked the same in Z4 BTW, so I'm marking it as an enhancement. On these points:

## Merging references

Zotero wants to edit these fields back into the target item; but the citekeys are not part of any of the items being merged, they only live in the BBT database. Patching around all this behaviour is super tricky and fragile, and I'd preferably wait until Zotero finally gets a proper field for the citekey, as it will make this process a *lot* more manageable.

I do display the citekey in the reference details but that takes a fair amount of trickery and the citekey is non-editable because editing that field yielded some nasty race conditions.

## Changes to dynamic keys after merge

That would be correct, as references with dynamic keys will get a new citekey whenever they change (and the merge is a change); the only exception to this is if the item being saved by Zotero happens to generate the same base key, but that base key is taken, *and* the postfix it had before is not in use by another reference. So if you have `gop2014` and `gop2014b` (presumably because you also had `gop2014a` but deleted it), and you change `gop2014b` in such a way that it would get `gop2014<postfix>`, BBT will try to retain `gop2014b` for that reference. In all other cases, it gets a fresh key. This is the nature of dynamic keys; any reference you change in any way after you change the pattern will get a new key according to that pattern, which a proviso that the postfix (but only the postfix) may be retained. This behaviour is here to stay, in principle, but once the real citekey field in Zotero emerges and they support it in the merge field I may make an exception to keep the selected key.

**Comment by nicholas-walters** [comment]
My workaround for this issue to right-click on the item in the library and select "Duplicate" item, it will generate a new item with the correct citation key. I then drag any associated files from the old merged item and deleted the merged copy. Tedious, but better than manually addressing all duplicates in the library without the built in duplicate items functionality.

**Comment by retorquere** [comment]
Wouldn't just refreshing the key be easier?

**Comment by nicholas-walters** [comment]
For clarity, in my case I merged two references in the library that had citation keys of Dellacorte2009 and Dellacorte2009a. I choose the reference with the citation key of Dellacoete2009a as the master that would remain and the resulting reference had the Dellacorte2009a citation key despite there being no Dellacorte2009 citation key in the library. 

Refreshing the citation key did not resolve this. I had this happen in two separate instances as well.

**Comment by retorquere** [comment]
Ah I see. Correct, duplicating the item will get you the desired effect, but in this case I'd personally opt to just pin the citekey to `Dellacorte2009a`. The BBT keymanager aims to be conservative about removing postfixes, so duplicating (which gets you the postfix) and then removing the original will work, but if you want to be sure, pin it.

**Comment by retorquere** [comment]
In #1221 I now have a solution where the merged keys are retained, regardless of which way the merge goes.

**Comment by retorquere** [comment]
(but it won't fully help for dynamic keys)

**Comment by retorquere** [comment]
This is fixed in latest BBT -- citekeys (dynamic or not) will be added in the `ids` field for the merged items.
