### ISSUE TITLE
Question: Why no auto-export with files?

### ISSUE THREAD

**Issue by mijalche** [retorquere/zotero-better-bibtex#750]
I do not remember was this discussed previously for Zotero 4, but why there is no option for auto-export with files? Can this be added in BBT for Z5? In my opinion this could be a good option and will support full integration with some apps like PocketBib. 
Thanks!

**Comment by retorquere** [comment]
It conflicts with the caching system; I cache the formatted references so if you export a large collection because one reference changed, only that one needs to be regenerated; BBT is [pretty slow](https://github.com/retorquere/zotero-better-bibtex/wiki/Performance) without the cache.

When exporting files, the same reference would get a different absolute path to its attachments depending on location of the bib file of the auto-export (meaning the exported reference I have cached is unusable). If I allow exporting the attachments that would mean I would have to skip caching (slow) or partial caching (a level of complexity I don't want to take on).

The main target for BBT is paper-writing, not app interoperability; looking at the App Store, Papership gets good ratings, perhaps that will be of help.

**Comment by mijalche** [comment]
Thanks! It is better BBT to be fast. I will explore Papership
