### ISSUE TITLE
Default BibLaTex Citation Keys Changed After Update

### ISSUE THREAD

**Issue by wraabe** [retorquere/zotero-better-bibtex#853]
## Background
I updated Zotero this morning, as Zotero demanded update to 5.0.33. It had a warning screen on top, and it would not permit the going directly to automatic update. So I went to Zotero.org, downloaded, installed. After install, Better BibLaTeX no longer active inside updated Zotero. So I clicked Activate. Then it started process of citation key database updates. 

## Problem

I received no warning about updating default citation keys. 
Custom citation keys remained consistent after, the default citation keys have changed format:

 - Old Style: bailey_new_1851-1
 - New Style: BaileyNewStoryMrs1851a

## Observations

I can't judge the pop-up warning about changing default citation keys because I never saw it. 

This may not be a technology problem per se but a workflow consistency problem. If a person, as I did, relied on default citation keys as references, those old LaTeX documents will continue to work with old exported .BIB files. 

But going back to those documents (and updating them) will mean that exports of new lists of citation references will need to be worked on manually, outside Zotero. Can no longer just export all the citation references after updating them, as defaults will have changed.

**Comment by retorquere** [comment]
When did you upgrade to Zotero 5 (and consequently, to BBT for Z5)?

I don't know what happened here. `[auth][shorttitle][year]` has been the default for BBT for a really, really long time. I have put out a Z5 compatible version by accident that had `[zotero:clean]` as the default, but changed that right back a few days later.

BBT has since been changed to only apply the default once; if you install BBT, it looks if you have an existing pattern (default or not), registers that, and won't change it after. If you didn't have it, it should warn you about it before fixing the pattern in place. I don't know why you haven't gotten this popup.

In any case, there is no need to change your existing documents. You can restore them all at once by:

1. Selecting all your references,
2. Right-click
3. Pick `refresh` from the menu that popped up.

I'd appreciate confirmation that this restored the citation keys for you.

**Comment by retorquere** [comment]
Wait, BBT was deactivated by Zotero? What platform are you on? I am on a Mac right now; I could update from within Zotero to 5.0.33, and after the restart BBT was active.

**Comment by wraabe** [comment]
On BBT preferences, it does not permit me to change citation key format. When I copy in [zotero:clean], it returns it to [auth][shorttitle][year] immediately upon tabbing off the field. 

On Mac. And yes, BBT was deactivated by Zotero after reinstall. I was not permitted to update via the  recommend update screen at Zotero startup, because of a warning. I had to close Zotero and install update with Zotero closed. When I restarted, BBT inactivated.

**Comment by retorquere** [comment]
If you type `[zotero:clean]` in that field, does it turn orange? If you hover over that field, what does the popup text say?

I've never seen a message on manual upgrade in Zotero, nor have I ever seen BBT been disabled after a Zotero upgrade between minor versions. Were you on Zotero 4 when Zotero demanded update to 5.0.33?

**Comment by retorquere** [comment]
Can you go into your Zotero profile, look in the `better-bibtex` folder, and see if you can find any files ending in numbers there?

**Comment by wraabe** [comment]
error: invalid filter 'clean' in pattern

**Comment by wraabe** [comment]
None end in numbers. Two .bak files do end in numbers before the bak, zotero.sqlite.1.bak (dec. 20) and zotero.sqlite.77.bak (today, 10:01 am)

**Comment by retorquere** [comment]
Wait, what version BBT are you on?

**Comment by retorquere** [comment]
Those sqlite files are in the main zotero profile folder; is there no subfolder called `better-bibtex` in there?

**Comment by wraabe** [comment]
BBT Version 5.0.49 (updated this morning).

All with numbers:
cache.json.1
cache.json.2 (thru 5)

db.json.1
db.json.2 (thru 5)

**Comment by retorquere** [comment]
What did you upgrade from? 5.0.49 is a month old; BBT is at 5.0.59.

Can you get me a copy of the files in the `better-bibtex` folder, as well as your `prefs.js`? I'm not sure what's going on but an upgrade this morning should not have gotten you 5.0.49.

Have you just now upgraded from Z4 to Z5? That would explain BBT being disabled because you'd have a Z4-compatible BBT in Z5.

**Comment by wraabe** [comment]
Better BibTex Folder:

[better-bibtex-folder.zip](https://github.com/retorquere/zotero-better-bibtex/files/1583374/better-bibtex-folder.zip)

prefs.js (changed extension from js so GitHub would accept)

[prefs.txt](https://github.com/retorquere/zotero-better-bibtex/files/1583382/prefs.txt)

**Comment by retorquere** [comment]
I really need to know whether you just upgraded from Zotero 4 to 5

**Comment by wraabe** [comment]
I have set Zotero for automatic updates, and I use it regularly, so I assume I updated to 5.0 around July 2017, shortly after release.

**Comment by retorquere** [comment]
So you did not upgrade Zotero recently then.

Did you upgrade BBT back in July, or just now?

**Comment by wraabe** [comment]
I did upgrade Zotero, but I assume I was already at 5.0.30 or 5.0.31, or 5.0.32, from last month or so.

I upgraded BBT just this morning. I'm not aware of having done updates to BBT recently (without some kind of nagging to get me to do it, I'm not likely to do it when it's working).

**Comment by retorquere** [comment]
I mean were you already using BBT since July, or has it always sat there disabled until today?

**Comment by wraabe** [comment]
Using it regularly during entire fall semester. Never disabled. Multiple documents.

**Comment by retorquere** [comment]
Then I really don't know why 

1. Zotero chose to disable BBT during this upgrade. It would be explainable if you upgraded Zotero from 4 to 5 but still had BBT 1.x. Zotero 5 would indeed disable BBT 1.x
2. You upgraded today but are still on a month-old version.

If you go into Zotero addins and let it search for new versions of extensions, does it find the newer BBT?

**Comment by wraabe** [comment]
OK, that worked. I had Zotero Plug-Ins set on "Default," which I assumed meant auto updates. Apparently not. So I used the "check for updates" menu (did not even know that gear had a pop-up). It updated and gave the message. I was able to set it to [zotero:clean] now. But it looks to me like it's still changing default ones to new style.

**Comment by retorquere** [comment]
"Still changing" in what sense? Have you done

1. Selecting all your references,
2. Right-click
3. Pick refresh from the menu that popped up.

since setting the new pattern?

I also still don't know how you ever got zotero-like keys from BBT by default. The default hasn't been zotero-like since forever.

**Comment by wraabe** [comment]
Refresh fixed it. Thanks much. All is well with my citation keys.
