### ISSUE TITLE
Thin space in author name

### ISSUE THREAD

**Issue by Edenharder** [retorquere/zotero-better-bibtex#859]
# Bug

Report ID: MQ2IG29M

The name `Versteegh, Marijn A. M.` is exported as `Versteegh, Marijn A.\,M.` and cause latex errors.

The full reference is [here](https://journals.aps.org/prl/abstract/10.1103/PhysRevLett.115.250401)

Happy new year!

**Comment by retorquere** [comment]
First: One problem, one issue please. I will be dealing with the problem you mentioned as a bug here. Please open a separate issue for the feature request.

There's a "thin space" (unicode character 8201) between `A.` and `M.`, not a space. A thin space is denoted in LaTeX as `\,`. Unfortunately it's impossible to see by eye whether you have a space or a thin space, but it's there in the error report.

**Comment by Edenharder** [comment]
Thanks for the solution! I have a question, could there be a "thin space" in the field of authors' names generally? I fetched these reference automatically with the plugin of zotero in Chrome.

**Comment by retorquere** [comment]
I've not seen this happen before, so I'd say it's not something that happens generally. It's certainly not in my test set (1.5k references) or my own library (3.5k references).

**Comment by retorquere** [comment]
I'm surprised it causes latex errors BTW. I've added it to an [MWE](https://www.sharelatex.com/project/54feca38f58d781e0c982eeb) and that compiles cleanly.

**Comment by Edenharder** [comment]
It's an error caused by `biblatex`, please find the source in [MWE](https://www.sharelatex.com/project/54feca38f58d781e0c982eeb)

**Comment by retorquere** [comment]
@njbart, do you think this is an error in biblatex, or should BBT be producing different output?

**Comment by njbart** [comment]
I tend to think that `\,` just isn’t permitted in a biblatex name field. You might want to use a thin space in formatted output for aesthetic reasons, but it just doesn’t make sense in an input string (even if it did not throw an error, it would interfere with parsing the string into separate first names or initials). If you don’t just want to take my word for it, bring it up on the biblatex bug tracker – but what I’d do is, just replace it with an ordinary space char.

**Comment by retorquere** [comment]
But this would be specific to names then.

**Comment by njbart** [comment]
Yes, indeed.

**Comment by retorquere** [comment]
So the problem now is I can't find a unicode class that maps onto space-ish characters, so this would be a hard coded list of characters that would map to a space.

What would be done with non-breaking spaces? Zero width spaces?

**Comment by njbart** [comment]
Non-breaking spaces (`~`) can appear in bibtex and biblatex names (Ward 1998; Hufflen 2006).

Zero width spaces – no idea. In any case, they don’t seem to throw errors as `\,` does.

---

Hufflen, Jean-Michel. 2006. “Names in BibTeX and MlBibTeX.” *TUGboat* 27 (2):243–253. https://www.tug.org/TUGboat/tb27-2/tb87hufflen.pdf.


Ward, Gregory P. 1998. “btOOL: An Object-Oriented Library for Processing BibTeX-Style Text Databases.” School of Computer Science, McGill University. https://gerg.ca/software/btOOL/btOOL.ps.gz.

**Comment by retorquere** [comment]
So that complicates matters. Is the non breaking space special because it's the only space-ish character that does not need to be replaced by a standard space, or is the thin space special because it should be?

**Comment by njbart** [comment]
On further reflection I’m coming around to the view that **none** of the space chars mentioned here so far (thin, non-breaking, zero-width) that may have been entered into a Zotero field (or obtained from some upstream source) should be exported to bibtex, biblatex, CSL JSON, or CSL YAML. 

While the non breaking space (`~`) can be used in both bibtex and biblatex to influence name parsing, I can’t think of any parsing decision you could sensibly try to influence from within Zotero by entering special space chars in a name field. (A multi-part surname, e.g., is protected by quotes in Zotero, not by joining the parts with a `~` char as you might do when using bib(la)tex.)

So, in my view, all thin & non-breaking space chars should be replaced with ordinary space chars, and any zero-width chars should be removed from names.

**Comment by retorquere** [comment]
I have an existing testcase that when given 
```
"lastName": "Medici",
"firstName": "Lorenzo de’<200b>"
```

used to export

```
author = {de’\mbox{} Medici, Lorenzo},
```

but which now exports

```
author = {de’ Medici, Lorenzo},
```

is this OK?

**Comment by njbart** [comment]
In this particular case, the zero-width space should be kept – it’s a special case because the citeprocs remove the space after a particle ending with an apostrophe, so the zero-width space is there to preserve the space. In fact, `de’ Medici` is the only name I’m aware of where this is necessary.

So the ZWS should be preserved in CSL JSON and CSL YAML output. (It seems to, but currently, after entering a zero-width space char at the last char in a Zotero first name field, I’m seeing it briefly in BBT’s CSL YAML output, but then the zero-width space char disappears from the Zotero field and from BBT’s output  – as if something was cleaning up the Zotero field. Any ideas on this?)

Are there any other invisible chars one might use for this purpose? (IIRC, you have been using a special char to do some trickery with the new biblatex name format and multi-char initials …)

For biblatex, the ZWS should be mapped to something, too. Can’t remember whether `\mbox{}` works with latex (but will try this later); in any case this does not seem ideal, since `author = {de’\mbox{} Medici, Lorenzo},` doesn’t seem to do preserve the space if used with pandoc-citeproc.

**Comment by retorquere** [comment]
I use `\u0097` (end of guarded area) to mark initials in the first name so `Ph\u0097ilippe` gets shortened to `Ph.` rather than `P.`; `\u200C` (zero-width non-joiner) also has special meaning but it's only used internally to help with the initials stuff. In any case, I should just simply let the zero-width space through then.

As to the mbox, I thought you preferred that:

* https://github.com/retorquere/zotero-better-bibtex/issues/566
* https://github.com/retorquere/zotero-better-bibtex/issues/565
* https://github.com/retorquere/zotero-better-bibtex/issues/384

No idea who would be doing the cleanup -- not me.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5243](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.64.5243.issue-859.xpi) ("leave ZWS alone for now").

**Comment by retorquere** [comment]
5243 replaces space-ish things but leaves the ZWS handling as it was for now.
If we have a known-to-work thing for bibtex/biblatex for `de' Medici`, shouldn't either pandoc adapt, or promot the use of the CSL formats?

**Comment by njbart** [comment]
Ok, looking over my comments in #566, #565, and #384, I’m positive that `\mbox{}` did work with latex back then, but something seems to have changed. Currently (latest TeX live), the ZWS seems to work with biblatex/latex, too, so maybe BBT should just export that to biblatex instead of `\mbox{}`.

I’m still puzzled about ZWSs (and zero-width non-joiners, too) disappearing from Zotero, though …

**Comment by retorquere** [comment]
BBT is very conservative about changing references. I only call `setField` on the `extra` field (just re-checked), and only save references in 3 instances:

* When a "pin citekey" is requested by user interaction
* When a "unpin citekey" is requested by user interaction
* When "scrub database" is enabled by the user, and that only happens once, at start (and only changes the `extra` field as mentioned)

So I'm fairly sure it isn't me.

**Comment by retorquere** [comment]
I can't find any relevant mention of 200b in the Zotero sources, either.

**Comment by njbart** [comment]
I never really thought it was you – but can you reproduce this (with a ZWS at the end of a first name field)?

**Comment by retorquere** [comment]
I'm testing that now. How long did you have to wait, and are you also on Zotero .33?

In extended name format, this now exports to

```
author = {family=Medici, given=Lorenzo, prefix=de’\u200B, useprefix=false}
```

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5246](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.64.5246.issue-859.xpi) ("pass through ZWS in unicode mode").

**Comment by njbart** [comment]
Right, 5.0.33. I had to wait just a few seconds.

`author = {family=Medici, given=Lorenzo, prefix=de’\u200B, useprefix=false}` is no good, unfortunately. It has to be `\mbox{}`.

**Comment by retorquere** [comment]
I've waited more than a few seconds and it's still there.

That second point really complicates matters a lot... the unicode -> latex mapping works without context right now so the translator (which may be called several layers down) has no concept of "I'm translating this unicode to latex for the purpose of...". I can't differentiate between "translating for regular name output" and "translating for extended name output" because I have no concept of "translating for". And the unicode translator has its own internal state; I can't just replace `\mbox{}` with `\u200b` or visa versa.

**Comment by njbart** [comment]
But BBT currently maps a ZWS to `\mbox{}`, right? Can’t you just leave that unchanged?

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5247](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.64.5247.issue-859.xpi) ("restore 200b -> mbox").

**Comment by retorquere** [comment]
5247 restores that (I had removed the ZWS mapping); so now the behavior is just "replace space-ish things with spaces in names".

**Comment by retorquere** [comment]
The ZWS is still in the reference BTW and it shows up on export without a hitch.

**Comment by retorquere** [comment]
So, good to go on 5247? I've added @Edenharder 's reference to the test suite.

**Comment by njbart** [comment]
To be honest, except for the Medici/ZWS example, I don’t have specific test cases for any of the unusual space chars. The thin space demonstrably causes trouble for latex, and arguably doesn’t serve a useful purpose, and the latter seems true for the non-breaking space aswell – so removing these two seems fine. If you’re removing any others, I would guess that’s ok, too – but I never came across any of these, and, as I said, don’t have, and can’t really think of any test cases either.

**Comment by retorquere** [comment]
*shrug* I don't have anything in my test suite, either. I'll deal with it when it crops up.
