### ISSUE TITLE
Biblatex export uses the incorrect field for notes

### ISSUE THREAD

**Issue by DavidPowell** [retorquere/zotero-better-bibtex#867]
When performing a biblatex export, any notes get added to the `annotation` field, as is expected by bibtex. However, this field is not supported by most biblatex styles. Instead, either the `addendum` or `note` fields should be used (ideally with the ability to control which one). This is discussed in a [stackexchange answer](https://tex.stackexchange.com/a/183917/22079).

My current workaround is to use a biblatex  source map to copy the `annotation` field to the `addendum` field, then delete the `annotation` field. This can be done by putting the following code in the preamble of my .tex file:

```latex
% Rename the "annotation" field produced by Zotero export to "addendum"
\DeclareSourcemap{
  \maps[datatype=bibtex]{
    \map{
      \step[fieldsource=annotation, final]
      \step[fieldset=addendum, origfieldval, final]
      \step[fieldset=annotation, null]
    }
  }
}
```

**Comment by retorquere** [comment]
@njbart, any thoughts?

In the interim, you could do this in a postscript

```
if (Translator.BetterLaBibTeX && this.has.annotation) {
  this.add({ name: 'note', value: this.has.annotation.value })
  this.remove('annotation')
}
```

**Comment by njbart** [comment]
> However, this field is not supported by most biblatex styles.

That’s intentional – standard bibliographies as recommended by, e.g., the Chicago Manual, or APA, do not include annotations. If you want these, you will need to use (a) available package options (e.g., in plain biblatex `\usepackage[style=reading]{biblatex}` prints annotations), (b) a custom style, (c) biblatex `DeclareSourcemap` declarations (which you seem to be familiar with), or (d) a BBT postscript (as indicated by @retorquere).

I do not think, however, that BBT should change its default mappings concerning annotations in any way.

**Comment by retorquere** [comment]
@DavidPowell do these 4 options cover your needs? I try to avoid adding new config options these days -- BBT has too many knobs to twiddle with as it is.

**Comment by DavidPowell** [comment]
@njbart It's true that the standard bibliography styles do not include annotations, but they do include addendums and notes (the difference between these is unclear to me). On the other hand, bibtex styles often do include such addendums. I don't really care what they are called, I just want a way to add my zotero notes to the bibliography entries.

@retorquere Since I have the workaround, my immediate problem is solved, if somewhat inelegantly. Anyone else coming across a similar problem can use these workarounds if you decide not to make any changes. I totally understand if you don't think that this is worth your while at the moment.

**Comment by njbart** [comment]
As to the difference between note and addendum, please do consult the biblatex manual.

There’s yet another (fifth) highly customizable solution  – add this to your document preamble (tested with plain biblatex):

```
\renewbibmacro*{finentry}{%
  \iffieldundef{annotation}
    {\finentry}
    {\setunit{\finentrypunct\par\vspace{\bibitemsep}\nobreak}
     \printfield{annotation}%
     \finentry}}
```

I’m afraid it won’t get any more elegant than that.

**Comment by retorquere** [comment]
It's not a matter of being worth my while (it's not a big change), it's that it would either:

1. change the behavior that users have come to rely on (not a good idea), or
2. adds another option to BBT, where BBTs preference screen is already overwhelming

These days I only go for option 2 if it's going to be of sufficiently general interest, or there's no easy workaround; option 1 seem elegant enough to me. If there is a general interest, I'll go with option 2.

**Comment by retorquere** [comment]
I don't mean to sound flip about this, BTW. But BBT aims to produce correct Bib(La)TeX output, not necessarily cater to every individual need. For individual needs, the postscript comes in. As to the issue title ("Biblatex export uses the incorrect field for notes"), I'll have to go with @njbart 's insights on what is and isn't correct for Bib(La)TeX. He know tons more about this than I do.

**Comment by njbart** [comment]
Well, best read the (fine) biblatex manual: It describes the `annotation` field as “useful … for annotated bibliographies”, so placing annotations (in the sense of personal comments, summarising and/or evaluating the work at hand) in this field seems entirely “correct” – and existing styles designed for formatting annotated bibliographies use this field precisely.

Of course one can resort to meddling with field names and/or content in order to get styles not designed for creating annotated bibliographies to print `annotation` fields, but this is not something, I feel, that BBT should support beyond what it is already offering in terms of its postscript mechanism.

**Comment by DavidPowell** [comment]
@retorquere Your response is quite reasonable. I agree that it doesn't make sense to change this behaviour based on just a single user's request.

@njbart Thanks for the clarification. I guess what I'm trying to do is an abuse of biblatex, so I'll stick with my hack as detailed above.
