### ISSUE TITLE
Importing string definitions

### ISSUE THREAD

**Issue by rpgoldman** [retorquere/zotero-better-bibtex#878]
- [x] I am on the latest release of BBT and Zotero
- [x] I am posting a single question, bug or feature request
- [x] I have included a descriptive subject of the problem
- [x] I am available for follow-up questions and testing

# Bug classification

## Non-export problems with BBT

I have a couple of files that have only definitions of `@string` in them (`strings.bib` and `names.bib`).  When I try to import these into Zotero with better-bibtex nothing happens at all.  I suspect that this is intentional (from other things I read here on github), and that the strings are supposed to be inline-expanded only when the definitions appear in the same files as uses.

If that's right, this isn't a bug, but it might be worth documenting on the wiki, since this isn't a strange thing to do when you are maintaining a bibtex database by hand.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5361](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.74.5361.issue-878.xpi) ("@strings").

**Comment by retorquere** [comment]
Try installing 5361, then go to `Preferences` / `Better BibTeX` / `Advanced` / `@strings`, and paste the contents of your `strings.bib` and `names.bib` there. They'll be available on every following bibtex import.

I think this is the best I can do. Imports are not really supposed to have side-effects apart from creating references.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5363](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.74.5363.issue-878.xpi) ("better be explicit").

**Comment by rpgoldman** [comment]
Thanks.  I've tried it and... I _think_ it works.  Is there something I should do to test this?
I have this in my strings in the preferences:
```
@STRING{AIM		= "AI Magazine"}
```
but when I export an entry that uses it I see this:
```
$ cat ~/refs/Exported\ Items.bib 

@article{bacchus:2001a,
  title = {{{AIPS}}'00 {{Planning Competition}}},
  volume = {22},
  number = {1},
  journal = {AIM},
  author = {Bacchus, Fahiem},
  year = {2001},
  pages = {47--56},
  topic = {planning;planning-algorithms;planning-systems;}
}
```
where the `journal` field contains a "quoted" version of the abbreviation, instead of either keeping the abbreviation or expanding it.

Sorry -- I feel like I'm the QA nightmare for BBT.

**Comment by retorquere** [comment]
`{AIM}` is the literal text `AIM`, not a reference to the @string `AIM`. Try removing the braces.

**Comment by retorquere** [comment]
Uh, hold, sorry, I thought that was your input. What text did you put in the prefs screen, and what reference did you import?

**Comment by rpgoldman** [comment]
That was my bad, I'm afraid.
1. The `@string` in my earlier post 
```
@STRING{AIM		= "AI Magazine"}
```
is what is in the preferences.
2. The `@article` containing `journal={AIM}` is what Zotero + BBT exported (using BBT preference).
3. The original bib file had the following:
```
@Article{bacchus:2001a,
  author =       "Fahiem Bacchus",
  title =        "{AIPS}'00 Planning Competition",
  journal =      AIM,
  year =         "2001",
  volume =       "22",
  number =       "1",
  pages =        "47--56",
  topic =        "planning;planning-algorithms;planning-systems;",
}
```
So I think BBT must be "deciding" to quote that "AIM" string.  Note that the string definitions were _not_ present when I imported that bibliography -- they were only present when I _exported_ that entry.
It seems actually pretty difficult to decide when to quote and when not to...

**Comment by rpgoldman** [comment]
OK, so this is not a bug, then.  So what I should have done was put the contents of the 2 string definition files in first, and then imported all the bib files.

Zotero is speedy enough that that isn't a real hardship. I'll give it a whirl.

One note, though: this makes it hard to have things like journal title abbreviations that can expand to long versions (e.g., when one is doing the references for a journal article, thesis, etc.) or to short versions (e.g., for a conference paper or proposal with tight page count limits).  Or am I missing something ?

**Comment by retorquere** [comment]
That's how it's supposed to be used, yes.

wrt journal abbreviations, zotero has an journal abbreviation field, and you can have BBT generate missing abbreviations during export. Having the journal abbreviation used instead of the full journal title is something the bib(la)tex style should take care of, or you can have something in your doc preamble that replaces the journal name with the abbreviation.

**Comment by rpgoldman** [comment]
In that case, would it be reasonable for BBT to look at the journal field, and either keep it as journal title, if quoted in some form (braces, quotes, etc.), and put it in the journal abbreviation field instead, if it's a "naked" string?  That would accord with the normal practice in hand-written bib files, I believe.

Note that people like me who have used abbreviations in name fields or other locations (e.g., address, publisher) are likely to be out of luck.

**Comment by retorquere** [comment]
You can have things that look like naked strings exported as naked strings by setting a preference in BBT ("assume..." in the export tab), but that's a heuristic, the information on whether something was originally a naked string is lost on import.

Given that, no, I can't export naked strings to one field or the other because BBT doesn't really have information on the origin of any field of the references; there's no such thing as a naked string after import, only during import. The imports are also definitely not meant to round-trip cleanly; import is meant to make the most sensible Zotero reference given a bibtex reference; export is meant to make the most sensible bibtex reference given a Zotero reference, but those transformations are not wholly lossless, such as with @string vars being resolved and then lost as string vars during import. There's no way to reverse that. 

There is the option to choose "use journal abbreviations" during export. For BibTeX export, that will put the journal abbrev in the journal field. For BibLaTeX, it will just add the journal abbrev field.

You can get as fancy as you like in a postscript to apply your own heuristics to export might-be-vars to different fields, but if you really like/want what @string vars do for you, Zotero as a whole (which doesn't know the concept at all) may be a bad fit for your use case. Jabref (which has its own problems) may be better for you.

**Comment by rpgoldman** [comment]
Thank you for the clarification.  It's not so much that I need the strings to behave as they did in hand-edited Bibtex, as I needed a better understanding of how they work in BBT.  Sounds like what I need to do is redo the import with the strings loaded into the preferences, and I should be fine.  The two cases where, I believe, one needs to be able to use abbreviations that vary (short versus long) is journal titles and booktitle in proceedings type entries.

If you'd like to just mark that as closed, that would be great, and thanks for taking the time to explain this so clearly.

**Comment by retorquere** [comment]
You can have the strings preloaded in the preferences or you can prepend them to the import file -- that's just what BBT does, it prepends the strings during the import. The strings in the preferences are only really useful if you plan to do multiple imports using the same strings. So yes, you'd have to re-do the imports to have this work.

WRT the abbreviations, your description sounds right, but the bib(la)tex style should handle that properly when given both, and BBT will produce both. If your style doesn't, you can have a BBT postscript replace the journal title with the journal abbreviation, but it's not something BBT will do itself.
