### ISSUE TITLE
TeXstudio detection flames out on Windows

### ISSUE THREAD

**Issue by Melfice51** [retorquere/zotero-better-bibtex#880]
- [x] I am on the latest release of BBT and Zotero
- [x] I am posting a single question, bug or feature request
- [x] I have included a descriptive subject of the problem
- [x] I am available for follow-up questions and testing

Hello, just updated Zotero to 5.0 (running on Windows 10). For some reason, Citekeys are not being generated for any of my sources (i.e., I previously had Citekeys for each of my sources, and they have since been removed post-update). Naturally, once I try to export my existing library, it fails. I also generated a new source in my library, although when that was downloaded from Google Scholar, that too was not given a Citekey. For what it's worth, I updated next to my colleague (who has a Mac), and he appears to have had zero issues. 

I looked through the entire preferences to make sure that I matched up with the suggested guidelines, but nothing changed. I apologize if this is not the correct setup for an issue, but I am at a loss. Any assistance at all would be greatly appreciated.

Thanks!

**Comment by John-McK** [comment]
I can confirm the behavior of citekeys not being generated, using Zotero 5.0.34 and BBT 5.0.74 under Win10.
Further, if you generate the keys 'by hand' as, say, bibtex: jones2000 in the Extra field, then on export the bib file will report this as:
@article{jones_firstwordoftitle_2000... etc,

despite the citation key format being set as [auth:lower][year]
HTH

**Comment by retorquere** [comment]
Are you guys sure you're using the "Better BibTeX" export rather than the standard "BibTeX" export?

**Comment by PhilippSchweizer** [comment]
I also can confirm, that the keys are not produced upon the start of zotero. The citekey column stays empty. I am using the "Better BibTex" export.

**Comment by tmgodinho** [comment]
I have the same issue as well. I think it was caused by the last Zotero update (5.0.34 BBT-5.0.74).
The citation key stays empy, no matter what. I use the Better BibLaTeX export.

The logs output shows this.
`[JavaScript Error: "Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsILocalFile.initWithPath]" {file: "chrome://zotero/content/xpcom/file.js" line: 46}]`

`[JavaScript Error: "TypeError: tex_studio_ts_1.TeXstudio is undefined" {file: "chrome://zotero-better-bibtex/content/BetterBibTeX.js" line: 1929}]`

`[JavaScript Error: "Serializer.store ignored, DB not yet loaded" {file: "chrome://zotero-better-bibtex/content/BetterBibTeX.js" line: 3033}]`

`[JavaScript Error: "Serializer.store ignored, DB not yet loaded" {file: "chrome://zotero-better-bibtex/content/BetterBibTeX.js" line: 3033}]` 

`[JavaScript Error: "Serializer.store ignored, DB not yet loaded" {file: "chrome://zotero-better-bibtex/content/BetterBibTeX.js" line: 3033}]`

`[JavaScript Error: "Zotero.BetterBibTeX.cache is undefined" {file: "Better BibLaTeX" line: 1431}]`

`[JavaScript Error: "Zotero.BetterBibTeX.cache is undefined" {file: "Better BibLaTeX" line: 1431}]`

`version => 5.0.34, platform => Win32, oscpu => Windows NT 6.3; WOW64, locale => pt-PT, appName => Zotero, appVersion => 5.0.34, extensions => Zotero LibreOffice Integration (5.0.8.SA.5.0.34, extension), Zotero Word for Windows Integration (5.0.7.SA.5.0.34, extension), Zotero Better Bib(La)Tex (5.0.74, extension), Shockwave Flash (28.0.0.137, plugin)`

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5359](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.74.5359.issue-880.xpi) ("search for texstudio errors out on windows").

**Comment by retorquere** [comment]
Oh wait, you're not seeing the citation key in the Zotero UI. My mistake. Can you try 5359 and look for the text `Trying to find TeXstudio:` in the error log?

**Comment by tmgodinho** [comment]
Here, I have found that line.
Do you think the TexStudio is causing this problem, because it was probably a coincidence but I also had TexStudio opened when the problem first appeared.

```
(3)(+0000001): {better-bibtex} Trying to find TeXstudio:
{"platform":"win32","pathsep":";","dirsep":"\\"}

(1)(+0000001): NS_ERROR_FILE_UNRECOGNIZED_PATH Exception: Component
returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH)
[nsILocalFile.initWithPath]
Zotero.File</this.pathToFile@chrome://zotero/content/xpcom/file.js:46:12
Zotero.BetterBibTeX<["./tex-studio.ts"]@chrome://zotero-better-bibtex/content/BetterBibTeX.js:3085:17
__webpack_require__@chrome://zotero-better-bibtex/content/common.js:55:12 Zotero.BetterBibTeX<["./BetterBibTeX.ts"]@chrome://zotero-better-bibtex/content/BetterBibTeX.js:1445:25
__webpack_require__@chrome://zotero-better-bibtex/content/common.js:55:12 webpackJsonpCallback@chrome://zotero-better-bibtex/content/common.js:26:23
@chrome://zotero-better-bibtex/content/BetterBibTeX.js:2:1

(3)(+0000001): Error: BBT: load of content/tex-studio.ts failed:Error:
Unexpected value
'\texstudio'::Zotero.File</this.pathToFile@chrome://zotero/content/xpcom/file.js:55:9
Zotero.BetterBibTeX<["./tex-studio.ts"]@chrome://zotero-better-bibtex/content/BetterBibTeX.js:3085:17
__webpack_require__@chrome://zotero-better-bibtex/content/common.js:55:12 Zotero.BetterBibTeX<["./BetterBibTeX.ts"]@chrome://zotero-better-bibtex/content/BetterBibTeX.js:1445:25
__webpack_require__@chrome://zotero-better-bibtex/content/common.js:55:12 webpackJsonpCallback@chrome://zotero-better-bibtex/content/common.js:26:23
@chrome://zotero-better-bibtex/content/BetterBibTeX.js:2:1
```

[Debug Output.txt](https://github.com/retorquere/zotero-better-bibtex/files/1634516/Debug.Output.txt)

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5362](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.74.5362.issue-880.xpi) ("why is this flaming out on Windows?").

**Comment by retorquere** [comment]
Try 5362. If it starts up without error (it should), could you please submit a BBT error report? I still want to know why TeXstudio detection fails on windows, the logs will tell me why.

**Comment by Aesara** [comment]
Report ID: F3UMPLX2

**Comment by tmgodinho** [comment]
I have also sent mine.
Report ID: RB6PMT5H

**Comment by retorquere** [comment]
Alright, those logs identified the problem. The tests are running, when they go green I'll issue a new release.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5367](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.74.5367.issue-880.xpi) ("skip empty path components").

**Comment by retorquere** [comment]
The release is scheduled and should be out in 15 minutes
