### ISSUE TITLE
question/feature request: better-bibtex for Continous Integration

### ISSUE THREAD

**Issue by rriemann** [retorquere/zotero-better-bibtex#900]
Hello,

has anyone already had the idea of a CLI version of this plugin that would allow to transform use the transformation from CSL to bibtex provided by this plugin as part of a continious integration pipline (I think of Gitlab, Travis, Jenkins)?

I found https://github.com/fiduswriter/biblatex-csl-converter and wonder how much is the difference between this plain npm and this plugin.

**Comment by retorquere** [comment]
(there's just me, so "anyone" collapses to "me") the bbt plugin does different things from the npm package (which bbt uses btw and I'm co-maintainer of that package).

BBT doesn't parse CSL json, only produces it. BBT is mainly about getting good references out of Zotero (so the Zotero db is the source data) in csl and bib(la)tex form and automating that process. If you're not interested in Zotero, you'll be much better off with the npm package.

**Comment by rriemann** [comment]
No, I am sure that occasionally other people read the issues here. I mean there is at least me. So you are not alone! 🙂 

So I could use Zotero to generate with BBT YAML snippets, organise them with git, and use continious integration to `cat` them together and produce with the npm a bibtex file?

I am looking for means to organise a synced library that I can easy connect to continious integration. The sync and API provided by Zotero is problematic with regards to data protection obligations and their API does not use BBT. :(

**Comment by retorquere** [comment]
Oh yeah that's totally possible. The BBT testing infrastructure includes a [second xpi](https://github.com/retorquere/zotero-better-bibtex/tree/master/test/fixtures/debug-bridge) (just zip the files) which allows controlling a running Zotero via a HTTP interface. It's fairly dumb, and totally unsafe; it has a web server running on localhost that you can send javascript snippets to and it will blindly run them inside Zotero. As long as you run it in a controlled environment (like a CI environment).

**Comment by retorquere** [comment]
Does that answer your question?

**Comment by rriemann** [comment]
:) Somehow. I wonder now if one can install and start zotero without xserver. This is though not a better bibtex question anymore. So please close this issue. Thanks once again!

**Comment by retorquere** [comment]
you can't install without X, but xvfb will do the job. That's what I use for my own tests.

**Comment by retorquere** [comment]
(xvfb fakes the presence of an X server)

**Comment by retorquere** [comment]
Not sure whether that would qualify as a CLI solution though. BBT is deeply interwoven with Zotero and prying it loose would be a *lot* of work.

**Comment by retorquere** [comment]
Also the npm package doesn't read CSL. It parses biblatex, is tolerant of bibtex (it can be used as a bibtex parser), and the internal state after parsing (which it calls JSON, but which it technically isn't) can be transformed to CSL (which can of course be dumped to JSON or YAML at your choice) or biblatex. It doesn't parse CSL.

> So I could use Zotero to generate with BBT YAML snippets

yes

> organise them with git,

sure

> and use continuous integration to cat them together

Also yes, but note that the CSL-YAML files will have the YAML header delimiter (`---`) at the top, so you can't use `cat` to cat them. A very simply python/ruby/node/whatever script could though.

> and produce with the npm a bibtex file?

No, because the npm will only parse biblatex, not CSL-JSON or CSL-YAML. biblatex isn't a great exchange format as it doesn't round-trip cleanly in Zotero.

> I am looking for means to organise a synced library that I can easy connect to continuous integration. The sync and API provided by Zotero is problematic with regards to data protection obligations and their API does not use BBT. :(

Nor will they ever. BBT has a lot of complexity they don't want to take into the main client.

If you want private sync, there is a way to set up a [private Zotero sync server](https://groups.google.com/forum/#!topic/zotero-dev/p5Mlvnw3nXY) although it seems non-trivial to get it to work, but if you want sync between clients but not have your data flow to the Zotero server, this is the best way I'm afraid. If you just want to merge stuff from multiple users into one bib file, but not sync these changes back to these users' library, this is what I'd do:

* Have those users configure BBT auto-export on the relevant part of their library and target a shared location (I'd usually suggest GDrive/Dropbox/etc here but you mentioned data privacy concerns, so you may want to find a different location). The best exporter for this would actually be BBT JSON as it round-trips much better than any other; it doesn't support auto-update right now but I could add it, it wouldn't be hard.
* Merge the results (JSON is fairly easy to merge, BibTeX can just be `cat`ted)
* Import everything into Zotero; you could use the plumbing from my test framework to clear out the library and re-import the merged file.
* Export everything to bibtex using BBT (also usign the test plumbing)

The test framework takes care of configuring, starting and closing Zotero. Setting up a private sync server would yield a better user experience (feedback on duplicates, everyone could install BBT at their choice, etc) but a non-sync-server solution could be made to work.
