### ISSUE TITLE
Disable "Copy as Better BibTex Citation Key Quick Copy"

### ISSUE THREAD

**Issue by jarmitage** [retorquere/zotero-better-bibtex#905]
I want to be able to quick copy full references (the default Zotero behaviour)

Is it possible to (a) disable the way BBT hijacks `Cmd-Shift-C`, (b) change the BBT quick copy shortcut to e.g. `Cmd-Alt-C`, or (c) add full reference as an option to BBT quick copy preferences?

Thanks for the great plugin!

**Comment by retorquere** [comment]
I don't hijack anything. In Zotero you can select anything you want for quick-copy in the `Export`->`Quick Copy` references, and I don't touch that behavior in any way. AAMOF if you want BBT to do anything there you have to manually select `Better BibTex Citation Key Quick Copy` as the default format there yourself. `Better BibTex Citation Key Quick Copy` is simply a reference exporter as any other, it gets called by Zotero for quick-copy but I can't even tell that's the reason; if you were to export your references normally, `Better BibTex Citation Key Quick Copy` will show up as one of the available formats, and will get you the same output. I want to stress this point: Zotero itself can be configured to call any exporter you have installed, and those exporters neither trigger this behavior, alter this behavior, or even know they're being invoked for this purpose. So:

a) technically the answer would have to be "no", but only because there is no hijack to disable, as I don't hijack it in any way shape of form, and 

b) you'd have to ask someone who does something with shortcuts, like Zutilo or the Zotero team itself, because BBT doesn't do anything with shortcuts anywhere and I have no plans to add shortcut behavior, and

c) that depends on whether you mean full reference as a BibTeX reference (possible, use `Better BibLaTeX` or `Better BibTeX` as the default format) or whether you mean a formatted reference (also possible but nothing to do with BBT, just use one of the standard styles from Zotero as the default format)

**Comment by retorquere** [comment]
To be even more specific: those exporters *cannot* trigger this behavior, *cannot* alter this behavior, and *cannot* even know they're being invoked for this purpose. BBT as a plugin could do these things, but doesn't. It just provides the exporter, which cannot etc etc.

**Comment by jarmitage** [comment]
Ok my mistake, a BBT export format was assigned to Quick Copy in Zotero prefs. I was looking for a way to change this from the BBT preferences tab and couldn't find anything, which is why I was a bit confused. Thanks for the explanation of how this works.

**Comment by retorquere** [comment]
No worries. The settings from the BBT tab change the behavior of the QC translator; at some point it made more technical sense to have all quick-copy behavior implemented by one translator; otherwise you'd have 10 separate translators in the export list, all doing pretty much the same work.
