### ISSUE TITLE
Reset the BBT database

### ISSUE THREAD

**Issue by milonemario** [retorquere/zotero-better-bibtex#911]
- [x] I have verified that I am on the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest) and Zotero
- [x] I am posting a single question, bug or feature request
- [x] I have included a descriptive subject of the problem
- [x] I am available for follow-up questions and testing

Suggestion: It would be nice to be able to reset the BBT database.

My problem was the following. I generated citation keys on my references using [auth:lower][year]. Then I realized that there were duplicated entries of some references. BBT added a letter (a, b,...) in order to accommodate for the duplicated entries. After I deleted the duplicated entries, I expected BBT to remove the suffixed letters when it was not necessary anymore. However, BBT kept the suffixed letter (I tried restarting, changing the pattern and using again [auth:lower][year], but nothing worked.

I understand the need for this behavior for consistence purposes when the references are already cited in some papers. However, I wanted to force BBT to recreate the keys as if it was running for the first time.

I could do that by simply removing the sqlite files in the Zotero folder, which forced BBT to recreate them. While easy to do, I suggest it would be nice to have this option in the BBT preferences.

Best regards,
Mario

**Comment by retorquere** [comment]
The reason I don't re-set the postfixes is exactly the reason you mentioned. Citekey stability is an important feature of BBT over the default Zotero BibTeX generation. There's a few things you can do to reset keys without deleting the DB:

1. If you want to reset the key, making any change and then undoing the change to the reference will generate a non-postfixed key if it's free.
2. Changing the pattern used to refresh all the keys in Z4 but doesn't anymore, mostly for performance reasons, but I think the key-stability it gets is actually desirable. You can get all keys to refresh by selecting your references, right-clicking, and selecting "Refresh".
3. The refresh algorithm however favors keeping the existing citekey if the refreshed key equals the current citekey plus a postfix it may have. In order to force-refresh, you'd have to select a different pattern (adding a fixed text to the end of the pattern should do it, something like `[auth:lower][year]reset`), refresh, then set the pattern back to what you wanted, and refresh again. This will force-refresh all non-pinned keys. Existing legitimate duplicates may get their postfixes swapped though.

These option will refresh your keys without deleting the DB -- deleting the DB would also have deleted all auto-exports if you had any, it's not just the keys.

WRT the click-to-remove-database, I don't want to go there, sorry. It's a dangerous option to have, it doesn't seem like it would be needed often, and the way you have done it is easy enough for something like this.

**Comment by milonemario** [comment]
Thanks a lot for your quick reply !

I haven't tried the third option you mention. Thanks for the tip.
I understand the danger of such an option.

And thanks a lot for this new version for Zotero 5, it greatly simplifies my work !! :)

Best regards,
Mario

**Comment by retorquere** [comment]
You're welcome
