### ISSUE TITLE
Allow force-refresh in addition to conservative refresh

### ISSUE THREAD

**Issue by 3e4** [retorquere/zotero-better-bibtex#914]
- [x] I have verified that I am on the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest) and Zotero
- [x] I am posting a single question, bug or feature request
- [x] I have included a descriptive subject of the problem
- [x] I am available for follow-up questions and testing

I am using zotero with Better Biblatex on several computers. I have set up autoexport to a local texmf folder on each computer.
I had trouble with one citekey, as it was `Author2000_shorttitle` on the one computer, but `Author2000_shorttitlea` on the other. Both Zotero installations were fully synced. Therefore, I was not able to compile the same .tex file on both machines with the same result.
As it turns out, there was the same article by the author in the Trash on one of the computers, but not on the other. Even though this item in trash did not have a citekey, it blocked the `Author2000_shorttitle`. After completely removing the item from the trash, I could regenerate the citekey of the item and it became `Author2000_shorttitle`, consistent with the other computer.

I think Trash items should be excluded when generating citekeys as the trash is not synced.

**Comment by retorquere** [comment]
Items in trash *are* ignored, and always have been. Try the following with a junk reference (just tested):

1. Pick any item that doesn't have a duplicate key. Let's say this has key `herbert1970`.
2. Right-click and duplicate the item. The duplicate will have citekey `herbert1970a`
3. Move the original to the Trash (**warning**: this will remove the item from any collections it is in, hence the junk reference)
4. Duplicate `herbert1970a` using right-click and duplicate
5. The new copy has key `herbert1970`.

Can you replay the staps by which you can replicate your problem? I can't reproduce the behavior you describe.

BTW, dynamic keys are ***not*** guaranteed to sync; if you want guaranteed sync, you need to pin the citekey. BBT cannot use the sync facility of Zotero so its own database is always only local. Syncable citekeys for Zotero has been discussed just about [forever](https://forums.zotero.org/discussion/15636/changes-to-fields-and-item-types-for-zotero-5-1) although it's supposed to be [real soon now](https://groups.google.com/d/msg/zotero-dev/IpqX0R3xfo8/CBhHOaihBgAJ), but the matter is out of my hands.

**Comment by 3e4** [comment]
My problem is after your step 3 (only one item "herbert" in collection)
4. Right click `herbert1970a` and select `Refresh BibTeX key`
5. *Expected result*: Key changes to `herbert1970`
*Observed result*: Key stays `herbert1970`
6. Purge "herbert" from Trash
7. Right click `herbert1970a` and select `Refresh BibTeX key`
8. Key changes to `herbert1970`

I don't need guaranteed key sync, but I want *deterministic* key generation. If I select all entries and refresh bibtex keys on two different installations of zotero with same library, I expect the same keys. But somehow the behavior is erratic. Now the key is not reset to `herbert1970` even I purged the Trash... Yesterday it worked.

_edit_ Just noticed I can `Pin` the key, then edit the "Extra" field. Or I duplicate and delete the original. Maybe you can close this issue...

**Comment by retorquere** [comment]
Refresh doesn't work that way. Refresh means "I've changed the pattern and I want to update the citekey accordingly for this reference". The key generation is deterministic, it's just deterministic in a different way than you had expected; it's conservative -- if the refreshed key is the same plus any postfix, the key remains as-is (deterministically). More specifically, if I updated the keys on refresh in the way you expect, the results would be less deterministic, because Zotero doesn't offer formal guarantees in what order selected references are handed off; if I would force-refresh, key postfixes could in principle swap around each time you do the refresh. Right now, they don't, so it's deterministic in that sense.

I could explore a force-refresh, but the default refresh is going to stay conservative; if you had changed the pattern in a way that would change the non-postfixed part, the key would have updated, but if the non-postfixed part stays the same, the postfix stays in place. I could have cited that reference with the postfix and I don't want it to go away just like that.

**Comment by retorquere** [comment]
It doesn't matter BTW whether the trashed reference is purged -- items in the trash don't influence the outcome. Another reason for the conservative approach to citekey generation is that it allows accidentally deleted items to reclaim their key when they are restored; that's not guaranteed, but if reclaimed immediately, it's likely under the current scenario that they'll get the existing key back.

**Comment by 3e4** [comment]
Dear Emiliano,

Thank you for this detailed explanation. I understood and now know how to get my citekeys in sync over several installations.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5868](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.99.5865.issue-914.xpi) ("fixes #914").

**Comment by retorquere** [comment]
I've added a hidden option to enable non-conservative refresh.
