### ISSUE TITLE
BBT doesn't finish initializing due to corrupted lokijs indexes. 

### ISSUE THREAD

**Issue by rabons** [retorquere/zotero-better-bibtex#920]
- [x] I have verified that I am on the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest) and Zotero
- [x] I am posting a single question, bug or feature request
- [x] I have included a descriptive subject of the problem
- [x] I am available for follow-up questions and testing

ID: AP2IYBZ4

# Bug classification
The pop-up message Better BibTeX: Initializing does not disappear.

Refreshing the citation keys also does not seem to work. I reinstalled the BetterBibTex-AddOn and also did a re-scan of the citekeys and a reset of the cache.

**Comment by retorquere** [comment]
Can you send a bbt error report?

**Comment by retorquere** [comment]
Sorry, I see you sent one, I'll take a look

**Comment by retorquere** [comment]
If you remove BBT (and restart), are you able to export references in the RIS format?

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5730](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.93.5726.issue-920.xpi) ("Merge branch 'master' into 920").

**Comment by retorquere** [comment]
Can you separately try 5730 and submit a new debug report?

**Comment by rabons** [comment]
I submitted a new report with 5730, ID 2NJY6UG4
RIS Export with BBT disabled works without any problems.
Thank you!

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5790](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.94.5787.issue-920.xpi) ("Merge branch 'master' into 920").

**Comment by retorquere** [comment]
How many references do you have? What I see in the logs, Zotero is still initializing, and BBT must wait until that is done. However if you can export using RIS in about the same amount of time, that would mean Zotero is done initializing.

Can you submit a new log using 5790?

**Comment by rabons** [comment]
I have around 2000 references, group libraries included. The reported error didn't show up a few weeks ago, though, and the number of references should not have dramatically changed.. I have waited longer now (about 5 minutes) with the new bug report ID AY2WSSP5

**Comment by retorquere** [comment]
Thanks, the longer wait showed the error. It looks to be an error in a library I use -- the guy is usually pretty responsive, but if he doesn't get back today I have a workaround lined up.

**Comment by rabons** [comment]
Thank you! Which guy are you referring to?

**Comment by retorquere** [comment]
I was intentionally vague because I don't mean to "out" him, but it's Techfort, the creator of the LokiJS DB; LokiJS is what keeps BBT performance good, so I'm very happy with what he's made, and bugs just happen sometimes. I've opened an issue [here](https://github.com/techfort/LokiJS/issues/660), but if that takes longer to resolve, I have a workaround. I want the fix in fast because if it affects you, it likely affects others.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5837](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.95.5835.issue-920.xpi) ("disable adaptive indexes").

**Comment by retorquere** [comment]
it's taking too long for my tastes. Try 5837.

**Comment by rabons** [comment]
It works now, that's great! Thank you.
I did another error report if you want to look at the new output (but note that this time there was no error). ID KKKEBV63

**Comment by retorquere** [comment]
Not necessary, I know what the error was. I have a workaround in place which I'll remove when the LokiJS guys fix the issue.

**Comment by lrnv** [comment]
Hi, 

I have the same issue here, the popup "Better BibTex : Initializing" wont leave my screen and is stuck at "Installation des convertisseurs" (sorry it's in french, means "Installing converters"). 

The issue is that i cant access to the better bibtex export. 

I updated Zotero and the plugin, but it still wont work. 

Is there a workaround yet ?

**Comment by retorquere** [comment]
It's not a matter of there being a workaround, the init not finishing is a symptom of an underlying error. The error that underlined #920 was fixed, so it's something else now.

In the help menu, restart with debugging enabled, after it restarts, from the help menu, view the log, save it from that popup, and attach it here, that should give me more info.

What OS are you on?

**Comment by lrnv** [comment]
Hi, 

Thanks for your fast answer. Here's the log : [log.txt](https://github.com/retorquere/zotero-better-bibtex/files/2659788/log.txt)

**Comment by retorquere** [comment]
I'd prefer to handle this on a new issue if you don't mind. It's very unlikely to be the same underlying problem.

**Comment by retorquere** [comment]
Thanks - that log has the info I need. Unfortunately I won't have access to a pc for the next 8 hours or so, but I'll probably have a fix tonight.

**Comment by lrnv** [comment]
Waouh thank you very much. Could you describe the issue to me ? 

Tonight will largely be soon enough.

**Comment by retorquere** [comment]
The problem is a recent new feature (editing of auto exports) expects stuff to be in the database I didn't properly migrate. Should have gotten it earlier, but easy to fix; probably just 30 minutes to code, but not without my PC at hand.

I would prefer a new issue, yes. Other people are getting notification mails for this issue where it likely does not affect them.
